<?php 

$ficheAlbum = $view->getHelper('ficheAlbum');



?>
<script src="<?php echo BDO_URL;?>jquery/jquery.mask.min" type="text/javascript"></script>
<div class="cadre1">
    <div class="middle_title"><h3>Proposition d'ajout et de correction</h3></div>
   <?php if(IssetNotEmpty($view->edition)) { ?> <a href="#null" onclick="javascript:history.back();"> Retour à la fiche Album</a> <?php } ?>
<script src="<?php echo BDO_URL;?>script/genautocomplete.js" type="text/javascript"></script>
<form enctype="multipart/form-data" action="" name="action" value="append" method="POST"> 	
     <?php if(IssetNotEmpty($view->edition)) { ?>
        <input type="hidden" name="txtTomeId" value="<?php echo $view->edition->ID_TOME; ?>">
        <input type="hidden" name="txtEditionId" value="<?php echo $view->edition->ID_EDITION; ?>">
               
    <?php } ?>
        <?php if(IssetNotEmpty($view->ID_TOME)) { ?>
         <input type="hidden" name="txtTomeId" value="<?php echo $view->ID_TOME; ?>">
        <?php } ?>
<table cellpadding="10" cellspacing="10" align="center" bgcolor="EED8BF">
          <!--DWLayoutTable-->
          <tbody>
            <tr bordercolor="#FFFFFF">
              <td rowspan="4" bordercolor="#FFFFFF" valign="top">
                  <?php if ($view->TYPE == "AJOUT") { ?>
                  <div id="titre_prop_album">Vous êtes ici sur la page de <b>proposition de nouvel album</b></div>
                   <div style="margin-top: 7px;">
                    - Pour une proposition de <b>nouvelle édition</b> concernant un album existant, vous pouvez également utiliser
                    ce formulaire mais un formulaire plus pratique pour vous est à votre disposition via la fiche album de votre collection
                    (ajoutez l'album à votre collection puis faites une demande de nouvelle édition)
                    <br />
                    - Pour une demande de <b>correction</b> sur un album existant, utilisez le lien indiqué sur les fiches albums ou sur les pages série
                </div>
                  <?php } ?>
              <p>Avant, tout merci de prendre le temps de lire les guides de saisie disponibles :
                        </p><ul type="SQUARE">
                            <li><a href="http://www.bdovore.com/forum/viewtopic.php?t=352" target="_blank">Tutorial : comment faire une demande d'ajout ou de correction</a>
                            </li><li><a href="http://www.bdovore.com/forum/viewtopic.php?t=617" target="_blank">Tutorial : les mangas V.O</a>
                            </li><li><a href="http://www.bdovore.com/forum/viewtopic.php?t=392" target="_blank">Tutorial : les BD et Comics V.O</a>
                            </li><li><a href="http://www.bdovore.com/forum/viewtopic.php?t=618" target="_blank">Tutorial : les séries francaises traduites en d'autres langues</a>
                            </li><li><a href="http://www.bdovore.com/forum/viewtopic.php?t=391" target="_blank">Tutorial : les artbooks</a>
                        </li></ul>
                          <p></p>
                          <p>Nos valideurs et correcteurs travaillent d'arrache pied (et bénévolement) pour que notre base de données soit la plus complète possible, aidez les en renseignant au mieux toutes les informations à votre disposition et en utilisant les propositions automatiques lors de la saisie !</p>
            <br> 
             <?php if ($view->TYPE == "AJOUT") { ?>
                <p>
                    Avant de commencer à remplir ce formulaire d'ajout, vous pouvez consulter la
                    <b><a href="<?php echo BDO_URL;?>listpropal?type=AJOUT">liste des demandes d'ajout en cours de traitement</a></b>
                    afin de vous éviter de saisir une proposition déjà faite récemment (et évidemment de bien vérifier
                    que l'album n'existe pas déjà via le moteur de recherche ou le <a href="<?php echo BDO_URL;?>browser">BDoBrowser</a>.
                </p>
                 <div style="padding-top: 10px;"><span class="i">La meilleure source pour remplir ce formulaire est <span class="b">votre exemplaire</span> (si vous en possédez un)</span> - Proverbe bdovorien présocrato-cambrien</div>
                  <?php } ?>
            
    <table frame="box" rules="groups" cellpadding="5" bgcolor="#DAC1B3" border="1" bordercolor="#FFFFCC" width="550px">

                  <tbody>

                    <tr bordercolor="#DAC1B3">

                      <td bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1"><strong>Couverture</strong></font> <div class="texte">(180px de large si possible)</div></td>

                            <td><?php if(IssetNotEmpty($view->edition)) { ?><img src="<?php echo BDO_URL_COUV.$view->edition->IMG_COUV;?>" align="middle" border="0" height="220" width="169"> <?php } ?>

                            </td>

                    </tr>

                    <tr bordercolor="#DAC1B3">

                      <td class="label" width="48%"><font size="-1">Envoyer depuis

                        un fichier local</font></td>

                      <td width="52%"> <input name="txtFileLoc" id="txtFileLoc" size="25" class="flat" type="file"></td>

                    </tr>

                    <tr bordercolor="#DAC1B3">

                      <td class="label"><font size="-1">Envoyer depuis une URL</font></td>

                      <td> <input name="txtFileURL" id="txtFileURL" size="40" class="flat" type="text"></td>

                    </tr>

                  </tbody>

                </table>
                 <?php if($view->TYPE <> "EDITION") { ?>
                <table frame="box" rules="groups" cellpadding="5" cellspacing="0" bgcolor="#DAC1B3" border="1" bordercolor="#FFFFCC" width="550px">
                  <!--DWLayoutTable-->
                  <tbody>
                    <tr bordercolor="#DAC1B3">
                      <td colspan="4" bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1"><strong>Informations
                        sur l'album</strong></font></td>
                    </tr>
                    <tr bordercolor="#DAC1B3">
                      <td bordercolor="#DAC1B3" class="label" width="81"><font color="#990000" size="-1"><strong>Titre</strong></font></td>
                      <td> <div align="left"> </div></td>
                      <td> <input name="txtTitre" id="txtTitre" value="<?php echo $view->edition->TITRE_TOME;?>" size="50" class="flat" type="text">
                          <br>
                          <span class="petite_police">
                            En l'absence de titre distinctif : "<i>Titre de la Série</i>, Tome X" ; "<i>Titre de la Série</i>" pour un one-shot
                        </span></td>
                    </tr>
                    <tr bordercolor="#DAC1B3">
                      <td colspan="4" bordercolor="#DAC1B3" class="label"> <table border="0" width="100%">
                          <tbody><tr>
                            <td width="25%">&nbsp;</td>
                            <td class="label" align="center" width="25%"><font color="#990000" size="-1"><strong>Intégrale</strong></font></td>
                            <td class="lable" align="center" width="25%"><font color="#990000" size="-1"><strong>Type</strong></font></td>
                            <td width="25%">&nbsp;</td>
                          </tr>
                          <tr>
                            <td>&nbsp;</td>
                            <td class="data" align="center"><input name="chkIntegrale" value="checkbox" <?php if ($view->edition->FLG_INT_TOME == 1) echo "checked='O'"; ?> type="checkbox"></td>
                            <td class="data" align="center"><select name="lstType" size="1"><option value="0" <?php if ($view->edition->FLG_TYP_TOME == 0) echo "selected='O'"; ?>>Album</option><option value="1" <?php if ($view->edition->FLG_TYP_TOME == 1) echo "selected='O'"; ?>>Coffret</option>
                              </select></td>
                            <td>&nbsp;</td>
                          </tr>
                        </tbody></table></td>
                    </tr>
                    <tr bordercolor="#DAC1B3">
                      <td bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1"><strong>Tome n°</strong></font></td>
                      <td> <div align="left"> </div></td>
                      <td colspan="2"> <input name="txtNumTome" id="txtNumTome" value="<?php echo $view->edition->NUM_TOME; ?>" size="2" class="flat" type="text"></td>
                    </tr>
                    <tr bordercolor="#DAC1B3">
                      <td bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1"><strong>Synopsis</strong></font></td>
                      <td><!--DWLayoutEmptyCell-->&nbsp;</td>
                      <td colspan="2"><textarea cols="50" name="txtHistoire" rows="8" id="txtHistoire"><?php echo $view->edition->HISTOIRE_TOME; ?>
</textarea><br>
                            <span class="petite_police">Utiliser ce champ pour indiquer le "résumé" de l'album. <u>Indiquez votre source !</u> (votre pseudo si vous en êtes l'auteur, le nom de l'éditeur,...).
                            <br /><br />
                            Vous pouvez également utiliser ce champ pour <u>laisser un commentaire</u> à vos correcteurs adorés et aimants</span>
                        </td>
                    </tr>
                  </tbody>
                </table>
                
                <br>

                <table frame="box" rules="groups" cellpadding="5" bgcolor="#DAC1B3" border="1" bordercolor="#FFFFCC" width="550px">

                  <tbody>

                    <tr bordercolor="#DAC1B3">

                      <td colspan="4" bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1"><strong>Informations

                        sur la série</strong></font><br>

                        <font size="-2">(Les modifications s'appliqueront à tous les albums

                        de la série)</font></td>

                    </tr>

                    <tr bordercolor="#DAC1B3">

                      <td bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1"><strong>Serie</strong></font></td>

                      <td width="39"> <div align="left">

                          <input name="txtSerieId" id="txtSerieId" value="<?php echo $view->edition->ID_SERIE; ?>" type="hidden">
                          <span id="spSerie"><?php echo $view->edition->ID_SERIE; ?></span>

                        </div></td>

                      <td width="571"> <input name="txtSerie" id="txtSerie" value="<?php echo $view->edition->NOM_SERIE; ?>" size="50" class="flat" type="text"></td>

                      

                    </tr>

                    <tr bordercolor="#DAC1B3">

                      <td bordercolor="#DAC1B3" class="label" width="8%"><font color="#990000" size="-1"><strong>Genre</strong></font></td>

                      <td width="6%"> <input name="txtGenreId" id="txtGenreId" value="<?php echo $view->edition->ID_GENRE; ?>" size="3" class="flat" type="hidden">
                                        <span id="spGenre" > <?php echo $view->edition->ID_GENRE; ?></span>
                      </td>
                                    
                      <td width="73%"> <input name="txtGenre" id="txtGenre"  value="<?php echo $view->edition->NOM_GENRE; ?>" size="30" class="flat" type="text"></td>

                      
                    </tr>

                    <tr bordercolor="#DAC1B3">

                    <td bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1"><strong>Achevée</strong></font></td>

                      <td>&nbsp;</td>

                      <td><select name="lstAchevee" size="1">

                      <option value="0" <?php if ($view->edition->FLG_FINI == 0) echo "selected"; ?>>Finie</option><option value="1" <?php if ($view->edition->FLG_FINI == 1) echo "selected"; ?>>En cours</option><option value="2" <?php if ($view->edition->FLG_FINI == 2) echo "selected"; ?>>One Shot</option><option value="3" <?php if ($view->edition->FLG_FINI == 3) echo "selected"; ?>>Interrompue/Abandonnée</option>

                        </select></td>

                      <td>&nbsp;</td>

                    </tr>

                  </tbody>

                </table>

                <br>

                 <table frame="box" rules="groups" cellpadding="5" cellspacing="0" bgcolor="#DAC1B3" border="1" bordercolor="#FFFFCC" width="550px">

                  <tbody>

                    <tr bordercolor="#DAC1B3">

                      <td colspan="4" bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1"><strong>Informations

                        sur les auteurs</strong></font><br> <font size="-2">(Vous

                        pouvez proposer deux scénaristes / dessinateurs par tome)</font><span class="petite_police"> (un seul par champ, à valider à la loupe si présent dans la base.
                            <br />Vous pouvez sélectionner "Collectif" comme 1er ou 2nd auteur si plus de 2)</span></td>

                    </tr>

                    <tr bordercolor="#DAC1B3">

                      <td bordercolor="#DAC1B3" class="label" width="18%"><font color="#990000" size="-1"><strong>Scenariste(s)</strong></font></td>

                      <td width="10%"> <input name="txtScenarId" id="txtScenarId" value="<?php echo $view->edition->ID_SCENAR; ?>" size="5" type="hidden">
                          <span id="spScenar"></span>
                      </td>

                      <td width="59%"> <input name="txtScenar" id="txtScenar" value="<?php echo $view->edition->scpseudo; ?>" size="40" class="flat" type="text"></td>

                      

                    </tr>

                    <tr bordercolor="#DAC1B3">

                      <td bordercolor="#DAC1B3" class="label">&nbsp;</td>

                      <td> <input name="txtScenarAltId"  id="txtScenarAltId" value="<?php echo $view->edition->ID_SCENAR_ALT; ?>" size="5" type="hidden">
                           <span id="spScenarAlt"></span>
                      </td>

                      <td> <input name="txtScenarAlt" id="txtScenarAlt" value="<?php echo $view->edition->scapseudo; ?>" size="40" class="flat" type="text"></td>

                     

                    </tr>

                    <tr bordercolor="#DAC1B3">

                      <td bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1"><strong>Dessinateur(s)</strong></font></td>

                      <td> <input name="txtDessiId" id="txtDessiId" value="<?php echo $view->edition->ID_DESSIN; ?>" size="5" type="hidden">
                           <span id="spDessi"></span>
                      </td>

                      <td bordercolor="#DAC1B3"> <input name="txtDessi"  id="txtDessi" value="<?php echo $view->edition->depseudo; ?>" size="40" class="flat" type="text"></td>

                      

                    </tr>

                    <tr bordercolor="#DAC1B3">

                      <td bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1">&nbsp;</font></td>

                      <td> <input name="txtDessiAltId" id="txtDessiAltId" value="<?php echo $view->edition->ID_DESSIN_ALT; ?>" size="5" type="hidden">
                          <span id="spDessiAlt"></span>
                      </td>

                      <td bordercolor="#DAC1B3"> <input name="txtDessiAlt" id="txtDessiAlt"  value="<?php echo $view->edition->deapseudo; ?>" size="40" class="flat" type="text"></td>

                     

                    </tr>

                    <tr bordercolor="#DAC1B3">

                      <td bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1"><strong>Coloriste</strong></font></td>

                      <td> <input name="txtColorId" id="txtColorId"  value="<?php echo $view->edition->ID_COLOR; ?>" size="5" type="hidden">
                      <span id="spColor"></span>
                      </td>

                      <td> <input name="txtColor" id="txtColor" value="<?php echo $view->edition->copseudo; ?>" size="40" class="flat" type="text">

                      </td>

                     

                    </tr>

                    <tr bordercolor="#DAC1B3">

                      <td bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1">&nbsp;</font></td>

                      <td> <input name="txtColorAltId" id="txtColorAltId"  value="<?php echo $view->edition->ID_COLOR_ALT; ?>" size="5" type="hidden">
                      <span id="spColorAlt"></span>
                      </td>

                      <td> <input name="txtColorAlt" id="txtColorAlt" value="<?php echo $view->edition->coapseudo; ?>" size="40" class="flat" type="text">

                      </td>

                     

                    </tr>

                  </tbody>

                </table>

                <br>
 <?php } ?>
                <table frame="box" rules="groups" cellpadding="5" bgcolor="#DAC1B3" border="1" bordercolor="#FFFFCC" width="550px">

                  <tbody>

                    <tr bordercolor="#DAC1B3">

                      <td colspan="4" class="label"><font color="#990000" size="-1"><strong>Informations

                        sur l'édition</strong></font></td>

                    </tr>

                    <tr bordercolor="#DAC1B3">

                      <td class="label" width="26%"> <font color="#990000" size="-1"><strong>Editeur</strong></font></td>

                      <td bordercolor="#DAC1B3" width="2%"> <input name="txtEditeurId" id="txtEditeurId" value="<?php echo $view->edition->ID_EDITEUR; ?>" size="7" type="hidden" >
                          <span id="spEditeur"><?php echo $view->edition->ID_EDITEUR; ?></span>
                      </td>

                      <td bordercolor="#DAC1B3" width="59%"> <input name="txtEditeur" id="txtEditeur" value="<?php echo $view->edition->NOM_EDITEUR; ?>" size="40" class="flat" type="text" onchange="changeEditeur();"></td>

                     

                    </tr>

                    <tr bordercolor="#DAC1B3">

                      <td class="label"> <font color="#990000" size="-1"><strong>Collection</strong></font></td>

                      <td bordercolor="#DAC1B3"> <input name="txtCollecId" id="txtCollecId" value="<?php echo $view->edition->ID_COLLECTION; ?>" size="7" type="hidden">
                      <span id="spCollec"><?php echo $view->edition->ID_COLLECTION; ?></span>
                      </td>

                      <td bordercolor="#DAC1B3"> <input name="txtCollec" id="txtCollec" value="<?php echo $view->edition->NOM_COLLECTION; ?>" size="40" class="flat" type="text"></td>

                      

                    </tr>
                   
                     <tr bordercolor="#DAC1B3">

                          <td bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1"><strong>ISBN-13 (EAN)</strong></font></td>
                            <td> <div align="left"> </div></td>
                            <td colspan="3">
                                <input name="txtEAN" id="txtEAN" value="<?php echo $view->edition->EAN_EDITION; ?>" size="13" maxlength="13" class="flat" type="text">
                                <span class="texte">ISBN à 13 chiffres <u>sans</u> trait d'union ni espace (aussi appelé EAN)</span>
                            </td>
                    </tr>         
                    <tr bordercolor="#DAC1B3">
                        <td bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1"><strong>ISBN-10</strong></font></td>
                        <td> <div align="left"> </div></td>
                        <td colspan="3">
                            <input name="txtISBN" id="txtISBN" value="<?php echo $view->edition->ISBN_EDITION; ?>" size="10" maxlength="10" class="flat" type="text">
                            <span class="texte">ISBN à 10 chiffres <u>sans</u> trait d'union ni espace (obsolète depuis janvier 2007)</span>
                        </td>
                    </tr>

                    <tr bordercolor="#DAC1B3">

                      <td class="label"> <font color="#990000" size="-1"><strong>Date de sortie</strong> <font color="#000000" size="-1">(aaaa-mm-jj)</font></font></td>

                      <td>&nbsp; </td>

                      <td> <input name="txtDateParution" id="txtDateParution3" value="<?php echo $view->edition->DATE_PARUTION_EDITION; ?>" size="15" class="flat" type="text">

                        </td>

                      <td>&nbsp;</td>

                    </tr>
                    <tr><td colspan="4"><span class="texte"><u>BDovore NE gère PAS les réimpressions</u>.<br>Assurez-vous que la date de l'album que vous proposez correspond à une édition originale ou à une réédition (couverture ou contenu différent), PAS à une réimpression (même contenu que la dernière édition)</span> </td></tr>


                   

                  </tbody>

                </table>

                <p> </p>
<table frame="box" rules="groups" cellpadding="5" bgcolor="#DAC1B3" border="1" bordercolor="#FFFFCC" width="550px">

              <tbody>

                <tr>

                    <td bordercolor="#DAC1B3" class="label"><font color="#990000" size="-1"><strong>Ajoutez

                      ici votre commentaire sur votre proposition</strong></font><br><font size="-2">(Vous

                        pouvez également utiliser ce champs pour signaler un doublon ou demander un effacement)</font><br> <br>

                      <textarea name="txtCommentaire" cols="60" rows="8" id="textarea"></textarea>

                    <p> </p></td>

                </tr>

              </tbody>

            </table>
                <div align="center">
                     <?php if ($view->TYPE == "AJOUT") { ?>
<table class="table_form_public">
                    <tr>
                        <td class="label">
                            Après ajout dans la base
                            <select name="cmbAction" size="1" id="cmbAction"><?php echo $view->OPTIONS;?></select>
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <input name="chkNotEmail" value="checked" type="checkbox" checked />
                            <font size="-1">recevoir un email d'information/confirmation après traitement de cette proposition par l'équipe</font>
                        </td>
                    </tr>
                </table>
                     <?php } ?>
                  <p></p>
                  <input type="hidden" name="type" value="<?php echo $view->TYPE; ?>">
<input type="hidden" name="action" value="append">
                  <input name="Submit" value="Valider la proposition" type="submit">

                  <br>

                </div></td>

            </tr>

          </tbody>

        </table>
</form>
</div>
<script>
    /*
     * On remplit les champs de saisie par l'autocompletion
     * 
     */
    <?php  if ($view->TYPE <> "EDITION") { ?>
    addAutocomplete("txtSerie","spSerie","txtSerieId","<?php echo BDO_URL; ?>getjson?data=Serie");
    addAutocomplete("txtGenre","spGenre","txtGenreId","<?php echo BDO_URL; ?>getjson?data=Genre");
    addAutocomplete("txtScenar","spScenar","txtScenarId","<?php echo BDO_URL; ?>getjson?data=Auteur");
    addAutocomplete("txtScenarAlt","spScenarAlt","txtScenarAltId","<?php echo BDO_URL; ?>getjson?data=Auteur");
    addAutocomplete("txtDessiAlt","spDessiAlt","txtDessiAltId","<?php echo BDO_URL; ?>getjson?data=Auteur");
    addAutocomplete("txtDessi","spDessi","txtDessiId","<?php echo BDO_URL; ?>getjson?data=Auteur");
    
     addAutocomplete("txtColor","spColor","txtColorId","<?php echo BDO_URL; ?>getjson?data=Auteur");
     addAutocomplete("txtColorAlt","spColorAlt","txtColorAltId","<?php echo BDO_URL; ?>getjson?data=Auteur");
      <?php } ?>
     addAutocomplete("txtEditeur","spEditeur","txtEditeurId","<?php echo BDO_URL; ?>getjson?data=Editeur");
     
     changeEditeur();
    function changeEditeur() {
        addAutocomplete("txtCollec","spCollec","txtCollecId","<?php echo BDO_URL; ?>getjson?data=Collection&id_editeur="+$("#txtEditeurId").val());
        //addSelectOption("txtCollec1","<?php echo BDO_URL; ?>getjson?data=Collection&id_editeur="+$("#txtEditeurId").val(),<?php echo issetNotEmpty($view->edition) ? $view->edition->ID_COLLECTION : 0;?>);
    
    }
     $(document).ready(function(){
  $('#txtDateParution3').mask('0000-00-00', {placeholder: "0000-00-00"});
});
</script>
    
    
