<script src="<?php echo BDO_URL;?>jquery/datatable/js/jquery.dataTables.min.js" type="text/javascript"></script>
<div class="cadre1">
   <h1>Propositions en cours </h1>									  
            Il y a actuellement <a href="<?php echo BDO_URL;?>proposition/listpropal?type=AJOUT"><b><?php echo $view->NBAJOUT;?> propositions d'album</b></a>, <a href="<?php echo BDO_URL;?>proposition/listpropal?type=EDITION"><b><?php echo $view->NBEDITION;?> propositions de nouvelle édition</b></a>
             et <a href="<?php echo BDO_URL;?>proposition/listpropal?type=CORRECTION"><b><?php echo $view->NBCORRECTION;?> propositions de correction</b></a>
             en cours de traitement pour l'ensemble de la communauté BDovore.
            <br /> 
            <h3> Liste des demandes <?php echo $view->type;?></h3>
    <table id="propal">
        <thead>
            <th>Série</th>
            <th>Tome</th>
            <th>Titre</th>
            <th>Demandé par</th>
            <th>Demandé le</th>
        </thead>
        <tbody>
            <?php if (isset ($view->dbs_edition)) { 
                foreach ($view->dbs_edition->a_dataQuery as $edition) {  ?>
            <tr>
                <td><?php echo $edition->NOM_SERIE;?></td>
                <td><?php echo $edition->NUM_TOME;?></td>
                <td><?php echo $edition->TITRE_TOME;?></td>
                
                <td><?php echo $edition->USERNAME;?></td>
                <td><?php echo $edition->PROP_DTE;?></td>
                
            </tr>
            <?php 
            }} ?>
             <?php if (isset ($view->dbs_prop)) { 
                foreach ($view->dbs_prop->a_dataQuery as $prop) {  ?>
            <tr>
                <td><?php echo $prop->SERIE;?></td>
                <td><?php echo $prop->NUM_TOME;?></td>
                <td><?php echo $prop->TITRE;?></td>
                
                <td><?php echo $prop->USERNAME;?></td>
                <td><?php echo $prop->PROP_DTE;?></td>
                
            </tr>
            <?php 
            }} ?>
            
        </tbody>
    </table>
</div>
<script>	
$(document).ready(function() {
    $('#propal').dataTable({
        "paging":   false,
        "ordering": true,
        "info":     false,
        "searching": false,
        "order": [[ 0, "asc" ]]
    } );
} );

</script>
