
<!-- cadre central de la page -->

<div class="cadre1">
	<h1>Bienvenue sur BDovore</h1>
	Gérer votre collection de bandes dessinées en ligne via une
	gargantuesque liste de plus de <strong>140 000</strong> <a
		href="<?php echo BDO_URL;?>listlast">BDs</a> : <a
		href="<?php echo BDO_URL;?>browser?lev_id=51&totalRows_RecAuteur=11&let=manga&user=&rb_browse=genr&pageNum_RecAuteur=0#L151">Mangas</a>,
	<a
		href="<?php echo BDO_URL;?>browser?lev_id=12&totalRows_RecAuteur=2&let=comics&user=&rb_browse=genr&pageNum_RecAuteur=0#L112">Comics</a>,
	<a
		href="<?php echo BDO_URL;?>browser?lev_id=82&let=revue&user=&rb_browse=genr&pageNum_RecAuteur=0">revues</a>,
	<a
		href="<?php echo BDO_URL;?>browser?lev_id=82&let=periodique&user=&rb_browse=genr&pageNum_RecAuteur=0">périodiques</a>,
	<a
		href="<?php echo BDO_URL;?>browser?lev_id=14&totalRows_RecAuteur=1&let=documentaire&user=&rb_browse=genr&pageNum_RecAuteur=0#L114">ouvrages
		d'étude</a>, <a
		href="<?php echo BDO_URL;?>browser?lev_id=4&totalRows_RecAuteur=2&let=art&user=&rb_browse=genr&pageNum_RecAuteur=0#L14">recueils
		d'illustrations</a> et puis des <a
		href="<?php echo BDO_URL;?>browser?lev_id=12&totalRows_RecAuteur=2&let=comics&user=&rb_browse=genr&pageNum_RecAuteur=0#L112">BD</a>,
	des <a
		href="<?php echo BDO_URL;?>browser?lev_id=65&totalRows_RecAuteur=1&let=autobiographie&user=&rb_browse=genr&pageNum_RecAuteur=0#L165">BD</a>,
	des <a
		href="<?php echo BDO_URL;?>browser?lev_id=6&totalRows_RecAuteur=4&let=aventure&user=&rb_browse=genr&pageNum_RecAuteur=0#L16">BD</a>,
	des <a
		href="<?php echo BDO_URL;?>browser?lev_id=51&totalRows_RecAuteur=11&let=manga&user=&rb_browse=genr&pageNum_RecAuteur=0#L151">BD</a>
	et encore <a
		href="<?php echo BDO_URL;?>browser?lev_id=37&totalRows_RecAuteur=69&rb_browse=genr&pageNum_RecAuteur=1#L137">des
		BD</a>. <a href="<?php echo BDO_URL;?>tutoriel" style="font-weight: bold;">Découvrez
		BDovore !</a>
</div>



<div id="bx-pager" style="margin:auto; text-align:center">
  <a data-slide-index="0" href="">[ Dernières sorties ]</a> - 
  <a data-slide-index="1" href="">[ Sorties à venir ]</a> - 
  <a data-slide-index="2" href="">[ Derniers avis ]</a>
</div>
<div class="slider2">
    <div class="slide" style="background-color:#fff">
        <div class="slideBdo">
            <div class="middle_title"><h3>Dernières sorties</h3></div>

            <?php
            foreach ($view->a_lastSorties as $lastSorties) {
                ?><div style="float:left;margin:5px 0 5px 5px"><?php echo urlAlbum ( $lastSorties ,'couvBig');?></div>
            <?php
            }
            ?>
            <hr class="expSep" />	
        </div>
     </div>
     <div class="slide">
         <div class="slideBdo">
             <div class="middle_title"><h3>Sorties à venir</h3></div>
              		 <?php
            foreach ($view->a_futurSorties as $futurSorties) {
                ?><div style="float:left;margin:5px 0 5px 5px"><?php echo urlAlbum ( $futurSorties ,'couvBig');?></div>
            <?php
            }
            ?>	
                        <hr class="expSep" />	
            
        </div>
    </div>
    <div class="slide">
    <div class="slideBdo">
        <div class="middle_title"><h3>Derniers avis</h3></div>
        	 <?php
        foreach ($view->a_lastCommentaires as $lastCommentaires) {
            ?><div style="float:left;margin:5px 0 5px 5px"><?php echo urlAlbum ( $lastCommentaires ,'couvBig');?></div>
        <?php
        }
        ?>	
           <hr class="expSep" />	
        </div>
    </div>
</div>
<hr class="expSep" />


<script type="text/javascript">
$(document).ready(function(){
	  $('.slider2').bxSlider({
		    slideWidth: 650,
  		    minSlides: 1,
		    maxSlides: 1,
		    adaptiveHeight:true,
		    pagerCustom: '#bx-pager'

		  });
});
</script>


<?php echo $view->LASTNEWS;?>