
  <script src="<?php echo BDO_URL;?>jquery/datatable/js/jquery.dataTables.min.js" type="text/javascript"></script>
<?php
    $ficheAlbum = $view->getHelper('ficheAlbum');
    $page = $view->getHelper('pagination');


?>
<div align="center" class="cadre1">
   <?php echo $page->menuAdmin(); ?>
    <h1>Suivi des fiches auteurs</h1>

    <div class="cadre1">
        
    </div>
    <br>

    <div class="cadre1">
        <h3>100 Dernières modifications de fiche auteur</h3>
        <br />
        <table id="listAlbum">
            <thead>
                <th>Auteur</th>
                <th>Type</th>
                <th>Date de modification</th>
                <th>Correcteur</th>
            </thead>
            <tbody>
                <?php foreach ($view->dbs_auteur->a_dataQuery as $auteur) { ?>
                <tr>
                    <td><a href="<?php echo $ficheAlbum->getURLAuteur($auteur) ?>" target="_blank"><?php echo $auteur->PSEUDO;?> </a> <a class="fancybox fancybox.iframe {width:600,height:600}" href="admin/editauteur?auteur_id=<?php echo $auteur->ID_AUTEUR; ?>"> <img src="<?php echo BDO_URL_IMAGE; ?>edit.gif" /></a></td>
                    <td><?php echo ($auteur->FLG_SCENAR ? "S/" : "" ).($auteur->FLG_DESSIN ? "D/" : "" ).($auteur->FLG_COLOR ? "C/" : "" ); ?></td>
                    <td><?php echo $auteur->VALID_DTE; ?></td>
                    <td><?php echo $auteur->VALIDATOR_USERNAME; ?></td>
                </tr>

                <?php } ?>
            </tbody>
        </table>
    </div>
    

</div>
<script>
$(document).ready(function() {
    $('#listAlbum').dataTable({
        "paging":   true,
        "ordering": true,
        "info":     false,
        "searching": false,
        "order": [[ 2, "desc" ]]
    } );
} );

</script>