<?php

$ficheAlbum = $view->getHelper('ficheAlbum');



?>
<script src="<?php echo BDO_URL;?>jquery/AnythingSlider/js/jquery.anythingslider.min.js" type="text/javascript"></script>
<!--

-->
    <script language="JavaScript">

                $.datepicker.setDefaults( $.datepicker.regional[ "fr" ] );

        $(function() {
                    $( "#date_achat" ).datepicker({dateFormat: "dd/mm/yy"});
                });
        function changeEdition () {
            window.location="album?id_tome=<?php echo $view->tome->ID_TOME;?>&id_edition="+ document.getElementById('sel_edition').value+"&frame=<?php echo $view->frame;?>" ;
        }

        function liencorrection () {
            parent.location.href="prop_correct?alb_id=<?php echo $view->tome->ID_TOME;?>&id_edition="+ document.getElementById('sel_edition').value;
            window.close();
        }

        function openSerie(){
            if (window.name == "Album") {
                window.opener.location="<?php echo BDO_URL;?>SerieBD?id_serie=<?php echo $view->tome->ID_SERIE;?>";}
            else {
            parent.location="<?php echo BDO_URL;?>SerieBD?id_serie=<?php echo $view->tome->ID_SERIE;?>";
            }
        }

        function setDteAchat(){
                    if (!$("cb_achat").is(':checked')) {
                            d = new Date();
                            mm = d.getMonth() + 1;
                            yyyy = d.getFullYear();
                            dd = d.getDate();
                            dte = "";
                            if (dd < 10) {
                                    dte = "0" + dd;
                            }
                            else {
                                    dte += dd;
                            }
                            if (mm < 10) {
                                    dte = dte + "/0" + mm;
                            }
                            else {
                                    dte = dte + "/" + mm;
                            }
                            dte = dte + "/" + yyyy;
                            $("#date_achat").val(dte);
                }
}
        //-->
//                $( document ).ready(function() {
//                  getComment(page=1, id_tome=<?php echo $view->tome->ID_TOME;?> );
//                });




            function viewComment() {

                <?php  if ($view->connected) { ?>

                $(".writecomment").show(100);
               // offset = $(".writecomment").offset().top;
                //$('html, body').animate({scrollTop: offset}, 'slow');
                <?php }
                 else {
                                            echo "alert('Vous devez vous authentifier pour écrire un avis de lecture !');";
                                        }
                                        ?>
            }

            function myComment(){
                writeComment($("#id_tome").val(),$("input[name='note']").val()*2, $("#t_comment").val() );
                $("#listcomment").empty();


                getComment(page=1, id_tome=<?php echo $view->tome->ID_TOME;?>);
            }

           function saveCollection() {
               if (!isValidEmailAddress($("#email_pret").val()) && $("#email_pret").val() != "") {
                 alert("L'adresse email de l'emprunteur est erroné !");
             }
             else {
                $("#save_collection").html("<img src='./script/ajax-loader.gif'>");

                var url = "./Macollection/majcollection?id_edition="+$("#user_edition").val();
                url += "&id_tome="+<?php echo $view->tome->ID_TOME; ?>;
                url += "&flg_achat="+ ($("#cb_achat").is(':checked') ? "O" : "N");
                url+= "&flg_pret="+($("#cb_pret").is(':checked') ? "O" : "N");
                url+= "&flg_dedicace="+($("#cb_dedicace").is(':checked') ? "O" : "N");
                url+= "&flg_tete="+($("#cb_tete").is(':checked') ? "O" : "N");
                url+= "&flg_cadeau="+ ($("#cb_cadeau").is(':checked') ? "O" : "N");
                url+= "&flg_lu="+ ($("#cb_lu").is(':checked') ? "O" : "N");
                 url+= "&flg_num="+ ($("#cb_num").is(':checked') ? "O" : "N");
                url+= "&date_achat="+$("#date_achat").val();
                url+= "&email_pret="+$("#email_pret").val();
                url+= "&nom_pret="+$("#nom_pret").val();
                url+= "&cote="+$("#prix").val();
                url+= "&comment="+encodeURIComponent($("#remarque").val());
                //alert (url);


                $.getJSON(url, function (data) {

                           if (data.length == 0) {$("#save_collection").html('<input type="button" value="Enregistrer les modifications" onclick="saveCollection();"/> <br>Données mises à jour !')};

                        }

                   );
                }
            }
    </script>


<div class="conteneuralb" itemprop="mainEntity" itemscope itemtype="http://schema.org/Book">

            <div class="alb-img">
                            <div id="couv"><img src="<?php echo ($view->tome->IMG_COUV ? BDO_URL_COUV.$view->tome->IMG_COUV : BDO_URL_COUV.'default.png' ); ?>" itemprop="image" name="imgEdition" id="imgEdition" alt="couverture" border="1"></div>
                            <div class="petite_police">&copy;<?php echo $view->tome->NOM_EDITEUR;?>/<?php echo $view->tome->scpseudo; ?></div>
                            <div class="petite_police"><?php echo $view->tome->COMMENT_EDITION ;?></div>
                            <div id="sponsor" align="center"><?php echo $ficheAlbum->getSponsor($view->tome, $img=true, $all=true); ?></div>
            </div>

        <div class="contentalb" id="alb-description">
            <h3 align="center"><?php echo $ficheAlbum->getTitreTome($view->tome,$url=false);?> <br>
                            <?php echo $ficheAlbum->urlSerie($view->tome,"_parent");?></h3>
            <p align="center">
            <?php if ($view->tome->NB_NOTE_TOME > 0) { ?> 
             <div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating"> 
                 <font size="-1">
            <meta itemprop='ratingValue' content='<?php echo $view->tome->MOYENNE_NOTE_TOME / 2.0; ?>'  />
                  <span id="noteTome<?php echo $view->tome->ID_TOME; ?>" style="vertical-align: -3px;"> </span> 
                  pour <span itemprop="reviewCount"><?php echo $view->tome->NB_NOTE_TOME ?></span> notes. 
             <script>$('#noteTome<?php echo $view->tome->ID_TOME; ?>').raty({score: <?php echo $view->tome->MOYENNE_NOTE_TOME/2.0; ?>, readOnly: true});</script> 
             </font></div>  <?php ;} ?>

             </p>
             <span itemprop="genre"><?php echo $view->tome->NOM_GENRE;?></span>  -   <?php echo $ficheAlbum->urlAuteur(array("ID_AUTEUR" => $view->tome->ID_SCENAR, "PSEUDO" => $view->tome->scpseudo),$target="_parent"). ($view->tome->scapseudo == "Aucun" ? "" : " - ".$ficheAlbum->urlAuteur(array("ID_AUTEUR" => $view->tome->ID_SCENAR_ALT,"PSEUDO" => $view->tome->scapseudo),$target="_parent"));
            if ($view->tome->scpseudo <> $view->tome->depseudo || $view->tome->deapseudo <> "Aucun" ) echo "/".$ficheAlbum->urlAuteur(array("ID_AUTEUR" => $view->tome->ID_DESSIN, "PSEUDO" => $view->tome->depseudo),$target="_parent").($view->tome->deapseudo == "Aucun" ? "" : " - ". $ficheAlbum->urlAuteur(array("ID_AUTEUR" => $view->tome->ID_DESSIN_ALT, "PSEUDO" => $view->tome->deapseudo),$target="_parent")); ?>
            <?php if ($view->tome->copseudo <> $view->tome->depseudo and $view->tome->copseudo <> "Aucun" and $view->tome->copseudo <> "<indéterminé>") echo "<br>Couleur : ".$ficheAlbum->urlAuteur(array("ID_AUTEUR" =>$view->tome->ID_COLOR,"PSEUDO" => $view->tome->copseudo),$target="_parent"); ?>
            <br> <b>Edition </b><font size="-1">
                            <?php if (count($view->dbs_edition->a_dataQuery) == 1) {
                                    if ($view->dateparution) {
                                        $dateparution = new DateTime($view->dateparution);
                                        $txt_dte = " - ".$dateparution->format("d/m/Y");
                                    }
                                    else {
                                        $txt_dte = "";
                                    }
                                    echo ' <span itemprop="publisher">'.$view->tome->NOM_EDITEUR.'</span>'.$txt_dte ;
                                    $edition_selected = $view->tome->ID_EDITION;
                                }
                                else {
                                    echo '<select name="select" onchange="changeEdition()" id="sel_edition">';
                                    $edition_selected = $view->tome->USER_EDITON ? $view->tome->USER_EDITON : $view->tome->ID_EDITION;
                                    foreach ($view->dbs_edition->a_dataQuery as $edition){
                                        // on ajoute les options
                                        echo '<option value="'.$edition->ID_EDITION .'"'.($edition->ID_EDITION == $edition_selected ? 'selected=""' : '') .'>'.$edition->NOM_EDITION .'</option>';
                                    }
                                    echo "</select>";
                                }
                            if (isset($view->tome->NOM_COLLECTION)) {
                                echo $view->tome->NOM_COLLECTION == "<N/A>" ? "" : "<br> Collection ".$view->tome->NOM_COLLECTION;
                                } ?></font>
                <br>
                <?php echo ($view->tome->FLG_TYPE_TOME == 1) ? "Coffret<br>" : "" ;?>
                <span class="petite_police"> 
                         <?php if ($view->tome->EAN_EDITION) {?>   EAN : <span itemprop="isbn"> <?php echo $view->tome->EAN_EDITION;?> </span>| <?php } ?>
                         <?php if ($view->tome->ISBN_EDITION AND !$view->tome->EAN_EDITION) {?> ISBN : <span itemprop="isbn"><?php echo $view->tome->ISBN_EDITION;?> </span>| <?php } ?> ID-BDovore : <?php echo $view->tome->ID_TOME;?> 
                </span>
                <br>
                <div class="action" id="action-menu">
                    <div align="center">
                        <div id="infoCollection<?php echo $view->tome->ID_TOME; ?>"></div>
                    </div>
                 </div>
    </div>

    <hr class="expSep">
    <div class="synopsis">
            <?php if ($view->tome->HISTOIRE_TOME <> "") { ?>
                <strong>Synopsis :</strong>

            <font size="-1"><?php echo nl2br($view->tome->HISTOIRE_TOME);?> </font>
                  
            <?php } ?><br>
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5aa565c61fcc82d7"></script> 
         <div class="addthis_inline_share_toolbox"></div>
        <br>
        <div id="simil">
            <a href="<?php echo BDO_URL;?>discovery?ID_TOME=<?php echo $view->tome->ID_TOME ?>" target="_parent" title="Albums similaires..." align="right">== Vous aimerez aussi peut être... ==</a>
            <br>
        </div>
        <br>
        <div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;">
            <p>
                <span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span><i>Une erreur sur cette fiche ou votre édition est différente ? Vous pouvez
                    <a href="<?php echo BDO_URL; ?>Proposition?id_edition=<?php echo $edition_selected; ?>" >
                    <b>proposer une correction</b>
                </a></i> ou 
                     <i><a href="<?php echo BDO_URL; ?>Proposition?type=EDITION&id_tome=<?php echo $view->tome->ID_TOME; ?>">
                <b>proposer l'ajout d'une autre édition</b></a></i>
            </p>
        </div>
    </div>
    
<hr class="expSep">
<div id="info_collection">
    <center><strong>Données privées</strong><br><span class="petite_police">(pour votre utilisation personnelle)</span></center>
    <hr style="align: center; width: 50%;">
    <input type="hidden" id="user_edition" value="<?php echo $view->tome->ID_EDITION; ?>" />
    <table>
        <tr>
            <td>
                Futur achat : <input name="cb_achat" id="cb_achat" value="O" type="checkbox" onclick="setDteAchat();">
                Date d'achat : <span class="petite_police">(dd/mm/aaaa)</span>  <input name="date_achat" id="date_achat" value="" size="10" maxlength="10" type="text">
                Prix/cote :<input class="numbersOnly" name="prix" id="prix" value="" size="4" maxlength="8" type="text">
            </td>
        </tr>
        <tr>
            <td>
                E.O :   <input name="cb_tete" id="cb_tete" value="O" type="checkbox" >
                Dédicace : <input name="cb_dedicace" id="cb_dedicace" value="O" type="checkbox" >
                Cadeau :<input name="cb_cadeau" id="cb_cadeau" value="checkbox" type="checkbox" >
                Lu :<input name="cb_lu" id="cb_lu" value="checkbox" type="checkbox" >
                Ed. numérique :<input name="cb_num" id="cb_num" value="checkbox" type="checkbox" >
            </td>
        </tr>
        <tr>
            <td>
                Prêt :
                <input name="cb_pret" id="cb_pret" value="checkbox" type="checkbox">
                Dernier emprunteur :
                <input name="nom_pret" id="nom_pret" value="" size="15" maxlength="100" type="text" >
                Email :
                <input name="email_pret" id="email_pret" value="" size="15" maxlength="100" type="text">
            </td>
        </tr>
        <tr>
            <td>
                Remarque personnelle (état, mémo, ...) :
                <textarea name="remarque" id="remarque" class="champ_commentaire"></textarea>
            </td>
        </tr>
    </table>
    <div id="save_collection"><input type="button" value="Enregistrer les modifications" onclick="saveCollection();"/></div>
</div>

<hr class="expSep">
<div class="comment" id="comment">
    <font color="#990000" face="Arial, Helvetica, sans-serif" size="-1">
    <strong>Commentaires des membres :</strong> <a onclick="viewComment();">

        (vous pouvez également donner un avis de lecture)

    </a>
    </font>
    <div >

        <table width="100%" border="0" align="center">
            

            <tr>
                <td>
                    <b><i>Ma Note:</i></b>
                    <span id="commentRaty" onclick="viewComment()"></span>
                    <script>$("#commentRaty").raty({ scoreName: 'note', half : true})</script>

                </td>
            </tr>
            <tr class="writecomment">
                <td>Avis de lecture * :
                    <textarea id="t_comment" class="champ_commentaire"></textarea></td>
            </tr>


            <tr class="writecomment">
                <td>

                    <input name="id_tome" type="hidden" id="id_tome" value="<?php echo $view->tome->ID_TOME ?>" />
                    <input type="submit" name="Submit" value="Enregistrer note/avis" onclick="myComment();"/>
                    <em>
                        <br><font size="-1">
                        * : Avis de lecture qui apparaîtra pour tous les visiteurs sur le site
                        <br />
                        </font>
                    </em>
                </td>
            </tr>
        </table>


    </div>
    <br>

    <div id="listcomment">
            <?php $i=0; foreach ($view->dbs_comment->a_dataQuery as $comment) { 
                $i++;
                $id_cmt = $view->tome->ID_TOME."_".$i;
                ?>
            <div class='listcomment' itemprop='review' itemscope itemtype='http://schema.org/Review' id="cmt-<?php echo $comment->user_id."-".$comment->ID_TOME; ?>"> 
                <div itemprop='reviewRating' itemscope itemtype='http://schema.org/Rating'>
                    <meta itemprop='worstRating' content = '1'/>
                    <meta itemprop='ratingValue' content='<?php echo round($comment->NOTE/2.0, 1); ?>' />
                    <span id='noteTome<?php echo $id_cmt ;?>'></span><meta itemprop='bestRating' content = '5'/>
                </div> 
                Posté par <span itemprop='author'><a href='./guest?user=<?php echo $comment->user_id; ?>' target='parent'><?php echo $comment->username; ?></a></span> le <meta itemprop='datePublished' content='<?php echo $comment->DTE_POST?>'><?php echo $comment->DTE_POST?>  
                <p>
                 <span itemprop='description'> <?php echo stripslashes(nl2br($comment->COMMENT)); ?></span></p> 
                <?php if ($comment->NOTE > 0) { ?>
                <script>$('#noteTome<?php echo $id_cmt ;?>').raty({score: <?php echo $comment->NOTE; ?>/2.0 , readOnly: true});</script>
                <?php } ?>
            </div>
              
                <div class="cadre1" id="social-<?php echo $comment->user_id."-".$comment->ID_TOME; ?>">
                        <ul class="social" style="list-style: none;/*! position: relative; *//*! left: 50%; *//*! margin-right: 3px; */font-size: 0.8em;float: right;">
                            <li style="float: left;/*! margin-left: 5px; *//*! padding-left: 5px; */"> 1 j'aime</li>
                            <li style="float: left;margin-left: 5px;padding-left: 5px;">2 commentaires</li>
                        </ul>
                        <div class="social">
                            <a><i class="far fa-thumbs-up" id="like-<?php echo $comment->user_id."-".$comment->ID_TOME; ?>" onClick="likeComment(<?php echo $comment->user_id; ?>, <?php echo $comment->ID_TOME ?>);"> J'aime</i></a> - 
                            <a><i class="far fa-comment-alt" id="add-cmt-<?php echo $comment->user_id."-".$comment->ID_TOME; ?>" onclick='$("#writecmt-<?php echo $comment->user_id."-".$comment->ID_TOME; ?>").toggle();'> Commenter</i></a>
                        </div>
                        <hr class="expSep">
                          <div class="cmt-social" style="width: 95%;float: right;padding-right:10px;" id="writecmt-<?php echo $comment->user_id."-".$comment->ID_TOME; ?>" >
                                  <textarea id="txt-<?php echo $comment->user_id."-".$comment->ID_TOME; ?>"  class="champ_commentaire"></textarea>
                                  <input type="button" value="Ok" style="float:right;" onclick="addCommentToReview(<?php echo $comment->user_id.",".$comment->ID_TOME; ?>);">
                          
                          </div>
                         <hr class="expSep">
                                        <div class="cmt-social" style="width:90%;float:right;" id="lst-cmt-<?php echo $comment->user_id."-".$comment->ID_TOME; ?>">
                                            
                                        </div>
                           <hr class="expSep">
                  </div> 
        <script>getSocialInfo(<?php echo $comment->user_id; ?>, <?php echo $comment->ID_TOME ?>);
        $("#lst-cmt-<?php echo $comment->user_id."-".$comment->ID_TOME; ?>").hide();</script>
            <?php } 
            if ($i == 0) { ?>
                    <i>Aucun commentaire pour cet album actuellement. <a onclick='viewComment();'>Soyez le premier !</a></i>
            <?php } ?>
    </div>


</div>
</div>
<script language="javascript">
   $(".writecomment").hide();
   $("#info_collection").hide();
   <?php if (User::minAccesslevel(2)) { ?>
      // récupération de l'éventuelle commentaire du membre
       var url = "./AlbumComment?page=1&id_tome=<?php echo $view->tome->ID_TOME; ?>&user_id=<?php echo $_SESSION['userConnect']->user_id;?>&all=1";
       $.getJSON(url,function (data) {
        if (data.length > 0) {
            $("#commentRaty").raty({ scoreName: 'note', half : true, score : data[0].NOTE / 2});
            $("#t_comment").val(data[0].COMMENT);
            $(".writecomment").show();
        }
        });

     function getInfoCollection () {
          $("#actionCollection").html("<img src='"+$.bdovore.URL+ "script/ajax-loader.gif'>");
     var url = $.bdovore.URL+"getjson?data=Useralbum&id_edition=<?php echo $view->tome->ID_EDITION?>";
      $.getJSON(url, function (data) {
          if (typeof data.data[0] == 'undefined') {
               // l'album n'est pas dans la collection : on ajoute les boutons
                $("#info_collection").hide();
                // Affichage des boutons
               /*  var madiv = '<div id="addAlbum<?php echo $view->tome->ID_EDITION; ?>" style="font-size:0.9em;"><a class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" href="javascript:addAlbum(<?php echo $view->tome->ID_TOME; ?>, <?php echo $view->tome->ID_EDITION; ?>,false, \'N\')" title="Ajouter cet album dans votre collection">Collection</a> - <a class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" href="javascript:addAlbum(<?php echo $view->tome->ID_TOME; ?>, <?php echo $view->tome->ID_EDITION; ?>,false, \'O\')" title="A acheter prochainement">Futur Achat</a></div>';
               $("#actionCollection").html(madiv);*/

           }
           else {
               $("#info_collection").show();
                var dte = data.data[0].DATE_AJOUT.substring(8,10) + "/" +   data.data[0].DATE_AJOUT.substring(5,7) + "/" +  data.data[0].DATE_AJOUT.substring(0,4);
               /* if (data[0].FLG_ACHAT === "O") {
                    $("#actionCollection" ).html('<div id="addAlbum' + <?php echo $view->tome->ID_EDITION; ?> + '" style="font-size:0.9em;">futur achat depuis le ' +dte + '<br><a class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" href="#" onclick="addAlbum(' + <?php echo $view->tome->ID_TOME; ?> + ', ' + <?php echo $view->tome->ID_EDITION; ?> + ',false\'N\');$(\'#cb_achat\').attr(\'checked\', false);" title="Ajouter cet album dans votre collection">Dans ma collection</a>  - <a class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="Supprimer l\' édition de ma collection" onclick="deleteEdition(' + <?php echo $view->tome->ID_EDITION; ?> + ')">Supprimer</a></div>');
                } else {
                    $("#actionCollection").html('<div id="addAlbum' + <?php echo $view->tome->ID_EDITION; ?> + '" style="font-size:0.9em;">ajouté à votre collection le ' + dte + ' - <a class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="Supprimer l\' édition de ma collection" onclick="deleteEdition(' + <?php echo $view->tome->ID_EDITION; ?> + ')">Supprimer</a></div>');
                }*/
              // $("#actionCollection").html('<div id="addAlbum<?php echo $view->tome->ID_EDITION; ?>" style="font-size:0.9em;">ajouté à votre collection le '+data[0].DATE_ACHAT.substring(0,10) +' - <a class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="Supprimer l\' édition de ma collection" onclick="deleteEdition(<?php echo $view->tome->ID_EDITION; ?>)">Supprimer</a></div>');

               // on renseigne chaque champs du formulaire
               if (data.data[0].FLG_ACHAT == 'O') {
                   $('#cb_achat').attr('checked', true);
               } else {
                   $("#date_achat").val(data.data[0].DATE_ACHAT.substring(8,10)+ '/' + data.data[0].DATE_ACHAT.substring(5,7)+ '/' + data.data[0].DATE_ACHAT.substring(0,4));
               }
                if (data.data[0].FLG_PRET == 'O') {
                   $('#cb_pret').attr('checked', true);
               }
               if (data.data[0].FLG_LU == 'O') {
                   $('#cb_lu').attr('checked', true);
               }
               $("#prix").val(data.data[0].cote);

                if (data.data[0].FLG_TETE == 'O') {
                   $('#cb_tete').attr('checked', true);
               }
               if (data.data[0].FLG_DEDICACE == 'O') {
                   $('#cb_dedicace').attr('checked', true);
               }
               if (data.data[0].FLG_CADEAU == 'O') {
                   $('#cb_cadeau').attr('checked', true);
               }
               if (data.data[0].FLG_NUM == 'O') {
                   $('#cb_num').attr('checked', true);
               }
               $("#nom_pret").val(data.data[0].NOM_PRET);
               $("#email_pret").val(data.data[0].EMAIL_PRET);
               $("#remarque").val(data.data[0].comment);
                $("#user_edition").val(data.data[0].ID_EDITION);
           }

        }

    );
    }
    getInfoCollection ();
    getInfoCollectionFromTome(<?php echo $view->tome->ID_SERIE; ?>, <?php echo $view->tome->ID_TOME; ?>, <?php echo $view->tome->ID_EDITION; ?>, exclu = <?php echo $view->tomeexclu; ?>)
   <?php } ?>
         $('.numbersOnly').keyup(function () {
                       this.value = this.value.replace(/[^0-9\.]/g,'');
                   });

     /* add simil */
     $( document ).ready(
             function () {
        var url_simil = "./simil/getTopSimil?ID_TOME=<?php echo $view->tome->ID_TOME; ?>";
        $.getJSON(url_simil, function (data) {
            if (data.length > 0) {

                for (var i=0; i<3;i++){
                    $("#simil").append("<a href='./Album?id_tome="+data[i].ID_TOME+  "&mobile=<?php echo $view->mobile; ?>&frame=<?php echo $view->frame; ?>' title='"+ data[i].TITRE_TOME.replace(/'/g, " ") +"'><img class= 'couvMedium' src='<?php echo BDO_URL_IMAGE;?>couv/"+ data[i].IMG_COUV+"'></a>&nbsp;");
                }
            }
        });});
</script>
