<script src="<?php echo BDO_URL;?>jquery/jquery.mask.min" type="text/javascript"></script>
<SCRIPT type="text/javascript"><!--
function newWindow(myCategory,myText,myForm,myElement,isMandatory,myEditeur) {
	if ((isMandatory == true) && (myText.length < 2)) {
		alert('Veuillez saisir au moins 2 caractères');
	}else {
		if (myCategory == "collection") {
			if (myEditeur == '') {
				alert("Veuillez saisir l'éditeur en premier");
			}else {
                mywindow=open("pickup?cat=" + myCategory + "&text=" + myText + "&ReturnDoc=" + myForm + "&ReturnElement=" + myElement + "&IdEditeur=" + myEditeur,'myname','scrollbars=yes,resizable=yes,width=350,height=270');
			}
		}else {
			mywindow=open('pickup?cat=' + myCategory + "&text=" + myText + "&ReturnDoc=" + myForm + "&ReturnElement=" + myElement,'myname','scrollbars=yes,resizable=yes,width=350,height=270');
		}
	}
}
function verifFieldNull(myField) {
    if(myField == "0") {
        alert('Veuillez attribuer une série à l\'album rogntudju !');
        return false;
    }else{
        return true;
    }
}
function verifAddExisting(myIdTome,myAction) {
    if(myAction == "2") {
        alert("Le membre ne semble pas avoir demandé qu'un album soit ajouté à sa collection ou futurs achats.");
        return false;
    }else if(myIdTome == "") {
        alert("Veuillez indiquer l'identifiant de l'album rogntudju !");
        return false;
    }else{
        return true;
    }
}
//--></SCRIPT>
<script src="<?php echo BDO_URL;?>script/genautocomplete.js" type="text/javascript"></script>
<div class="fond_admin">
	<div class="titre_admin">Traitement des albums en attente</div>
	<div class="date_before_valid"><?php echo $view->DATEBEFOREVALID;?></div>
    <table width="100%">
        <tr>
            <form action="<?php echo $view->URLACTION;?>" method="post" enctype="multipart/form-data" name="myform" target="_self" id="myform" onsubmit="return verifFieldNull(document.myform.txtSerieId.value);">
                <!--Debut colonne gauche -->
                <td width="65%" valign="top">
                    <table class="tableaux_admin">
                        <tr> 
                            <td width="15%" class="label" align="center">Album</td>
                            <input name="txtPropId" type="hidden" id="txtPropId" value="<?php echo $view->PROPID;?>" />
                            <td width="85%">
                                <input name="txtTitre" type="text" id="txtTitre" value="<?php echo $view->TITRE;?>" size="65%" class="<?php echo $view->CLTITRE;?>" />
                            </td>
                        </tr>
                        <tr bordercolor="#FFFFCC"> 
                            <td><!--DWLayoutEmptyCell-->&nbsp;</td>
                            <td class="original"><?php echo $view->ORITITRE;?>&nbsp;</td>
                        </tr>
                        <tr bordercolor="#FFFFCC"> 
                            <td colspan="2" class="label">
                                <table width="100%" border="0">
                                    <tr>
                                        <td width="25%" align="center">Type</td>
                                        <td width="25%" align="center">Tome</td>
                                        <td width="25%" align="center">Int&eacute;grale</td>
                                        <td width="25%" align="center">Prix</td>
                                    </tr>
                                    <tr>
                                        <td align="center">
                                            <select name="lstType" size="1"><?php echo $view->OPTTYPE;?></select>
                                        </td>
                                        <td align="center"><input name="txtNumTome" type="text" id="txtNumTome" value="<?php echo $view->TOME;?>" size="2" class="<?php echo $view->CLTOME;?>" /></td>
                                        <td align="center"><input type="checkbox" name="chkIntegrale" value="checkbox" <?php echo $view->ISINT;?> /></td> 
                                        <td align="center"><input name="txtPrixVente" type="text" id="txtPrixVente" value="<?php echo $view->PRIX_VENTE;?>" size="3" style="text-align: center;" /></td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr bordercolor="#FFFFCC"> 
                            <td class="label">Intro Tome</td>
                            <td valign="top">
                                <textarea name="txtHistoire" class="champ_commentaire"><?php echo $view->HISTOIRE;?></textarea>
                            </td>
                        </tr>
                    </table>
                    
                    <table class="tableaux_admin">
                        <tr> 
                            <td class="label" align="center">Serie</td>
                            <td>
                                <div align="center"> 
                                    <input name="txtSerieId" type="text" id="txtSerieId2" value="<?php echo $view->IDSERIE;?>" size="3" class="<?php echo $view->CLIDSERIE;?>" />
                                </div>
                            </td>
                            <td>
                                <input name="txtSerie" type="text" id="txtSerie3" value="<?php echo $view->SERIE;?>" size="40" class="<?php echo $view->CLSERIE;?>" /> <?php echo $view->LIENEDITSERIE;?>
                            </td>
                            <td>
                                <img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('serie',document.myform.txtSerie.value,'myform','txtSerie',true)" />
                            </td>
                        </tr>
                        <tr> 
                            <td colspan="2">&nbsp;</td>
                            <td class="original"><?php echo $view->ORISERIE;?></td>
                            <td><!--DWLayoutEmptyCell-->&nbsp;</td>
                        </tr>
                        <tr> 
                            <td width="15%" class="label" align="center">Genre</td>
                            <td width="14%"> 
                                <div align="center"> 
                                    <input name="txtGenreId" id="txtGenreId" type="text" value="<?php echo $view->IDGENRE;?>" size="1" class="<?php echo $view->CLIDGENRE;?>" />
                                </div>
                            </td>
                            <td width="65%">
                                <input name="txtGenre" id="txtGenre" type="text" value="<?php echo $view->GENRE;?>" size="30"class="<?php echo $view->CLGENRE;?>" />
                            </td>
                            <td width="6%">
                                <img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('genre',document.myform.txtGenre.value,'myform','txtGenre',false)" />
                            </td>
                        </tr>
                        <tr> 
                            <td colspan="2">&nbsp;</td>
                            <td class="original"><?php echo $view->ORIGENRE;?></td>
                            <td>&nbsp;</td>
                        </tr>
                    </table>
                    
                    <table class="tableaux_admin">
                        <tr> 
                            <td width="18%" class="label">
                                Scenariste
                            </td>
                            <td width="10%">
                                <input name="txtScenarId" id="txtScenarId" type="text" value="<?php echo $view->IDSCEN;?>" size="4" class="<?php echo $view->CLIDSCEN;?>" />
                            </td>
                            <td width="59%">
                                <input name="txtScenar" id="txtScenar" type="text" value="<?php echo $view->SCENARISTE;?>" size="33"class="<?php echo $view->CLSCENARISTE;?>" />
                            </td>
                            <td width="13%">
                                <img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('auteur',document.myform.txtScenar.value,'myform','txtScenar',true)" />
                            </td>
                        </tr>
                        <tr> 
                            <td colspan="2">&nbsp;</td>
                            <td class="original"><?php echo $view->ORISCENARISTE;?></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr> 
                            <td width="18%" class="label">
                                Scenariste #2
                            </td>
                            <td width="10%">
                                <input name="txtScenarAltId" id="txtScenarAltId" type="text" value="<?php echo $view->IDSCENALT;?>" size="4" class="<?php echo $view->CLIDSCENALT;?>" />
                            </td>
                            <td width="59%">
                                <input name="txtScenarAlt" id="txtScenarAlt" type="text" value="<?php echo $view->SCENARISTEALT;?>" size="33"class="<?php echo $view->CLSCENARISTEALT;?>" />
                            </td>
                            <td width="13%">
                                <img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('auteur',document.myform.txtScenarAlt.value,'myform','txtScenarAlt',true)" />
                            </td>
                        </tr>
                        <tr> 
                            <td colspan="2">&nbsp;</td>
                            <td class="original"><?php echo $view->ORISCENARISTEALT;?></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr> 
                            <td class="label">Dessinateur</td>
                            <td> <input name="txtDessiId" id="txtDessiId" type="text" value="<?php echo $view->IDDESS;?>" size="4" class="<?php echo $view->CLIDDESS;?>"></td>
                            <td> <input name="txtDessi" id="txtDessi" type="text" value="<?php echo $view->DESSINATEUR;?>" size="33" class="<?php echo $view->CLDESSINATEUR;?>"></td>
                            <td> <img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('auteur',document.myform.txtDessi.value,'myform','txtDessi',true)"></td>
                        </tr>
                        <tr> 
                            <td colspan="2">&nbsp;</td>
                            <td class="original"><?php echo $view->ORIDESSINATEUR;?></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr> 
                            <td class="label">Dessinateur #2</td>
                            <td> <input name="txtDessiAltId" id="txtDessiAltId" type="text" value="<?php echo $view->IDDESSALT;?>" size="4" class="<?php echo $view->CLIDDESSALT;?>"></td>
                            <td> <input name="txtDessiAlt" id="txtDessiAlt" type="text" value="<?php echo $view->DESSINATEURALT;?>" size="33" class="<?php echo $view->CLDESSINATEURALT;?>"></td>
                            <td> <img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('auteur',document.myform.txtDessiAlt.value,'myform','txtDessiAlt',true)"></td>
                        </tr>
                        <tr> 
                            <td colspan="2">&nbsp;</td>
                            <td class="original"><?php echo $view->ORIDESSINATEURALT;?></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr> 
                            <td class="label">Coloriste</td>
                            <td> <input name="txtColorId" id="txtColorId" type="text" value="<?php echo $view->IDCOLOR;?>" size="4" class="<?php echo $view->CLIDCOLOR;?>"></td>
                            <td> <input name="txtColor" id="txtColor" type="text" value="<?php echo $view->COLORISTE;?>" size="33" class="<?php echo $view->CLCOLORISTE;?>"></td>
                            <td> <img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('auteur',document.myform.txtColor.value,'myform','txtColor',true)"></td>
                        </tr>
                        <tr> 
                            <td colspan="2">&nbsp;</td>
                            <td class="original"><?php echo $view->ORICOLORISTE;?></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr> 
                            <td class="label">Coloriste #2</td>
                            <td> <input name="txtColorAltId" id="txtColorAltId" type="text" value="<?php echo $view->IDCOLORALT;?>" size="4" class="<?php echo $view->CLIDCOLORALT;?>"></td>
                            <td> <input name="txtColorAlt" id="txtColorAlt" type="text" value="<?php echo $view->COLORISTEALT;?>" size="33" class="<?php echo $view->CLCOLORISTEALT;?>"></td>
                            <td> <img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('auteur',document.myform.txtColorAlt.value,'myform','txtColorAlt',true)"></td>
                        </tr>
                        <tr> 
                            <td colspan="2">&nbsp;</td>
                            <td class="original"><?php echo $view->ORICOLORISTEALT;?></td>
                            <td>&nbsp;</td>
                        </tr>
                    </table>

                    <table class="tableaux_admin">
                        <tr> 
                            <td width="16%" class="label">Editeur</td>
                            <td width="12%" align="center"><input name="txtEditeurId" id="txtEditeurId" type="text" value="<?php echo $view->IDEDIT;?>" size="3" class="<?php echo $view->CLIDEDIT;?>" /></td>
                            <td width="58%"><input name="txtEditeur" id="txtEditeur" type="text" value="<?php echo $view->EDITEUR;?>" size="33"class="<?php echo $view->CLEDITEUR;?>" onchange="changeEditeur();" /></td>
                            <td width="14%"><img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('editeur',document.myform.txtEditeur.value,'myform','txtEditeur',true)"></td>
                        </tr>
                        <tr> 
                            <td colspan="2">&nbsp;</td>
                            <td class="original"><?php echo $view->ORIEDITEUR;?></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr> 
                            <td class="label">Collection</td>
                            <td align="center"><input name="txtCollecId" id="txtCollecId" type="text" value="<?php echo $view->IDCOLLEC;?>" size="3" class="<?php echo $view->CLIDCOLLEC;?>" /></td>
                            <td><select name="txtCollec" id="txtCollec" class="<?php echo $view->CLCOLLECTION;?>" onchange="$('#txtCollecId').val($('#txtCollec').val());"></select></td>
                            <td><img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('collection',document.myform.txtCollec.value,'myform','txtCollec',false,document.myform.txtEditeurId.value)"></td>
                        </tr>
                        <tr> 
                            <td colspan="2">&nbsp;</td>
                            <td class="original"><?php echo $view->ORICOLLECTION;?></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr> 
                            <td colspan="4" class="label">
                                <table class="tableaux_admin_sans-bord">
                                    <tr> 
                                        <td align="center">
                                            <a href="<?php echo $view->URLEAN;?>" title="Teste le code EAN sur BDNet" target="_blank">EAN</a> : 
                                            <input name="txtEAN" type="text" value="<?php echo $view->EAN;?>" size="14" /><?php echo $view->ISEAN;?>
                                        </td>
                                        <td align="center">
                                            <a href="<?php echo $view->URLISBN;?>" title="Teste le code ISBN sur Amazon" target="_blank">ISBN</a> : 
                                            <input name="txtISBN" type="text" value="<?php echo $view->ISBN;?>" size="10" /><?php echo $view->ISISBN;?>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr> 
                            <td colspan="4" class="label">
                                <table class="tableaux_admin_sans-bord">
                                    <tr> 
                                        <td width="22%" align="center">
                                            Date Parution
                                            <div class="petite_police" style="margin-bottom: 10px;">(aaaa-mm-jj)</div>
                                            <input name="txtDateParution" type="text" id="txtDateParution" value="<?php echo $view->DTPAR;?>" size="10" />
                                        </td>
                                        <td width="1%" align="center"></td>
                                        <td width="8%" align="center">
                                            <div>Tirage de t&ecirc;te</div>
                                            <input type="checkbox" name="chkTT" value="checkbox" <?php echo $view->ISTT;?> />
                                        </td>
                                        <td width="1%" align="center"></td>
                                        <td width="68%" align="center">
                                            Description de l'édition<br />
                                            <textarea name="txtCommentEdition" class="textarea_description_edition"><?php echo $view->COMMENT;?></textarea>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                    <br />
                    <table class="tableaux_admin">
                        <tr> 
                            <td colspan="4" bordercolor="#FFFFCC" class="label">
                                <p>
                                    <b>Ajouter comme nouvelle édition d'un album d&eacute;j&agrave; existant<br /></b>
                                </p>
                            </td>
                        </tr>
                        <tr> 
                            <td width="14%" class="label"><div align="center">Album</div></td>
                            <td width="13%">
                                <div align="left"> 
                                    <input name="txtExistingTomeId" type="text" id="txtExistingTomeId" value="" size="5" />
                                </div>
                            </td>
                            <td width="62%"><input name="txtExistingTome" type="text" id="txtExistingTome" value="" size="40" /></td>
                            <td width="11%"><img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('album',document.myform.txtExistingTome.value,'myform','txtExistingTome',true)"></td>
                        </tr>
                    </table>
                    <div align="center"> 
                        <p></p>
                        <div style="float: left;">Simple mise à jour de la proposition :</div>
                        <div align="center" style="width: 20px; margin: auto; text-align: center;"><input type="checkbox" name="chkUpdate" value="O" /></div>
                        <br />
                        <input type="submit" name="Submit" value="<?php echo $view->ACTIONNAME;?>" />
                        <br />
                        <br />
                        <br />
                        <table width="100%">
                            <tr align="center">
                                <td width="35%">
                                    <?php echo $view->BOUTONPRECEDENT;?>
                                </td>
                                <td width="30%">
                                    &nbsp;
                                </td>
                                <td width="35%">
                                    <?php echo $view->BOUTONSUIVANT;?>
                                </td>
                            </tr>
                            <tr><td colspan="3">&nbsp;</td></tr>
                            
                        </table>
                    </div>
                <!--Fin colonne gauche -->
                </td>
                
                
                <!--Debut colonne droite -->
                <td width="35%" valign="top">
                    <table width="100%" cellpadding="5" bgcolor="#D35E5E" style="font-size: 0.9em;">
                        <tr> 
                            <td width="25%" align="center" class="to_be_corrected">
                                rouge
                            </td>
                            <td width="75%" align="center">
                                Absence d'Information ou de Validation
                            </td>
                        </tr>
                        <tr> 
                            <td align="center" class="has_changed">jaune</td>
                            <td align="center">Champ non validé ou Validé puis modifié</td>
                        </tr>
                        <tr>
                            <td align="center" class="original">gris</td>
                            <td align="center">Information actuellement dans la base</td>
                        </tr>
                    </table>
                    <table class="tableaux_admin">
                        <tr> 
                            <td align="center">
                                <img src="<?php echo $view->URLIMAGE;?>" width="180" border="0" align="absmiddle" />
                                <br />
                                <?php echo $view->DIMIMAGE;?>
                            </td>
                        </tr>
                        <tr> 
                            <td class="label">
                                Redimensionner la couverture :
                                <input type="checkbox" name="chkResize" value="checked" />
                            </td>
                        </tr>
                        <tr> 
                            <td class="label">
                                Envoyer depuis un fichier local :
                                <br /><input name="txtFileLoc" type="file" id="txtFileLoc2" style="width: 100%;" class="flat" />
                            </td>
                        </tr>
                        <tr> 
                            <td class="label">
                                Envoyer depuis une URL :
                                <br /><input name="txtFileURL" type="text" id="txtFileURL2" style="width: 100%;" class="flat" />
                            </td>
                        </tr>
                        <tr> 
                            <td class="label">
                                Effacer cette couverture :
                                <input type="checkbox" name="chkDelete" value="checked" />
                            </td>
                        </tr>
                    </table>
            </form>
                    <table class="cadre_texte-admin">
                        <tr>
                            <td>
                                <div class="b">Bla bla des correcteurs</div>
                                <form action="<?php echo $view->URLCOMMENTCORR;?>" method="post" name="formcorr">
                                    <p class="texte">
                                        Statut courant de la proposition :
                                        <select name="cmbStatus" size="1" style="background-color: <?php echo $view->COLOR_STATUS;?>;"><?php echo $view->OPTIONSTATUS;?></select>
                                    </p>
                                    <span class="texte">Commentaires des correcteurs<br /></span>
                                    <textarea name="txtCommentCorr" class="textarea_description_edition" style="background-color: <?php echo $view->COLOR_STATUS;?>; border: 1px dotted #FFFFFF;"><?php echo $view->CORRCOMMENT;?></textarea>
                                    <br />
                                    <?php echo $view->CURRENTSTATUS;?>
                                    <input name="txtComBut" value="Valider" type="submit" />
                                </form>
                            </td>
                        </tr>
                    </table>	
                    <table class="cadre_texte-admin">
                        <tr>
                            <td>
                                <p class="texte"><b>Albums Approchants</b></p>
                                <div class="texte">
                                     <!-- BEGIN CloseBlock -->
                                    <?php foreach ($view->dbs_tome->a_dataQuery as $tome) { ?>
                                     <div class="mw50 left">
                                      <a href="<?php echo BDO_URL."admin/editalbum?alb_id=".$tome->ID_TOME;?>" target="_blank"><?php echo $tome->TITRE_TOME;?></a><br />
                                     </div>
                                    <?php } ?>
                                      <!-- END CloseBlock -->
                                </div>
                            </td>
                        </tr>
                    </table>
                    <table class="cadre_texte-admin">
                        <form action="<?php echo $view->URLUTILVALID;?>" method="post" name="subform" id="subform" onsubmit="return verifAddExisting(document.subform.txtFutAlbId.value, document.subform.PropAction.value)">
                            <tr>
                                <td>
                                    <p class="texte"><b>Ajout d'un album existant</b></p>
                                    <p class="texte">
                                        Action sur la collection de l'utilisateur : <span class="b"><?php echo $view->ACTIONUTIL;?></span>
                                    </p>
                                    <p>
                                        <input name="PropAction" type="hidden" id="PropAction" value="<?php echo $view->PROPACTION;?>" />
                                        <input name="txtFutAlbId" type="text" id="txtFutAlbId" size="5" /> 
                                        <input name="txtFutAlb" type="text" id="txtFutAlb" size="23" /> 
                                        <img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('album',document.subform.txtFutAlb.value,'subform','txtFutAlb',true)">
                                    </p>
                                    <p>
                                        <input name="txtFutButton" value="Valider" type="submit" />
                                    </p>
                                    <p class="texte">
                                        Aide : Si l'album propos&eacute; existe d&eacute;j&agrave; 
                                        et que l'utilisateur a demand&eacute; l'ajout de cet album dans 
                                        sa collection, sélectionner l'album 
                                        existant via le formulaire et valider.
                                    </p>
                                </td>
                            </tr>
                        </form>
                    </table>
                    <table class="cadre_texte-admin">
                        <tr>
                            <td>
                                <p class="texte">
                                    <div class="b">Contact</div>
                                    <a href="mailto:<?php echo $view->ADRESSEMAIL;?>?subject=<?php echo $view->MAILSUBJECT;?>" class="b">
                                        Envoyer un email à <?php echo $view->MEMBRE;?>
                                    </a>
                                    (<?php echo $view->ADRESSEMAIL;?>)
                                </p>
                            </td>
                        </tr>
                    </table>
                    <table class="cadre_texte-admin">
                        <tr>
                            <td>
                                <p class="texte">
                                    <b>Menu Express</b>
                                </p>
                                <div class="texte">
                                    <a href='<?php echo BDO_URL;?>admin/addserie' class="fancybox fancybox.iframe {width:400,height:160}">
                                        Ajout rapide d'une série
                                    </a>
                                    <br />
                                    <a href='<?php echo BDO_URL;?>admin/addauteur' class="fancybox fancybox.iframe {width:400,height:160}">
                                        Ajout rapide d'un auteur
                                    </a>
                                </div>
                            </td>
                        </tr>
                    </table>
                </td>
                <!--Fin colonne droite -->
            <!--Fermeture du form plus haut -->
        </tr>
    </table>
    <table width="64%">
        <form action="<?php echo $view->URLDELETE;?>" method="post" name="subform2">
            <tr align="center">
                <td class="cadre_texte-admin">
                    <span class="texte">En cas de <span class="b">suppression</span>, le contenu (à modifier) du champ suivant sera envoyé par email à l'utilisateur :</span>
                    <br />
                    <div class="b">Sujet : <?php echo $view->SUJET_EMAIL;?></div>
                    <textarea name="txtMailRefus" class="textarea_description_edition" style="height: 12em;"><?php echo $view->CORPS_EMAIL;?></textarea>
                    <br />
                    <input type="submit" value="Supprimer" name="subform2" />
                </td>
            </tr>
        </form>
    </table>
</div>
<script>
    /*
     * On remplit les champs de saisie par l'autocompletion
     * 
     */
    
    addAutocomplete("txtSerie3","txtSerieId2","txtSerieId2","<?php echo BDO_URL; ?>getjson?data=Serie");
    addAutocomplete("txtGenre","txtGenreId","txtGenreId","<?php echo BDO_URL; ?>getjson?data=Genre");
    addAutocomplete("txtScenar","txtScenarId","txtScenarId","<?php echo BDO_URL; ?>getjson?data=Auteur");
    addAutocomplete("txtScenarAlt","txtScenarAltId","txtScenarAltId","<?php echo BDO_URL; ?>getjson?data=Auteur");
    addAutocomplete("txtDessiAlt","txtDessiAltId","txtDessiAltId","<?php echo BDO_URL; ?>getjson?data=Auteur");
    addAutocomplete("txtDessi","txtDessiId","txtDessiId","<?php echo BDO_URL; ?>getjson?data=Auteur");
    
     addAutocomplete("txtColor","txtColorId","txtColorId","<?php echo BDO_URL; ?>getjson?data=Auteur");
     addAutocomplete("txtColorAlt","txtColorAltId","txtColorAltId","<?php echo BDO_URL; ?>getjson?data=Auteur");
     addAutocomplete("txtEditeur","txtEditeurId","txtEditeurId","<?php echo BDO_URL; ?>getjson?data=Editeur");
     
     addAutocomplete("txtExistingTome","txtExistingTomeId","txtExistingTomeId","<?php echo BDO_URL; ?>getjson?data=Album");
     
     addAutocomplete("txtFutAlb","txtFutAlbId","txtFutAlbId","<?php echo BDO_URL; ?>getjson?data=Album");
     changeEditeur();
    function changeEditeur() {
        addSelectOption("txtCollec","<?php echo BDO_URL; ?>getjson?data=Collection&id_editeur="+$("#txtEditeurId").val(),<?php echo $view->IDCOLLEC + 0;?>);
        $('#txtCollecId').val(<?php echo $view->IDCOLLEC + 0;?>);
        //addAutocomplete("txtCollec","spCollec","txtCollecId","<?php echo BDO_URL; ?>getjson?data=Collection&id_editeur="+$("#txtEditeurId").val());
    }
    
    $(document).ready(function(){
  $('#txtDateParution').mask('0000-00-00', {placeholder: "0000-00-00"});
});
</script>
    
