
        
<?php
    $ficheAlbum = $view->getHelper('ficheAlbum');
    $page = $view->getHelper('pagination');
   $date_courante_21 = new DateTime();
   $date_courante_21->modify("+ ".$view->validationdelay." days");
     // Tableau pour les choix d'options
            $opt_type[0][0] = 0;
            $opt_type[0][1] = 'Album';
            $opt_type[1][0] = 1;
            $opt_type[1][1] = 'Coffret';

            $opt_action[0] = "Insérer dans la collection";
            $opt_action[1] = "Insérer comme achat futur";
            $opt_action[2] = "Aucune";

            $opt_status[0][0] = 0;
            $opt_status[0][1] = "En cours";
            $opt_status[1][0] = 2;
            $opt_status[1][1] = "En pause";
            $opt_status[2][0] = 3;
            $opt_status[2][1] = "Aide requise";
            $opt_status[3][0] = 4;
            $opt_status[3][1] = "Aide apportée";
           
?>
<script src="<?php echo BDO_URL;?>jquery/datatable/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script>

function deleteProposition(idpropale,typeprop){
    var url = "<?php echo BDO_URL ?>adminproposition/deleteproposition?src=list&ID="+idpropale+"&type="+typeprop;
    $.getJSON(url, function(data){
        if (data.length == 0) {
            alert("Proposition supprimée !");
            window.location.reload();
            
        } else
            {
                alert("Erreur lors de la suppression !");
            }
    });
}
</script>
<div align="center" class="cadre1">
   <?php echo $page->menuAdmin(); ?>
    <h1>Administration des propositions</h1>
    
    <div class="cadre1">
        <h3>Propositions en attente : </h3>
         Il y a actuellement <a href="?type=AJOUT"><b><?php echo $view->NBAJOUT;?> propositions d'album</b></a>, <a href="?type=EDITION"><b><?php echo $view->NBEDITION;?> propositions de nouvelle édition</b></a>
             et <a href="?type=CORRECTION"><b><?php echo $view->NBCORRECTION;?> propositions de correction</b></a>
             en cours de traitement pour l'ensemble de la communauté BDovore.
            <br />
    </div>
    
     <div class="cadre1">
        
         <div class="fond_admin">
	<div class="titre_admin"><?php echo $view->TITRE_ADMIN;?></div>
	<div class="date_before_valid"><?php echo $view->DATEBEFOREVALID;?></div>
    <table class="donnees" align="center" id="propal">
        <thead> 
            <td width="70" class="entete_admin">
                ID
           </td>
            <td width="83" class="entete_admin">
                Date
           </td>
            <td width="131" class="entete_admin">
                Utilisateur
           </td>
            <td width="166" class="entete_admin">
                Série
            </td>
            <td width="166" class="entete_admin">
                Titre
            </td>
            <td width="70" class="entete_admin">
                Statut
            </td>
            <td width="30" class="entete_admin"><img src="<?php echo BDO_URL_IMAGE;?>edit.gif" width="18" height="13" title="Consulter la proposition" /></td>
            <td width="30" class="entete_admin"><img src="<?php echo BDO_URL_IMAGE;?>poubelle.gif" width="25" height="24" title="Supprimer la proposition" /></td>
        </thead>
        <tbody>
        <!-- BEGIN PropBlock -->
        <?php if (issetNotEmpty($view->dbs_prop))  { foreach ($view->dbs_prop->a_dataQuery as $prop) { 
                $date_parution = new DateTime($prop->DTE_PARUTION);
		
                if ($date_parution > $date_courante_21){
			$stylevaliddelay = 'style="background-color: #FFDB70;" title="Parution le '.$prop->DTE_PARUTION.'"';
		  
                }
                ?>
            <tr> 
                <td class="data_admin"><?php echo $prop->ID_PROPOSAL;?></td>
                <td class="data_admin_petit"><?php echo $prop->PROP_DTE;?></td>
                <td class="data_admin"><?php echo $prop->USERNAME;?></td>
                <td class="data_admin"><?php echo $prop->SERIE;?></td>
                <td class="data_admin"><?php echo $prop->TITRE;?></td>
                <td class="data_admin <?php echo "status".$prop->STATUS;?>"><?php echo GetOption1Value($opt_status,$prop->STATUS);?></td>
                <td class="data_admin"><a href="<?php echo $view->URLEDIT.$prop->ID_PROPOSAL;?>"><img src="<?php echo BDO_URL_IMAGE;?>edit.gif" width="18" height="13" border="0" /></a></td>
                <td class="data_admin" <?php echo $stylevaliddelay;?>><a onclick="deleteProposition(<?php echo $prop->ID_PROPOSAL; ?>,'AJOUT');"><img src="<?php echo BDO_URL_IMAGE;?>poubelle.gif" width="20" height="21" border="0" /></a></td>
            </tr>
        <?php }} ?>
            <?php if (issetNotEmpty($view->dbs_edition))  { foreach ($view->dbs_edition->a_dataQuery as $prop) { 
                 $date_parution = new DateTime($prop->DATE_PARUTION_EDITION);
		
                if ($date_parution > $date_courante_21){
			$stylevaliddelay = 'style="background-color: #FFDB70;" title="Parution le '.$prop->DTE_PARUTION.'"';
		  
                }?>
            <tr> 
                <td class="data_admin"><?php echo $prop->ID_EDITION;?></td>
                <td class="data_admin_petit"><?php echo $prop->PROP_DTE;?></td>
                <td class="data_admin"><?php echo $prop->USERNAME;?></td>
                <td class="data_admin"><?php echo $prop->NOM_SERIE;?></td>
                <td class="data_admin"><?php echo $prop->TITRE_TOME;?></td>
                <td class="data_admin <?php echo "status".$prop->PROP_STATUS;?>"><?php echo GetOption1Value($opt_status,$prop->PROP_STATUS);?></td>
                <td class="data_admin"><a href="<?php echo $view->URLEDIT.$prop->ID_EDITION;?>"><img src="<?php echo BDO_URL_IMAGE;?>edit.gif" width="18" height="13" border="0" /></a></td>
                <td class="data_admin" <?php echo $view->STYLE_VALIDDELAY;?>><a onclick="deleteProposition(<?php echo $prop->ID_EDITION ?>,'EDITION');"><img src="<?php echo BDO_URL_IMAGE;?>poubelle.gif" width="20" height="21" border="0" /></a></td>
            </tr>
        <?php }} ?>
            
        </tbody>
        <!-- END PropBlock --> 
    </table>
</div>
    </div>
     
</div>
<script>	
$(document).ready(function() {
    $('#propal').dataTable({
        "paging":   false,
        "ordering": true,
        "info":     false,
        "searching": false,
        "order": [[ 0, "asc" ]]
    } );
} );

</script>