<script src="<?php echo BDO_URL; ?>jquery/jQuery-TE_v.1.4.0/jquery-te-1.4.0.min.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="<?php echo BDO_URL;?>jquery/jQuery-TE_v.1.4.0/jquery-te-1.4.0.css" />
<div class="cadre1">
    <form method='post' action='?status=ok'>
    <h3>Publication d'une nouvelle news</h3>
    <br>
    
    Titre : <input name="txttitre" id="txttitre" value="<?php echo $view->titrenews;?>" size="50" type="text" /> <br/>
    <textarea name="txtcontent" cols="45" rows="8" id="txtcontent"><?php echo $view->txtnews;?></textarea>
    <input type='hidden' id='newsid' value='<?php echo $view->newsid;?>'/>
    <p align="center"><input type='submit' value="Valider" /></p>
    </form>
</div>
<script>$("#txtcontent").jqte(); </script>
    
    