<?php
$ficheAlbum = $view->getHelper('ficheAlbum');
?>
<div class="colleft">
    <div class="col1wrap">
        <div class="col1 fond">
            <!-- Column 1 start -->

            <div class="middle_title">
                <h3>Le Guide BD</h3>
            </div>
            <form id="form1" name="form1" method="get">
                <div id="select_origine">
                    <label for="o1">BD </label>  <input type="radio" name="origine" id="o1" value="1" <?php if ($view->origine == 1) echo "checked"; ?> onclick="$('#form1').submit();">  <label for="o2">Mangas </label> <input type="radio" name="origine" id="o2" value="2" <?php if ($view->origine == 2) echo "checked"; ?> onclick="$('#form1').submit();">  <label for="o3">Comics</label>  <input type="radio" name="origine" id="o3" value="3" <?php if ($view->origine == 3) echo "checked"; ?> onclick="$('#form1').submit();">
                    &nbsp; <div id="select_genre">Genre : <select data-placeholder="Choisir un ou plusieurs genres..." name="a_idGenre[]" id="a_idGenre" style="width:350px;" multiple="multiple" size="10">

<?php
foreach ($view->dbs_genre->a_dataQuery as $genre) {

    $selected = (isset($_GET['a_idGenre']) and (in_array($genre->ID_GENRE, $_GET['a_idGenre']))) ? 'selected' : '';

    echo '<option value="' . $genre->ID_GENRE . '" ' . $selected . '>' . $genre->LIBELLE . '</option>';
}
?>

                        </select>  <input type="submit" name="submitGuide" value="Ok"></div>
                </div>
                <br>

                <div  id="rb_mode">
                                <input id="rb_mode2" name="rb_mode" value="3" <?php echo $view->a_chGuide[2]["checked"]; ?> onclick="$('#form1').submit();" type="radio"><label for="rb_mode2">Avis</label>
                                <input id="rb_mode3" name="rb_mode" value="4" onclick="$('#form1').submit();" <?php echo $view->a_chGuide[3]["checked"]; ?> type="radio"><label for="rb_mode3">Nouveautés</label>
                                 <input id="rb_mode6" name="rb_mode" value="7" onclick="$('#form1').submit();" <?php echo $view->a_chGuide[6]["checked"]; ?> type="radio"><label for="rb_mode6">Tendances</label>
                                <input id="rb_mode4" name="rb_mode" value="5" onclick="$('#form1').submit();" <?php echo $view->a_chGuide[4]["checked"]; ?> type="radio"><label for="rb_mode4">A paraitre</label>

                                <input id="rb_mode5" name="rb_mode" value="6" onclick="$('#form1').submit();" <?php echo $view->a_chGuide[5]["checked"]; ?> type="radio"><label for="rb_mode5">Ajouts</label>
                                <input id="rb_mode0" name="rb_mode" value="1" onclick="$('#form1').submit();" <?php echo $view->a_chGuide[0]["checked"]; ?> type="radio"><label for="rb_mode0">Top Bdovore</label>
                                <input id="rb_mode1" name="rb_mode" value="2" onclick="$('#form1').submit();" <?php echo $view->a_chGuide[1]["checked"]; ?>  type="radio"><label for="rb_mode1">Incontournables</label>
                            </div>


                    </tr>

                </table>

            </form>

            <br>

<?php
if (isset($view->dbs_tome)) {?>
    <table class="list_album">

     <?php
     $tr = true;
    foreach ($view->dbs_tome->a_dataQuery as $tome) {
        if ($tr)
               echo "<tr>";

            echo "<td class='mw50'>" . $ficheAlbum->big($tome,$sep=true,$getUrlSerie=true) . "</td>";

        if (!$tr) {
            echo "</tr>";
        }
        $tr = !$tr;

    }
    if (!$tr)
                        echo "</tr>";
    ?>
    </table>
 <?php
}

if (isset($view->dbs_serie)) {?>
    <table class="list_album">

     <?php
     $tr = true;

    foreach ($view->dbs_serie->a_dataQuery as $serie) {
        if ($tr)
               echo "<tr>";

            echo "<td class='mw50'>" . $ficheAlbum->serie($serie,"big");

    if (!$tr) {
            echo "</tr>";
        }
        $tr = !$tr;

    }
    if (!$tr)
                        echo "</tr>";
    ?>
    </table>
 <?php
}

if (isset($view->dbs_comment)) {
    //echo ("<table>");

    foreach ($view->dbs_comment->a_dataQuery as $tome) {
        ?>

                    <div class='cadre1'>
                        
                            <div style='vertical-align:top;float:left;padding-right:10px'>
                    <?php echo $ficheAlbum->urlalbum($tome, 'couvBig'); ?>


                                </div>
                                <div>

                                    <strong><?php echo $ficheAlbum->urlalbum($tome, 'albTitle'); ?></strong>
                                     <br><span id='noteTome<?php echo $tome->ID_TOME; ?>'> </span>   <?php if (User::minAccesslevel(1)) { ?>
                                    <a title="Passer ce commentaire en status privé" onclick="setCommentPrivate(<?php echo $tome->user_id;?>,<?php echo $tome->ID_TOME; ?>);"><img src="<?php echo BDO_URL_IMAGE;?>poubelle.gif"></a>
                                        <?php } ?><br>
                                    <span class="fiche_album">
                                     S&eacute;rie : <?php echo $ficheAlbum->urlSerie($tome); ?> <br>
                                    Publié par <a href='./guest?user=<?php echo $tome->user_id; ?>'><?php echo $tome->username; ?></a> le <?php echo $tome->DTE_POST; ?>
                                    
                                    </span>
                                  
                                       <p> <?php echo (stripslashes(nl2br($tome->COMMENT))); ?>
                                </div>
                         <hr class="expSep" />
                        
                    </div>
                    <script>$('#noteTome<?php echo $tome->ID_TOME; ?>').raty({score: <?php echo $tome->NOTE / 2; ?>, readOnly: true});</script>
                  
    <?php
    }
}
?><div align="center">
<?php
// pagination

$a_qstring = $_GET;
unset($a_qstring["page"]);
$qstring = http_build_query($a_qstring);
if ($view->NUM_PAGE > 1)
    echo "<a href='./leguide?" . $qstring . "&page=" . ($view->NUM_PAGE - 1) . "'>Précédent &nbsp;</a>";
if ($view->NUM_PAGE < 20)
    echo "<a href='./leguide?" . $qstring . "&page=" . ($view->NUM_PAGE + 1) . "'>&nbsp;Suivant</a>";
?>
            </div>
            <!-- Column 1 end -->
        </div>
    </div>
    <!-- Debut de la partie de droite -->
    <div class="col2">
        <!-- Column 2 start -->
               <!-- Column 2 start -->
        <div id="actu" class="right fond">
        <div class="middle_title">
            <h3>Actualité</h3>
        </div>
            
            <div class="right">
        <?php 
         $genre ="";
        foreach ($view->ACTUAIR as $actu) { 
            if ($actu->ORIGINE_GENRE <> $genre) {
                echo "<div class='middle_content'>".$actu->ORIGINE_GENRE ."</div>";
            }
            echo $ficheAlbum->urlAlbum($actu,$class="couvMedium",$sponsor=FALSE)." ";
            $genre = $actu->ORIGINE_GENRE;
      } ?>
            </div>
        </div>
         <div id="last" class="right fond">
    <div class="middle_title">
    <h3><a href="<?php echo BDO_URL;?>leguide?rb_mode=6&rb_list=album&submitGuide=Envoyer">Derniers ajouts</a>
    <a href="<?php echo BDO_URL;?>rss">
    <img src="<?php echo BDO_URL_IMAGE;?>site/feed.png" style="border: 0;" alt="logo fil rss" title="Suivez l'actualité des ajouts d'albums sur le site grace à ce fil rss" />
    </a></h3>
    </div>
        <div class="cadre1" style="margin:3px 3px 3px 3px ;">
            <?php 
           
            foreach ($view->LASTAJOUT as $ajout) {
                echo $ficheAlbum->urlAlbum($ajout,$class="albTitle")."<br />";
            }?>
        </div>
        
         </div>
        <!-- Column 2 end -->
    </div>
</div>
<script>
    $(document).ready(function() {
        $("#select_origine").buttonset();
         $("#rb_mode").buttonset();
          $("#a_idGenre").chosen({max_selected_options: 10});
    });

</script>
