<?php
  $ficheAlbum = $view->getHelper('ficheAlbum');
?>
<div class="colleft">
  <div class="col1wrap">
    <div class="col1 fond">
      <!-- Column 1 start -->
      <div class="middle_title">
        <h3>Le Guide BD</h3>
      </div>
      <br />
      <form id="form1" name="form1" method="get">
        <div class="nbGalerie">
          <div class="nbConteneur">
            <div class="newButton">
              <input type="radio" name="origine" id="o1" value="1" <?php if ($view->origine == 1) echo "checked"; ?> onclick="$('#form1').submit();">  
              <label for="o1">BD</label>
              <input type="radio" name="origine" id="o2" value="2" <?php if ($view->origine == 2) echo "checked"; ?> onclick="$('#form1').submit();">  
              <label for="o2">Mangas</label> 
              <input type="radio" name="origine" id="o3" value="3" <?php if ($view->origine == 3) echo "checked"; ?> onclick="$('#form1').submit();">
              <label for="o3">Comics</label>  
            </div>
          </div>
          
            <div id="select_genre">
              <br />
              <select data-placeholder="Choisir un ou plusieurs genres..." name="a_idGenre[]" id="a_idGenre" style="width:350px;" multiple="multiple" size="10">
              <?php
                foreach ($view->dbs_genre->a_dataQuery as $genre) {
                    $selected = (isset($_GET['a_idGenre']) and (in_array($genre->ID_GENRE, $_GET['a_idGenre']))) ? 'selected' : '';
                    echo '<option value="' . $genre->ID_GENRE . '" ' . $selected . '>' . $genre->LIBELLE . '</option>';
                }
              ?>
              </select>  <input type="submit" name="submitGuide" value="Ok">
            </div>
        </div>
        <br />

        <div  class="nbConteneur">
          <div class="newButton">
            <input id="rb_mode2" name="rb_mode" value="3" <?php echo $view->a_chGuide[2]["checked"]; ?>  type="radio">
            <label for="rb_mode2"><a href="<?php echo BDO_URL; ?>leguide/avis" style="color:white;">Avis</a></label>
            <input id="rb_mode3" name="rb_mode" value="4" <?php echo $view->a_chGuide[3]["checked"]; ?> type="radio">
            <label for="rb_mode3"><a href="<?php echo BDO_URL; ?>leguide/sorties_bd" style="color:white;">Nouveautés</a></label>
            <input id="rb_mode6" name="rb_mode" value="7" <?php echo $view->a_chGuide[6]["checked"]; ?> type="radio">
            <label for="rb_mode6"><a href="<?php echo BDO_URL; ?>leguide/actualites_bd" style="color:white;">Tendances</a></label>
            <input id="rb_mode4" name="rb_mode" value="5" <?php echo $view->a_chGuide[4]["checked"]; ?> type="radio">
            <label for="rb_mode4"><a href="<?php echo BDO_URL; ?>leguide/prochaines_sorties_bd" style="color:white;">A paraitre</a></label>

            <input id="rb_mode5" name="rb_mode" value="6" <?php echo $view->a_chGuide[5]["checked"]; ?> type="radio">
            <label for="rb_mode5"><a href="<?php echo BDO_URL; ?>leguide/ajouts" style="color:white;">Ajouts</a></label>
            <input id="rb_mode0" name="rb_mode" value="1" <?php echo $view->a_chGuide[0]["checked"]; ?> type="radio">
            <label for="rb_mode0"><a href="<?php echo BDO_URL; ?>leguide/top_bd" style="color:white;">Top Bdovore</a></label>
            <input id="rb_mode1" name="rb_mode" value="2" <?php echo $view->a_chGuide[1]["checked"]; ?>  type="radio">
            <label for="rb_mode1"><a href="<?php echo BDO_URL; ?>leguide/incontournables" style="color:white;">Incontournables</a></label>
          </div>
        </div>
      </form>

      <br />

<?php
if (isset($view->dbs_tome)) {?>
    <table class="list_album">

     <?php
     $tr = true;
    foreach ($view->dbs_tome->a_dataQuery as $tome) {
        if ($tr)
               echo "<tr>";

            echo "<td class='mw50'>" . $ficheAlbum->big($tome,$sep=true,$getUrlSerie=true) . "</td>";

        if (!$tr) {
            echo "</tr>";
        }
        $tr = !$tr;

    }
    if (!$tr)
                        echo "</tr>";
    ?>
    </table>
 <?php
}

if (isset($view->dbs_serie)) {?>
    <table class="list_album">

     <?php
     $tr = true;

    foreach ($view->dbs_serie->a_dataQuery as $serie) {
        if ($tr)
               echo "<tr>";

            echo "<td class='mw50'>" . $ficheAlbum->serie($serie,"big");

    if (!$tr) {
            echo "</tr>";
        }
        $tr = !$tr;

    }
    if (!$tr)
                        echo "</tr>";
    ?>
    </table>
 <?php
}

if (isset($view->dbs_comment)) {
    //echo ("<table>");

    foreach ($view->dbs_comment->a_dataQuery as $tome) {
        ?>

                    <div class='cadre1'itemscope itemtype="http://schema.org/Book" >
                        <table>
                            <tr><td style='vertical-align:top'>
                    <?php echo $ficheAlbum->urlalbum($tome, 'couvBig'); ?>


                                </td>
                                <td style='vertical-align:top;width:100%'>

                                    <?php echo $ficheAlbum->getTitreTome($tome, true, true); ?><br>
                                     <?php if ((($tome->NOM_SERIE AND ($tome->TITRE_TOME AND (strtolower($tome->NOM_SERIE) != strtolower($tome->TITRE_TOME)) )))) echo $ficheAlbum->urlSerie($tome); ?>
                                    <div itemprop="review" itemscope itemtype="http://schema.org/Review">
                                    <div itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating" >
                                            <meta itemprop='ratingValue' content='<?php echo $tome->NOTE / 2; ?>' />   
                                            <meta itemprop="worstRating" content = "1">
                                            <meta itemprop="bestRating" content = "5">
                                            <span id='noteTome<?php echo $tome->ID_TOME."_".$tome->user_id; ?>'> </span>
                                    </div>
                                        <?php if (User::minAccesslevel(1)) { ?>
                                    <a title="Passer ce commentaire en status privé" onclick="setCommentPrivate(<?php echo $tome->user_id;?>,<?php echo $tome->ID_TOME; ?>);"><img src="<?php echo BDO_URL_IMAGE;?>poubelle.gif"></a>
                                        <?php } ?>
                                    <p class="fiche_album">
                                      
                                     Publié par <span itemprop='author'><a href='./guest?user=<?php echo $tome->user_id; ?>'><?php echo $tome->username; ?></a></span> le <meta itemprop='datePublished' content='<?php echo $tome->DTE_POST; ?>' /><?php echo $tome->DTE_POST; ?></p>
                                    <p>  <span itemprop='description'><?php echo (stripslashes(nl2br($tome->COMMENT))); ?></span>
                                    </div>
                                    <div class="cadre1" id="social-<?php echo $tome->user_id."-".$tome->ID_TOME; ?>">
                                            <ul class="social" style="list-style: none;/*! position: relative; *//*! left: 50%; *//*! margin-right: 3px; */font-size: 0.8em;float: right;">
                                                <li style="float: left;/*! margin-left: 5px; *//*! padding-left: 5px; */"> 1 j'aime</li>
                                                <li style="float: left;margin-left: 5px;padding-left: 5px;">2 commentaires</li>
                                            </ul>  
                                        <hr class="expSep">
                                      </div> 
                                        <div class="social">
                                                <a><i class="far fa-thumbs-up" id="like-<?php echo $tome->user_id."-".$tome->ID_TOME; ?>" onClick="likeComment(<?php echo $tome->user_id; ?>, <?php echo $tome->ID_TOME ?>);"> J'aime</i></a> - 
                                                <a><i class="far fa-comment-alt" id="add-cmt-<?php echo $tome->user_id."-".$tome->ID_TOME; ?>" onclick='$("#writecmt-<?php echo $tome->user_id."-".$tome->ID_TOME; ?>").toggle();'> Commenter</i></a>
                                        </div>
                                        <hr class="expSep">
                                          <div class="cmt-social" style="width: 95%;float: right;padding-right:10px;" id="writecmt-<?php echo $tome->user_id."-".$tome->ID_TOME; ?>" >
                                                  <textarea id="txt-<?php echo $tome->user_id."-".$tome->ID_TOME; ?>"  class="champ_commentaire"></textarea>
                                                  <input type="button" value="Ok" style="float:right;" onclick="addCommentToReview(<?php echo $tome->user_id.",".$tome->ID_TOME; ?>);">

                                          </div>
                                        <hr class="expSep">
                                        <div class="cmt-social" style="width:90%;float:right;" id="lst-cmt-<?php echo $tome->user_id."-".$tome->ID_TOME; ?>">
                                            
                                        </div>
                                        <hr class="expSep">
                                    <script>getSocialInfo(<?php echo $tome->user_id; ?>, <?php echo $tome->ID_TOME ?>);
                                            $("#lst-cmt-<?php echo $tome->user_id."-".$tome->ID_TOME; ?>").hide();
                                    </script>
                                 </td>                     
                        </tr>
                        </table>
                    </div>
                  <?php if ($tome->NOTE > 0) { ?> <script>$('#noteTome<?php echo $tome->ID_TOME."_".$tome->user_id; ?>').raty({score: <?php echo $tome->NOTE / 2; ?>, readOnly: true});</script><?php } ?>

    <?php
    }
}
?><div align="center">
<?php
// pagination

$a_qstring = $_GET;
unset($a_qstring["page"]);
$qstring = http_build_query($a_qstring);
if ($view->NUM_PAGE > 1)
    echo "<a href='".$_SERVER['PATH_INFO'] ."?" . $qstring . "&page=" . ($view->NUM_PAGE - 1) . "'>Précédent &nbsp;</a>";
if ($view->NUM_PAGE < 20)
    echo "<a href='".$_SERVER['PATH_INFO']."?" . $qstring . "&page=" . ($view->NUM_PAGE + 1) . "'>&nbsp;Suivant</a>";
?>
            </div>
            <!-- Column 1 end -->
        </div>
    </div>
    <!-- Debut de la partie de droite -->
    <div class="col2">
        <!-- Column 2 start -->
               <!-- Column 2 start -->
        <div id="actu" class="right fond">
            <div class="middle_title">
                <h3>Actualité</h3>
            </div>
            
            <div class="right">
                <?php 
                 $genre ="";
                foreach ($view->ACTUAIR as $actu) { 

                    echo $ficheAlbum->urlAlbum($actu,$class="couvMedium",$sponsor=FALSE)." ";

              } ?>
            </div>
        </div>
         <div id="last" class="right fond">
    <div class="middle_title">
    <h3><a href="<?php echo BDO_URL;?>leguide?rb_mode=6&rb_list=album&submitGuide=Envoyer">Derniers ajouts</a>
    <a href="<?php echo BDO_URL;?>rss">
    <img src="<?php echo BDO_URL_IMAGE;?>site/feed.png" style="border: 0;" alt="logo fil rss" title="Suivez l'actualité des ajouts d'albums sur le site grace à ce fil rss" />
    </a></h3>
    </div>
        <div class="cadre1" style="margin:3px 3px 3px 3px ;">
            <?php 
           
            foreach ($view->LASTAJOUT as $ajout) {
                echo $ficheAlbum->urlAlbum($ajout,$class="albTitle")."<br />";
            }?>
        </div>
        
         </div>
        <!-- Column 2 end -->
    </div>
</div>
<script>
    $(document).ready(function() {
        $("#select_origine").buttonset();
         $("#rb_mode").buttonset();
          $("#a_idGenre").chosen({max_selected_options: 10});
    });

</script>
