<?php
$ficheAlbum = $view->getHelper('ficheAlbum');
$pageinate = $view->getHelper('Pagination');
?>

<SCRIPT language="Javascript">
<!-- 

    function Chargement() {
        d = document.add_collect;
        for (i = 0; i < d.elements.length; i++) {
            if (d.elements[i].name == "sel_alb[]") {
                d.elements[i].checked = true;
            }
        }
    }

//--> 
</SCRIPT>
<div class="colleft">
<div class="col1wrap">
				<div class="col1 fond">
						
					
	
        <!-- Column 1 start -->


        <!-- cadre central de la page -->
        <div class="cadre1">
            <div style="float: right;">
                <!-- AddThis Button BEGIN -->
                <script type="text/javascript">var addthis_pub = "zeas";
    var addthis_brand = "BDovore";
    var addthis_header_color = "#990000";
    var addthis_header_background = "#DAC1B3";</script><a href="http://www.addthis.com/bookmark?v=20" onmouseover="return addthis_open(this, '', '[URL]', '[TITLE]')" onmouseout="addthis_close()" onclick="return addthis_sendto()"><img src="<?php echo BDO_URL_IMAGE; ?>site/lg-addthis-fr.gif" width="125" height="16" alt="Partager cette page" style="border:0"/></a>
                <noscript>
                <span class="petite_police"><br />Javascript absent/désactivé dans votre navigateur : bouton inactif</span>
                </noscript>
                <script type="text/javascript" src="http://s7.addthis.com/js/200/addthis_widget.js"></script>
                <!-- AddThis Button END -->
            </div>

            <div class="middle_title">
                <h3>Fiche Série 
           
<?php echo $view->serie->NOM_SERIE; ?> <?php if (User::minAccesslevel(1)) { ?><a class="fancybox fancybox.iframe {width:600,height:600}" href="admin/editserie?serie_id=<?php echo $view->serie->ID_SERIE; ?>"> <img src="<?php echo BDO_URL_IMAGE; ?>edit.gif" /></a> <?php } ?></h3></div>
            <br />
            <table><tr><td style="vertical-align:top">
          <img src="<?php echo BDO_URL_COUV.$view->serie->IMG_COUV_SERIE; ?>" class="couvBig" style="float:left; margin:2px;">
                    </td> 
                <td style="vertical-align:top">
                   <?php if ($view->serie->NB_NOTE_SERIE > 0) { ?> <span id="note_serie"></span>
                   <script>$("#note_serie").raty({score: <?php echo $view->serie->NOTE_SERIE/2.0; ?>, readOnly: true});</script> <?php } ?>
                    <div ><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
            <strong>Genre : </strong>
            </font>
<?php echo $view->serie->NOM_GENRE; ?>
            <br />
            <font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
            <strong>Nombre de tome: </strong>
            </font>
<?php echo $view->serie->NB_TOME; ?>
            <br />
            <font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
            <strong>Albums dans la base: </strong>
            </font>
<?php echo $view->serie->NB_ALBUM; ?>
            <br />
            <font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
            <strong>Avancement : </strong>
            </font>
<?php echo $view->serie->LIB_FLG_FINI_SERIE; ?>
            <br />
            <?php if ($view->serie->HISTOIRE_SERIE) { ?>
            <font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif">
            <strong>Synopsis : </strong>
            </font>
            <?php echo nl2br($view->serie->HISTOIRE_SERIE); ?>
            <?php } ?>
            </p>
            </div>
                </td>
          </table>
<?php echo $view->SERNOTE; ?>
                <br />
<hr class="expSep" />
                <!-- END CommentBlock -->

              <br> 
        </div>

       
            <div class="cadre1"><div class="middle_title">
 <h3>Albums </h3> </div>
                <!-- BEGIN AlbBlock -->
                <table class="list_album">
<?php
$tr = true;
foreach ($view->dbs_tome->a_dataQuery as $tome) {
    if ($tr)
        echo "<tr>";

    echo "<td class='mw50'>" . $ficheAlbum->big($tome,$sep=true,$getUrlSerie=false) . "</td>";

    if (!$tr) {
        echo "</tr>";
    }
    $tr = !$tr;
    ?>



                    <?php
                    }
                    if (!$tr)
                        echo "</tr>";
                    ?></table>

                <div align="center"> </div>

                <div align="center">
<?php
if ($view->serie->NB_ALBUM > 20) {
    $max_page = ceil($view->serie->NB_ALBUM / 20);
    if ($max_page > 1) {
        echo($pageinate->paginate($ficheAlbum->getURLSerie($view->serie ),"?page=",$max_page,$view->NUM_PAGE,$adj=3));
    }
   }
?> </div>
                <div align="center"></div>
                <div align="center"> </div>
            </div>
       <!-- Column 1 end -->
					</div>
</div>
    				<!-- Debut de la partie de droite -->
<div class="col2">
    <div id="actu" class="right fond">
			<div class="middle_title">

	<h3>Même auteur...</h3>

	</div>		<!-- Column 2 start -->
	            <?php 
                    //echo count($view->SERIESIMI);
                    foreach ($view->SERIESIMI as $o_serie)
                   {
                      echo $ficheAlbum->serie($o_serie);  
                    } ?>
    </div>
				<!-- Column 2 end -->
</div>
</div>
