<div class="cadre1">
<h2>Connexion - Pseudo oublié</h2>
</div>
<div class="cadre1">
<form name="form1" method="post" action="?login=ok">
  <table align="center" border="0" cellspacing="1" cellpadding="5">

    <tr>
      <td align="right">L'adresse email pour ce pseudo :</td>
      <td><input name="txtemail" type="text" id="txtemail" maxlength="40" size="40"></td>
    </tr>
    <tr>

      <td colspan="2" align="center">
      Si un pseudo existe, il sera renvoyé sur l'adresse email indiqué<br/>
          <input type="submit" name="Submit" value="Envoyer">
        </td>
    </tr>
    
  </table>
</form>
</div>
