<script language="JavaScript">
    $.datepicker.setDefaults($.datepicker.regional[ "fr" ]);
    $(function() {
        $("#txtanniv").datepicker({dateFormat: "yy-mm-dd"});
    });
</script>
<div class="cadre1" style="margin-top: 5px;">
    <form name="form1" method="post" action="<?php echo BDO_URL; ?>compte?act=update&user_id=<?php echo $view->USERID; ?>">
        <br>
        <h2> Compte de <font color="#990000"><?php echo $view->UTILISATEUR; ?></font></h2>


        <table align="center" border="0" cellpadding="5" cellspacing="0" bordercolor="#FFFFCC">
            <tr>
                <td align="right">E-mail :</td>
                <td><input name="txtemail" type="email" id="txtemail" value="<?php echo $view->EMAIL; ?>" size="30"></td>

            </tr>
            


        </table>
        <br />
        <h3> Personnalisation</h3>
        <table border="0" cellpadding="5" cellspacing="0" bordercolor="#FFFFCC">

            <tr>
                <td  align="right">Autoriser les autres utilisateurs &agrave; consulter ma collection :</td>
                <td><select name="lstOpenCollec" size="1">
                        <option value="Y" <?php echo $view->YESISSELECTED; ?>>Oui</option>
                        <option value="N" <?php echo $view->NOISSELECTED; ?>>Non</option>
                    </select></td>
            </tr>
            <tr>
                <td colspan="2">D'autres utilisateurs pourront acc&eacute;der &agrave;
                    votre collection via l'adresse suivante : <br /><a href="<?php echo $view->URLCOLLEC; ?>" target="_parent"><?php echo $view->URLCOLLEC; ?></a></td>
            </tr>
            <tr>
                <td align="center">Selection du carr&eacute; magique :</td>
                <td><select name="lstCarre" size="1"><?php echo $view->OPTIONCARRE; ?>
                    </select></td>
            </tr>
            <tr>
                <td  align="center">Afficher le contenu explicite (*):</td>
                <td><select name="lstAdultContent" size="1">
                        <option value="1" <?php echo $view->ADULTYESISSELECTED; ?>>Oui</option>
                        <option value="0" <?php echo $view->ADULTNOISSELECTED; ?>>Non</option>
                    </select>
                    </td>
            </tr>
            <tr>
                <td colspan="2">(*) BDovore recence tous les types de BD, Comics et Mangas ; par défaut les couvertures des contenus "pour adulte" ne sont pas affichées sur le site et application mobile
                </td>
            </tr>
           <!-- <tr>
                <td align="right">Je souhaite recevoir la newsletter de BDovore :</td>
                <td><input type="checkbox" name="txtNewsletter" value="checked" <?php echo $view->IS_NEWSLETTER; ?>></td>
            </tr>
-->
        </table>
        <br>

        <div align="center">
            <input type="submit" name="Submit2" value="Mettre a jour"><br /><br />
        </div>
    </form>

</div>

<div class="cadre1">
    <h3>Changement du mot de passe</h3>
    <form action="<?php echo BDO_URL; ?>compte?act=newpass&user_id=<?php echo $view->USERID; ?>" method="post">
        <table border="0" cellspacing="1" cellpadding="5" align="center">
            <tr>
                <td align="right">Nouveau mot de passe :</td>
                <td ><input name="txtpass1" type="password" id="txtpass1"></td>
            </tr>
            <tr>
                <td align="right">Confirmation :</td>
                <td><input name="txtpass2" type="password" id="txtpass2"></td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <input type="submit" name="SubmitPass" value="Valider">
                </td>
            </tr>
        </table>
    </form>
</div>
<div class="cadre1">

    <h2>Suppression de compte BDoVORE</h2>
    <div align="center">Si vous voulez supprimer votre profil BDoVore définitivement, cette option est pour vous.
        Votre collection, les commentaires et notes que vous avez pu ajouter seront supprimés.
        Peut être souhaitez vous <a href="<?php echo BDO_URL; ?>export">exporter votre collection</a> avant cela ?<br />
        <br />
        <input type="button" name="delete" value="Suppression du compte BDoVORE" onClick="
        if (confirm('Suppression définitive du compte sans retour arrière !')) {
            if (confirm('Après cette dernière confirmation, votre compte sera supprimé !\nVoulez vous vraiment supprimer votre compte et donc votre collection ?')) {
                window.location.href = '<?php echo BDO_URL; ?>compte?act=delete&user_id=<?php echo $view->USERID; ?>';
            }
        }
               "></div>

</div>
