<div class="cadre1" style="min-height:500px;">
    <?php if ($view->validInscription) { ?>
        <h2>Inscription réussie !</h2>
        Votre inscription a bien été enregistrée sur le site. <br>
        Vous pouvez vous connecter avec votre login et mot de passe en cliquant sur <a onclick="$('#loginBox').show();">le menu connexion</a> ou  en renseignant vos informations ci-dessous
       <form id="loginForm" method="post" action="<?php echo BDO_URL;?>">
                        <fieldset id="loginBody">
                            <fieldset>
                                <label for="user_login">Pseudo</label>
                                <input type="text" name="user_login" id="user_login" />
                            </fieldset>
                            <fieldset>
                                <label for="user_password">Mot de passe</label>
                                <input type="password" name="user_password" id="user_password" />
                            </fieldset>
                            <input type="submit" id="submitLoginConnect" name="submitLoginConnect" value="Se connecter" />
                            <label for="chkvisit">Rester connecter</label><input type="checkbox" style="width:auto;margin-top: 12px;" id="chkvisit" name="chkvisit" />
                        </fieldset>
                        </form>
    <?php } 
    else { ?>
<h2>Créez votre compte Bdovore</h2>

<div class="cadre1" id="create_account" style = "text-align:center">
     <font color="#990000" size="3" face="Arial, Helvetica, sans-serif"><?php echo $view->ERRORTEXT;?></font>
            <form name="form1" method="post" action="?act=post">
                <font color="<?php echo $view->COLORNEWUSER;?>">Nom de l'utilisateur</font><br/>
                     <input type="Text" name="NewUser" value="<?php echo $view->USERNAME;?>"><br />
                    <font color="<?php echo $view->COLORNEWPASS1;?>">Mot de passe</font><br />
                  <input type="Password" name="NewPass1" value="<?php echo $view->PASSWORD1;?>"><br />
                  <font color="<?php echo $view->COLORNEWPASS2;?>">Mot de passe (confirmation)</font><br />
                     <input type="password" name="Newpass2" value="<?php echo $view->PASSWORD2;?>">
                    <br />
                            <font color="<?php echo $view->COLORNEWEMAIL;?>">Adresse E-mail *</font><br />
                       <input type="Text" name="NewEmail" value="<?php echo $view->EMAIL;?>">
                    <br />
                     <br />
                      <input type="submit" name="Validation" value="Soumettre">
                      <br />
                   
                           
                  
                
            </form>
       
        
         <font>
                                *L'indication d'une adresse que vous <u>consultez régulièrement</u> est <u>indispensable</u> pour un fonctionnement correct du site
                                et notamment afin de garantir une <u>bonne communication</u> entre l'équipe du site et vous.<br>                                
                                Votre adresse ne sera transmise à aucun tiers et ne sera l'objet d'aucune publicité.
             </font>
</div>
<?php } ?>
</div>
