<div class="cadre1" style="min-height:500px;">
    <?php if ($view->validInscription) { ?>
        <h2>Inscription réussie !</h2>
        Votre inscription a bien été enregistrée sur le site. <br>
        <?php if ($view->source == "ios") { ?>
        Vous pouvez fermer cet écran et vous connecter à l'application avec votre nom d'utilisateur et votre mot de passe. Merci !
        <?php } else { ?>
        Vous pouvez vous connecter avec votre login et mot de passe en cliquant sur <a onclick="$('#loginBox').show();">le menu connexion</a> ou  en renseignant vos informations ci-dessous
       <form id="loginForm" method="post" action="<?php echo BDO_URL;?>">
                        <fieldset id="loginBody">
                            <fieldset>
                                <div class="input-container">
                                 <i class="fa fa-user icon"></i>
                                <input type="text" name="user_login" id="user_login" placeholder="login"/>
                                </div>
                            </fieldset>
                            <fieldset>
                                <div class="input-container">
                                 <i class="fa fa-key icon"></i>
                                <input type="password" name="user_password" id="user_password" placeholder="Mot de passe" />
                                </div>
                            </fieldset>
                            <input type="submit" id="submitLoginConnect" name="submitLoginConnect" value="Se connecter" />
                            <label for="chkvisit">Rester connecter</label><input type="checkbox" style="width:auto;margin-top: 12px;" id="chkvisit" name="chkvisit" />
                        </fieldset>
                        </form>
    <?php }} 
    else { ?>
<h2>Créez votre compte Bdovore</h2>

<div class="cadre1" id="create_account" style = "text-align:center">
     <font color="#990000" size="3" face="Arial, Helvetica, sans-serif"><?php echo $view->ERRORTEXT;?></font>
            <form name="form1" method="post" action="?act=post&source=<?php echo $view->source;?>">
               <div class="input-container">
                     <i class="fa fa-user icon"></i>
                     <input type="Text" name="NewUser" value="<?php echo $view->USERNAME;?>" placeholder="Nom d'utilisateur" required  class="input-field">
               </div>
                <div class="input-container">
                     <i class="fa fa-envelope icon"></i>
                     <input type="email" name="NewEmail" value="<?php echo $view->EMAIL;?>" placeholder="Adresse email" required class="input-field">
                </div>
                <div class="input-container">
                     <i class="fa fa-key icon"></i>
                    <input type="Password" name="NewPass1" value="<?php echo $view->PASSWORD1;?>" placeholder="Mot de passe" required class="input-field"><br />
                </div>
                 <div class="input-container">
                    <i class="fa fa-key icon"></i>
                  <input type="password" name="Newpass2" value="<?php echo $view->PASSWORD2;?>" placeholder="Confirmation du mot de passe" required class="input-field">
                    
                 </div>  <br />
                      <input type="submit" name="Validation" value="Soumettre" class="btn">
                      <br />
                   
                           
                  
                
            </form>
       
        
         <font>
                                *L'indication d'une adresse que vous <u>consultez régulièrement</u> est <u>indispensable</u> pour un fonctionnement correct du site
                                et notamment afin de garantir une <u>bonne communication</u> entre l'équipe du site et vous.<br>                                
                                Votre adresse ne sera transmise à aucun tiers et ne sera l'objet d'aucune publicité.
             </font>
</div>
<?php } ?>
</div>
