<div class="cadre1" style="min-height:500px;">
    <?php if (issetNotEmpty($view->validUpdate ?? Null)) { ?>
        <h2>Mot de passe mis à jour avec succès !</h2>
        Votre mot de passe a été mis à jour avec succès. <br>
        <?php if ($view->source == "ios") { ?>
        Vous pouvez fermer cet écran et vous connecter à l'application avec votre nom d'utilisateur et votre nouveau mot de passe. Merci !
        <?php } else { ?>
        Vous pouvez vous connecter avec votre login et nouveau mot de passe en cliquant sur <a onclick="$('#loginBox').show();">le menu connexion</a> ou en renseignant vos informations ci-dessous
        <form id="loginForm" method="post" action="<?php echo BDO_URL;?>">
            <fieldset id="loginBody">
                <fieldset>
                    <div class="input-container">
                        <i class="fa fa-user icon"></i>
                        <input type="text" name="user_login" id="user_login" placeholder="Login"/>
                    </div>
                </fieldset>
                <fieldset>
                    <div class="input-container">
                        <i class="fa fa-key icon"></i>
                        <input type="password" name="user_password" id="user_password" placeholder="Mot de passe" />
                    </div>
                </fieldset>
                <input type="submit" id="submitLoginConnect" name="submitLoginConnect" value="Se connecter" />
                <label for="chkvisit">Rester connecté</label><input type="checkbox" style="width:auto;margin-top: 12px;" id="chkvisit" name="chkvisit" />
            </fieldset>
        </form>
    <?php }} else { ?>
        <h2>Mettez à jour votre mot de passe</h2>
        <div class="cadre1" id="update_password" style="text-align:center">
            
            <form name="updateForm" id="updateForm" method="post" action="?act=update&token=<?php echo $view->token;?>">
                <div class="input-container">
                    <i class="fa fa-key icon"></i>
                    <input type="password" name="NewPass1" id="NewPass1" placeholder="Nouveau mot de passe" required class="input-field">
                </div>
                <div class="input-container">
                    <i class="fa fa-key icon"></i>
                    <input type="password" name="NewPass2" id="NewPass2" placeholder="Confirmez le mot de passe" required class="input-field">
                </div>
                <!-- Champ caché pour le token -->
                <input type="hidden" name="token" value="<?php echo htmlspecialchars($view->token); ?>">
                <input type="submit" name="UpdateSubmit" value="Mettre à jour le mot de passe" class="btn">
                <br />
            </form>
            <font>
                *Veuillez entrer et confirmer votre nouveau mot de passe. Assurez-vous qu'il est sécurisé et facile à retenir.
            </font>
        </div>
    <?php } ?>
</div>

<script>
document.getElementById('updateForm').addEventListener('submit', function(event) {
    var password1 = document.getElementById('NewPass1').value;
    var password2 = document.getElementById('NewPass2').value;

    if (password1 !== password2) {
        alert('Les mots de passe ne correspondent pas. Veuillez réessayer.');
        event.preventDefault(); // Empêche l'envoi du formulaire
    }
});
</script>
