<?php
$ficheAlbum = $view->getHelper('ficheAlbum');
$ficheAuteur = $view->getHelper("ficheAuteur");
?>
<table class="browser" width="100%">
    <tr>
        <td class="milieu" align="center" colspan="3"><?php echo $view->TOTALROW ?? "";?></td>
    </tr>
    <tr>
        <td class="milieu" align="center" colspan="3"><?php echo $view->URLPREVPAGE;?> <?php echo $view->URLNEXTPAGE;?></td>
    </tr>
    <?php 
    if ($view->FICHEAUTEUR ?? "") {
    ?>
    <tr>
        <td class="bord_gauche">&nbsp;</td>
        <td class="milieu"><img
            src="<?php echo BDO_URL_IMAGE;?>site/spacer.gif"
            width='10px'
            height='1px' />
    
    <?php 
    if (isset($view->a_row[0])) {
       // unset($view->a_row[0]->NUM_TOME);
        echo '<a href="'.BDO_URL.'auteur-bd-'.$view->FICHEAUTEUR.'">Fiche auteur</a><br>';
    }?>
    </td>
    </tr>
        <?php
    }
    ?>
    <!-- BEGIN DataBlock -->
    <?php
    foreach ($view->a_row as $row) {
    ?>
    <tr>
        <td class="bord_gauche">&nbsp;</td>
        <td class="milieu"><img
            src="<?php echo BDO_URL_IMAGE;?>site/spacer.gif"
            width=<?php echo $row['WSPACER'];?>
            height=<?php echo $row['HSPACER'];?> />
            <div id='onglet_div_plus_<?php echo $row['LEVSIGN'];?>'
                style='DISPLAY: block'
                class='browser-elem'
                onMouseOver='this.classList.add("ui-state-hover")'
                onMouseOut='this.classList.remove("ui-state-hover")'
                onClick='Block_None_Div("onglet_div_xhr_<?php echo $row['LEVSIGN'];?>");
                Block_None_Div("onglet_div_plus_<?php echo $row['LEVSIGN'];?>");
                Block_None_Div("onglet_div_moins_<?php echo $row['LEVSIGN'];?>");
                $.get("<?php echo $row['URLEVEL'];?># <?php echo $row['LEVSIGN'];?>", function(data) {
  $("#onglet_div_xhr_<?php echo $row['LEVSIGN'];?>").html(data);
});
                '>
<span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-arrowthick-2-n-s"></span>
                <?php echo $row['NAMELEVEL'];?> <?php echo $row['URLEDIT'] ?? "";?></div>
            <div class="ui-state-active browser-elem" id='onglet_div_moins_<?php echo $row['LEVSIGN'];?>'
                style='DISPLAY: none'
                onMouseOver='this.classList.add("ui-state-hover")'
                onMouseOut='this.classList.remove("ui-state-hover")'
                onClick='Block_None_Div("onglet_div_xhr_<?php echo $row['LEVSIGN'];?>");
                Block_None_Div("onglet_div_plus_<?php echo $row['LEVSIGN'];?>");
                Block_None_Div("onglet_div_moins_<?php echo $row['LEVSIGN'];?>")'>
<span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-arrowthickstop-1-n"></span><?php echo $row['NAMELEVEL'];?> <?php echo $row['URLEDIT'] ?? "";?></div>
            <div id='onglet_div_xhr_<?php echo $row['LEVSIGN'];?>'
                style='DISPLAY: none' class='browser-elem'></div></td>
    </tr>
    <?php
}
?>

    <!-- END DataBlock -->
</table>
