<?php
$ficheAlbum = $view->getHelper('ficheAlbum');
?>
<table class="browser" width="100%">
        <?php
    if ($view->TOTALROW) {
        ?>
    <tr>
        <td class="milieu" align="center" colspan="3"><?php echo $view->TOTALROW;?>
        </td>
    </tr>
        <?php
    }
    if ($view->URLPREVPAGE or $view->URLNEXTPAGE) {
    ?>
    <tr>
    <td class="milieu" align="center" colspan="3"><?php echo $view->URLPREVPAGE;?> <?php echo $view->URLNEXTPAGE;?></td>
    </tr>
        <?php
    }
    if ($view->FICHESERIE) {
    ?>
    <tr>
    <td class="milieu" colspan="3">
    <?php echo $ficheAlbum->serie($view->a_row[0]);?>
    </td>
    </tr>
        <?php
    }
    ?>
    <!-- BEGIN DataBlock -->
        <?php
foreach ($view->a_row as $row) {
    ?>
    <tr>
        <td class="bord_gauche">&nbsp;</td>
        <td class="milieu" width="10px"><img
            src="<?php echo BDO_URL_IMAGE;?>site/spacer.gif"
            width='10px'
            height='1px' /></td>
        <td>
            <?php
    if ($row->ID_TOME) {
        unset($row->NOM_SERIE);
        echo $ficheAlbum->big($row);
    }
    else
        echo $ficheAlbum->serie($row);
    ?>

        </td>
    </tr>
        <?php
}
?>  <?php
    if ($view->TOTALROW) {
        ?>
    <tr>
        <td class="milieu" align="center" colspan="3"><?php echo $view->TOTALROW;?>
        </td>
    </tr>
        <?php
    }
    if ($view->URLPREVPAGE or $view->URLNEXTPAGE) {
    ?>
    <tr>
    <td class="milieu" align="center" colspan="3"><?php echo $view->URLPREVPAGE;?> <?php echo $view->URLNEXTPAGE;?></td>
    </tr>
        <?php
    }?>
    
    <!-- END DataBlock -->
</table>
<script>
     // hack pour mobile
    if (!$.browser.mobile) {
    $(document).ready(function() {
            $(".fancybox")
        .fancybox({
            type: 'iframe',
            autoSize : false
        });
    });
} else {
    $(document).ready(function() {
            $(".fancybox")
        .each( function () {
            this.href = this.href + "&mobile=T";
        });
    });
 }

 </script>