<?php
$ficheAlbum = $view->getHelper('ficheAlbum');
?>
<div id="actu" style="padding:5px;" class="cadre1">
    <div class="cadre1">
        <h1>BDovore, gestion de collection BD comics et mangas pour les dévoreurs de BD </h1>
        <p align="center">
       G&eacute;rez votre <b>collection de bandes dessin&eacute;es</b> en ligne via une

        gargantuesque base de données de plus de <strong><?php echo number_format(intVal($view->nbTome),0,',', ' ' ); ?></strong> <a

            href="<?php echo BDO_URL; ?>leguide/actualites_bd"><b>BDs</b></a>,  <a

            href="<?php echo BDO_URL; ?>leguide/actualites_bd?origine=2"><b>Mangas</b></a> et

        <a

            href="<?php echo BDO_URL; ?>leguide/actualites_bd?origine=3"><b>Comics</b></a>.
            <br>  
            <a href='https://play.google.com/store/apps/details?id=com.mobileapp.bdovore'><img alt='Disponible sur Google Play' src='https://play.google.com/intl/en_us/badges/static/images/badges/fr_badge_web_generic.png' width="140px" height="63px" style="margin-bottom: -7px;"/></a>
            <a href="https://apps.apple.com/fr/app/bdovore/id1519677181?itsct=apps_box_badge&amp;itscg=30200" style="display: inline-block; overflow: hidden; border-top-left-radius: 13px; border-top-right-radius: 13px; border-bottom-right-radius: 13px; border-bottom-left-radius: 13px; width: 140px;height: 47px;"><img src="https://tools.applemediaservices.com/api/badges/download-on-the-app-store/black/fr-fr?size=140x47&amp;releaseDate=1593561600&h=d4303f9776e5f1c99c675c024483651e" alt="Download on the App Store" style="border-top-left-radius: 13px; border-top-right-radius: 13px; border-bottom-right-radius: 13px; border-bottom-left-radius: 13px; width: 140px; height: 47px;"></a>
            
            <br>
         Besoin d'une visite guidée ?<a href="<?php echo BDO_URL; ?>tutoriel" style="font-weight: bold;"> Suivez le tutoriel BDovore !</a> <br>
        </p>
    </div>
    
    <hr class="expSep" />
    <div class="cadre1" id="news_du_site">
        <div class="middle_title" ><h3>A la Une</h3></div>
        <div style="margin: 5px;" >

           <?php $lastNews = $view->a_lastNews[0]; ?>

            <div class="cadre1">
                <h4><?php echo $lastNews->news_titre;?> - Postée par <?php echo $lastNews->news_posteur;?> </h4>
                <div>
                    <p>
                        <?php echo $lastNews->news_text;?>
                    </p>
                </div>
            </div>


        </div>
    </div>
            <!-- Column 2 start -->

    
    <div class="cadre1">
        <div class="middle_title"><h3><a href="./leguide/avis">Dernières Critiques</a></h3></div>
        <table class="list_album">
              <?php
              $tr = true;
              foreach ($view->a_lastComment as $lastComment) {
                  if ($tr)
                      echo "<tr>";
                  echo "<td class='mw50'>" . $ficheAlbum->getFicheWithComment($lastComment) . "</td>";

                  if (!$tr) {
                      echo "</tr>";
                  }
                  $tr = !$tr;
              }
              ?>
          </table>
    </div>

    <hr class="expSep" />
    <div class="cadre1">
        <div class="middle_title">
            <h3><a href="./leguide/actualites_bd">Albums BD Mangas Comics tendances</a></h3>
        </div>
        
            <div style='margin:0 auto; max-width:900px;'>
                <?php 
                 $genre ="";
                 $close="";
                 $i = 0;

                 echo "<div style='float:left; padding:1px;margin:0 auto;/*max-width:265px;*/'>";
                foreach ($view->ACTUAIR as $actu) { 
                     $i++;               

                    echo "<div style='float:left;padding:2px;height:210px;'>".$ficheAlbum->urlAlbum($actu,$class="couvBig",$sponsor=FALSE)."</div>";
                     if ($i==4) {                    
                        echo "</div>";
                        $i=0;
                        echo "<div style='float:left; padding:1px;margin:0 auto;/*max-width:275px;*/'>";
                        $close = "</div>";
                    }
                    //$genre = $actu->ORIGINE_GENRE;

                } 
                echo $close;
              ?>
            </div>
       
    </div>
    <hr class="expSep" />
    <div class="cadre1">
        <div class="middle_title"><h3><a href="./leguide/sorties_bd">Derni&egrave;res sorties</a> <a href="<?php echo BDO_URL; ?>rss/dernieres_sorties"> <img src="<?php echo BDO_URL_IMAGE; ?>site/feed.png" style="border: 0;" alt="logo fil rss" title="Suivez l'actualité des ajouts d'albums sur le site grace à ce fil rss" /></a></h3></div>
          <table class="list_album">
            <?php
            $tr = true;
            foreach ($view->a_lastSorties as $lastSorties) {
                if ($tr)
                    echo "<tr>";
                echo "<td class='mw50'>" . $ficheAlbum->big($lastSorties, $sep = true, $getUrlSerie = true) . "</td>";

                if (!$tr) {
                    echo "</tr>";
                }
                $tr = !$tr;
            }
            ?>
        </table>
        <hr class="expSep" />
        <div class="fright"><a href="./leguide/sorties_bd">Toutes les dernières sorties</a></div>
        <hr class="expSep" />
    </div>
    <hr class="expSep" />

    <div class="cadre1">
        <div class="middle_title"><h3><a href="./leguide/prochaines_sorties_bd">Sorties &agrave; venir</a> <a href="<?php echo BDO_URL; ?>rss/sorties_a_venir"> <img src="<?php echo BDO_URL_IMAGE; ?>site/feed.png" style="border: 0;" alt="logo fil rss" title="Suivez l'actualité des ajouts d'albums sur le site grace à ce fil rss" /></a></h3></div>
        <table class="list_album">
            <?php
            $tr = true;
            foreach ($view->a_futurSorties as $futurSorties) {
                if ($tr)
                    echo "<tr>";
                echo "<td class='mw50'>" . $ficheAlbum->big($futurSorties, $sep = true, $getUrlSerie = true) . "</td>";

                if (!$tr) {
                    echo "</tr>";
                }
                $tr = !$tr;
            }
            ?>
        </table>
        <hr class="expSep" />
        <div class="fright"><a href="./leguide/prochaines_sorties_bd">Toutes les futures sorties</a></div>
        <hr class="expSep" />
    </div>
    <hr class="expSep" />
     <?php echo $view->LASTNEWS; ?>   
    <hr class="expSep" />
    <div class="cadre1">
        <div id="lastajout" class="right fond">
            <div class="middle_title">
                <h3><a href="<?php echo BDO_URL;?>leguide/ajouts">Derniers ajouts</a>
                    <a href="<?php echo BDO_URL;?>rss">
                    <img src="<?php echo BDO_URL_IMAGE;?>site/feed.png" style="border: 0;" alt="logo fil rss" title="Suivez l'actualité des ajouts d'albums sur le site grace à ce fil rss" />
                    </a>
                </h3>
            </div>
            <div class="cadre1" style="margin:3px 3px 3px 3px ;">
                <?php 

                foreach ($view->LASTAJOUT as $ajout) {
                    echo $ficheAlbum->urlAlbum($ajout,$class="albTitle")."<br />";
                }?>
            </div>
        </div>
    </div>
     <hr class="expSep" />
 </div>
         

