d<?php 
$ficheAlbum = $view->getHelper('ficheAlbum');
?>
<div class="colleft">
<div class="col1wrap">
				<div class="col1 fond">
						<!-- Column 1 start -->

<!-- cadre central de la page -->

<div class="cadre1" id="message_accueil">

	<h1>BDovore, le site des dévoreurs de BD </h1>

        G&eacute;rer votre <b>collection de bandes dessin&eacute;es</b> en ligne via une

	gargantuesque base de données de plus de <strong><?php echo $view->nbTome; ?></strong> <a

		href="<?php echo BDO_URL;?>leguide"><b>BDs</b></a>,  <a

		href="<?php echo BDO_URL;?>leguide?origine=2"><b>Mangas</b></a> et 

	<a

		href="<?php echo BDO_URL;?>leguide?origine=3"><b>Comics</b></a>. <br>
                <br> Retrouvez par exemple :<br>
                <ul>
                    <li><a href="<?php echo BDO_URL;?>browser?a_idGenre[]=82">- des revues</a>,
                    <a

            href="<?php echo BDO_URL;?>browser?a_idGenre[]=83">des p&eacute;riodiques</a>,
                    </li>
                    <li>- des 
                        <a

                                href="<?php echo BDO_URL;?>browser?a_idGenre[]=14">ouvrages
                            
            d'&eacute;tude</a> et des <a

		href="<?php echo BDO_URL;?>browser?a_idGenre[]=4">recueils

		d'illustrations</a> </li>
                <li>- et puis des <a

		href="<?php echo BDO_URL;?>browser?a_idGenre[]=12">BD</a>,

	des <a

		href="<?php echo BDO_URL;?>browser?a_idGenre[]=65">BD</a>,

	des <a

		href="<?php echo BDO_URL;?>browser?a_idGenre[]=6">BD</a>,

	des <a

		href="<?php echo BDO_URL;?>browser?a_idGenre[]=51">BD</a>

	et encore <a

		href="<?php echo BDO_URL;?>browser?a_idGenre[]=37">des

            BD</a>.</li>
                </ul><br /> <a href="<?php echo BDO_URL;?>tutoriel" style="font-weight: bold;">D&eacute;couvrez

		BDovore !</a> <span align="right">Bdovore sur mobile : <a href='http://phone.bdovore.com'>phone.bdovore.com</a> ou l'application Android sur <a href='https://play.google.com/store/apps/details?id=com.bdovore.phone.android&hl=fr_FR'>Google Play</a></span>

</div>

<div style="padding:5px;">
<h2>Dernières Critiques</h2></div>

<table id="list-last-critique" >
    <thead>
        <tr>
        <th><div class="middle_title"><h3 align="center"><a href="./leguide?rb_mode=3&rb_list=album&submitGuide=Envoyer">BD</a></h3></div></th>
        <th class="alb-col2"><div class="middle_title"><h3 align="center"><a href="./leguide?rb_mode=3&rb_list=album&origine=2&submitGuide=Envoyer">Mangas</a></h3></div></th>
        <th class="alb-col3"><div class="middle_title"><h3 align="center"><a href="./leguide?rb_mode=3&rb_list=album&origine=3&submitGuide=Envoyer">Comics</a></h3></div></th>
</tr>
    </thead>
    <tbody>
     <tr>
         <td><?php echo $ficheAlbum->getFicheWithComment($view->a_lastBD[0]); ?></td>
         <td class="alb-col2"><?php echo $ficheAlbum->getFicheWithComment($view->a_lastManga[0]); ?></td>
         <td class="alb-col3"><?php echo $ficheAlbum->getFicheWithComment($view->a_lastComics[0]); ?></td>
     </tr>
     <tr>
         <td><?php echo $ficheAlbum->getFicheWithComment($view->a_lastBD[1]); ?></td>
         <td class="alb-col2"><?php echo $ficheAlbum->getFicheWithComment($view->a_lastManga[1]); ?></td>
         <td class="alb-col3"><?php echo $ficheAlbum->getFicheWithComment($view->a_lastComics[1]); ?></td>
     </tr>
     <tr>
         <td><?php echo $ficheAlbum->getFicheWithComment($view->a_lastBD[2]); ?></td>
         <td class="alb-col2"><?php echo $ficheAlbum->getFicheWithComment($view->a_lastManga[2]); ?></td>
         <td class="alb-col3"><?php echo $ficheAlbum->getFicheWithComment($view->a_lastComics[2]); ?></td>
     </tr>
    </tbody>
     <tfoot>
         <tr>
             <td><div class="fright"><a href="leguide">Tous les avis BD</div></td>
             <td class="alb-col2"><div class="fright"><a href="./leguide?rb_mode=3&rb_list=album&origine=2&submitGuide=Envoyer">Tous les avis Mangas</div> </td>
             <td class="alb-col3"><div class="fright"><a href="./leguide?rb_mode=3&rb_list=album&origine=3&submitGuide=Envoyer">Tous les avis Comics</div></td>
         </tr>
     </tfoot>
 </table>


<hr class="expSep" />
          <div class="cadre1">


              <div class="middle_title"><h3><a href="./leguide?rb_mode=4&rb_list=album&submitGuide=Envoyer">Derni&egrave;res sorties</a> <a href="<?php echo BDO_URL ; ?>rss/dernieres_sorties"> <img src="<?php echo BDO_URL_IMAGE ; ?>site/feed.png" style="border: 0;" alt="logo fil rss" title="Suivez l'actualité des ajouts d'albums sur le site grace à ce fil rss" /></a></h3></div>


<table class="list_album">
            <?php
            $tr = true;
            foreach ($view->a_lastSorties as $lastSorties) {
                if ($tr) echo "<tr>";
                 echo "<td class='mw50'>" . $ficheAlbum->big($lastSorties,$sep=true,$getUrlSerie=true) . "</td>";

                if (!$tr) {
                    echo "</tr>";
                }
                $tr = !$tr;
            }

            ?>
</table>
            <hr class="expSep" />
   <div class="fright"><a href="./leguide?rb_mode=4&rb_list=album&submitGuide=Envoyer">Toutes les dernières sorties</a></div>       
 <hr class="expSep" />
          </div>
       <hr class="expSep" />   
    
<div class="cadre1">
             <div class="middle_title"><h3><a href="./leguide?rb_mode=5&rb_list=album&submitGuide=Envoyer">Sorties &agrave; venir</a> <a href="<?php echo BDO_URL ; ?>rss/sorties_a_venir"> <img src="<?php echo BDO_URL_IMAGE ; ?>site/feed.png" style="border: 0;" alt="logo fil rss" title="Suivez l'actualité des ajouts d'albums sur le site grace à ce fil rss" /></a></h3></div>
<table class="list_album">
              		 <?php
            $tr = true;
            foreach ($view->a_futurSorties as $futurSorties) {
                if ($tr) echo "<tr>";
                 echo "<td class='mw50'>" . $ficheAlbum->big($futurSorties,$sep=true,$getUrlSerie=true) . "</td>";

                if (!$tr) {
                    echo "</tr>";
                }
                $tr = !$tr;

            }

            ?>	
    </table>
             <hr class="expSep" />
   <div class="fright"><a href="./leguide?rb_mode=5&rb_list=album&submitGuide=Envoyer">Toutes les futures sorties</a></div>       
 <hr class="expSep" />
</div>
                        <hr class="expSep" />	

            

        

  

       	

       

<hr class="expSep" />





<?php echo $view->LASTNEWS;?>
				
					<!-- Column 1 end -->
					</div>
</div>
				<!-- Debut de la partie de droite -->
<div class="col2">
					<!-- Column 2 start -->
	            <?php echo $view->ACTUAIR;?>
	            <?php echo $view->LASTAJOUT;?>
				<!-- Column 2 end -->
</div>
</div>
<!-- Fin de la partie de droite -->


