<h2>Contrôle des règles de cohérence des données</h2>
Le résultat est limité à 200 lignes

<form name="formregle" method="post">
	<div>
		Contrôle : <select name="id_queryRegle">';
<?php
foreach ($view->a_queryRegle as $id_queryRegle => $queryRegle) {
    $selected = ($id_queryRegle == $_POST['id_queryRegle']) ? 'SELECTED' : '';
    echo '<option value="' . $id_queryRegle . '" ' . $selected . ' >' . $queryRegle['title'] . '</option>';
}
?>
</select><br /> <label for="viewQuery"><input type="checkbox"
			id="viewQuery" name="viewQuery" value="checked"
			<?php echo $_POST ['viewQuery'] ;?>> voir la requête</label> <br />
		<input type="submit" name="execformvalue" value="Chercher">
	</div>
</form>

<?php
if (isset($_POST['execformvalue']) and isset($_POST['id_queryRegle'])) {
    
    $query = $view->a_regle[$_POST['id_queryRegle']]->query;
    $nbr = $view->a_regle[$_POST['id_queryRegle']]->nbr;
    $cmpt = $view->a_regle[$_POST['id_queryRegle']]->cmpt;
    $a_obj = $view->a_regle[$_POST['id_queryRegle']]->a_obj;
    
    $title = $view->a_queryRegle[$_POST['id_queryRegle']]["title"];
    if (isset($_POST['viewQuery']) and ! empty($_POST['viewQuery'])) {
        echo_pre($query);
    }
    
    if ($nbr > 0) {
        echo '<h3>' . $title . '</h3>';
        echo $cmpt . ' lignes sur ' . $nbr;
        tableOfFetchObj($a_obj, array(), false);
    }
    else {
        echo 'Aucune ligne de résultat !';
	}
}