<div class="cadre1">
    <h1>Votre BDtheque en ligne avec Bdovore</h1>
    Bdovore vous permet de gérer votre collection de BD en ligne gratuitement, suivre <strong>l'actualité BD</strong>, partager <strong>vos envies de BD</strong>, suivre vos <strong>statisques</strong>...<br>
    Et comme Bdovore est une association à but non lucratif, c'est un site gratuit et sans publicité : votre collection et vos données ne seront jamais utilisées, revendues ou partagées avec des tiers.  <br>
   
    Vous voulez en savoir plus avant de vous lancer ? Suivez le guide : <a href="<?php echo BDO_URL;?>tutoriel">tutoriel de la bdtheque</a>
    <br>Vous avez déjà un compte ? <strong><a onclick="$('#loginBox').show();">identifiez-vous ici ! </a></strong>
   
<img src="<?php echo BDO_URL_IMAGE; ?>CaptureCollection.png" style="max-width:45%;float:right;" />

    <div class="cadre1 mw50" id="create_account" style = "text-align:center">
        <br><br><h2>Créez votre compte Bdovore</h2>
     Vous n'avez pas de compte ? <br>
     Créez votre compte gratuitement pour ajouter des BD à votre collection<br><br>   
            <form name="form1" method="post" action="<?php echo BDO_URL?>compte/inscription?act=post">
                <div class="input-container">
                     <i class="fa fa-user icon"></i>
                     <input type="Text" name="NewUser" value="" placeholder="Nom d'utilisateur" required  class="input-field">
               </div>
                <div class="input-container">
                     <i class="fa fa-envelope icon"></i>
                     <input type="email" name="NewEmail" value="" placeholder="Adresse email" required class="input-field">
                </div>
                <div class="input-container">
                     <i class="fa fa-key icon"></i>
                    <input type="Password" name="NewPass1" value="" placeholder="Mot de passe" required class="input-field"><br />
                </div>
                 <div class="input-container">
                    <i class="fa fa-key icon"></i>
                  <input type="password" name="Newpass2" value="" placeholder="Confirmation du mot de passe" required class="input-field">
                    
                 </div>  <br />
                      <input type="submit" name="Validation" value="Soumettre" class="btn">
                      <br />
                      <br />
                   
                            <font>
                                *L'indication d'une adresse que vous <u>consultez régulièrement</u> est <u>indispensable</u> pour un fonctionnement correct du site
                                et notamment afin de garantir une <u>bonne communication</u> entre l'équipe du site et vous.<br>                                
                                Votre adresse ne sera transmise à aucun tiers et ne sera l'objet d'aucune publicité.
                            </font>
                  
                
            </form>
  
    <br>  
            <a href='https://play.google.com/store/apps/details?id=com.mobileapp.bdovore'><img alt='Disponible sur Google Play' src='https://play.google.com/intl/en_us/badges/static/images/badges/fr_badge_web_generic.png' width="140px" height="63px" style="margin-bottom: -7px;"/></a>
            <a href="https://apps.apple.com/fr/app/bdovore/id1519677181?itsct=apps_box_badge&amp;itscg=30200" style="display: inline-block; overflow: hidden; border-top-left-radius: 13px; border-top-right-radius: 13px; border-bottom-right-radius: 13px; border-bottom-left-radius: 13px; width: 140px;height: 47px;"><img src="https://tools.applemediaservices.com/api/badges/download-on-the-app-store/black/fr-fr?size=140x47&amp;releaseDate=1593561600&h=d4303f9776e5f1c99c675c024483651e" alt="Download on the App Store" style="border-top-left-radius: 13px; border-top-right-radius: 13px; border-bottom-right-radius: 13px; border-bottom-left-radius: 13px; width: 140px; height: 47px;"></a>
            
    
    
    </div>
   
        
  
</div>