<?php
$ficheAlbum = $view->getHelper('ficheAlbum');
$pageinate = $view->getHelper('Pagination');
?>


<div class="colleft">
<div class="col1wrap">
                <div class="col1 fond">



        <!-- Column 1 start -->


        <!-- cadre central de la page -->
        <div class="cadre1">
             

            <div class="middle_title addthis">
                <h3>Fiche Collection

            <?php echo $view->collection->NOM_COLLECTION; ?> 
            <?php if (User::minAccesslevel(1)) { ?><a class="fancybox fancybox.iframe {width:600,height:600}" href="admin/editcollection?collec_id=<?php echo $view->collection->ID_COLLECTION; ?>"> <img src="<?php echo BDO_URL_IMAGE; ?>edit.gif" /></a> <?php } ?></h3></div>
            <br />
          
          
                  <div ><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif">
            <strong>Editeur : </strong>
            </font>
<?php echo $view->collection->NOM_EDITEUR; ?>
            <br />
            <font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif">
            <strong>Albums dans la base: </strong>
            </font>
<?php echo $view->nb_album; ?>
            <br />
           
            <br />
           
                <div class="addthis_inline_share_toolbox" style="float: right;">
                <!-- AddThis Button BEGIN -->
                <!-- Go to www.addthis.com/dashboard to customize your tools --> <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5aa565c61fcc82d7"></script> 
                <noscript>
                <span class="petite_police"><br />Javascript absent/désactivé dans votre navigateur : bouton inactif</span>
                </noscript>
                
            </div>
            </div>
               


<hr class="expSep" />
                <!-- END CommentBlock -->

              <br>
        </div>


            <div class="cadre1"><div class="middle_title">
 
                    <span id="album_as"> Albums par séries</span>   

                </div>


        </div>
                <!-- BEGIN AlbBlock -->
                <table class="list_album">
<?php
$tr = true;
if (count($view->dbs_tome->a_dataQuery) == 0) echo "Aucun album pour cette collection";
foreach ($view->dbs_tome->a_dataQuery as $tome) {
    if ($tr)
        echo "<tr>";

    echo "<td class='mw50'>" . $ficheAlbum->big($tome,$sep=true,$getUrlSerie=true) . "</td>";

    if (!$tr) {
        echo "</tr>";
    }
    $tr = !$tr;
    ?>



                    <?php
                    }
                    if (!$tr)
                        echo "</tr>";
                    ?></table>

                <div align="center">
<?php

if ($view->nb_album > 20) {
    $max_page = ceil($view->nb_album / 20);
    if ($max_page > 1) {
        echo($pageinate->paginate($ficheAlbum->getURLCollection($view->collection ),"?page=",$max_page,$view->page,$adj=3));
    }
   }
?> </div>
            </div>
       <!-- Column 1 end -->
                    </div>
                    <!-- Debut de la partie de droite -->
<div class="col2">
    <div id="actu" class="right fond">
            <div class="middle_title">

    <h3>Derniers ajouts...</h3>

    </div>      <!-- Column 2 start -->
                <?php
                    //echo count($view->SERIESIMI);
                    foreach ($view->lastAlbum->a_dataQuery as $o_tome)
                   {
                      echo $ficheAlbum->small($o_tome);
                    } ?>
    </div>
                <!-- Column 2 end -->
</div>
</div>
<script>
    $(document).ready(function() {
        $("#select_activite").buttonset();
        
        
    });
    // affichage des infos de bio : on affiche le début et un bouton "voir plus"
        if ($("#bioauteur").height() > 120) {
             $("#bioauteur").addClass("textmasked");
             $("#more").show();
            $("#less").hide();
        } else {
            $("#more").hide();
            $("#less").hide();
        }
    function moreBio () {
        $("#bioauteur").removeClass("textmasked");
         $("#more").hide();
         $("#less").show();
    }
    
    function lessBio () {
        $("#bioauteur").addClass("textmasked");
         $("#more").show();
         $("#less").hide();
    }
</script>