<?php echo $view->MENUCOLL;?>
<div class="cadre1">
	<h3>Mon actualit&eacute;</h3>
	<form action="<?php echo $view->ACTION;?>" method="post">
		<table border="0">
			<tr>
				<td><span class="texte"> Voir les nouveautés concernant : </span></td>
				<td>&nbsp;</td>
				<td><span class="texte"> Parues depuis : </span></td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td><select name="lstSource" size="1">
						        <?php echo $view->OPTSOURCE;?>
					        </select></td>
				<td>&nbsp;</td>
				<td><select name="lstDuree">
						        <?php echo $view->OPTDUREE;?>
					        </select></td>
				<td>&nbsp;</td>
				<td><input type="submit" name="Submit" value="Rafraîchir" /></td>
				<td>&nbsp;</td>
				<td><a href="<?php echo BDO_URL;?>membres/aut_favoris"> Gérer
						mes auteurs favoris </a></td>
			</tr>
		</table>
	</form>
	<table width="100%" height="29" class="donnees">
		<tr>
			<td width="15%" class="entete"><div align="center">
					<font color="#0000FF"><strong><a
							href="<?php echo BDO_URL;?>membres/actualites?cle=1&sort=asc&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img
								src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12"
								height="12" hspace="5" border="0"></a>Genre<a
							href="<?php echo BDO_URL;?>membres/actualites?cle=1&sort=DESC&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img
								src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12"
								height="12" hspace="5" border="0"></a></strong></font>
				</div></td>
			<td width="20%" class="entete"><div align="center">
					<font color="#0000FF"><strong><a
							href="<?php echo BDO_URL;?>membres/actualites?cle=4&sort=asc&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img
								src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12"
								height="12" hspace="5" border="0"></a>Auteur<a
							href="<?php echo BDO_URL;?>membres/actualites?cle=4&sort=DESC&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img
								src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12"
								height="12" hspace="5" border="0"></a></strong></font>
				</div></td>
			<td width="20%" class="entete"><div align="center">
					<font color="#0000FF"><strong><a
							href="<?php echo BDO_URL;?>membres/actualites?cle=2&sort=asc&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img
								src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12"
								height="12" hspace="5" border="0"></a>S&eacute;rie<a
							href="<?php echo BDO_URL;?>membres/actualites?cle=2&sort=DESC&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img
								src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12"
								height="12" hspace="5" border="0"></a></strong></font>
				</div></td>
			<td width="5%" class="entete"><div align="center">
					<strong>Tome</strong>
				</div></td>
			<td width="25%" class="entete"><div align="center">
					<strong>Titre</strong>
				</div></td>
			<td width="15%" class="entete"><div align="center">
					<font color="#0000FF"><strong><a
							href="<?php echo BDO_URL;?>membres/actualites?cle=3&sort=asc&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img
								src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12"
								height="12" hspace="5" border="0"></a>Date de Parution <a
							href="<?php echo BDO_URL;?>membres/actualites?cle=3&sort=DESC&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img
								src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12"
								height="12" hspace="5" border="0"></a></strong></font>
				</div></td>
		</tr>
		<!-- BEGIN DetailBlock -->
		<tr>
			<td width="15%" class="data"><div align="center"><?php echo $view->GENRE;?></div></td>
			<td width="20%" class="data"><div align="center"><?php echo $view->AUTEUR;?></div></td>
			<td width="20%" class="data"><div align="center">
					<a
						href="<?php echo BDO_URL;?>serie?id_serie=<?php echo $view->SERID;?>"><?php echo $view->SERIE;?></a>
				</div></td>
			<td width="5%" class="data"><div align="center"><?php echo $view->TOME;?></div></td>
			<td width="25%" class="data"><a href="<?php echo $view->URLTITRE;?>"><?php echo $view->TITRE;?></a></td>
			<td width="15%" class="data">
				<div align="center"><?php echo $view->DTEPAR;?></div>
			</td>
		</tr>
		<!-- END DetailBlock -->
	</table>
	<p class="texte"><?php echo $view->BARRENAVIGATION;?></p>
</div>