<link href="<?php echo BDO_URL;?>style/style1.css" rel="stylesheet" type="text/css" />
<div align="center">
  <table width="100%" border="0">
    <tr> 
      <td><div align="center">
          <h3><strong><?php echo $view->MESSAGE;?></strong></h3>
        </div></td>
    </tr>
  </table>
</div>
<div align="center"></div>
<p align="center"><a href="<?php echo $view->QUERYSTRING;?>">Ajouter d'autres album</a> 
  <a href="userhome">Afficher ma collection</a></p>

