<form name="form_bdnet" method="post" action="<?php echo $view->URLACTION1;?>">
  <table width="600" border="1" cellpadding="5" bordercolor="#666666" bgcolor="#FFFFCC">
    <tr bordercolor="#FFFFCC"> 
      <td width="20%" class="label">Adresse BDNET</td>
      <td width="80%"><input name="txtURLBDNET" type="text" value="<?php echo $view->SCENARISTE;?>" size="40">
        <input type="submit" name="Submit" value="Envoyer"> </td>
    </tr>
  </table>
</form>
<form name="form_amazon" method="post" action="<?php echo $view->URLACTION2;?>">
  <table width="600" border="1" cellpadding="5" bordercolor="#666666" bgcolor="#FFFFCC">
    <tr bordercolor="#FFFFCC"> 
      <td width="20%" class="label">Adresse Amazon</td>
      <td width="80%"><input name="txtURLAmazon" type="text" value="<?php echo $view->SCENARISTE;?>" size="40">
        <input type="submit" name="Submit2" value="Envoyer"> </td>
    </tr>
  </table>
</form>
<p>&nbsp;</p>
