<table width="773" height="29" border="1" cellpadding="1" cellspacing="1">
  <tr> 
    <td width="60" height="25"> <div align="center"><font color="#0000FF"><strong><font size="2" face="Arial, Helvetica, sans-serif"><a href="../admin/adminnews?cle=1&sort=asc"><img src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12" height="12" hspace="5" border="0"></a>ID<a href="../admin/adminnews?cle=1&sort=DESC"><img src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12" height="12" hspace="5" border="0"></a></font></strong></font></div></td>
    <td width="75"><div align="center"><font color="#0000FF"><strong><font size="2" face="Arial, Helvetica, sans-serif"><a href="../admin/adminnews?cle=2&sort=asc"><img src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12" height="12" hspace="5" border="0"></a>Date<a href="../admin/adminnews?cle=2&sort=DESC"><img src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12" height="12" hspace="5" border="0"></a></font></strong></font></div></td>
    <td width="90"><div align="center"><font color="#0000FF"><strong><font size="2" face="Arial, Helvetica, sans-serif"><a href="../admin/adminnews?cle=3&sort=asc"><img src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12" height="12" hspace="5" border="0"></a>Auteur<a href="../admin/adminnews?cle=3&sort=DESC"><img src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12" height="12" hspace="5" border="0"></a></font></strong></font></div></td>
    <td width="120"><div align="center"><font color="#0000FF"><strong><font size="2" face="Arial, Helvetica, sans-serif"><a href="../admin/adminnews?cle=4&sort=asc"><img src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12" height="12" hspace="5" border="0"></a>Publication<a href="../admin/adminnews?cle=4&sort=DESC"><img src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12" height="12" hspace="5" border="0"></a></font></strong></font></div></td>
    <td width="225"><div align="center"><font color="#0000FF"><strong><font size="2" face="Arial, Helvetica, sans-serif"><a href="../admin/adminnews?cle=5&sort=asc"><img src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12" height="12" hspace="5" border="0"></a>Titre<a href="../admin/adminnews?cle=5&sort=DESC"><img src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12" height="12" hspace="5" border="0"></a></font></strong></font></div></td>
    <td width="30"><div align="center"><font color="#0000FF"><strong><img src="<?php echo BDO_URL_IMAGE;?>edit.gif" width="18" height="13"></strong></font></div></td>
    <td width="30"> <div align="center"><img src="<?php echo BDO_URL_IMAGE;?>poubelle.gif" width="25" height="24"> 
      </div></td>
  </tr>
</table>
<!-- BEGIN NewsBlock -->
<table width="773" height="29" border="1" cellpadding="1" cellspacing="1">
  <tr> 
    <td width="60" height="25"> <div align="center"><font color="#000000"><font size="2" face="Arial, Helvetica, sans-serif"><?php echo $view->ID;?></font></font></div></td>
    <td width="75"><div align="center"><font color="#000000" size="2" face="Arial, Helvetica, sans-serif"><?php echo $view->DATE;?></font></div></td>
    <td width="90"><div align="center"><font color="#000000" size="2" face="Arial, Helvetica, sans-serif"><?php echo $view->AUTEUR;?></font></div></td>
    <td width="120"><div align="center"><font color="#000000"><font color="#000000"><font size="2" face="Arial, Helvetica, sans-serif"><?php echo $view->LEVEL;?></font></font></font></div></td>
    <td width="225"><div align="center"><font color="#000000"><font color="#000000"><font size="2" face="Arial, Helvetica, sans-serif"><?php echo $view->TITRE;?></font></font></font></div></td>
    <td width="30"><div align="center"><font color="#000000"><a href="<?php echo $view->URLEDIT;?>"><img src="<?php echo BDO_URL_IMAGE;?>edit.gif" width="18" height="13" border="0"></a></font></div></td>
	<td width="30"> <div align="center"><a href="<?php echo $view->URLDELETE;?>"><img src="<?php echo BDO_URL_IMAGE;?>poubelle.gif" width="20" height="21" border="0"></a></div></td>
  </tr>
</table>
<!-- END NewsBlock -->
