<SCRIPT LANGAUGE="JavaScript"><!--
function newWindow(myCategory,myText,myForm,myElement,isMandatory,myEditeur) {
	if ((isMandatory == true) && (myText.length < 3)) {
		alert('Veuillez saisir au moins 3 caractères');
	}
	else {
		if (myCategory == "collection") {
			if (myEditeur == '') {
				alert("Veuillez saisir l'éditeur en premier");
			}
			else {
			mywindow=open("pickup?cat=" + myCategory + "&text=" + myText + "&ReturnDoc=" + myForm + "&ReturnElement=" + myElement + "&IdEditeur=" + myEditeur,'myname','scrollbars=yes,resizable=yes,width=350,height=270');
			}
		}
		else {
			mywindow=open('pickup?cat=' + myCategory + "&text=" + myText + "&ReturnDoc=" + myForm + "&ReturnElement=" + myElement,'myname','scrollbars=yes,resizable=yes,width=350,height=270');
		}
	}
}

function urlsource(){
	document.forms['form1'].action = "<?php echo $view->URLREFRESH;?>?serie="+document.forms['form1'].elements['txtSerieId'].value;
    //alert("Saisissez les champs requis");
	return true;
}

function Chargement() { 
 for (i = 0; i < document.myform.elements.length; i++) {
   if (document.myform.elements[i].name == "alb_id[]") {
     document.myform.elements[i].checked = true;
   }
 }
}
//--></SCRIPT>
<table width="100%" border="1">
  <tr> 
    <!-- Debut colonne Gauche-->
    <td width="50%" valign="top"> <form name="form1" method="post" action="" onSubmit="return urlsource()">
        <table width="100%" border="1" cellpadding="5" cellspacing="0" bordercolor="#333333" bgcolor="#FFFFCC">
          <tr bordercolor="#FFFFCC"> 
            <td width="10%" class="label"> <div align="center">Serie</div></td>
            <td width="10%"> <div align="left"> 
                <input name="txtSerieId" type="text" id="txtSerieId" value="<?php echo $view->IDSERIE;?>" size="5">
              </div></td>
            <td width="27%"> <input name="txtSerie" type="text" id="txtSerie" value="<?php echo $view->SERIE;?>" size="40"></td>
            <td width="28%"><img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('serie',document.form1.txtSerie.value,'form1','txtSerie',true)"></td>
            <td width="51"> <input name="Submit1" type="submit" id="Submit1" value="Rafraichir"></td>
          </tr>
        </table>
      </form>
      <br> <form action="<?php echo $view->URLACTION;?>" method="post" enctype="multipart/form-data" name="myform" target="_self" id="myform">
        <table width="100%" border="1" cellpadding="5" cellspacing="0" bordercolor="#333333" bgcolor="#FFFFCC">
          <!-- BEGIN AlbumsBlock -->
          <tr bordercolor="#999999"> 
            <td colspan="3" align="center"><?php echo $view->TOME;?> - <?php echo $view->TITRE;?></td>
          </tr>
          <tr bordercolor="#999999"> 
            <td width="43%" align="center"><img src="<?php echo $view->URLIMAGE;?>" width="111" height="150"><input type="hidden" name="url_bdo[<?php echo $view->IDTOME;?>]" value="<?php echo $view->IMAGENAME;?>"><br>
              <?php echo $view->DIMENSION;?><br>
              <?php echo $view->SIZE;?></td>
            <td width="14%" align="center"><input type="checkbox" name="alb_id[]" value="<?php echo $view->IDTOME;?>"> 
              <input name="num_tome[<?php echo $view->IDTOME;?>]" type="hidden" value="<?php echo $view->TOME;?>"></td>
            <td width="43%" align="center"><p><img src="<?php echo $view->URLIMGAMAZON;?>" width="111" height="150"> 
                <input type="hidden" name="url_amz[<?php echo $view->IDTOME;?>]" value="<?php echo $view->URLIMGAMAZON;?>">
              </p>
              <p><a href="<?php echo $view->URLPAGEAMAZON;?>">Voir sur Amazon</a></p></td>
          </tr>
          <!-- END AlbumsBlock -->
          <tr bordercolor="#FFFFCC"> 
            <td colspan="3" align="center"><a name="ici" href="#ici" onClick="Chargement();">Tout 
              selectionner</a></td>
          </tr>
        </table>
        <br>
        <p> 
        <div align="center"></p> 
          <input type="submit" name="Submit" value="<?php echo $view->ACTIONNAME;?>">
          <br>
        </div>
      </form></td>
    <!-- Debut colonne Gauche-->
    <td width="50%"> <table width="100%" border="1">
        <tr> 
          <td bordercolor="#FFFFCC" bgcolor="#FFFFCC"><p>&nbsp;</p>
            <p><strong>Menu Express</strong><br>
              <a href="<?php echo $view->URLEDITSERIE;?>">Retour à la fiche série</a><br>
            </p></td>
        </tr>
      </table></td>
  </tr>
</table>

