<form action="<?php echo $view->URLACTION;?>" method="post" enctype="multipart/form-data" name="myform" target="_self" id="myform">
    <table class="fond_admin">
        <!--DWLayoutTable-->
        <tr> 
            <td width="75%" rowspan="4" valign="top">
                <?php echo $view->ADMINSERIEDETAIL;?>

                <?php echo $view->ADMINALBUMDETAIL;?>

                <table class="tableaux_admin" width="100%">
                    <tr> 
                        <td class="label">
                            <p>Différentes éditions : <?php echo $view->NBEDITIONS;?></p>
                            <table>
                                <tr> 
                                    <td width="8%" class="entete">Defaut</td>
                                    <td width="23%" class="entete">Editeur</td>
                                    <td width="23%" class="entete">Collection</td>
                                    <td width="14%" class="entete">Parution</td>
                                    <td width="12%" class="entete">Attributs</td>
                                    <td width="13%" class="entete">Couverture</td>
                                    <td width="7%" class="entete">Editer</td>
                                </tr>
                              <!-- BEGIN EditionBlock -->
                                <tr> 
                                    <td align="center" class="data"<?php echo $view->BGCOLOR;?>><p> 
                                        <label> 
                                        <input name="btnDefEdit" type="radio" value="<?php echo $view->BTNVALUE;?>" <?php echo $view->ISCHECKED;?> />
                                        </label>
                                        <br />
                                    </p></td>
                                    <td class="data"<?php echo $view->BGCOLOR;?>><?php echo $view->EDITEUR;?></td>
                                    <td class="data"<?php echo $view->BGCOLOR;?>><?php echo $view->COLLECTION;?></td>
                                    <td class="data"<?php echo $view->BGCOLOR;?>><?php echo $view->DTPAR;?></td>
                                    <td valign="middle" class="data" align="center"<?php echo $view->BGCOLOR;?>><img src="<?php echo $view->IMGTT;?>" width="15" height="20" /></td>
                                    <td align="center" class="data"<?php echo $view->BGCOLOR;?>><a href="<?php echo $view->URLIMAGE;?>" target="_blank"><img src="<?php echo $view->URLIMAGE;?>" width="50" height="60" border="0" align="absmiddle" /></a></td>
                                    <td align="center" class="data"<?php echo $view->BGCOLOR;?>><a href="<?php echo $view->URLEDITEDITION;?>"><img src="<?php echo BDO_URL_IMAGE;?>edit.gif" width="18" height="13" border="0" /></a></td>
                                </tr>
                            <!-- END EditionBlock -->
                            </table>
                            <p><a href="<?php echo $view->URLAJOUTEDITION;?>" class="b">Ajouter une nouvelle édition</a></p>
                        </td>
                    </tr>
                </table>
                <div class="submit"> 
                    <input type="submit" name="Submit" value="<?php echo $view->ACTIONNAME;?>" />
                </div>
            </td>
            <td width="287" height="47" bordercolor="#FFFFFF"></td>
        </tr>
        
        <!-- colonne de droite -->
        <tr width="100%"> 
            <td class="cadre_texte-admin">
                <p><strong>Statistiques</strong></p>
                <p>
                    <ul>
                        <li><?php echo $view->NBUSERS;?> utilisateur(s) ont cet album dans leur collection</li>
                        <li><?php echo $view->NBUSERS2;?> utilisateur(s) ont un commentaire sur cet album</li>
                    </ul>
                </p>
                <p><strong>Menu Express</strong></p>
                <p>
                    <ul>
                        <a href="<?php echo $view->URLDELETE;?>"><li>Supprimer cet album</li></a>
                        <a href="<?php echo $view->URLFUSIONDELETE;?>"><li>Fusionner en conservant certaines éditions</li></a>
                        <a href="<?php echo $view->URLSPLIT;?>"><li>Créer un nouvel album à partir des éditions actuelles</li></a>
                        <a href="<?php echo $view->URLFUSION;?>"><li>Fusionner cet album</li></a>
                        <li><a href=# onclick="javascript:window.open('addserie','myserie','scrollbars=no,resizable=yes,width=440,height=140');return(false)"><li>
                            Ajout rapide d'une série
                        </li></a>
                        <a href=# onclick="javascript:window.open('addauteur','myauteur','scrollbars=no,resizable=yes,width=400,height=150');return(false)"><li>
                            Ajout rapide d'un auteur
                        </li></a>
                    </ul>
                </p>
            </td>
        </tr>
  </table>
</form>