<table class="tableaux_admin">
    <tr> 
        <td align="center">
            <img src="<?php echo $view->URLIMAGE;?>" width="180" border="0" align="absmiddle" />
            <br />
            <?php echo $view->DIMIMAGE;?>
        </td>
    </tr>
    <tr> 
        <td class="label">
            Redimensionner la couverture : 
            <input type="checkbox" name="chkResize" value="checked" />
        </td>
    </tr>
    <tr> 
        <td class="label">
            Envoyer depuis un fichier local :
            <br /><input name="txtFileLoc" type="file" id="txtFileLoc" style="width: 100%;" />
        </td>
    </tr>
    <tr> 
        <td class="label">
            Envoyer depuis une URL :
            <br /><input name="txtFileURL" type="text" id="txtFileURL" style="width: 100%;" />
        </td>
    </tr>
</table>