<p><a href="nwl.redaction">Rédiger une nouvelle newsletter</a> </p>
<p>Liste des newsletters : </p>
<table width="100%" border="1" cellspacing="0" cellpadding="0">
  <tr>
  	<td width="15%" class="entete"><div align="center"><strong>Date d'envoi</strong></div></td>
    <td width="15%" class="entete"><div align="center"><strong>Date Maj</strong></div></td>
    <td width="20%" class="entete"><div align="center"><strong>Auteur</strong></div></td>
    <td width="25%" class="entete"><div align="center"><strong>Status</strong></div></td>
    <td width="35%" class="entete"><div align="center"><strong>Commentaire</strong></div></td>
  </tr>
  <!-- BEGIN NewsBlock -->
  <tr>
  	<td width="15%" class="data"><a href="nwl.redaction?nwl_id=<?php echo $view->NWLID;?>"><?php echo $view->DTESEND;?></a></td>
    <td width="15%" class="data"><?php echo $view->DTEMAJ;?></td>
    <td width="20%" class="data"><?php echo $view->AUTEUR;?></td>
    <td width="25%" class="data"><?php echo $view->STATUS;?></td>
    <td width="35%" class="data"><?php echo $view->COMMENT;?></td>
  </tr>
  <!-- END NewsBlock -->
</table>
