<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Document sans titre</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>

<body bgcolor="#FFFFCC" onLoad="<?php echo $view->BODYONLOAD;?>">
<form action="<?php echo $view->URLACTION;?>" method="post" name="input_form" onSubmit="return valider()">
  <table width="100%" border="1" bgcolor="#FFFFCC">
    <tr bordercolor="#FFFFCC"> 
      <td width="7%">Pseudo</td>
      <td width="93%"> <input name="txtPseudo" type="text" id="txtPseudo" size="40"></td>
    </tr>
    <tr bordercolor="#FFFFCC"> 
      <td>Nom</td>
      <td><input name="txtNom" type="text" id="txtNom" size="40"></td>
    </tr>
    <tr bordercolor="#FFFFCC"> 
      <td>Prenom</td>
      <td> <input name="txtPrenom" type="text" id="txtPrenom" size="40"> </td>
    </tr>
    <tr bordercolor="#FFFFCC"> 
      <td colspan="2"> <input type="submit" name="Submit" value="Envoyer"></td>
    </tr>
  </table>
</form>
</body>
</html>
