<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title><?php echo $view->SERTITLE;?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link href="<?php echo BDO_URL;?>style/style1.css" rel="stylesheet" type="text/css" />
</head>

<body>

<div class="cadre1">
			<!-- BEGIN AddBlock -->
			<table width="100%" border="0" align="center">
				<tr>
					<td>
						<p><strong>Noter et commenter <font color="#990000"><?php echo $view->SERTITLE;?></font></strong></p>
					</td>
				</tr>
			  	<form name="form1" method="post" action="commentserie">
				    <tr>
					    <td> Note:
							<select name="note" id="note">
							<option value="1">1</option>
							    <option value="2">2</option>
							    <option value="3">3</option>
							    <option value="4">4</option>
							    <option value="5" selected>5</option>
							    <option value="6">6</option>
							    <option value="7">7</option>
							    <option value="8">8</option>
							    <option value="9">9</option>
							    <option value="10">10</option>
							</select>
							<em>(notez de 1-bof &agrave; 10 - culte)</em>
							<br />
						</td>
				    </tr>
				    <tr>
					      <td>Commentaire : </td>
				    </tr>
				    <tr>
					    <td>
							<p align="left">
					        	<textarea name="comment" class="champ_commentaire"></textarea>
					        </p>
						</td>
				    </tr>
				    <tr>
				    	<td>
							<p align="center">
				          		<input name="id_serie" type="hidden" id="id_serie" value="<?php echo $view->SERID;?>" />
								<input name="lib_tome" type="hidden" id="lib_tome" value="<?php echo $view->SERTITLE;?>" />
				          		<input type="submit" name="Submit" value="Valider" />
				        	</p>
						</td>
				    </tr>
				</form>
			</table>
			<!-- END AddBlock -->
			<?php echo $view->LISTCOMMENT;?>
		</div>

</body>
</html>
