<?php header ( 'Content-Type: text/html; charset=UTF-8' );?>
<!-- cadre central de la page -->

<div class="cadre1">
	<h1><?php echo $view->errorCode;?></h1>

<h2>Page introuvable</h2>

Cette page ne peut pas être trouvée.<br /> 
Si le problème persiste, merci de contacter l'équipe de développement via l'adresse : developpeurs@bdovore.com<br />
<br />
<h2>Page not found</h2>
The server was unable to find the requested page.<br />
If the problem persists, please email our development team : developpeurs@bdovore.com<br />
</pre>
</div>
