<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title><?php echo $view->DOCTITRE;?></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<META name="description" content="Le site des collectionneurs de BD. Gérer votre collection de bandes dessinées en ligne et gratuitement !">
<META name="keywords" content="bd, bandes dessinées, bandes, dessinées, bande, dessinée, profiler, bdprofiler, comics, manga, collection, collections, bdvore, collectionneur, dedicace, auteurs, albums, editeurs, base de données, série BD, séries BD, liste série, <?php echo $view->PAGEKEYWORD;?>">
<META name="author" content="Tomlameche/Latruffe">
<META name="identifier-url" content="http://www.bdovore.com">
<META name="reply-to" content="">
<META name="revisit-after" content="7 days">
<META name="robots" content="all">
</head>
<body>
<p>Séries de bandes dessinées commençant par un <?php echo $view->INITIALE;?> présentes sur BDovore</p>
<!-- BEGIN SeriesBlock -->
<a href="<?php echo $view->URLSERIE;?>"><?php echo $view->SERIE;?></a><br />
<!-- END SeriesBlock -->
<br />
<a href="indexation">Index des séries</a> 
</body>
</html>
