<?php echo $view->MENUGUEST;?>
<div class="cadre1">
    <h2>Mes futurs achats</h2>
      <p><?php echo $view->PASDALBUM;?></p>
      <div align="center">	  
      <!-- BEGIN AlbBlock -->
	  <br>
        <table width="650" border="0" bordercolor="#000000" bgcolor="#EEDED6" dwcopytype="CopyTableRow">
          <tr> 
            <td width="25%" style="vertical-align:top;align:center;"> <img src="<?php echo $view->COUVALBUM;?>" alt="" width="133" border="1"> 
                <a href="<?php echo $view->URLAMAZON;?>" target="_blank"></a></td>
            <td width="75%" align="left" style="vertical-align:top;align:center;"> 
				<table width="100%" height="75%" border="1" cellpadding="3" cellspacing="0" bordercolor="#000000" frame="border" rules="all">
                <tbody>
                  <tr> 
				<td width="17%" bgcolor="#C8857C"><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"><strong>Titre 
                      :</strong></font></td>
                    <td width="54%" bgcolor="#DAC1B3"><font size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
                      <a href="#" onclick="window.open('<?php echo BDO_URL;?>membres/album?id_tome=<?php echo $view->IDTOME;?>','Album','width=550,height=600,scrollbars=1')"><?php echo $view->ALBTITLE;?></a></font></td>
                    <td width="29%" rowspan="7" align="left" valign="top" bgcolor="#DAC1B3"><p><font size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
                        <b>Remarques</b></font></p>
						<p><?php echo $view->REMARQUE;?></p>
                      
                      </td>
                  </tr>
                  <tr>
<td bgcolor="#C8857C"><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"><strong>S&eacute;rie 
                      :</strong></font></td>
                    <td bgcolor="#DAC1B3"><font size="-1" face="Verdana, Arial, Helvetica, sans-serif"><a href="<?php echo $view->URLSERIE;?>"><?php echo $view->SERIE;?></a></font></td>
                     
                     </tr>
                  <tr> 
                    <td bgcolor="#C8857C"><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"><strong>Tome 
                      :</strong></font></td>
                    <td bgcolor="#DAC1B3"><font size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
                      <?php echo $view->NUMTOME;?></font></td>
                  </tr>
                  <tr> 
                    <td bgcolor="#C8857C"><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"><strong>Genre 
                      :</strong></font></td>
                    <td bgcolor="#DAC1B3"><font size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
                      <?php echo $view->ALBGENRE;?></font></td>
                  </tr>
                  <tr> 
                    <td bgcolor="#C8857C"><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"><strong>Scénario 
                      :</strong></font></td>
                    <td bgcolor="#DAC1B3"><font size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
                      <?php echo $view->ALBSCENAR;?></font></td>
                  </tr>
                  <tr> 
                    <td bgcolor="#C8857C"><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"><strong>Dessin 
                      :</strong></font></td>
                    <td bgcolor="#DAC1B3"><font size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
                      <?php echo $view->ALBDESSIN;?></font></td>
                  </tr>
                  <tr> 
                    <td bgcolor="#C8857C"><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"><strong>Editeur 
                      : </strong></font></td>
                    <td bgcolor="#DAC1B3"><font size="-1"><?php echo $view->ALBEDITEUR;?></font></td>
                  </tr>
                </tbody>
              </table> 
			  
              <a href="<?php echo $view->URLAMAZON;?>" target="_blank"><font size="-1">Commander sur 
              Amazon</font></a></td>
          </tr>
        </table>
      <!-- END AlbBlock -->
	  </div>
	  <p><?php echo $view->BARRENAVIGATION;?> </p>
      </div>