<?php echo $view->MENUGUEST;?>
<div class="cadre1">

<h2>En quelques chiffres</h2>
<p><img src="<?php echo BDO_URL;?>graphs/rep_genres?user=<?php echo $view->USERID;?>" alt="Repartition par genres" border="0"></p>
<p><img src="<?php echo BDO_URL;?>graphs/rep_editeurs?user=<?php echo $view->USERID;?>" alt="Repartition par editeurs" border="0"></p>
<p><img src="<?php echo BDO_URL;?>graphs/rep_series?user=<?php echo $view->USERID;?>" alt="Repartition par séries" border="0"></p>
<p><img src="<?php echo BDO_URL;?>graphs/rep_auteurs?user=<?php echo $view->USERID;?>" alt="Repartition par auteurs" border="0"></p>
<p><img src="<?php echo BDO_URL;?>graphs/rep_achats_mois?user=<?php echo $view->USERID;?>" alt="Derniers Achats" border="0"></p>

</div>


