<?php echo $view->MENUGUEST;?>
<div class="cadre1">
    <table width="100%" border="0">
        <tr> 
            <td width="340">
                <table width="300" border="0">
                    <tr> 
                        <td colspan=3 class="CarreMagique" align="center">
                            <font color="#990000">
                                <strong>Mon Carr&eacute; Magique</strong>
                            </font>
                        </td>
                    </tr>
                    <tr> 
                        <td width="100" class="CarreMagique"><?php echo $view->ALB1;?></td>
                        <td width="100" class="CarreMagique"><?php echo $view->ALB2;?></td>
                        <td width="100" class="CarreMagique"><?php echo $view->ALB3;?></td>
                    </tr>
                    <tr> 
                        <td class="CarreMagique"><?php echo $view->ALB4;?></td>
                        <td class="CarreMagique"><?php echo $view->ALB5;?></td>
                        <td class="CarreMagique"><?php echo $view->ALB6;?></td>
                    </tr>
                    <tr> 
                        <td class="CarreMagique"><?php echo $view->ALB7;?></td>
                        <td class="CarreMagique"><?php echo $view->ALB8;?></td>
                        <td class="CarreMagique"><?php echo $view->ALB9;?></td>
                    </tr>
                </table>
            </td>
            <td>
                <p>
                    <font color="#990000"><strong>Information sur le membre</strong></font>
                <p>
                    Date d'arriv&eacute;e sur BDovore : <?php echo $view->DTEARRIVEE;?>
                    <br />
                    Nombre de posts sur le forum : <?php echo $view->NBPOSTS;?>
                </p>
                <p><font color="#990000"><b>Informations sur la collection de l'utilisateur</b></font></p>
                <p>
                    Nombre d'albums : <?php echo $view->NBALBUMS;?> dont <?php echo $view->NBINTEGRALES;?> int&eacute;grales.
                    <br />
                    Nombre de coffrets : <?php echo $view->NBCOFFRETS;?>
                    <br />
                    Nombre de s&eacute;ries suivies par cet utilisateur : <?php echo $view->NBSERIES;?>
                    <br />
                    Nombre d'achats pr&eacute;vus par cet utilisateur : <?php echo $view->NBACHATS;?>
                </p>
                <p><font color="#990000"><b>Contributions &agrave; la base de donn&eacute;es</b></font></p>
                <p>
                    Propositions de nouveaux albums : <?php echo $view->NBPROPS;?>
                    <br />
                    Propositions de corrections : <?php echo $view->NBCORRECTIONS;?>
                </p>
                <p>&nbsp;</p>
                <p><br /><br /></p>
            </td>
            <td width="100">
                <table width="100%" border="0">
                    <tr> 
                        <td align="center">
                            <font color="#990000"><b>Derniers achats</b></font>
                        </td>
                    </tr>
                    <tr> 
                        <td class="CarreMagique"><?php echo $view->LASTPURCH1;?></td>
                    </tr>
                    <tr> 
                        <td class="CarreMagique"><?php echo $view->LASTPURCH2;?></td>
                    </tr>
                    <tr> 
                        <td class="CarreMagique"><?php echo $view->LASTPURCH3;?></td>
                    </tr>
                    <tr> 
                        <td class="CarreMagique"><?php echo $view->LASTPURCH4;?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>