<?php echo $view->MENUGUEST;?>
<div class="cadre1">
    <h2>Mes derniers achats</h2>
      <div align="center">	  
      <!-- BEGIN AlbBlock -->
	  <br>
      <table width="650" border="0" bordercolor="#000000" bgcolor="#EEDED6" dwcopytype="CopyTableRow">
        <tr> 
          <td width="13%" valign="top" align="center"> <img src="<?php echo $view->COUVALBUM;?>" alt="" width="133" height="173" border="1"></td>
          <td width="87%" align="left" valign="top"> <table width="100%" height="75%" border="1" cellpadding="3" cellspacing="0" bordercolor="#000000" frame="border" rules="all">
              <tbody>
                
                <tr> 
                  <td width="25%" bgcolor="#C8857C"><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"><strong>Titre 
                    :</strong></font></td>
                  <td width="75%" bgcolor="#DAC1B3"><font size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
                    <a href="#" onclick="window.open('<?php echo BDO_URL;?>membres/album?id_tome=<?php echo $view->IDTOME;?>','Album','width=550,height=600,scrollbars=1')"><?php echo $view->ALBTITLE;?></a></font></td>
                </tr>
<tr> 
                  <td bgcolor="#C8857C"><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"><strong>S&eacute;rie 
                    :</strong></font></td>
                  <td bgcolor="#DAC1B3"><font size="-1" face="Verdana, Arial, Helvetica, sans-serif"><a href="<?php echo $view->URLSERIE;?>"><?php echo $view->SERIE;?></a></font></td>
                </tr>
                <tr> 
                  <td bgcolor="#C8857C"><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"><strong>Tome 
                    :</strong></font></td>
                  <td bgcolor="#DAC1B3"><font size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
                    <?php echo $view->NUMTOME;?></font></td>
                </tr>
                <tr> 
                  <td bgcolor="#C8857C"><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"><strong>Genre 
                    :</strong></font></td>
                  <td bgcolor="#DAC1B3"><font size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
                    <?php echo $view->ALBGENRE;?></font></td>
                </tr>
                <tr> 
                  <td bgcolor="#C8857C"><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"><strong>Scénario 
                    :</strong></font></td>
                  <td bgcolor="#DAC1B3"><font size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
                    <?php echo $view->ALBSCENAR;?></font></td>
                </tr>
                <tr> 
                  <td bgcolor="#C8857C"><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"><strong>Dessin 
                    :</strong></font></td>
                  <td bgcolor="#DAC1B3"><font size="-1" face="Verdana, Arial, Helvetica, sans-serif"> 
                    <?php echo $view->ALBDESSIN;?></font></td>
                </tr>
                <tr> 
                  <td height="30" bgcolor="#C8857C"><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif"><strong>Editeur 
                    : </strong></font></td>
                  <td bgcolor="#DAC1B3"><font size="-1"><?php echo $view->ALBEDITEUR;?></font></td>
                </tr>
              </tbody>
            </table></td>
        </tr>
        <tr> 
          <td valign="top" align="center">&nbsp;</td>
          <td align="left" valign="top"> <table width="100%" border="1" bordercolor="#EEDED6">
                <tr> 
                  <td bordercolor="#000000" bgcolor="#DAC1B3"> 
                    <p><?php echo $view->NOTE;?></p>
                    <p><?php echo $view->COMMENTAIRE;?></p></td>
              </tr>
            </table></td>
        </tr>
      </table>
      <!-- END AlbBlock -->
	  </div>
	  <br>
    </div>