<div class="cadre1">
<h2>Le Guide BD</h2>
		<a href="listlast?rb_mode=futur">A paraitre</a> 
		- <a href="listlast?rb_mode=last_par">Derni&egrave;res parutions</a>
		- <a href="listop?rb_mode=top_vote">Top des notes</a> 
		- <a href="listop?rb_mode=top_rep">Albums les plus répandus</a>
		- <a href="listlast?rb_mode=last_cmt">Derniers commentaires</a> 

		<table width="100%" align="center" cellpadding="10" cellspacing="10">	  
			<tr bordercolor="#FFFFFF">
		  		<td valign="top" bordercolor="#FFFFFF"> 
            		<form name="form1" method="post" action="listop">
              			<table width="100%" border="1" cellpadding="5" cellspacing="0" bordercolor="#FFFFCC" bgcolor="#DAC1B3"   frame="box" rules="groups">
              				<tr>
                				<td><label for="rb_list1"><input id="rb_list1" name="rb_list" type="radio" value="album" <?php echo $view->ALBCHECK;?>>
                  				Albums</label><br />
				  				<label for="rb_list2"><input id="rb_list2" type="radio" name="rb_list" value="serie" <?php echo $view->SERCHECK;?>>
                  				Séries</label> 
				  				</td>
                				<td>
                				<label for="rb_top1"><input id="rb_top1" type="radio" name="rb_mode" value="top_vote" <?php echo $view->TOPCHECKED;?>>
                  				Top des votes</label><br /> 
			                  <label for="rb_top2"><input id="rb_top2" type="radio" name="rb_mode" value="top_rep" <?php echo $view->REPCHECKED;?>>
                  				Les plus r&eacute;pandus</label>
								</td>

                				<td align="center">Genre : 
                  				<select name="sel_genre" size="1" id="sel_genre">
								<?php echo $view->OPTIONS;?>
        		 				 </select>
        		 				 <br /><input type="submit" name="Submit" value="Envoyer"></td>
              			</tr>
            		</table>
  				</form>
  			</td>
  		</tr>
	 </table>
</div>
<div class="cadre1">

	<table width="100%" border="1" align="center" cellpadding="5" cellspacing="0" bordercolor="#000000" frame="hsides" rules="rows">
	<!-- BEGIN AlbBlock -->
   		<tr>
        	
          <td width="110"> <div align="left"><a href=<?php echo $view->URLALBUM;?> title="<?php echo $view->TITRE;?>"><img src='<?php echo BDO_URL_COUV;?><?php echo $view->IMGCOUV;?>'  border="none" width="100" heigh="140"></a>
              <br>
              <font size="-2">&copy; <?php echo $view->EDITEUR;?></font> </div></td>
        	<td valign="top">
				<p><a href=<?php echo $view->URLALBUM;?>><font size="-1" face="Verdana, Arial, Helvetica, sans-serif" color="#990000"><strong><?php echo $view->TITRE;?></strong></font></a> 
            	<?php echo $view->EDITALBUM;?><br/>
            	Série : <a href="<?php echo $view->URLSERIE;?>"><?php echo $view->SERIE;?></a> <?php echo $view->EDITSERIE;?><br/>
            	Editeur : <?php echo $view->EDITEUR;?> <br />
          		Scénario :<a href="<?php echo $view->URLSCEN;?>"><?php echo $view->SCEN;?></a> <br />
				Dessin : <a href="<?php echo $view->URLDESS;?>"><?php echo $view->DESS;?></a><br />
				Note : <?php echo $view->MOYENNE;?> pour <?php echo $view->NBVOTE;?> vote(s)<br />
				<?php echo $view->NBUSER;?> utilisateurs possèdent cet album
				</p>
			</td>
      </tr>
	  <!-- END AlbBlock -->
	  <!-- BEGIN SerBlock -->
   	  <tr>
          <td width="110"> <div align="left"><a href=<?php echo $view->URLSERIE;?> title="<?php echo $view->SERTITRE;?>"><img src='<?php echo BDO_URL_COUV;?><?php echo $view->IMGCOUV;?>'  border="none" width="100" heigh="140"></a>
            </div></td>       
    	<td valign="top"> <a href=<?php echo $view->URLSERIE;?>><font size="-1" face="Verdana, Arial, Helvetica, sans-serif" color="#990000"><strong><?php echo $view->SERTITRE;?></strong></font></a> 
		<?php echo $view->EDITALBUM;?><br/>
          Avancement : <?php echo $view->SERAVCT;?> <?php echo $view->EDITSERIE;?> <br>
			Note : <?php echo $view->MOYENNE;?><br>
          <?php echo $view->NBUSER;?> utilisateurs possèdent un album de cette s&eacute;rie
		</td>
      </tr>
	  <!-- END SerBlock -->
  </table>
	<div align="center"><a href="listop?<?php echo $view->PREC;?>">Pr&eacute;c&eacute;dent</a> 
  <a href="listop?<?php echo $view->SUIV;?>">Suivant</a></div>
</div>