<div class="cadre1">
<h3>Proposition <?php echo $view->TYPEENCOURS;?> en cours... <?php echo $view->NBTOTAL;?></h3>
      <!-- BEGIN LinksBlock -->
      <a href="listpropal?type=<?php echo $view->TYPEAUTRE;?>"><?php echo $view->AJOUTCORRECTION;?></a><br>
      <!-- END LinksBlock -->
<br>
      <table width="100%" height="29" class="donnees">
        <tr> 
          <td width="20%" class="entete"><div align="center"><font color="#0000FF"><strong>
		  <a href="<?php echo BDO_URL;?>listpropal?type=<?php echo $view->TYPE;?>&cle=1&sort=asc">
		  	<img src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12" height="12" hspace="5" border="0"></a>S&eacute;rie
		 <a href="<?php echo BDO_URL;?>listpropal?cle=1&sort=DESC&type=<?php echo $view->TYPE;?>">
		 	<img src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12" height="12" hspace="5" border="0"></a></strong></font></div></td>
          <td width="5%" class="entete"><div align="center"><strong>Tome</strong></div></td>
          <td width="25%" class="entete"><div align="center"><strong>Titre</strong></div></td>
          <td width="20%"  class="entete"><div align="center"><font color="#0000FF"><strong><a href="<?php echo BDO_URL;?>listpropal?type=<?php echo $view->TYPE;?>&cle=2&sort=asc"><img src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12" height="12" hspace="5" border="0"></a>Demand&eacute;e 
              Par<a href="<?php echo BDO_URL;?>listpropal?type=<?php echo $view->TYPE;?>&cle=2&sort=desc"><img src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12" height="12" hspace="5" border="0"></a></strong></font></div></td>
          <td width="15%" class="entete"> <div align="center"><font color="#0000FF"><strong><a href="<?php echo BDO_URL;?>listpropal?cle=3&sort=asc&type=<?php echo $view->TYPE;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12" height="12" hspace="5" border="0"></a>Demand&eacute; 
              le <a href="<?php echo BDO_URL;?>listpropal?type=<?php echo $view->TYPE;?>&cle=3&sort=desc"><img src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12" height="12" hspace="5" border="0"></a></strong></font></div></td>
        </tr>
        <!-- BEGIN DetailBlock -->
        <tr> 
          <td width="20%" class="data"><div align="center"><?php echo $view->SERIE;?></div></td>
          <td width="5%" class="data"><div align="center"><?php echo $view->TOME;?></div></td>
          <td width="25%" class="data"><?php echo $view->TITRE;?></td>
          <td width="20%"  class="data"><div align="center"><?php echo $view->AUTEUR;?></div></td>
          <td width="15%" class="data"> <div align="center"><?php echo $view->DTEPAR;?></div></td>
        </tr>
        <!-- END DetailBlock -->
      </table>
<p class="texte"><?php echo $view->BARRENAVIGATION;?></p>
</div>