<?php
if (Bdo_Cfg::user()->minAccessLevel(2)) {
    ?>
		    <div id="loginContainer" class="shadow">
               <a href="#" id="loginButton"><span><?php echo $_SESSION['userConnect']->username;?></span><em></em></a>
                <div style="clear:both"></div>
                <div id="loginBox" class="shadow">                
                    <form id="loginForm" method="post" action="<?php echo BDO_URL;?>">
                        <fieldset id="loginBody">
                            <input type="submit" id="submitLoginDisconnect" name="submitLoginDisconnect" value="Se déconnecter" />
                        </fieldset>
                        <span><a href="<?php echo BDO_URL;?>membres/profil"><font
		style="font-size: 10">Mon compte</font></a></span>
                    </form>
                </div>
            </div>
<?php
}
else {
    ?>
		    <div id="loginContainer" class="shadow">
               <a href="#" id="loginButton"><span>Connexion</span><em></em></a>
                <div style="clear:both"></div>
                <div id="loginBox" class="shadow">                
                    <form id="loginForm" method="post" action="<?php echo BDO_URL;?>">
                        <fieldset id="loginBody">
                            <fieldset>
                                <label for="user_login">Pseudo</label>
                                <input type="text" name="user_login" id="user_login" />
                            </fieldset>
                            <fieldset>
                                <label for="user_password">Mot de passe</label>
                                <input type="password" name="user_password" id="user_password" />
                            </fieldset>
                            <input type="submit" id="submitLoginConnect" name="submitLoginConnect" value="Se connecter" />
                            <label for="chkvisit"><input type="checkbox" id="chkvisit" name="chkvisit" />Se souvenir de moi.</label>
                        </fieldset>
                        <span><a href="#">Vous n'êtes pas inscrit ?</a></span>
                        <span><a href="#">Mot de passe oublié ?</a></span>
                                            </form>
                        <div id="openidProvider">
                        	<!-- Simple OpenID Selector -->
	<form action="<?php echo BDO_URL;?>auth/provideropenid" method="get" id="openid_form">
		<input type="hidden" name="action" value="verify" />

			<div id="openid_choice">
				Vous connectez par :
				<div id="openid_btns"></div>
			</div>
			<div id="openid_input_area">
				<input id="openid_identifier" name="openid_identifier" type="text" value="http://" />
				<input id="openid_submit" type="submit" value="Sign-In"/>
			</div>
			<noscript>
				<p>OpenID is service that allows you to log-on to many different websites using a single indentity.
				Find out <a href="http://openid.net/what/">more about OpenID</a> and <a href="http://openid.net/get/">how to get an OpenID enabled account</a>.</p>
			</noscript>

	</form>
	<!-- /Simple OpenID Selector -->

                        </div>

                </div>
            </div>
<?php
/*
        Connexion par fournisseur d'OpenId ...
        <ul>
        <li><a href="<?php echo BDO_URL;?>auth/google" title="Google"><img src="<?php echo BDO_URL_IMAGE;?>/site/openid_provider/google.png" /></a></li>
        </ul>
 */
}
?>