<!-- BEGIN NewsBlock -->
<table width="75%" border="1" cellpadding="0" cellspacing="0" bordercolor="#FFFFFF">
  <tr>
    <td width="18%"><img src="<?php echo BDO_URL_IMAGE;?>News_entete.gif" width="90" height="20" hspace="0" vspace="0"></td>
    <td width="38%" bordercolor="#FFFFFF"><strong><font color="#0000FF" size="2" face="Arial, Helvetica, sans-serif"><?php echo $view->TITRE;?></font></strong></td>
    <td bordercolor="#FFFFFF"> <div align="right"><font size="1" face="Arial, Helvetica, sans-serif"><font color="#0000FF" size="2" face="Arial, Helvetica, sans-serif"><font color="#333333">Post&eacute;e
        par<strong> <?php echo $view->AUTEUR;?></strong></font></font> le <?php echo $view->DATE;?></font></div></td>
  </tr>
</table>
<table width="75%" border="1" cellpadding="5" bordercolor="#000000">
  <tr>
    <td colspan="3" bordercolor="#FFFFFF"><font size="2" face="Arial, Helvetica, sans-serif"><?php echo $view->NEWSCONTENT;?></font></td>
  </tr>
</table>
<!-- END NewsBlock -->
<p> <?php echo $view->BARRENEWS;?> </p>
