<hr class="expSep" />
<div class="cadre1" id="news_du_site">
    <div class="middle_title" ><h3>News du site</h3></div>
     <div  id="newsfacebook"class="cadre1" ><div class="middle_title" id="titlefacebook"><h3>Sur facebook</h3></div></div>
    <div id="accordion" >
    <?php
        foreach ($view->a_lastNews as $lastNews) {
            ?>
        <div class="cadre1">
      <h4><?php echo $lastNews->news_titre;?>- Postée par <?php echo $lastNews->news_posteur;?> le <?php echo $lastNews->news_date;?></h4>
      <div>
        <p>
    <?php echo $lastNews->news_text;?>
        </p>
      </div>
      </div>
                     <?php
        }
        ?>

    </div>
     
</div>
<script>

/*$(function() {
    $( "#accordion" ).accordion({header: "h4", collapsible: true, heightStyle: "content"});
});
*/
</script>
