
<p></p>
<table width="75%" border="1" cellpadding="0" cellspacing="0" bordercolor="#CCCCCC">
  <tr bordercolor="#FFFFFF"> 
    <td height="25"><strong><font color="#990000" face="Arial, Helvetica, sans-serif"><?php echo $view->TITRE;?></font></strong></td>
    <td> 
      <div align="right"><font face="Arial, Helvetica, sans-serif"><font color="#0000FF" face="Arial, Helvetica, sans-serif"><font color="#333333">Post&eacute;e 
        par<strong> <?php echo $view->AUTEUR;?></strong></font></font> le <?php echo $view->DATE;?></font></div></td>
  </tr>
  <tr bordercolor="#FFFFFF"> 
    <td colspan="3"><font face="Arial, Helvetica, sans-serif"><?php echo $view->NEWSCONTENT;?></font></td>
  </tr>
</table>
<font color="#0000FF" size="1" face="Arial, Helvetica, sans-serif"><?php echo $view->ACTION;?></font>
<p>&nbsp; </p>

