<?php echo $view->MENUCOLL;?>
<div class="cadre1">
	<form name="form1" method="post" action="../membres/profil?act=update&user_id=<?php echo $view->USERID;?>">
	  <h2>Profil de <font color="#990000"><?php echo $view->UTILISATEUR;?></font></h2>


	    <table align="center" border="0" cellpadding="5" cellspacing="0" bordercolor="#FFFFCC">
          <tr> 
		  <td align="right">Adresse e-mail :</td>
		  <td><input name="txtemail" type="text" id="txtemail" value="<?php echo $view->EMAIL;?>" size="50"></td>
		  <td align="center" rowspan="4"><img name="Photo" src="<?php echo $view->PICTURE;?>" alt=""></td>
		</tr>
		<tr> 
		  <td align="right">Ville :</td>
		  <td><input name="txtlocation" type="text" id="txtlocation" value="<?php echo $view->LOCATION;?>"></td>
		</tr>
        <tr> 
		  <td align="right">Date de naissance :</td>
		  <td><input name="txtanniv" type="text" id="txtanniv" value="<?php echo $view->BIRTHDAY;?>">(aaaa-mm-jj)</td>
		</tr>
		<tr> 
		  <td align="right">Mot de passe :</td>
		    <td><a href="../membres/profil?act=newpass&user_id=<?php echo $view->USERID;?>">
		    Changer le mot de passe</a></td>
		</tr>
		<tr> 
		  <td colspan=2>&nbsp;</td>
		  <td align="center"><a href="../membres/profil?act=image&user_id=<?php echo $view->USERID;?>">
		  Changer l'avatar du forum</a></td>
		</tr>
	  </table>
	  <br />
	  <h3>Personnalisation</h3>
	    <table border="0" cellpadding="5" cellspacing="0" bordercolor="#FFFFCC">
          <tr> 
            <td align="right">Nombres de réponses affichées lors des recherches :</td>
            <td><select name="lstRowDisplay" size="1">
				<?php echo $view->OPTIONDISPLAY;?>
			  </select></td>
          </tr>
          <tr> 
            <td align="right">Nombre d'albums affich&eacute;s dans la fiche s&eacute;rie :</td>
            <td><select name="lstRowSerie" size="1" id="lstRowSerie">
				<?php echo $view->OPTIONDISPLAYSERIE;?>
			  </select></td>
          </tr>
          <tr> 
            <td  align="right">Autoriser les autres utilisateurs &agrave; consulter ma collection :</td>
            <td><select name="lstOpenCollec" size="1">
                <option value="Y" <?php echo $view->YESISSELECTED;?>>Oui</option>
                <option value="N" <?php echo $view->NOISSELECTED;?>>Non</option>
              </select></td>
          </tr>
          <tr> 
            <td colspan="2">D'autres utilisateurs pourront acc&eacute;der &agrave; 
              votre collection via l'adresse suivante : <br /><a href="<?php echo $view->URLCOLLEC;?>"><?php echo $view->URLCOLLEC;?></a></td>
          </tr>
          <tr> 
            <td align="right">Selection du carr&eacute; magique :</td>
            <td><select name="lstCarre" size="1"><?php echo $view->OPTIONCARRE;?>
              </select></td>
          </tr>
          <tr> 
		  <td align="right">Je souhaite recevoir la newsletter de BDovore :</td>
		    <td><input type="checkbox" name="txtNewsletter" value="checked" <?php echo $view->IS_NEWSLETTER;?>></td>
		</tr>

	  </table>
<br>

	<div align="center">
	<input type="submit" name="Submit2" value="Mettre a jour"><br /><br />
	</div>
</div>

<div class="cadre1">

      <h2>Suppression de compte BDoVORE</h2>
      <div align="center">Si vous voulez supprimer votre profil BDoVore définitivement, cette option est pour vous.
      Votre collection, les commentaires et notes que vous avez pu ajouter seront supprimés.
      Peut être souhaitez vous <a href="../membres/export">exporter votre collection</a> avant cela ?<br />
          <br />
          <input type="button" name="delete" value="Suppression du compte BDoVORE" onClick="
          if(confirm('Suppression définitive du compte sans retour arrière !')){
           if(confirm('Après cette dernière confirmation, votre compte sera supprimé !\nVoules vous vraiment supprimer votre compte et donc votre collection ?')){
           window.location.href='../membres/profil?act=delete&user_id=<?php echo $view->USERID;?>';
          }
          }
          "></div>

</form>
</div>
