<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title><?php echo $view->DOCTITRE;?></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php echo $view->CSSSTYLE;?>
<style type="text/css">
<!-- BEGIN CSSBlock -->
<?php echo $view->ADDITIONALCSS;?>
<!-- END CSSBlock -->
</style>
</head>
<body>
<div id="logo"><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Galerie Photos</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link href="http://www.www.bdovore.com/style/design.css" rel="stylesheet" type="text/css">

<style type="text/css">
<!-- BEGIN CSSBlock -->

<!-- END CSSBlock -->
</style>
</head>
<body>
<div id="logo"><img src="<?php echo BDO_URL_IMAGE;?>site/bdovore.gif" alt="BDovore" /></div>
<div id="login"><?php echo $view->LOGIN;?></div>
<div id="menu"><?php echo $view->MENU;?></div>
<div id="content"><?php echo $view->CONTENT;?></div>

</body>
</html>
