<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
    <title><?php echo $view->DOCTITRE;?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <?php echo $view->CSSSTYLE;?>
</head>

<body>

<div id="fiche">
    <div id="couv">
        <img id="couv2" src="<?php echo $view->URLCOUV;?>" alt="Couverture" />
        <br />
        &copy; <?php echo $view->SHORTEDIT;?>
    </div>
    <table id="info">
        <tr>
            <td class="album" colspan="2"><a href="#" onclick="window.open('<?php echo $view->URLTITRE;?>','Album','width=500,height=400,scrollbars=1')"><?php echo $view->TITRE;?></a></td>
        </tr>
        <tr>
            <td class="entete"><?php echo $view->LBLSERIE;?></td>
            <td class="contenu"><a href="<?php echo $view->URLSERIE;?>" target="_blank"><?php echo $view->SERIE;?></a></td>
        </tr>
        <tr>
            <td class="entete">Scénario :</td>
            <td class="contenu"><a href="<?php echo $view->URLSCENAR;?>" target="_blank"><?php echo $view->SCENARISTE;?></a></td>
        </tr>
        <tr>
            <td class="entete">Dessin :</td>
            <td class="contenu"><a href="<?php echo $view->URLDESSIN;?>" target="_blank"><?php echo $view->DESSINATEUR;?></a></td>
        </tr>
        <tr>
            <td class="entete">Couleurs :</td>
            <td class="contenu"><a href="<?php echo $view->URLCOLOR;?>" target="_blank"><?php echo $view->COLORISTE;?></a></td>
        </tr>
        <tr>
            <td class="entete">Editeur :</td>
            <td class="contenu"><?php echo $view->EDITEUR;?></td>
        </tr>
        <tr>
            <td class="entete">Parution :</td>
            <td class="contenu"><?php echo $view->DTEPARUTION;?></td>
        </tr>
        <tr>
            <td class="afutur" colspan="2"><a href="#" onclick="window.open('<?php echo $view->URLACHATFUTUR;?>','Album','width=200,height=80,scrollbars=1')">Ajouter à mes achats futurs</a></td>
        </tr>
    </table>
    <div class="space">&nbsp;</div>
</div>
<div class="space">&nbsp;</div>
</body>
</html>