<div class="cadre1">
<!-- BEGIN NewsBlock -->
<p></p>
<table width="95%" border="0" align="center" cellpadding="3" cellspacing="0" bordercolor="#B64444"> 
<tbody><tr bordercolor="#FFFFFF"> 
                              <td height="25" bordercolor="#B64444" bgcolor="#C8857C"><strong><font color="#990000" face="Arial, Helvetica, sans-serif" size="2">
<?php echo $view->TITRE;?>
</font></strong></td>
<td bordercolor="#B64444" bgcolor="#C8857C"> 
                                <div align="right"><font face="Arial, Helvetica, sans-serif" size="1"><font color="#0000ff" face="Arial, Helvetica, sans-serif" size="2"><font color="#333333">Postée 
                                  par <strong><?php echo $view->AUTEUR;?></strong></font></font> 
                                  le <?php echo $view->DATE;?></font></div></td> 
  </tr> 

    
  <tr bordercolor="#B64444"> 
    <td colspan="2"><font size="2" face="Arial, Helvetica, sans-serif"><?php echo $view->NEWSCONTENT;?></font></td>
  </tr>
</table>
<!-- END NewsBlock -->
<p> <?php echo $view->BARRENEWS;?> </p>
</div>
