<?php echo $view->MENUCOLL;?>
<link href="<?php echo BDO_URL;?>style/export.css" rel="stylesheet" type="text/css">

<div class="cadre1">
   	
<form action="export?act=export" method="post" name="export">

<div class="expTitle">Exportation de données</div>

<div class="expFieldBlock">
<div class="expTitle2">ALBUMS</div>
Titre<input type="checkbox" name="sel_field[]" value="1" checked /><br />
Série<input type="checkbox" name="sel_field[]" value="0" <?php echo $view->SELFIELD0;?> /><br />
Tome<input type="checkbox" name="sel_field[]" value="2" <?php echo $view->SELFIELD2;?> /><br />
ISBN<input type="checkbox" name="sel_field[]" value="3" <?php echo $view->SELFIELD3;?> /><br />
Genre<input type="checkbox" name="sel_field[]" value="4" <?php echo $view->SELFIELD4;?> /><br />
Scénariste<input type="checkbox" name="sel_field[]" value="5" <?php echo $view->SELFIELD5;?> /><br />
Déssinateur<input type="checkbox" name="sel_field[]" value="6" <?php echo $view->SELFIELD6;?> /><br />
Editeur<input type="checkbox" name="sel_field[]" value="7" <?php echo $view->SELFIELD7;?> /><br />
Collection<input type="checkbox" name="sel_field[]" value="8" <?php echo $view->SELFIELD8;?> /><br />
Date de parution<input type="checkbox" name="sel_field[]" value="9" <?php echo $view->SELFIELD9;?> /><br />
</div>


<div class="expFieldBlock">
<div class="expTitle2">COLLECTION</div>
Date d'ajout<input type="checkbox" name="sel_field[]" value="10" <?php echo $view->SELFIELD10;?> /><br />
Note<input type="checkbox" name="sel_field[]" value="11" <?php echo $view->SELFIELD11;?> /><br />
Commentaire<input type="checkbox" name="sel_field[]" value="12" <?php echo $view->SELFIELD12;?> /><br />
Album prêté<input type="checkbox" name="sel_field[]" value="13" <?php echo $view->SELFIELD13;?> /><br />
Emprunteur<input type="checkbox" name="sel_field[]" value="14" <?php echo $view->SELFIELD14;?> /><br />
Date d'achat<input type="checkbox" name="sel_field[]" value="15" <?php echo $view->SELFIELD15;?> /><br />
Prix d'achat<input type="checkbox" name="sel_field[]" value="16" <?php echo $view->SELFIELD16;?> /><br />
Cadeau<input type="checkbox" name="sel_field[]" value="17" <?php echo $view->SELFIELD17;?> /><br />
Edition originale<input type="checkbox" name="sel_field[]" value="18" <?php echo $view->SELFIELD18;?> /><br />
</div>



<div class="expRadioBlock">

      <div align="center">
       <div class="expTitle2">Format</div>
      </div>

        <p> 
           
         <label><input type="radio" name="info" value="0" <?php echo $view->TYPE0;?> />Excel</label><br/>
          <label><input type="radio" name="info" value="1" <?php echo $view->TYPE1;?> />CSV</label><br/>
          <label><input type="radio" name="info" value="2" <?php echo $view->TYPE2;?> />XML</label><br/>
          <label><input type="radio" name="info" value="3" <?php echo $view->TYPE3;?> />HTML</label>
        </p>
</div>

<div class="expRadioBlock">

      <div align="center">
        	<div class="expTitle2">Information à exporter</div>
      </div>

        <p> 
          <label><input type="radio" name="contenu" value="0" <?php echo $view->CONTENU0;?> />Collection</label><br/>
          <label><input type="radio" name="contenu" value="1" <?php echo $view->CONTENU1;?> />Achats Futurs</label><br/>
          <label><input type="radio" name="contenu" value="2" <?php echo $view->CONTENU2;?> />Albums manquants</label>
        </p>
</div>
<hr class="expSep" />
<div class="expRadioBlock">
Mémoriser la selection<input type="checkbox" name="memsel" value="checked" /><br />
</div>
<hr class="expSep" />
<p>
<input type="submit" name="Submit2" value="Exporter" /> <br />
</p>
</form>

</div>

      </form>





