<SCRIPT language="Javascript"> 
<!-- 
  
function Chargement() { 
 d = document.exclAlb;
 for (i = 0; i < d.elements.length; i++) {
   if (d.elements[i].name == "sel_tome[]") {
     d.elements[i].checked = true;
   }
 }
} 
  
//--> 
</SCRIPT>

<?php echo $view->MENUCOLL;?>
<div class="cadre1">
<div class="genTitle">S&eacute;ries &agrave; compl&eacute;ter</div>
<form name ="selSerie" action="<?php echo $view->ACTION1;?>" method="post">

<div class="genBlock">
<p>Rechercher les albums manquants dans :</p>
<p><select name="lstSerie" size="1" id="lstSerie" onChange="submit();"><?php echo $view->OPTSOURCE;?></select></p>
<p><a href="<?php echo $view->URLEXCLUSERIE;?>">Exclure cette série de mes albums à compléter</a></p>
<p><a href="<?php echo $view->RAZSERIE;?>">Annuler les exclusions pour cette série</a></p>
</div>
<hr class="genSep"/>
</form>
<form name ="exclAlb" action="<?php echo $view->ACTION2;?>" method="post">
<div class="genBlock"> 
        <table class="genTable">
          <tr> 
            <td class="genTitle">Sel</td>
            <td class="genTitle"><a href="<?php echo BDO_URL;?>membres/albmanquant?cle=1&sort=asc&id_serie=<?php echo $view->SERID;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechehautr.gif" width="12" height="12" hspace="5" border="0"></a>Titre<a href="<?php echo BDO_URL;?>membres/albmanquant?cle=1&sort=desc&id_serie=<?php echo $view->SERID;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechebasr.gif" width="12" height="12" hspace="5" border="0"></a></td>
            <td class="genTitle"><a href="<?php echo BDO_URL;?>membres/albmanquant?cle=2&sort=asc&id_serie=<?php echo $view->SERID;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechehautr.gif" width="12" height="12" hspace="5" border="0"></a>Tome<a href="<?php echo BDO_URL;?>membres/albmanquant?cle=2&sort=desc&id_serie=<?php echo $view->SERID;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechebasr.gif" width="12" height="12" hspace="5" border="0"></a></td>
            <td class="genTitle"><a href="<?php echo BDO_URL;?>membres/albmanquant?cle=3&sort=asc&id_serie=<?php echo $view->SERID;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechehautr.gif" width="12" height="12" hspace="5" border="0"></a>Date 
              Parution <a href="<?php echo BDO_URL;?>membres/albmanquant?cle=3&sort=desc&id_serie=<?php echo $view->SERID;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechebasr.gif" width="12" height="12" hspace="5" border="0"></a></td>
          </tr>
          <!-- BEGIN DetailBlock -->
          <tr> 
            <td class="genData"><input type="checkbox" name="sel_tome[]" value="<?php echo $view->IDTOME;?>"></td>
            <td class="genData"><a href="<?php echo $view->URLTITRE;?>"><?php echo $view->TITRE;?></a></td>
            <td class="genData"><?php echo $view->TOME;?></td>
            <td class="genData"><?php echo $view->DTEPAR;?></td>
          </tr>
          <!-- END DetailBlock -->
        </table>
 <p><a name="ici" href="#ici" onClick="Chargement();">Tout sélectionner</a></p>
 <p><input name="B_Add" type="submit" id="B_Add2" value="Exclure des albums manquants"></p>
 </div>
 </form>


<hr class="genSep"/>
<form name ="selSerieExclu" action="<?php echo $view->ACTIONEXCLU;?>" method="post">

<div class="genBlock">
<p>Liste des séries avec au moins un album exclu :</p>
<p><select name="id_serie" size="1" id="idSerieExclu" ><?php echo $view->OPTSOURCEEXCLU;?></select></p>
<p><input name="actAnnExclu" type="submit" id="B_annEclu" value="Annuler les exclusions pour cette série"></p>
</div>
<hr class="genSep"/>
</form>


</div>
