<?php echo $view->MENUCOLL;?>
<div class="cadre1">
	  <form action="<?php echo BDO_URL;?>membres/mass_update" method="post" name="Filter">
        <table width="495" border="1" cellspacing="0" bordercolor="#990000" frame="box" rules="groups">
          <tr bordercolor="#EEDED6"> 
            <td width="139"><strong>Champs à éditer</strong></td>
            <td width="225"><strong>Filtres</strong></td>
            <td width="117"> </td>
          </tr>
          <tr bordercolor="#EEDED6"> 
            <td> 
              <select name="lstCle0"><?php echo $view->OPTIONCLE0;?>
                 
              </select></td>
            <td> 
              <input type="checkbox" name="chkFiltre1" value="checkbox" <?php echo $view->ISCHECKED1;?>>
              Futurs achats</td>
            <td> 
              <input type="checkbox" name="chkFiltre2" value="checkbox" <?php echo $view->ISCHECKED2;?>>
              Non noté</td>
          </tr>
          <tr bordercolor="#EEDED6"> 
            <td> 
              <select name="lstCle1"><?php echo $view->OPTIONCLE1;?>
                </select></td>
            <td> 
              <input type="checkbox" name="chkFiltre3" value="checkbox" <?php echo $view->ISCHECKED3;?>>
              Albums prêtés</td>
            <td> 
              <input type="checkbox" name="chkFiltre4" value="checkbox" <?php echo $view->ISCHECKED4;?>>
              Non commenté</td>
          </tr>
          <tr bordercolor="#EEDED6"> 
            <td> 
              <select name="lstCle2"><?php echo $view->OPTIONCLE2;?>
                </select></td>
            <td>Recherche : 
              <input name="str_search" type="text" id="str_search" value="<?php echo $view->STRSEARCH;?>" size="15" maxlength="50">
			  <br>
			  Albums: 
          <input name="cb_album" type="checkbox" id="cb_album" value="cb_album" <?php echo $view->ALBCHECK;?>>
          Séries: 
          <input name="cb_serie" type="checkbox" id="cb_serie" value="cb_serie" <?php echo $view->SERCHECK;?>>
          Auteurs: 
          <input name="cb_aut" type="checkbox" id="cb_aut" value="cb_aut" <?php echo $view->AUTCHECK;?>>
			  </td>
            <td> </td>
          </tr>
          <tr bordercolor="#EEDED6"> 
            <td> 
              <select name="lstCle3"><?php echo $view->OPTIONCLE3;?>
                </select></td>
            <td colspan="2" align="center"> 
              <input type="submit" name="Submit2" value="Rafraichir"></td>
          </tr>
          <tr bordercolor="#EEDED6"> 
            <td> 
              <select name="lstCle4"><?php echo $view->OPTIONCLE4;?>
                </select></td>
            <td> </td>
            <td> </td>
          </tr>
        </table>
	  </form> <br>
	  <form action="<?php echo $view->URLFORM;?>" method="post" name="Values">
		<table width="100%" height="55" border="1" cellpadding="1" cellspacing="1" class="Tableur" rules="all">
          <tr> 
            <td width="182" height="25" class="EnteteTableur">Serie</td>
            <td width="36" class="EnteteTableur">Tome</td>
            <td width="208" class="EnteteTableur">Titre</td>
			
            <!-- BEGIN TitleBlock -->
            <td class="EnteteTableur"><input name="<?php echo $view->KEYNAME;?>" type="hidden" value="<?php echo $view->KEYVALUE;?>">
              <?php echo $view->TITRE;?></td>
            <!-- END TitleBlock -->
			<td width="5%" class="EnteteTableur"></td>
          </tr>
          <!-- BEGIN RowBlock -->
          <tr> 
            <td class="DataTableur"><a href="<?php echo $view->URLSERIE;?>"><?php echo $view->ALBSERIE;?></a></td>
            <td class="DataTableur" ><?php echo $view->ALBTOME;?></td>
            <td class="DataTableur"><input name="idedition[]" type="hidden" value="<?php echo $view->IDEDITION;?>">
              <a href="#" onclick="window.open('<?php echo $view->URLTOME;?>','Album','width=580,height=530,scrollbars=1')"><?php echo $view->ALBTITRE;?></a></td>
            <!-- BEGIN ColumnBlock -->
            <td class="DataTableur"><?php echo $view->CHAMP;?></td>
            <!-- END ColumnBlock -->
			<td width="5%"><a href="<?php echo $view->URLDELETE;?>"><img src="<?php echo BDO_URL_IMAGE;?>poubelle.gif" width="25" height="24" border="0"></a></td>
          </tr>
          <!-- END RowBlock -->
		  
        </table>
        <br>

        <div align="right">
          <input type="submit" name="Submit3" value="Valider">
        </div>
<div align="left"><?php echo $view->BARRENAVIGATION;?></div>
	  </form>
	  </div>



