<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<link href="<?php echo BDO_URL;?>style/addition.css" rel="stylesheet" type="text/css">
<title><?php echo $view->DOCTITRE;?></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<SCRIPT LANGUAGE="JavaScript"><!--
function changeSource(myForm, myElement, myTitle, withID) {
    window.opener.document.forms[myForm].elements[myElement].value = myTitle;
	window.opener.document.forms[myForm].elements[myElement+'Id'].value = withID;
	window.close(self);
}

//--></SCRIPT>

</head>

<body>
<table width="100%" class = "addtable">
  <tr>
    <td class="addTitle">Serie</td>
    <td class="addTitle">Tome</td>
    <td class="addTitle">Titre</td>
  </tr>
<!-- BEGIN ResultBlock -->
  <tr>
    <td class="addDataSmall"><?php echo $view->SERIE;?></td>
    <td class="addDataSmall"><?php echo $view->NUMTOME;?></td>
    <td class="addDataSmall"><a href="<?php echo $view->RETURNURL;?>"><?php echo $view->TITRE;?></a></td>
  </tr>
<!-- END ResultBlock -->
</table>

</body>
</html>
