<link href="<?php echo BDO_URL;?>style/addition.css" rel="stylesheet" type="text/css">

<?php echo $view->MENUCOLL;?>
<div class="cadre1">
<a href="<?php echo BDO_URL;?>membres/detailAddition"><! a href="javascript:alert('Fermer pour travaux !')">Detail 
de la valorisation</a>
</div>

<form name="addForm" method="get" action="">
<div class="cadre1">

  <div class="addTitle">Achats depuis le début de votre collection</div>
  <div class="addFreeBlock"> 
    <table class="addTable">
      <tr> 
        <td class="addTitle">Annee</td>
        <td class="addTitleMiddle">Qté</td>
        <td class="addTitle">Coût</td>
      </tr>
      <!-- BEGIN YearBlock -->
      <tr> 
        <td class="addData"><a href="<?php echo $view->URLANNEE;?>"><?php echo $view->ANNEE;?></a></td>
        <td class="addData"><?php echo $view->QUANTITE;?></td>
        <td class="addDataRight"><?php echo $view->COUT;?></td>
      </tr>
      <!-- END YearBlock -->
    </table>
  </div>

  <div align="center">
    Sélectionner l'information à afficher 
    <input name="annee" type="hidden" value="<?php echo $view->ANNEE;?>">
      <label><input type="radio" name="info" value="0" <?php echo $view->TYPE0;?> onClick="submit();">Coût</label>
      <label><input type="radio" name="info" value="1" <?php echo $view->TYPE1;?> onClick="submit();">Nombre</label>
	</div>
<!--        <div class="addFreeBlock"> <img src="<?php echo $view->IMGANNEE;?>" class="addImg"> </div>-->
    <div class="addFreeBlock" style="width:601px;height:281px"> <img src="<?php echo $view->IMGANNEE;?>" class="addImg"> </div>
</div>

<div class="cadre1"> 
    <div class="addTitle">Achats pour l'année <?php echo $view->ANNEE;?></div>
    <div class="addFreeBlock"> 
      <select name="mois" size="12" onChange="submit();" class="addSelect"><?php echo $view->OPTMOIS;?>
      </select>
    </div>
        <table class="addTable">
          <tr> 
            <td class="addTitle">Serie</td>
            <td colspan="2" class="addTitleMiddle">Titre</td>
            <td class="addTitle">Date</td>
            <td class="addTitle">Coût</td>
            <td width="10">&nbsp;</td>
          </tr>
          <!-- BEGIN MonthBlock -->
          <tr> 
            <td class="addDataSmall"><a href="<?php echo $view->URLALBSERIE;?>" class="addLiens"><?php echo $view->ALBSERIE;?></a></td>
            <td class="addDataSmall"><?php echo $view->ALBTOME;?></td>
            <td class="addDataSmall"><a href="#" onclick="window.open('<?php echo BDO_URL;?>membres/useralbum?id_tome=<?php echo $view->IDTOME;?>&id_edition=<?php echo $view->IDEDITION;?>','Album','width=580,height=530,scrollbars=1')"  class="addLiens"><?php echo $view->ALBTITRE;?></a></td>
            <td class="addDataSmall"><?php echo $view->ALBDATEACHAT;?></td>
            <td class="addDataSmall"><?php echo $view->ALBCOUT;?></td>
            <td class="addDataSmall">&nbsp;</td>
          </tr>
          <!-- END MonthBlock -->
        </table>

      <div class="addFreeBlock" style="width:601px;height:281px"> <img src="<?php echo $view->IMGMOIS;?>" class="addImg"> </div>
</div>
</form>





