<link href="<?php echo BDO_URL;?>style/addition.css" rel="stylesheet" type="text/css" />
<div style="position:absolute;top:1em;left:60%">
	<form action="usersearch" method="post" name="search" target="_self">
	<div class="cadre1">
					Recherche : 
   			    	<input name="str_search" type="text" id="str_search" value="" size="20" maxlength="50" /> 
			    	<input type="submit" name="Submit" value="Envoyer" />
					<br />
			    	Albums: 
		        	<input name="cb_album" type="checkbox" id="cb_album" value="cb_album" checked />
		        	S&eacute;ries: 
		        	<input name="cb_serie" type="checkbox" id="cb_serie" value="cb_serie" />
		        	Auteurs: 
		        	<input name="cb_aut" type="checkbox" id="cb_aut" value="cb_aut" />

					<table width="100%" border="0">
		            	<tr> 
				            <td width="73%">
								<div align="left"> 
					                <input name="rb_mode" type="radio" value="1" checked />
					                Mes BD 
					                <input type="radio" name="rb_mode" value="2" />
					                Pr&ecirc;t 
					                <input type="radio" name="rb_mode" value="3" />
					                A pr&eacute;voir
								</div>
							</td>
					        <td width="27%">
								<div align="right">
									<a href="userbrowser">
										BD Browser
									</a>
								</div>
							</td>
			            </tr>
					</table>
				</div>
	</form>
</div>

<?php echo $view->MENUCOLL;?>
<div class="cadre1">
			<table width="132" border="1">
		        <tr> 
			        <td width="77" align="center">
						<a href="<?php echo BDO_URL;?>membres/addition">
							Statistiques
						</a>
					</td>
			        <td width="39" align="center">
						<a href="<?php echo $view->URLAIDE;?>">
							Aide
						</a>
					</td>
				</tr>
			</table>
			<div class="addTitle">
				R&eacute;sum&eacute; de la valorisation
			</div>
			<div class="addFreeBlock">
				<div class="addTitle2">
					Valorisation de la collection
				</div>
				<table width="400" class = "addStats">
		            <tr> 
		                <td class="addTitle">&nbsp;</td>
		                <td class="addTitle">Nombres</td>
		                <td class="addTitle">Valeur</td>
		            </tr>
		            <tr> 
			            <td class="addDataLeft">
							Album au prix d'achat
						</td>
		                <td class="addData">
							<a href="<?php echo $view->URLNBPA;?>" title="<?php echo $view->TITRENBPA;?>"><?php echo $view->NBPA;?></a>
						</td>
		                <td class="addData"><?php echo $view->VALPA;?></td>
		            </tr>
		            <tr> 
			            <td class="addDataLeft">Album au prix bdovore</td>
		                <td class="addData">
							<a href="<?php echo $view->URLNBPB;?>" title="<?php echo $view->TITRENBPB;?>"><?php echo $view->NBPB;?></a>
						</td>
		                <td class="addData"><?php echo $view->VALPB;?></td>
		            </tr>
		            <tr> 
			            <td class="addDataLeft">Album au prix par d&eacute;faut</td>
		                <td class="addData">
							<a href="<?php echo $view->URLNBPD;?>" title="<?php echo $view->TITRENBPD;?>"><?php echo $view->NBPD;?></a>
						</td>
		                <td class="addData"><?php echo $view->VALPD;?></td>
		            </tr>
		            <tr> 
		                <td class="addDataLeft">Coffrets</td>
		                <td class="addData">
							<p><a href="<?php echo $view->URLNBC;?>" title="<?php echo $view->TITRENBC;?>"><?php echo $view->NBC;?></a></p>
						</td>
		                <td class="addData"><?php echo $view->VALC;?></td>
		            </tr>
		            <tr> 
			            <td class="addDataLeft">Non valoris&eacute;s</td>
		                <td class="addData">
							<a href="<?php echo $view->URLNBNV;?>" title="<?php echo $view->TITRENBNV;?>"><?php echo $view->NBNV;?></a>
						</td>
		                <td class="addData"><?php echo $view->VALNV;?></td>
		            </tr>
		            <tr> 
		                <td class="addDataLeft">Total</td>
		                <td class="addData">
							<a href="<?php echo $view->URLNBTOT;?>" title="<?php echo $view->TITRENBTOT;?>"><?php echo $view->NBTOT;?></a>
						</td>
		                <td class="addData"><?php echo $view->VALTOT;?></td>
		            </tr>
	            </table>
			</div>
			<div class="addFreeBlock">
				<form name="form1" method="post" action="<?php echo $view->URLRECALC;?>">
					<div class="addTitle2">
						Param&egrave;tres de valorisation
					</div>
					<table class="addStats">
			            <tr> 
				            <td class="addDataLeft">Prix par d&eacute;faut d'un album</td>
				            <td>
								<input name="txtPrixAlbum" type="text" value="<?php echo $view->DEFALB;?>" size="6" class="flat" />
				            </td>
			            </tr>
			            <tr> 
				            <td class="addDataLeft">Prix par d&eacute;faut d'une int&eacute;grale</td>
				            <td>
								<input name="txtPrixIntegrale" type="text" value="<?php echo $view->DEFINT;?>" size="6" class="flat" />
				            </td>
			            </tr>
			            <tr> 
				            <td class="addDataLeft">Prix par d&eacute;fault / surco&ucirc;t d'un coffret</td>
				            <td>
								<input name="txtPrixCoffret" type="text" value="<?php echo $view->DEFCOFFRET;?>" size="6" class="flat" />
				            </td>
			            </tr>
			            <tr> 
				            <td class="addDataLeft">Valorisation des coffrets</td>
				            <td>
								<select name="lstCoffret" class="flat">
									<?php echo $view->OPTVALOCOFFRET;?>
			                    </select>
				            </td>
			            </tr>
			            <tr> 
				            <td height="31">&nbsp;</td>
				            <td valign="bottom">
								<input type="submit" name="Submit2" value="Recalculer">
							</td>
				        </tr>
					</table>
		        </form>
			</div>
			<hr class="addSep" />
			<div class="addTitle">D&eacute;tail de la valorisation</div>
			<form action="<?php echo $view->URLACTION;?>" method="post" name="formMAJ">
				<table width="100%" border="1">
			        <tr> 
				        <td></td>
			        </tr>
			        <tr> 
				        <td>
							<table width="100%" height="55" border="1" cellpadding="1" cellspacing="1" class="Tableur">
				                <tr> 
					                <td height="25" class="addTitle">S&eacute;rie</td>
					                <td class="addTitle">Tome</td>
					                <td class="addTitle">Titre</td>
					                <td class="addTitle">Editeur / parution</td>
					                <td width="100" class="addTitle">Prix du march&eacute;</td>
					                <td width="100" class="addTitle">Prix Achat</td>
					                <td width="100" class="addTitle">Prix Retenu</td>
				                </tr>
				                <!-- BEGIN RowBlock -->
				                <tr> 
					                <td class="DataTableur">
										<a href="<?php echo $view->URLSERIE;?>"><?php echo $view->ALBSERIE;?></a>
									</td>
					                <td class="DataTableur"><?php echo $view->ALBTOME;?></td>
					                <td class="DataTableur">
										<a href="#" onclick="window.open('<?php echo $view->URLTOME;?>','Album','width=600,height=800,scrollbars=1')">
											<?php echo $view->ALBTITRE;?>
										</a>
									</td>
					                <td class="DataTableur"><?php echo $view->ALBEDITEUR;?></td>
					                <td class="DataTableur"><?php echo $view->PRIX;?></td>
					                <td class="DataTableur">
										<input name="prix_achat[<?php echo $view->IDEDITION;?>]" type="text" id="txtPrixAchat" value="<?php echo $view->PRIXACHAT;?>" size="6" class="flat" />
									</td>
					                <td class="DataTableur"><?php echo $view->PRIXRETENU;?></td>
				                </tr>
				                <!-- END RowBlock -->
				                <tr> 
					                <td colspan="4" class="DataTableur">&nbsp;</td>
					                <td class="DataTableur">&nbsp;</td>
					                <td class="DataTableur">&nbsp;</td>
				                </tr>
				                <tr> 
					                <td colspan="4" class="DataTableur">&nbsp;</td>
					                <td class="DataTableur">&nbsp;</td>
					                <td class="DataTableur">
										<input type="submit" name="Submit3" value="Mettre à jour" />
									</td>
				                </tr>
				            </table>
						</td>
			        </tr>
				</table>
			</form>
			<?php echo $view->BARRENAVIGATION;?>
</div>