<?php echo $view->MENUCOLL;?>
<div class="cadre1">
	<div class="genTitle">Mon actualité</div>
	<form name ="selType" action="<?php echo $view->ACTION;?>" method="post">
	<div class="genBlock">
		<table border="0">
		    <tr> 
				<td>
					<span class="texte">
						Voir les nouveautés concernant :			        <select name="lstSource" size="1">
				        <?php echo $view->OPTSOURCE;?>
			        </select>
					</span>
				</td>
				<td>&nbsp;</td>
			    <td>
					<span class="texte">
						Parues depuis :			        <select name="lstDuree">
				        <?php echo $view->OPTDUREE;?>
			        </select>
					</span>
				</td>
				<td>&nbsp;</td>

			    <td>
					<input type="submit" name="Submit" value="Rafraîchir" />
				</td>

			</tr>
		</table>
	</div>

	</form>
	<div class="genBlock">
		<table width="100%" height="29" class="genTable">
			<tr> 
			    <td width="15%" class="genTitle"><a href="<?php echo BDO_URL;?>membres/actualites?cle=1&sort=asc&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechehautr.gif" width="12" height="12" hspace="5" border="0"></a>Genre<a href="<?php echo BDO_URL;?>membres/actualites?cle=1&sort=DESC&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechebasr.gif" width="12" height="12" hspace="5" border="0"></a></td>
				<td width="20%" class="genTitle"><a href="<?php echo BDO_URL;?>membres/actualites?cle=4&sort=asc&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechehautr.gif" width="12" height="12" hspace="5" border="0"></a>Auteur<a href="<?php echo BDO_URL;?>membres/actualites?cle=4&sort=DESC&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechebasr.gif" width="12" height="12" hspace="5" border="0"></a></td>
			    <td width="20%" class="genTitle"><a href="<?php echo BDO_URL;?>membres/actualites?cle=2&sort=asc&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechehautr.gif" width="12" height="12" hspace="5" border="0"></a>S&eacute;rie<a href="<?php echo BDO_URL;?>membres/actualites?cle=2&sort=DESC&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechebasr.gif" width="12" height="12" hspace="5" border="0"></a></td>
			    <td width="5%" class="genTitle">Tome</td>
			    <td width="25%" class="genTitle">Titre</td>
			    <td width="15%" class="genTitle"><a href="<?php echo BDO_URL;?>membres/actualites?cle=3&sort=asc&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechehautr.gif" width="12" height="12" hspace="5" border="0"></a>Date Parution <a href="<?php echo BDO_URL;?>membres/actualites?cle=3&sort=DESC&duree=<?php echo $view->DUREE;?>&lstSource=<?php echo $view->SRC;?>"><img src="<?php echo BDO_URL_IMAGE;?>flechebasr.gif" width="12" height="12" hspace="5" border="0"></a></td>
			</tr>
			<!-- BEGIN DetailBlock -->
			<tr> 
			    <td width="15%" class="genData"><div align="center"><?php echo $view->GENRE;?></div></td>
				<td width="20%" class="genData"><div align="center"><?php echo $view->AUTEUR;?></div></td>
			    <td width="20%" class="genData"><div align="center"><a href="<?php echo BDO_URL;?>serie?id_serie=<?php echo $view->SERID;?>"><?php echo $view->SERIE;?></a></div></td>
			    <td width="5%" class="genData"><div align="center"><?php echo $view->TOME;?></div></td>
			    <td width="25%" class="genData"><a href="<?php echo $view->URLTITRE;?>"><?php echo $view->TITRE;?></a></td>
			    <td width="15%" class="genData"> <div align="center"><?php echo $view->DTEPAR;?></div></td>
			</tr>
			<!-- END DetailBlock -->
		</table>
	</div>
	<p class="texte"><?php echo $view->BARRENAVIGATION;?></p>
</div>