<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Document sans titre</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>

<body>
<table width="780" height="29" border="1" cellpadding="1" cellspacing="1">
  <tr> 
    <td width="60" height="25"> 
      <div align="center"><font color="#0000FF"><strong><font size="2" face="Arial, Helvetica, sans-serif"><a href="../admin/usermanagement?cle=1&sort=asc"><img src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12" height="12" hspace="5" border="0"></a>ID<a href="../admin/usermanagement?cle=1&sort=DESC"><img src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12" height="12" hspace="5" border="0"></a></font></strong></font></div></td>
    <td width="118"><div align="center"><font color="#0000FF"><strong><font size="2" face="Arial, Helvetica, sans-serif"><a href="../admin/usermanagement?cle=2&sort=asc"><img src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12" height="12" hspace="5" border="0"></a>Utilisateur<a href="../admin/usermanagement?cle=2&sort=DESC"><img src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12" height="12" hspace="5" border="0"></a></font></strong></font></div></td>
    <td width="107"><div align="center"><font color="#0000FF"><strong><font size="2" face="Arial, Helvetica, sans-serif"><a href="../admin/usermanagement?cle=4&sort=asc"><img src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12" height="12" hspace="5" border="0"></a>Status<a href="../admin/usermanagement?cle=4&sort=DESC"><img src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12" height="12" hspace="5" border="0"></a></font></strong></font></div></td>
    <td width="126"><div align="center"><font color="#0000FF"><strong><font size="2" face="Arial, Helvetica, sans-serif"><a href="../admin/usermanagement?cle=5&sort=asc"><img src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12" height="12" hspace="5" border="0"></a>Nb 
        de visites<a href="../admin/usermanagement?cle=5&sort=DESC"><img src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12" height="12" hspace="5" border="0"></a></font></strong></font></div></td>
    <td width="168"><div align="center"><font color="#0000FF"><strong><font size="2" face="Arial, Helvetica, sans-serif"><a href="../admin/usermanagement?cle=6&sort=asc"><img src="<?php echo BDO_URL_IMAGE;?>flechehaut.gif" width="12" height="12" hspace="5" border="0"></a>Derni&egrave;re 
        Visite<a href="../admin/usermanagement?cle=6&sort=DESC"><img src="<?php echo BDO_URL_IMAGE;?>flechebas.gif" width="12" height="12" hspace="5" border="0"></a></font></strong></font></div></td>
    <td width="30"> 
      <div align="center"><img src="<?php echo BDO_URL_IMAGE;?>poubelle.gif" width="25" height="24"> 
      </div></td>

  </tr>
</table>
<!-- BEGIN UsersBlock -->
<table width="780" height="29" border="1" cellpadding="1" cellspacing="1">
  <tr> 
    <td width="60" height="25"> <div align="center"><font color="#000000"><font size="2" face="Arial, Helvetica, sans-serif"><?php echo $view->ID;?></font></font></div></td>
    <td width="118"><div align="center"><font color="#000000" size="2" face="Arial, Helvetica, sans-serif"><?php echo $view->USERNAME;?></font></div></td>
    <td width="107"><div align="center"><font color="#000000"><font size="2" face="Arial, Helvetica, sans-serif"><?php echo $view->STATUS;?></font></font></div></td>
    <td width="126"><div align="center"><font color="#000000"><font size="2" face="Arial, Helvetica, sans-serif"><?php echo $view->NBVISITES;?></font></font></div></td>
    <td width="168"><div align="center"><font color="#000000"><font size="2" face="Arial, Helvetica, sans-serif"><?php echo $view->LASTVISIT;?></font></font></div></td>
	<td width="30"> <div align="center"><a href="<?php echo $view->URLDELETE;?>"><img src="<?php echo BDO_URL_IMAGE;?>poubelle.gif" width="20" height="21" border="0"></a></div></td>
  </tr>
</table>
<!-- END UsersBlock -->
<br />
<?php echo $view->NAVBLOCK;?>
</body>
</html>
