<div style="position:absolute;top:1em;left:60%"> 
  <form action="usersearch" method="post" name="search" target="_self">
<div class="cadre1">
Recherche : 
          <input name="str_search" type="text" id="str_search" value="" size="20" maxlength="50"> 
          <input type="submit" name="Submit" value="Envoyer"> <br>
          Albums: 
          <input name="cb_album" type="checkbox" id="cb_album" value="cb_album" checked>
          S&eacute;ries: 
          <input name="cb_serie" type="checkbox" id="cb_serie" value="cb_serie">
          Auteurs: 
          <input name="cb_aut" type="checkbox" id="cb_aut" value="cb_aut"> </td>
      <table width="100%" border="0">
            <tr> 
              <td width="73%"><div align="left"> 
                  <input name="rb_mode" type="radio" value="1" checked>
                  Mes BD 
                  <input type="radio" name="rb_mode" value="2">
                  Pr&ecirc;t 
                  <input type="radio" name="rb_mode" value="3">
                  A pr&eacute;voir</div></td>
              <td width="27%"><div align="right"><a href="userbrowser">BD 
                  Browser</a></div></td>
            </tr>
          </table>
          </div>
  </form>
</div>
<div class="cadre1">
<p>&nbsp; 
      <table width="100%" border="1">
        <tr> 
          <td colspan="2">Param&egrave;tres de valorisation</td>
        </tr>
        <tr> 
          <td width="44%"><table width="400" border="1">
              <tr> 
                <td colspan="3">Valorisation de la collection</td>
              </tr>
              <tr> 
                <td>&nbsp;</td>
                <td>Nombres</td>
                <td>Valeur</td>
              </tr>
              <tr> 
                <td width="59%">Album valoris&eacute;s au prix d'achat</td>
                <td width="23%"><a href="<?php echo $view->URLNBPA;?>" title="<?php echo $view->TITRENBPA;?>"><?php echo $view->NBPA;?></a></td>
                <td width="18%"><?php echo $view->VALPA;?></td>
              </tr>
              <tr> 
                <td>Album valoris&eacute;s au prix bdovore</td>
                <td><a href="<?php echo $view->URLNBPB;?>" title="<?php echo $view->TITRENBPB;?>"><?php echo $view->NBPB;?></a></td>
                <td><?php echo $view->VALPB;?></td>
              </tr>
              <tr> 
                <td>Album valoris&eacute;s au prix par d&eacute;faut</td>
                <td><a href="<?php echo $view->URLNBPD;?>" title="<?php echo $view->TITRENBPD;?>"><?php echo $view->NBPD;?></a></td>
                <td><?php echo $view->VALPD;?></td>
              </tr>
              <tr> 
                <td>Coffrets</td>
                <td><p><a href="<?php echo $view->URLNBC;?>" title="<?php echo $view->TITRENBC;?>"><?php echo $view->NBC;?></a></p></td>
                <td><?php echo $view->VALC;?></td>
              </tr>
              <tr> 
                <td>Albums non valoris&eacute;s</td>
                <td><a href="<?php echo $view->URLNBNV;?>" title="<?php echo $view->TITRENBNV;?>"><?php echo $view->NBNV;?></a></td>
                <td><?php echo $view->VALNV;?></td>
              </tr>
              <tr> 
                <td>Total</td>
                <td><a href="<?php echo $view->URLNBTOT;?>" title="<?php echo $view->TITRENBTOT;?>"><?php echo $view->NBTOT;?></a></td>
                <td><?php echo $view->VALTOT;?></td>
              </tr>
            </table></td>
          <td width="56%"> <form name="form1" method="post" action="<?php echo BDO_URL;?>membres/addition?action=refresh">
              <table width="100%" border="1">
                <tr> 
                  <td width="38%">Param&egrave;tres de valorisations</td>
                  <td width="62%">&nbsp;</td>
                </tr>
                <tr> 
                  <td>Prix par d&eacute;faut d'un album</td>
                  <td> <input name="txtPrixAlbum" type="text" value="<?php echo $view->DEFALB;?>" size="6" class="flat"> 
                  </td>
                </tr>
                <tr> 
                  <td>Prix par d&eacute;faut d'une int&eacute;grale</td>
                  <td><input name="txtPrixIntegrale" type="text" value="<?php echo $view->DEFINT;?>" size="6" class="flat"></td>
                </tr>
                <tr> 
                  <td>Surco&ucirc;t coffret</td>
                  <td><select name="lstCoffret" class="flat"><?php echo $view->OPTVALOCOFFRET;?>
                    </select> <input name="txtPrixCoffret" type="text" value="<?php echo $view->DEFCOFFRET;?>" size="6" class="flat"></td>
                </tr>
                <tr> 
                  <td>&nbsp;</td>
                  <td><input type="submit" name="Submit2" value="Recalculer"></td>
                </tr>
              </table>
            </form></td>
        </tr>
      </table><br>
	  <form action="<?php echo $view->URLACTION;?>" method="post" name="formMAJ">
<table width="100%" border="1">
        <tr> 
          <td>D&eacute;tail de la valorisation</td>
        </tr>
        <tr> 
          <td>
		  
		  <table width="100%" height="55" border="1" cellpadding="1" cellspacing="1" class="Tableur">
              <tr> 
                <td width="182" height="25" class="EnteteTableur">Serie</td>
                <td width="36" class="EnteteTableur">Tome</td>
                <td width="208" class="EnteteTableur">Titre</td>
                <td width="208" class="EnteteTableur">Prix du march&eacute;</td>
                <td width="208" class="EnteteTableur">Prix Achat</td>
              </tr>
              <!-- BEGIN RowBlock -->
              <tr> 
                <td class="DataTableur"><a href="<?php echo $view->URLSERIE;?>"><?php echo $view->ALBSERIE;?></a></td>
                <td class="DataTableur" ><?php echo $view->ALBTOME;?></td>
                <td class="DataTableur"><a href="#" onclick="window.open('<?php echo $view->URLTOME;?>','Album','width=600,height=800,scrollbars=1')"><?php echo $view->ALBTITRE;?></a></td>
                <td class="DataTableur"><?php echo $view->PRIX;?></td>
                <td class="DataTableur"><input name="prix_achat[<?php echo $view->IDTOME;?>]" type="text" id="txtPrixAchat" value="<?php echo $view->PRIXACHAT;?>" size="6" class="flat"></td>
              </tr>
              <!-- END RowBlock -->
            </table>
		  </td>
        </tr>
      </table>
</form>
<?php echo $view->BARRENAVIGATION;?>
</div>



