  <!-- BEGIN CmtBlock -->
<table id="<?php echo $view->DTEPOST;?>" width="100%" border="1" align="center" cellpadding="3" cellspacing="0" bordercolor="#B64444"> 
    <tr bordercolor="#FFFFFF"> 
        <td height="25" bordercolor="#B64444" bgcolor="#C8857C">
            <b><font color="#990000" face="Arial, Helvetica, sans-serif" size="2">
                Note : <?php echo $view->NOTE;?>
            </font></b>
        </td>
        <td bordercolor="#B64444" bgcolor="#C8857C"> 
            <div align="right"><font face="Arial, Helvetica, sans-serif" size="1">
                <font color="#0000ff" face="Arial, Helvetica, sans-serif" size="2"><font color="#333333">
                    Postée par <b><?php echo $view->USERNAME;?></b>
                </font></font> 
                le <?php echo $view->CMTDATE;?>
            </font><?php echo $view->URLDELETE;?></div>
        </td> 
    </tr>
        
    <tr bordercolor="#B64444"> 
        <td colspan="2"><font size="2" face="Arial, Helvetica, sans-serif"><?php echo $view->CMTTEXTE;?></font></td>
    </tr>
</table>
<!-- END CmtBlock -->
