
        
	<p><font color="#990000" size="+1"><strong>La mise en ligne gratuite de votre collection de bandes dessinées</strong></font></p>
	
	<p>A la manière de DVDProfiler, BDovore vous offre la
	possibilité de rendre consultable votre collection de bandes dessinées. Cela
	permet à vos interlocuteurs, lors de votre intervention sur un forum, de savoir
	quels sont vos goûts, quels sont les albums que vous avez lus.</p>
	<div align="center"><a href="<?php echo BDO_URL;?>guest?user=4578" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_guest.png" alt="Naviguer dans une collection" border="0"></a></div>
	<p>Cela permet également aux personnes susceptibles de vous
	offrir des bandes dessinées de savoir quelles sont celles que vous possédez
	déjà et aussi quels sont vos goûts. Fini la BD en double ou en triple dans la
	collection&nbsp;! Sympa pour les potes toujours en quête de cadeau
	danniversaire&nbsp;!</p>
	
	<p><font size="-2">Astuce&nbsp;: cette fonction doit être activée dans votre
	profil&nbsp;: par défaut, personne ne peut accéder à votre collection. Pour l'autoriser et pour savoir quel est le lien vers votre collection, rendez-vous dans votre profil.</font></p>

	<div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_bdprofiler_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_bdprofiler.png" alt="Ouvrir sa Collection" border="0"></a></div>
	
      <br>
      
      <p>
		Encore des questions sur BDovore ? Rendez-vous sur le <a href="http://forum.bdovore.com/index">forum</a> !
	  </p>




