
 <p><font color="#990000" size="+1"><strong>Gérer sa collection</strong></font></p>
      <p><font color="#990000" size="-1"><strong>Construire sa collection</strong></font></p>
      <p><strong>Ajouter des albums dans sa collection (éventuellement sous forme 
        d'achat futur)</strong></p>
      <p>L'ajout d'album peut se faire à partir de trois sources différentes (dans 
        tous les cas, vous devez être loggué pour pouvoir ajouter des albums à 
        votre collection )&nbsp;:</p>
      <ul>
        <li>Depuis une Fiche Album&nbsp;: cliquez simplement sur le lien ajouter 
          à ma collection.<br>
          <br>
          <div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_ajout_fiche_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_ajout_fiche.png" alt="Ajouter un album depuis une fiche" border="0"></a></div>
          <br>
        </li>
        <li>Depuis une Fiche Série&nbsp;: sélectionnez les albums que vous voulez 
          ajouter à votre collection et cliquez sur le bouton situé en bas du 
          formulaire.<br>
          <br>
          <div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_ajout_serie_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_ajout_serie.png" alt="Ajouter un album depuis la fiche série" border="0"></a></div>
          <br>
        </li>
        <li>Depuis le résultat d'une recherche&nbsp;: sélectionnez les albums 
          que vous voulez ajouter à votre collection et cliquez sur le bouton 
          situé en bas du formulaire.<br>
          <br>
          <div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_ajout_search_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_ajout_search.png" alt="Ajouter un album depuis l'écran recherche" border="0"></a></div>
          <br>
        </li>
      </ul>
      <p><font size="-2"><img src="<?php echo BDO_URL_IMAGE;?>tuto/icon_idea.gif"> Vous pouvez choisir d'ajouter un album 
        à la liste de vos achats futurs plutôt qu'à votre collection. Pour cela, 
        dans une Fiche Album, cliquez sur Achat futur et dans la Fiche Série ou 
        la recherche, cochez la case "Achat futur".</font></p>
      <p>Il est possible de rajouter un commentaire sur un achat futur (recommandé 
        par untel par exemple). Pour cela, utilisez la case remarque présente 
        dans votre fiche album. Ce champ sera repris lors de l'export des achats 
        futurs en format Excel (pratique quand on va chez le libraire)</p>
      <div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_remarque_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_remarque.png" alt="Remarque" border="0"></a></div>
      <p>Une fois votre achat effectué, rendez-vous sur votre fiche album et décochez 
        simplement la case achat futur.</p>
      <div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_flg_ajout_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_flg_ajout.png" alt="Achat futur" border="0"></a></div>
      <p>Si un album que vous possédez n'est pas présent dans la base, vous pouvez 
        proposer son ajout.</p>
      <p><b>La gestion des intégrales et des coffrets</b></p>
      <p>Les intégrales et les coffrets sont gérés différemment dans la base de 
        donnée. En effet, lorsque BDovore calculera le nombre d'albums présents 
        dans votre collection, une distinction sera faite entre les intégrales 
        (qui seront comptées comme un album) et les coffrets (qui feront l'objet 
        d'une comptabilisation séparée). </p>
      <p>Par conséquent, nous vous conseillons plutôt, lors de la saisie du coffret, 
        de sélectionner les albums qui composent le coffret ainsi que le coffret 
        lui même.</p>
      <p><font color="#990000" size="-1"><strong>La personnalisation de sa collection</strong></font></p>
      <p>Rendez-vous sur votre fiche album. C'est à partir de la que vous pourrez 
        entrer l'information propre aux albums que vous possédez.</p>
      <div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_fiche_album_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_fich_alb.png" alt="Fiche Album" border="0"></a></div>
      <p>Vous pouvez choisir, dans le cas d'albums ayant fait l'objet de rééditions, 
        quelle est l'édition que vous possédez (menu déroulant "Edition" dans ce cas). L'information propre à votre édition 
        sera alors affichée lorsque vous parcourrez votre collection (référence 
        à l'éditeur, couverture etc). Si vous ne trouvez pas l'édition que vous 
        possédez dans la base, vous pouvez la rajouter vous-mêmes via le menu déroulant.</p>
      <p>Vous pouvez indiquer si l'album a fait l'objet d'une dédicace ou non.</p>
      <p>Vous pouvez également mettre une remarque sur vos albums. Cette remarque 
        vous est propre et ne sera pas visible par les autres utilisateurs.</p>
      <p>Enfin, il vous est également possible de noter et de commenter les albums 
        que vous avez dans votre collection. Cette démarche est utile pour vous 
        mais aussi pour les autres utilisateurs de BDovore. Cela permettra éventuellement 
        de faire découvrir aux autres utilisateurs des albums que vous avez particulièrement 
        apprécié lorsqu'ils seront repris dans les statistiques générales du site.</p>
      <p><font color="#990000" size="-1"><strong>La gestion des prêts</strong></font></p>
      <p>Lorsqu'un album "sort" de votre bibliothèque, il est possible d'indiquer 
        la date du prêt ainsi que le nom de l'emprunteur. Particulièrement utile 
        quand vous avez des amis distraits. La gestion des prêts se fait à partir 
        de la fiche album.</p>
      <p>Astuce&nbsp;: lorsque vous naviguez dans votre collection, il est possible 
        de n'afficher que les albums ayant fait l'objet d'un prêt.</p>
      <p><b>&nbsp;</b></p>
      <p><font color="#990000" size="-1"><strong>Naviguer dans sa collection</strong></font></p>
      <p><strong>Le Garde-manger</strong></p>
      <p>L'écran garde-manger vous indique en quelques chiffres l'état de votre 
        collection. Vous y retrouvez le nombre d'albums présents dans la collection 
        ainsi que quelques statistiques sur la collection. Depuis cet écran, vous 
        pouvez accéder directement à la page des statistiques détaillées.</p>
      <div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_gardemanger_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_gardemanger.png" alt="Le garde-manger" border="0"></a></div>
      <p>Vous pouvez également voir les 5 derniers albums insérés dans votre collection 
        et donc accéder simplement aux Fiches Albums (en cliquant sur l'icône 
        où directement sur le nom de l'album).</p>
      <p>De même, vous pouvez ôter un album de votre collection en cliquant sur 
        l'icône "Poubelle" sur la droite (cela s'applique aussi aux achats futurs).</p>
      <p>Toujours à partir de cet écran, il vous est possible d'exporter votre 
        collection</p>
      <p><strong>L'écran "Mes étagères"</strong></p>
      <p>Il affiche l'entièreté de votre collection, classée suivant les critères 
        de votre choix. De nombreux filtres sont disponibles (et combinables) 
        pour retrouver rapidement l'album que vous recherchez.</p>
      <p>Il est à noter qu'à partir du moment où vous rentrez sur l'écran "Mes étagères", 
        le panneau de recherche en haut à droite va porter uniquement sur votre 
        collection. De même que le BD Browser accessible depuis ce même panneau.</p>
      <div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_album_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_album.png" alt="Fiche Album" border="0"></a></div>
      <p>A partir de là, tous les fonctionnalités qui étaient disponible pour 
        naviguer dans la base sont désormais à votre disposition pour naviguer 
        dans votre collection.</p>
      <p><font color="#990000" size="-1"><strong>Exporter sa collection</strong></font></p>
      <p>Actuellement, BDovore permet d'exporter votre collection en format pdf 
        (universel) et en format Excel. L'export au format pdf génèrera un fichier 
        comprenant les informations sur l'album ainsi que la couverture, ainsi 
        que la note et votre commentaire sur chaque album, trié par genre et série. 
        L'export se fait depuis l'&eacute;cran garde-manger.</p>
      <p>L'export au format Excel fournira sensiblement la même information, mais 
        ne reprendra ni vos commentaires, ni la couverture</p>
      <p>Vous pouvez exporter soit l'entièreté de votre collection, soit uniquement 
        vos achats futurs (pratique pour aller chez son libraire). Dans ce cas, 
        le fichier Excel reprendra vos remarques sur l'album et indiquera s'il 
        s'agit pour vous d'un achat dans une nouvelle série où d'un achat dans 
        une série que vous avez déjà commencée.</p>




