
        
	<p><font color="#990000" size="+1"><strong>Les statistiques</strong></font></p>
	<p><font color="#990000" size="-1"><strong>Les statistiques propres à votre collection</strong></font></p>
	
	<p>Les statistiques détaillées sont accessibles depuis le
	garde-manger (menu «&nbsp;Ma table&nbsp;»). Elles fournissent un complément
	d'information sur votre collection, de manière graphique&nbsp;:</p>
	
<ul><li>La répartition par genre sous forme de camembert</li>
	
	<li>La répartition par éditeur sous forme de camembert</li>
	
	<li>Un classement des auteurs/dessinateurs en fonction du nombre
	de fois où ils sont représentés dans votre collection.<br>
<br>
	<div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_cam1_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_cam1.png" alt="Répartition par Genre" border="0"></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_cam2_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_cam2.png" alt="Répartition par Editeur" border="0"></a></div>
<br>
</li></ul>
	
	<p>Nul doute que cette section est appelée à évoluer au gré de
	vos demandes.</p>
	
	<p><font color="#990000" size="-1"><strong>Les statistiques du site</strong></font></p>

	<p>A partir des collections des utilisateurs et des notes
	attribuées aux albums, BDovore fournit différents types de statistique.</p>
	
	<p>La page d'accueil du site présente les 10 séries les mieux
	notées par les utilisateurs ainsi que les albums les plus répandus dans la
	collection des utilisateurs.</p>
	
	<p>Un clic sur ces liens vous enverra directement vers la fiche
	album / fiche série appropriée.</p>
	
	<font size="-2"><p><img src="<?php echo BDO_URL_IMAGE;?>tuto/icon_idea.gif"> Laissez votre souris sur un de ces liens pour
	disposer d'informations complémentaires.</p></font>
	
	<p>Des statistiques supplémentaires sont disponibles via le
	lien «&nbsp;Les albums favoris&nbsp;» présent dans le menu. Vous pourrez y
	découvrir les albums et les séries les mieux notés ou les plus répandus, triés
	par genre.</p>
	<div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_stat_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_stat.png" alt="Les statistiques du site" border="0"></a></div>
	<p>N'oubliez pas de commenter et de noter vos albums pour
	contribuer à ces statistiques&nbsp;!</p>



