
        
	<p><font color="#990000" size="+1"><strong>Le suivi de l'actualité de la Bande Dessinée</strong></font></p>
	<p><font color="#990000" size="-1"><strong>L'actualité du site</strong></font></p>
	
	<p>Il vous est tout d'abord possible de	visualiser sur la page d'accueil du site
    les 10 derniers albums ajoutés dans la base de données ainsi que les
	10 derniers albums commentés par les utilisateurs (en bas à droite).</p>

	<p><font color="#990000" size="-1"><strong>Mon actualité</strong></font></p>
	
	<p>La base de données de BDovore est mise à jour régulièrement
	et de nouveaux albums sont ajoutés toutes les semaines (plusieurs centaines par
	mois).</p>
	
	<p>L'écran "Mon actualité" (accessible depuis le Garde-manger) va vous permettre de trier ces
	nouvelles sortie en fonction de ce qui vous intéresse.</p>
	
	<div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_actualite_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_actualite.png" alt="Mon Actualité" border="0"></a></div>
	
	<p>Vous allez donc pouvoir repérer tous les albums sortis
	récemment dans une des séries que vous suivez (plus de risque de passer à
	coté).</p>
	
	<p>Vous allez également pouvoir repérer les nouveaux albums sur
	lesquels vos dessinateurs / scénaristes préférés ont travaillé.</p>
	
	<p>Enfin, vous avez la possibilité de voir les
	intégrales ou les coffrets nouvellement sortis (pratique si vous êtes à la
	recherche de ce type d'objets)</p>





