

    <p><font color="#990000" size="+1"><strong>Les statistiques</strong></font></p>
    <p><font color="#990000" size="-1"><strong>Les statistiques propres à votre collection</strong></font></p>

    <p>Les statistiques détaillées sont accessibles depuis votre collection (menu «&nbsp;Ma Collection&nbsp;»). Elles fournissent un complément
    d'information sur votre collection, de manière graphique&nbsp;:</p>
    <p>Vous piuvez également avoir des statistiques sur le "prix" de votre collection et suivre dans le temps le budget de votre fringale de BD</p>


</li></ul>

    <p>Nul doute que cette section est appelée à évoluer au gré de
    vos demandes.</p>

    <p><font color="#990000" size="-1"><strong>Les statistiques du site</strong></font></p>

    <p>A partir des collections des utilisateurs et des notes
    attribuées aux albums, BDovore fournit différents types de statistique.</p>

    <p>La page d'accueil du site présente en Actualité les albums récents les mieux
    notées par les utilisateurs ainsi que les albums les plus répandus dans la
    collection des utilisateurs.</p>

    <p>Un clic sur ces liens vous enverra directement vers la fiche
    album / fiche série appropriée.</p>

    

    <p>Des statistiques supplémentaires sont disponibles via le
    lien «&nbsp;Guide BD&nbsp;». Vous pourrez y
    découvrir les albums et les séries les mieux notés ou les plus répandus, les tendances et les derniers commentaires de la communauté.</p>
    <p>N'oubliez pas de commenter et de noter vos albums pour
    contribuer à ces statistiques&nbsp;!</p>



