
<div id="tabs">
  <ul>
    <li><a href="#tabs1">La base Bdovore</a></li>
    <li><a href="tutoriel?page=2">Votre collection</a></li>
    <li><a href="tutoriel?page=3">Les statistiques</a></li>
    <li><a href="tutoriel?page=4">L'actualit&eacute;</a></li>
    <li><a href="tutoriel?page=5">Mise en ligne</a></li>
  </ul>
<div id="tabs1">
    <h2>Bdovore c'est qui c'est quoi ?</h2>
    Bdovore est un site communautaire et gratuit, géré par l'association Bdovore, à but non lucratif et consacrée à la bandes-dessinnées.  <br>
    La base de données, le site web et la page facebook sont gérés par une petite équipe de bénévoles. <a href="<?php echo BDO_URL;?>presentation" >Voir ici pour une présentation</a> 
<h2>La base de
        donn&eacute;es</h2>
      <p>La base de donn&eacute;es contient plus de <?php echo $view->NBALB; ?> volumes, r&eacute;partis
        au travers de plus de <?php echo $view->NBSERIE;?> s&eacute;ries ou one-shots.</p>
      <p>Chaque album poss&egrave;de sa fiche (Fiche Album), contenant les informations
        cl&eacute; sur cet album. De la m&ecirc;me mani&egrave;re, une Fiche S&eacute;rie
        est disponible, pour visualiser en un coup d&#8217;&#339;il tous les albums
        qui composent la s&eacute;rie.</p>
      <div align="center"><a href="Album?id_tome=24283" class="fancybox fancybox.iframe {width:600,height:500}"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_fich_alb.png" alt="Fiche S&eacute;rie" border="0"></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="<?php echo BDO_URL;?>serie-bd-5269-le_combat_ordinaire" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_fich_serie.png" alt="Fiche S&eacute;rie" border="0"></a></div>
      <p>Il est bien entendu possible de naviguer de la fiche album vers la fiche
        s&eacute;rie et r&eacute;ciproquement en cliquant sur le nom de l&#8217;album
        ou de la s&eacute;rie.</p>
      
      <h3>Naviguer dans la base de donn&eacute;es de BDovore</h3>
      <p>La navigation dans la base de donn&eacute;e vers les fiches album et
        les fiches s&eacute;rie peut se faire de 2 mani&egrave;res diff&eacute;rentes
        :</p>
      <p><strong>Par le panneau de recherche :</strong></p>
      <p>Il se trouve toujours en haut au centre de l&#8217;&eacute;cran
        : il permet de rechercher un mot cl&eacute; parmi les titres des albums,
        le nom des s&eacute;ries ou bien encore le nom des auteurs.</p>
      <div align="center"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_rech.png" width="300">
      </div>
      <p>Le r&eacute;sultat de la recherche vous permet ensuite d&#8217;acc&eacute;der
        aux Fiches Album ou aux Fiches S&eacute;rie.</p>
      <div class="ui-widget">
    <div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;">
        <p><span class=".ui-state-focus ui-icon ui-icon-lightbulb" style="float: left; margin-right: .3em;"></span>
        <strong>Idée !</strong><div class="idea">Laissez vous guider par la recherche automatique : lorsque vous commencez à taper, le moteur vous propose automatiquement
                    les séries, les albums ou les auteurs correspondant à votre recherche.</div></p>
    </div>
</div>

      <p><strong>Par
        le BD Browser :</strong></p>
      <p>Il est accessible par le lien Browser
        disponible dans le menu. Le BD Browser vous permet de naviguer
        sous forme d&#8217;arbre dans la base de donn&eacute;es de BDovore.</p>
      <div align="center"><a href="<?php echo BDO_URL;?>browser?lev_id=2437&totalRows_RecAuteur=2&let=larc&rb_browse=aut&pageNum_RecAuteur=0&lev2_id=5269#2L5269" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_browser.png" alt="BD Browser" border="0"></a></div>
      <p>A ce jour trois types de navigation sont disponibles : par auteur, par
        &eacute;diteur et par genre.</p>
      <ul>
        <li>Auteur -&gt; S&eacute;ries sur lesquelles il a travaill&eacute; -&gt;
          Albums pr&eacute;sents dans la S&eacute;rie -&gt; Fiche Album<br>
        </li>
        <li>Genre -&gt; Premi&egrave;re lettre de la S&eacute;rie -&gt; S&eacute;ries
          -&gt; Fiche S&eacute;rie<br>
        </li>
        <li>Editeur -&gt; Collections pr&eacute;sentes chez l&#8217;&eacute;diteur
          -&gt; S&eacute;ries pr&eacute;sente dans la collection -&gt; Fiche S&eacute;rie</li>
      </ul><br />
      <h3>Apporter votre contribution &agrave; la base de donn&eacute;es : les corrections et les ajouts</h3>
      <h3>Ajouter un album dans la base</h3>
      <p>Si un album n&#8217;est pas disponible dans la base BDovore, il vous
        est possible de l&#8217;ajouter (en utilisant le lien Proposer un album
        disponible dans votre &laquo; Espace personnel  &raquo; ( menu Ma Collection, onglet Proposition).</p>
      <div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_ajout_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_ajout.png" alt="Ajouter un album" border="0"></a></div>
      <p>Vous pouvez alors remplir une Fiche Album qui sera valid&eacute; par
        un administrateur du site avant son ajout dans la base (pour &eacute;viter
        de cr&eacute;er des doublons parmi les albums).</p>
      <div class="ui-widget">
    <div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;">
        <p><span class=".ui-state-focus ui-icon ui-icon-lightbulb" style="float: left; margin-right: .3em;"></span>
        <strong>Idée !</strong><div class="idea">Si vous &ecirc;tes
      loggu&eacute; sur le site, vous pouvez demander &agrave; ce que l&#8217;album
      soit ajout&eacute; &agrave; votre collection une fois sa validation effectu&eacute;e.
      Vous pouvez m&ecirc;me choisir d&#8217;&ecirc;tre averti par mail de cette
      validation.</div></p>
    </div>
</div>

      <br />
      <h3>Corriger l&#8217;information
        contenue dans la base de donn&eacute;e</h3>
      <p>Si vous remarquez des erreurs sur les albums contenus dans la base (ne
        dites pas non, nous savons qu&#8217;il y en a), vous pouvez corriger en
        ligne l&#8217;information stock&eacute;e dans la base. La correction est
        possible depuis n&#8217;importe quelle fiche album.</p>
      <div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_corr_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_corr.png" alt="Ajouter un album" border="0"></a></div>
      <p>Les propositions de correction sont alors trait&eacute;es par un administrateur,
        ces derni&egrave;res pouvant avoir un impact sur la collection d&#8217;autres
        utilisateurs.</p>
      <h3>Le suivi de vos propositions</h3>
      <p>Vous pouvez suivre &agrave; tout moment le statut de vos propositions
        de correction ou d&#8217;ajout &agrave; partir de l&#8217;&eacute;cran
        &laquo; Suivi de mes propositions &raquo; disponible dans votre espace personnel (menu &laquo; ma collection, onglet mes propositions)
        &raquo;).</p>
      <div align="center"><a href="<?php echo BDO_URL_IMAGE;?>tuto/tut_suivi_big.png" target="_blank"><img src="<?php echo BDO_URL_IMAGE;?>tuto/tut_suivi.png" alt="Ajouter un album" border="0"></a></div>

</div>
</div>

  <script>
  $(function() {
    $( "#tabs" ).tabs({
      beforeLoad: function( event, ui ) {
        ui.jqXHR.error(function() {
          ui.panel.html(
            "Couldn't load this tab. We'll try to fix this as soon as possible. " +
            "If this wouldn't be a demo." );
        });
      }
    });
  });
  </script>

