<?php
echo date('d/m/Y H:i:s').'
<br />continuer ? '.$view->continuer
."<br />nbuser_id = ".$view->nbuser;

if ($view->continuer == "oui") {
    ?>
<script>
document.cachenbuserbytome.nbruser_ID_TOME.value = "<?php echo $view->nbruser_ID_TOME;?>";
    $.get("<?php echo BDO_URL;?>cache/nbuserbytome", $("#cachenbuserbytome").serialize(), function(data) {
     $("#ddcachenbuserbytome").html(data);
    //alert("Data Loaded: " + data);
    });
  </script>
<?php
}
else {
    ?>
<script>
document.cachenbuserbytome.continuer.value = "";
document.cachenbuserbytome.nbruser_ID_TOME.value = "<?php echo $view->nbruser_ID_TOME;?>";
var options;
options =
{ label: "lancer",
icons: {
    primary: "ui-icon-play"
        }
};
$("#lancernbuserbytome").button( "option", options );
</script>
<?php }?>