<?php
$ficheAlbum = $view->getHelper('ficheAlbum');
$pageinate = $view->getHelper('Pagination');
?>


<div class="colleft">
<div class="col1wrap">
                <div class="col1 fond">



        <!-- Column 1 start -->


        <!-- cadre central de la page -->
        <div class="cadre1">
            <div style="float: right;">
                <!-- AddThis Button BEGIN -->
                <script type="text/javascript">var addthis_pub = "zeas";
    var addthis_brand = "BDovore";
    var addthis_header_color = "#990000";
    var addthis_header_background = "#DAC1B3";</script><a href="http://www.addthis.com/bookmark?v=20" onmouseover="return addthis_open(this, '', '[URL]', '[TITLE]')" onmouseout="addthis_close()" onclick="return addthis_sendto()"><img src="<?php echo BDO_URL_IMAGE; ?>site/lg-addthis-fr.gif" width="125" height="16" alt="Partager cette page" style="border:0"/></a>
                <noscript>
                <span class="petite_police"><br />Javascript absent/désactivé dans votre navigateur : bouton inactif</span>
                </noscript>
                <script type="text/javascript" src="http://s7.addthis.com/js/200/addthis_widget.js"></script>
                <!-- AddThis Button END -->
            </div>

            <div class="middle_title">
                <h3>Fiche Auteur

<?php echo $view->auteur->PSEUDO; ?> <?php if (User::minAccesslevel(1)) { ?><a class="fancybox fancybox.iframe {width:600,height:600}" href="admin/editauteur?auteur_id=<?php echo $view->auteur->ID_AUTEUR; ?>"> <img src="<?php echo BDO_URL_IMAGE; ?>edit.gif" /></a> <?php } ?></h3></div>
            <br />
          
          <img src="<?php echo BDO_URL_IMAGE."auteur/".($view->auteur->IMG_AUT ?$view->auteur->IMG_AUT : "default_auteur.png" ); ?>" class="couvBig" style="float:left; margin:2px;">
                    </td>
                
                  <div ><font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif">
            <strong>Pseudo : </strong>
            </font>
<?php echo $view->auteur->PSEUDO; ?>
            <br />
            <font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif">
            <strong>Nom : </strong>
            </font>
<?php echo $view->auteur->NOM." , ".$view->auteur->PRENOM; ?>
            <br />
            <font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif">
            <strong>Activité : </strong>
            </font>
<?php $sep = ""; if ($view->auteur->FLG_SCENAR) {echo ("scénariste" ); $sep = ", ";}
if ($view->auteur->FLG_DESSIN) {echo ($sep."dessinateur" ); $sep = ", ";}
if ($view->auteur->FLG_COLOR) {echo ($sep."coloriste" ); $sep = ", ";}
?>
            <br />
            <font color="#990000" size="-1" face="Verdana, Arial, Helvetica, sans-serif">
            <strong>Albums dans la base: </strong>
            </font>
<?php echo ($view->nb_total_album ); ?>
            <br />
            
   <?php if ($view->page == 1) echo $view->auteur->COMMENT; ?>

            </div>
               


<hr class="expSep" />
                <!-- END CommentBlock -->

              <br>
        </div>


            <div class="cadre1"><div class="middle_title">
  <form id="form1" name="form1" method="get">
                <div id="select_activite">
                    <span id="album_as"> Albums en tant que...</span>   <label for="a1">Scénariste </label>  <input type="radio" name="activite" id="a1" value="1" <?php if ($view->activite == 1) echo "checked"; ?> onclick="$('#form1').submit();">  <label for="a2">Dessinateur </label> <input type="radio" name="activite" id="a2" value="2" <?php if ($view->activite == 2) echo "checked"; ?> onclick="$('#form1').submit();">  <label for="a3">Coloriste</label>  <input type="radio" name="activite" id="a3" value="3" <?php if ($view->activite == 3) echo "checked"; ?> onclick="$('#form1').submit();">

                </div>


  </form>  </div>
                <!-- BEGIN AlbBlock -->
                <table class="list_album">
<?php
$tr = true;
if (count($view->dbs_tome->a_dataQuery) == 0) echo "Aucun album pour cet auteur pour cette activité";
foreach ($view->dbs_tome->a_dataQuery as $tome) {
    if ($tr)
        echo "<tr>";

    echo "<td class='mw50'>" . $ficheAlbum->big($tome,$sep=true,$getUrlSerie=true) . "</td>";

    if (!$tr) {
        echo "</tr>";
    }
    $tr = !$tr;
    ?>



                    <?php
                    }
                    if (!$tr)
                        echo "</tr>";
                    ?></table>

                <div align="center">
<?php

if ($view->nb_album > 20) {
    $max_page = ceil($view->nb_album / 20);
    if ($max_page > 1) {
        echo($pageinate->paginate($ficheAlbum->getURLAuteur($view->auteur ),"?activite=".$view->activite ."&page=",$max_page,$view->page,$adj=3));
    }
   }
?> </div>
            </div>
       <!-- Column 1 end -->
                    </div>
</div>
                    <!-- Debut de la partie de droite -->
<div class="col2">
    <div id="actu" class="right fond">
            <div class="middle_title">

    <h3>Derniers ajouts...</h3>

    </div>      <!-- Column 2 start -->
                <?php
                    //echo count($view->SERIESIMI);
                    foreach ($view->lastAlbum->a_dataQuery as $o_tome)
                   {
                      echo $ficheAlbum->small($o_tome);
                    } ?>
    </div>
                <!-- Column 2 end -->
</div>
</div>
<script>
    $(document).ready(function() {
        $("#select_activite").buttonset();
    });
</script>