<?php
$ficheAlbum = $view->getHelper('ficheAlbum');
?>

<div class="colleft">
<div class="col1wrap">
                <div class="col1 fond">

                                    <div class="cadre1">
                                        <p>Les Bdovore qui ont <?php echo $ficheAlbum->urlalbum($view->tome,$class='albTitle'); ?> <?php if ($view->tome->NOM_SERIE <> $view->tome->TITRE_TOME) { ?> (série  <?php echo $ficheAlbum->urlserie($view->tome); ?> )<?php } ?> dans leur collection, ont aussi :
                                            <br></p>
                        <!-- Column 1 start -->

    <?php
      $cpt = 1;
     foreach ($view->a_simil as $simil) {
            ?>
             <?php echo $ficheAlbum->big($simil,$sep=true,$getUrlSerie=true); ?>



    <?php

    }
    ?>

<!-- Column 1 end -->
<hr class="expSep">
                                    </div>
                     </div>

</div>
                    <!-- Debut de la partie de droite -->
<div class="col2">
                  <!-- Column 2 start -->
        <div id="actu" class="right fond">
        <div class="middle_title">
            <h3>Actualité</h3>
        </div>
            
            <div class="right">
        <?php 
         $genre ="";
        foreach ($view->ACTUAIR as $actu) { 
            if ($actu->ORIGINE_GENRE <> $genre) {
                echo "<div class='middle_content'>".$actu->ORIGINE_GENRE ."</div>";
            }
            echo $ficheAlbum->urlAlbum($actu,$class="couvMedium",$sponsor=FALSE)." ";
            $genre = $actu->ORIGINE_GENRE;
      } ?>
            </div>
        </div>
         <div id="last" class="right fond">
    <div class="middle_title">
    <h3><a href="<?php echo BDO_URL;?>leguide?rb_mode=6&rb_list=album&submitGuide=Envoyer">Derniers ajouts</a>
    <a href="<?php echo BDO_URL;?>rss">
    <img src="<?php echo BDO_URL_IMAGE;?>site/feed.png" style="border: 0;" alt="logo fil rss" title="Suivez l'actualité des ajouts d'albums sur le site grace à ce fil rss" />
    </a></h3>
    </div>
        <div class="cadre1" style="margin:3px 3px 3px 3px ;">
            <?php 
           
            foreach ($view->LASTAJOUT as $ajout) {
                echo $ficheAlbum->urlAlbum($ajout,$class="albTitle")."<br />";
            }?>
        </div>
        
         </div>
        <!-- Column 2 end -->
</div>
</div>