<?php
$ficheAlbum = $view->getHelper('ficheAlbum');
?>

<div class="colleft">
<div class="col1wrap">
				<div class="col1 fond">
                                   
                                    <div class="cadre1" width="100%" height="600px">
                                        <p>Les Bdovore qui ont <?php echo $ficheAlbum->urlalbum($view->tome,$class="albTitle"); ?> dans leur collection, ont aussi
                                            <br></p>
						<!-- Column 1 start --> 
 
    <?php 
      $cpt = 1;
     foreach ($view->a_simil as $simil) {
            ?><div class='cadre1'>
             <?php echo $ficheAlbum->big($simil,$sep=true,$getUrlSerie=true); ?>
                  <a href="simil?ID_TOME=<?php echo $simil->ID_TOME ;?>">Albums similaires à <?php echo $simil->TITRE_TOME;?>...</a>
             </div>
           
            
    <?php  
           
    }
    ?>
 
<!-- Column 1 end -->
<hr class="expSep">
                                    </div>
                     </div>
                                    
</div>
    				<!-- Debut de la partie de droite -->
<div class="col2">
					<!-- Column 2 start -->
	            <?php echo $view->ACTUAIR;?>
	            <?php echo $view->LASTAJOUT;?>
				<!-- Column 2 end -->
</div>
</div>	