<?php header ( 'Content-Type: text/html; charset=UTF-8' );?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title><?php echo $view->PAGETITLE;?></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="content-language" content="fr" />
<meta name="description" content="<?php echo $view->DESCRIPTION;?> BDovore - Le site des collectionneurs de BD. Gérer votre collection de bandes dessinées en ligne et gratuitement !" />
<meta name="keywords" content="bd, bandes dessinées, bandes, dessinées, bande, dessinée, profiler, bdprofiler, comics, manga, collection, collections, bdvore, collectionneur, dedicace, auteurs, albums, editeurs, gratuit, base de données, <?php echo $view->PAGEKEYWORD;?>" />
<meta name="author" content="Tomlameche/Latruffe/Zéas" />
<meta name="identifier-url" content="http://www.bdovore.com" />
<meta name="reply-to" content="" />
<meta name="revisit-after" content="7 days" />
<meta name="robots" content="all" />
<link rel="shortcut icon" href="<?php echo BDO_URL;?>favicon.ico" />

<!-- Declaration fil rss -->
<link rel="alternate" type="application/rss+xml" title="BDovore - Les dernières news du site" href="<?php echo BDO_URL;?>rss-news" />
<link rel="alternate" type="application/rss+xml" title="BDovore - Les derniers albums ajoutés" href="<?php echo BDO_URL;?>rss" />
<link rel="alternate" type="application/rss+xml" title="BDovore - Les derniers avis sur les albums" href="<?php echo BDO_URL;?>rss-avis" />
<link rel="alternate" type="application/rss+xml" title="BDovore - Les derniers avis sur les séries/one-shots" href="<?php echo BDO_URL;?>rss-avis-serie" />


<link href="<?php echo BDO_URL;?>style/style1.css" rel="stylesheet" type="text/css" />
<link href="<?php echo BDO_URL;?>style/main.css" rel="stylesheet" type="text/css" />

<script src="<?php echo BDO_URL;?>script/library.js" type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>script/script.js" type="text/javascript"></script>
<?php
if (User::minAccesslevel(0)) {
?>
<script src="<?php echo BDO_URL;?>script/navigation_onglet.js" type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>script/excel.js" type="text/javascript"></script>

<script src="<?php echo BDO_URL;?>script/menu.js" type="text/javascript"></script>
<link href="<?php echo BDO_URL;?>style/menu.css" rel="stylesheet" type="text/css" />
<?php
}
?>

<!-- Jquery -->
<script src="<?php echo BDO_URL;?>js/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>js/jquery.metadata.js" type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>jquery.autocomplete.js" type="text/javascript"></script>

<script src="<?php echo BDO_URL;?>js/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
<link href="<?php echo BDO_URL;?>css/bdovore/jquery-ui-1.10.1.custom.min.css" rel="stylesheet">

<script src="<?php echo BDO_URL;?>js/bxslider/jquery.bxslider.min.js" type="text/javascript"></script>
<link href="<?php echo BDO_URL;?>css/bxslider/jquery.bxslider.css" rel="stylesheet">

<!-- Add mousewheel plugin (this is optional) -->
<script type="text/javascript" src="<?php echo BDO_URL;?>js/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>

<!-- Add fancyBox main JS and CSS files -->
<script type="text/javascript" src="<?php echo BDO_URL;?>js/fancybox/source/jquery.fancybox.js?v=2.1.4"></script>
<link rel="stylesheet" type="text/css" href="<?php echo BDO_URL;?>js/fancybox/source/jquery.fancybox.css?v=2.1.4" media="screen" />

<!-- Add Button helper (this is optional) -->
<link rel="stylesheet" type="text/css" href="<?php echo BDO_URL;?>js/fancybox/source/helpers/jquery.fancybox-buttons.css?v=1.0.5" />
<script type="text/javascript" src="<?php echo BDO_URL;?>js/fancybox/source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>

<!-- Add Thumbnail helper (this is optional) -->
<link rel="stylesheet" type="text/css" href="<?php echo BDO_URL;?>js/fancybox/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7" />
<script type="text/javascript" src="<?php echo BDO_URL;?>js/fancybox/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>

<!-- Add Media helper (this is optional) -->
<script type="text/javascript" src="<?php echo BDO_URL;?>js/fancybox/source/helpers/jquery.fancybox-media.js?v=1.0.5"></script>

<script>

$(document).ready(function() {
    $(".fancybox")
    .fancybox({
        type: 'iframe',
        autoSize : false
    });
});

// boutons haut / bas
$(document).ready(function() {

    $(window).scroll(function() {
        if ($(this).scrollTop() < $(document).height() - 200) {
            $('.scrolldown').fadeIn();
        } else {
            $('.scrolldown').fadeOut();
        }
        if ($(this).scrollTop() > 100) {
            $('.scrollup').fadeIn();
        } else {
            $('.scrollup').fadeOut();
        }
    });
    $('.scrollup').click(function() {
        $("html, body").animate({
            scrollTop : 0
        }, 600);
        return false;
    });

    $('.scrolldown').click(function() {
        $("html, body").animate({
            scrollTop : $(document).height()
        }, 600);
        return false;
    });

});
</script>


</head>

<body onLoad="<?php echo $view->BODYONLOAD;?>">
    <div id="header" style="position: relative; z-index: 10;">
        <div class="fondNoir"></div>
        <div id="logo">
            <a href="<?php echo BDO_URL;?>"><img
                src="<?php echo BDO_URL_IMAGE;?>site/logo_bdovore4.gif" border="0"
                alt="logo BDovore" id="logo" /></a>
        </div>
        <div id="searchtable">
            <ul id="menusite1">
                <li><a class="menuGene" href="<?php echo BDO_URL;?>presentation"
                    title="C'est quoi ce bidule ?">Présentation</a></li>
                <li>&nbsp;&nbsp;<a class="menuGene" href="<?php echo BDO_URL_FORUM;?>index"
                    title="Le forum">Forum</a></li>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;<a class="menuGene" href="<?php echo BDO_URL;?>contacts"
                    title="Les coordonnées des tauliers du bidule au cas où...">Contacts</a></li>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a class="menuGene" href="<?php echo BDO_URL;?>browser"
                    title="Le BDo'Browser ! Oh Yeah!">Browser</a></li>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a class="menuGene" href="<?php echo BDO_URL;?>leguide"
                    title="Le top des votes, les albums les plus répandus, les derniers commentaires, les dernières sorties...">Le
                        Guide BD</a></li>
            </ul>
            <form action="<?php echo BDO_URL;?>membres/search" method="post"
                name="search" target="_self">
                <input name="str_search" type="text" id="str_search"
                    onblur="if (!this.value) this.value='Rechercher...';"
                    onfocus="if (this.value=='Rechercher...') this.value='';" size="20"
                    maxlength="50" value="Rechercher..." /> <input type="submit"
                    name="Submit" value="Ok" />
            </form>
        </div>
        <div id="login">
            <?php echo $view->LOGINBARRE;?>
        </div>
        <hr class="expSep" />
    </div>

    <?php if (User::minAccesslevel(0)) include dirname(__FILE__).DS.'..'.DS.'views_controllers'.DS.'menuadmin.phtml';?>


    <div id="content" style="position: relative; z-index: 10;">
        <div class="fond"></div>
                    <?php echo $view->BODY;?>
    </div>


    <div id="footer" style="position: relative; z-index: 10;">
        <div class="fond"></div>

        <div id="titre_avertissement">Avertissement</div>
        <div id="texte_avertissement">Les images présentes sur ce site sont la
            propriété de leurs auteurs et éditeurs respectifs et sont soumises à
            copyright. Leur utilisation n'a pour but que d'illustrer
            l'information contenue dans la base de donnée du site. Cependant, si
            ces derniers le désirent, ces images seront retirées sur simple
            demande de leur part.</div>
        <div id="texte_avertissement">
            <font color="#990000"> Lien destiné au référencement par les moteurs
                de recherche : </font> <a href="<?php echo BDO_URL;?>indexation">Liste
                des séries</a>
        </div>
    </div>


</body>
</html>
