<?php
header ( 'Content-Type: text/html; charset=UTF-8' );
$jquery = $view->getHelper('jquery');
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html<?php if (isset($view->opengraph)) echo ' xmlns:og="http://ogp.me/ns#"'; ?>>
<head>
<title><?php echo $view->PAGETITLE;?></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="content-language" content="fr" />
<meta name="description" content="<?php echo htmlentities($view->DESCRIPTION);?> BDovore - Le site des collectionneurs de BD. G&eacute;rer votre collection de bandes dessin&eacute;es en ligne et gratuitement !" />
<meta name="keywords" content="<?php echo htmlentities($view->KEYWORD);?> bd, bandes dessin&eacute;es, bandes, dessin&eacute;es, bande, dessin&eacute;e, profiler, bdprofiler, comics, manga, collection, collections, bdvore, collectionneur, dedicace, auteurs, albums, editeurs, gratuit, base de donn&eacute;es, <?php echo $view->PAGEKEYWORD;?>" />
<meta name="author" content="Tomlameche/Latruffe/Z&eacute;as" />

<meta name="category" content="BD, bande dessinee" />   
<meta name="robots" content="index, follow" />
<?php if (isset($view->opengraph)) { ?>
<!-- open graph -->
<meta property="og:title" content="<?php echo $view->PAGETITLE;?>" />
<meta property="og:type" content="<?php echo $view->opengraph["type"] ;?>" />
<meta property="og:url" content="<?php echo BDO_URL.$_SERVER['REQUEST_URI']; ?>" />
<meta property="og:image" content="<?php echo $view->opengraph["image"] ;?>" />
    <?php if ($view->opengraph["type"] == "book") { ?>
        <meta property="book:author" content="<?php echo $view->opengraph["author"] ;?>" />
        <meta property="book:isbn" content="<?php echo $view->opengraph["isbn"] ;?>" />
        <meta property="book:release_date" content="<?php echo $view->opengraph["release_date"] ;?>" />
        <meta property="book:tag" content="<?php echo $view->opengraph["tag"] ;?>" />
    <?php } ?>
<?php } ?>
<!-- Include media queries -->
<meta name="viewport" content="width=device-width"/>
<meta name="apple-mobile-web-app-capable" content="yes" />
<link rel="shortcut icon" href="<?php echo BDO_URL;?>favicon.ico" />

<!-- Declaration fil rss -->
<link rel="alternate" type="application/rss+xml" title="BDovore - Les derni&egrave;res news du site" href="<?php echo BDO_URL;?>rss-news" />
<link rel="alternate" type="application/rss+xml" title="BDovore - Les derniers albums ajout&eacute;s" href="<?php echo BDO_URL;?>rss" />
<link rel="alternate" type="application/rss+xml" title="BDovore - Les derniers avis sur les albums" href="<?php echo BDO_URL;?>rss-avis" />
<link rel="alternate" type="application/rss+xml" title="BDovore - Les derniers avis sur les s&eacute;ries/one-shots" href="<?php echo BDO_URL;?>rss-avis-serie" />


<link href="<?php echo BDO_URL;?>style/style1.css" rel="stylesheet" type="text/css" />
<link href="<?php echo BDO_URL;?>style/main.css" rel="stylesheet" type="text/css" />

<script src="<?php echo BDO_URL;?>script/library.js" type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>script/script.js" type="text/javascript"></script>


<!-- Jquery -->
<script src="<?php echo BDO_URL;?>jquery/jquery-1.10.2.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $.bdovore= {} // namespace
    $.bdovore.URL = '<?php echo BDO_URL; ?>';
</script>
<script src="<?php echo BDO_URL;?>jquery/jquery.metadata.js" type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>jquery/raty/jquery.raty.js" type="text/javascript"></script>
<!--<script src="<?php echo BDO_URL;?>jquery.autocomplete.js" type="text/javascript"></script> -->

<script src="<?php echo BDO_URL;?>jquery/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>jquery/jquery-ui/datepicker-fr.js" type="text/javascript"></script>
<link href="<?php echo BDO_URL;?>jquery/jquery-ui/bdovore/jquery-ui-1.10.1.custom.min.css" rel="stylesheet">

<script src="<?php echo BDO_URL;?>jquery/bxslider/jquery.bxslider.min.js" type="text/javascript"></script>
<link href="<?php echo BDO_URL;?>jquery/bxslider/jquery.bxslider.css" rel="stylesheet">

<link rel="stylesheet" href="<?php echo BDO_URL;?>jquery/responsivemobilemenu/rmm-css/responsivemobilemenu.css" type="text/css"/>
<script type="text/javascript" src="<?php echo BDO_URL;?>jquery/responsivemobilemenu/rmm-js/responsivemobilemenu.js"></script>
<!-- Add mousewheel plugin (this is optional) -->
<script type="text/javascript" src="<?php echo BDO_URL;?>jquery/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>

<!-- Add fancyBox main JS and CSS files -->
<script type="text/javascript" src="<?php echo BDO_URL;?>jquery/fancybox/source/jquery.fancybox.js?v=2.1.4"></script>
<link rel="stylesheet" type="text/css" href="<?php echo BDO_URL;?>jquery/fancybox/source/jquery.fancybox.css?v=2.1.4" media="screen" />

<!-- Add Button helper (this is optional) -->
<link rel="stylesheet" type="text/css" href="<?php echo BDO_URL;?>jquery/fancybox/source/helpers/jquery.fancybox-buttons.css?v=1.0.5" />
<script type="text/javascript" src="<?php echo BDO_URL;?>jquery/fancybox/source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>

<!-- Add Thumbnail helper (this is optional) -->
<link rel="stylesheet" type="text/css" href="<?php echo BDO_URL;?>jquery/fancybox/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7" />
<script type="text/javascript" src="<?php echo BDO_URL;?>jquery/fancybox/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>
<link href="<?php echo BDO_URL;?>jquery/datatable/css/jquery.dataTables.css" rel="stylesheet"
    type="text/css" />
<script src="<?php echo BDO_URL;?>script/comment.js" type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>jquery/jquery.cookie.js" type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>script/detectmobilebrowser.js" type="text/javascript"></script>
<?php
if (User::minAccesslevel(2)) {
?>

    <script src="<?php echo BDO_URL;?>script/collection.js" type="text/javascript"></script>


<?php
}
?>

<script>
if (!$.browser.mobile) {
    $(document).ready(function() {
            $(".fancybox")
        .fancybox({
            type: 'iframe',
            autoSize : false
        });
    });
} else {
    $(document).ready(function() {
            $(".fancybox")
        .each( function () {
            var q_string = this.href.split("?");
            var q_anchor = this.href.split("#");
            if (q_string.length == 1) {
                this.href = q_anchor[0] + "?mobile=T";
            } else {
                this.href = q_anchor[0] + "&mobile=T" ;
            }
            if (q_anchor.length == 2) {
                this.href = this.href + "#" + q_anchor[1];
            } 
            
        });
    });
 }


// boutons haut / bas
$(document).ready(function() {
/*
    $(window).scroll(function() {
        if ($(this).scrollTop() < $(document).height() - 200) {
            $('.scrolldown').fadeIn();
        } else {
            $('.scrolldown').fadeOut();
        }
        if ($(this).scrollTop() > 100) {
            $('.scrollup').fadeIn();
        } else {
            $('.scrollup').fadeOut();
        }
    });
    $('.scrollup').click(function() {
        $("html, body").animate({
            scrollTop : 0
        }, 600);
        return false;
    });

    $('.scrolldown').click(function() {
        $("html, body").animate({
            scrollTop : $(document).height()
        }, 600);
        return false;
    });
*/
        $.datepicker.setDefaults( $.datepicker.regional[ "fr" ] );

});
</script>


  <script>
  $.widget( "custom.catcomplete", $.ui.autocomplete, {
    _renderMenu: function( ul, items ) {
      var that = this,
        currentCategory = "";
      $.each( items, function( index, item ) {
        if ( item.category != currentCategory ) {
          ul.append( "<li class='ui-autocomplete-category'>" + item.category + "</li>" );
          currentCategory = item.category;
        }
        that._renderItemData( ul, item );
      });
    }
  });
  $(function() {
        var cache = {};
        $( "#search" ).catcomplete({
          minLength: 2,
          source: function( request, response ) {
            var term = request.term;
            if ( term in cache ) {
              response( cache[ term ] );
              return;
            }

            $.getJSON( "<?php echo BDO_URL;?>search/auto", request, function( data, status, xhr ) {
              cache[ term ] = data;
              response( data );
            });
          },
          select: function( event, ui ) {
            //alert( ui.item.category + ' ' + ui.item.label);
                if (ui.item.category=='Séries') {
                    window.location.href = "<?php echo BDO_URL;?>serie-bd-"+ encodeURIComponent(ui.item.ID_SERIE)+"-"+string_to_slug(ui.item.label);
                }
                if (ui.item.category=='Auteurs') {
                    window.location.href = "<?php echo BDO_URL;?>auteur-bd-"+encodeURIComponent(ui.item.ID_AUTEUR)+"-"+string_to_slug(ui.item.label);
                }
                if (ui.item.category=='Albums') {
                    if (!$.browser.mobile) {
                        $.fancybox.open(
                                {
                                    type: 'iframe',
                                    autoSize : false,
                                    href : "<?php echo BDO_URL;?>Album?id_tome="+ui.item.ID_TOME,
                                    title : ui.item.label,
                                    width:600,
                                    height:600
                                });
                    } 
                    else {
                         window.location.href = "<?php echo BDO_URL;?>Album?id_tome="+encodeURIComponent(ui.item.ID_TOME) + "&mobile=T";
                    }
                }
                        if (ui.item.category=='Bdovore') {
                    window.location.href = "<?php echo BDO_URL;?>guest?user="+encodeURIComponent(ui.item.ID_USER);
                }
          }
        });
      });

  </script>
    <script>
 if (!$.browser.mobile) {
  $(function() {
    $( '*' ).tooltip({
      position: {
        my: "center bottom-20",
        at: "center top",
        using: function( position, feedback ) {
          $( this ).css( position );
          $( "<div>" )
            .addClass( "arrow" )
            .addClass( feedback.vertical )
            .addClass( feedback.horizontal )
            .appendTo( this );
        }
      }
    });
  });
 }

  </script>

<link href="<?php echo BDO_URL;?>jquery/jquery_util.css" rel="stylesheet">


<link href="<?php echo BDO_URL;?>jquery/cool-login/cool-login.css" rel="stylesheet">
<script src="<?php echo BDO_URL;?>jquery/cool-login/cool-login.js" type="text/javascript"></script>


    <link type="text/css" rel="stylesheet" href="<?php echo BDO_URL;?>jquery/openid-selector/css/openid.css" />
    <script type="text/javascript" src="<?php echo BDO_URL;?>jquery/openid-selector/js/openid-jquery.js"></script>
    <script type="text/javascript" src="<?php echo BDO_URL;?>jquery/openid-selector/js/openid-fr.js"></script>
        <script type="text/javascript">
        $(document).ready(function() {
            openid.init('openid_identifier');
            openid.setDemoMode(false); //Stops form submission for client javascript-only test purposes
        });
    </script>

<!-- Multiselect chosen widget -->
<script type="text/javascript" src="<?php echo BDO_URL;?>jquery/chosen/chosen/chosen.jquery.js"></script>
<!-- coockiechoice -->
<script src="<?php echo BDO_URL; ?>script/cookiechoices.js"></script><script>document.addEventListener('DOMContentLoaded', function(event){cookieChoices.showCookieConsentBar('Ce site utilise des cookies pour vous offrir le meilleur service. En poursuivant votre navigation, vous acceptez l’utilisation des cookies.', 'J’accepte', 'En savoir plus', '<?php echo BDO_URL;?>/mentionslegales/');});</script>
<link type="text/css" rel="stylesheet" href="<?php echo BDO_URL;?>jquery/chosen/chosen/chosen.css" />
<?php
if ($view->a_cssFile){
foreach($view->a_cssFile as $cssFile) {
echo "\n".'<link type="text/css" rel="stylesheet" href="'.BDO_URL.$cssFile.'" />';
}
}
//          -o-transform: rotate(270deg);

?>




<style type="text/css">
div.verticaltext {
        color:#333;
 writing-mode:tb-rl;
 -webkit-transform:rotate(270deg);
 -moz-transform:rotate(270deg);
 white-space:nowrap;
 border:0px solid red;
 display:block;
 text-align:left;
 width:20px;
 height:200px;
 text-shadow: 0px 0px 1px #333;
 font-family: Arial, Verdana, Helvetica, sans-serif;
 font-size:14px;
 font-weight:normal;
}
</style>
</head>

<body onLoad="<?php echo $view->BODYONLOAD;?>">


    <div id="header" style="position: relative; z-index: 10;">
        <div class="fondNoir"></div>
        <div id="logo">
            <a href="<?php echo BDO_URL;?>"><img
                src="<?php echo BDO_URL_IMAGE;?>site/bdovore4.gif" border="0"
                alt="logo BDovore" id="logo" /></a>
        </div>
        <div id="searchtable" class="rmm">
            <ul id="menusite1">
                            <li> <a class="menuGene" href="<?php echo BDO_URL;?>"
                    title="Retour à l'accueil">Accueil</a></li>
                <li><a class="menuGene" href="<?php echo BDO_URL;?>browser"
                    title="Le BDo'Browser ! Oh Yeah!">Browser</a></li>
                <li><a class="menuGene" href="<?php echo BDO_URL;?>leguide"
                    title="Le top des votes, les albums les plus r&eacute;pandus, les derniers commentaires, les derni&egrave;res sorties...">Le
                        Guide BD</a></li>

                                 <li><a class="menuGene" href=<?php
                                                if (User::minAccesslevel(2)) {
                                                    echo '"'.BDO_URL."macollection".'"';
                                                }
                                                else{
                                                    echo ("'#' onclick='".'$("#loginBox").show()'."'");
                                                }
                                                ?>
                    title="Tout pour votre collection de BD">Ma Collection</a></li>
                                <li><a class="menuGene" href="<?php echo BDO_URL_FORUM;?>index"
                    title="Le forum">Forum</a></li>
                                <li><a class="menuGene" href="<?php echo BDO_URL;?>presentation"
                    title="C'est quoi ce bidule ?">Pr&eacute;sentation</a></li>
                                <?php
if (User::minAccesslevel(1)) { ?><li>
<a class="menuGene" href="<?php echo BDO_URL;?>admin"
title="Pour les admins !">Admin</a></li> <?php } ?>
            </ul>
            <br />
            <form action="<?php echo BDO_URL;?>browser" method="post"
                id="formsearch" name="formsearch" target="_self">
                
<div class="ui-widget">
    <a class="facebook-social" id="facebookheader" target="_blank" href="https://fr-fr.facebook.com/bdovore/" title="Suivez-nous sur Facebook" style="opacity: 1;"><img src="<?php echo BDO_URL_IMAGE;?>site/facebook.png"></a>
                     <a class="aide-header" id="aideheader" href="<?php echo BDO_URL; ?>tutoriel" title="Besoin d'aide ? Suivez le guide"><img src="<?php echo BDO_URL_IMAGE;?>site/help.png"></a>
               
                     <input name="search" type="text" id="search"
                    onblur="if (!this.value) this.value='Rechercher album, série, auteur...';"
                    onfocus="if (this.value=='Rechercher album, série, auteur...') this.value='';" size="40"
                    maxlength="60" value="Rechercher album, série, auteur..." />
                <img id="img_loupe" src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif">
</div>
            </form>
        </div>
            <?php echo $view->LOGINBARRE;?>

        <hr class="expSep" />
    </div>



    <div id="content">

        <div class="colmask rightmenu">
                     <?php
                    if (Bdo_Error::notEmpty()) echo $jquery->alert(Bdo_Error::flush());
                    if ($view->a_alertPage) echo $jquery->alert($view->a_alertPage);


                    ?>

                            <?php echo $view->BODY;?>


        </div>
    </div>


    <div id="footer" class="shadow fond">
        <div id="social">Contacts, informations diverses via le forum ou via <a class="facebook-social" id="facebookfooter" target="_blank" href="https://fr-fr.facebook.com/bdovore/" title="Suivez-nous sur Facebook" style="opacity: 1;"><img src="<?php echo BDO_URL_IMAGE;?>site/facebook.png"></a>
                     <a class="aide-header" id="aidefooter" href="<?php echo BDO_URL; ?>tutoriel" title="Besoin d'aide ? Suivez le guide"><img src="<?php echo BDO_URL_IMAGE;?>site/help.png"></a>
               </div>
        <div id="titre_avertissement">Avertissement</div>
        <div id="texte_avertissement">Les images pr&eacute;sentes sur ce site sont la
            propri&eacute;t&eacute; de leurs auteurs et &eacute;diteurs respectifs et sont soumises &agrave;
            copyright. Leur utilisation n'a pour but que d'illustrer
            l'information contenue dans la base de donn&eacute;e du site. Cependant, si
            ces derniers le d&eacute;sirent, ces images seront retir&eacute;es sur simple
            demande de leur part.</div>
        <div id="mentionsllegales"><a href="<?php echo BDO_URL; ?>mentionslegales">Mentions Légales</a></div>
        <div id="indexation">
            <font color="#990000"> Toutes les séries de bandes-dessinées : </font>
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=A">A</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=B">B</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=C">C</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=D">D</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=E">E</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=F">F</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=G">G</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=H">H</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=I">I</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=J">J</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=K">K</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=L">L</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=M">M</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=N">N</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=O">O</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=P">P</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=Q">Q</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=R">R</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=S">S</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=T">T</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=U">U</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=V">V</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=W">W</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=X">X</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=Y">Y</a> -
                        <a href="<?php echo BDO_URL;?>liste_serie_bd?lettre=Z">Z</a> -
                        <br>
                        <font color="#990000"> Tous les auteur de bandes-dessinées : </font>
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=A">A</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=B">B</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=C">C</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=D">D</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=E">E</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=F">F</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=G">G</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=H">H</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=I">I</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=J">J</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=K">K</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=L">L</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=M">M</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=N">N</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=O">O</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=P">P</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=Q">Q</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=R">R</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=S">S</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=T">T</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=U">U</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=V">V</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=W">W</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=X">X</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=Y">Y</a> -
                        <a href="<?php echo BDO_URL;?>liste_auteur_bd?lettre=Z">Z</a> -

        </div>
    </div>
<a href="#" class="scrollup">Scroll</a>
<a href="#" class="scrolldown">Scroll</a>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<?php echo GOOGLE_ID; ?>', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>
