<?php header ( 'Content-Type: text/html; charset=UTF-8' );?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title><?php echo $view->PAGETITLE;?></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="content-language" content="fr" />
<meta name="description"
    content="<?php echo $view->DESCRIPTION;?> BDovore - Le site des collectionneurs de BD. Gérer votre collection de bandes dessinées en ligne et gratuitement !" />
<meta name="keywords"
    content="bd, bandes dessinées, bandes, dessinées, bande, dessinée, profiler, bdprofiler, comics, manga, collection, collections, bdvore, collectionneur, dedicace, auteurs, albums, editeurs, gratuit, base de données, <?php echo $view->PAGEKEYWORD;?>" />
<meta name="author" content="Tomlameche/Latruffe/Zéas" />
<meta name="identifier-url" content="http://www.bdovore.com" />
<meta name="reply-to" content="" />
<meta name="revisit-after" content="7 days" />
<meta name="robots" content="all" />
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<?php echo GOOGLE_ID; ?>', 'auto');
  ga('send', 'pageview');

</script>
<script src="<?php echo BDO_URL;?>jquery/jquery-1.10.2.min.js" type="text/javascript"></script>
<!-- Add fancyBox main JS and CSS files -->
<script type="text/javascript" src="<?php echo BDO_URL;?>jquery/fancybox/source/jquery.fancybox.js?v=2.1.4"></script>
<link rel="stylesheet" type="text/css" href="<?php echo BDO_URL;?>jquery/fancybox/source/jquery.fancybox.css?v=2.1.4" media="screen" />

<body onLoad="<?php echo $view->BODYONLOAD;?>">

    <script>

$(document).ready(function() {
    $(".fancybox")
    .fancybox({
        type: 'iframe',
        autoSize : false
    });
});</script>

        <div class="fond"></div>
                <?php
                    if (Bdo_Error::notEmpty()) echo $jquery->alert(Bdo_Error::flush());
                    if ($view->a_alertPage) echo $jquery->alert($view->a_alertPage);
                                        if ($view->a_infoPage) echo $jquery->info($view->a_infoPage);

                    ?>
                    <?php echo $view->BODY;?>



</body>
</html>