<?php header ( 'Content-Type: text/html; charset=UTF-8' );
$jquery = $view->getHelper('jquery');
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title><?php echo $view->PAGETITLE;?></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="content-language" content="fr" />
<meta name="description"
	content="<?php echo $view->DESCRIPTION;?> BDovore - Le site des collectionneurs de BD. Gérer votre collection de bandes dessinées en ligne et gratuitement !" />
<meta name="keywords"
	content="bd, bandes dessinées, bandes, dessinées, bande, dessinée, profiler, bdprofiler, comics, manga, collection, collections, bdvore, collectionneur, dedicace, auteurs, albums, editeurs, gratuit, base de données, <?php echo $view->PAGEKEYWORD;?>" />
<meta name="author" content="Tomlameche/Latruffe/Zéas" />
<meta name="identifier-url" content="http://www.bdovore.com" />
<meta name="reply-to" content="" />
<meta name="revisit-after" content="7 days" />
<meta name="robots" content="all" />


<script src="<?php echo BDO_URL;?>jquery/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>jquery/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
    
<script type="text/javascript"> 
    $.bdovore= {} // namespace
    $.bdovore.URL = '<?php echo BDO_URL; ?>';
</script>
<link href="<?php echo BDO_URL;?>jquery/jquery-ui/bdovore/jquery-ui-1.10.1.custom.min.css" rel="stylesheet">
<script src="<?php echo BDO_URL;?>script/comment.js" type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>script/collection.js" type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>jquery/raty/jquery.raty.js" type="text/javascript"></script>
<link href="<?php echo BDO_URL;?>style/main.css" rel="stylesheet"
	type="text/css" />
<script src="<?php echo BDO_URL;?>script/lightbox.js"
	type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>script/navigation_onglet.js"
	type="text/javascript"></script>
	
	
<link href="<?php echo BDO_URL;?>style/style_iframe.css" rel="stylesheet"
	type="text/css" />
<script src="<?php echo BDO_URL;?>script/script.js"
	type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>script/library.js"
	type="text/javascript"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<?php echo GOOGLE_ID; ?>', 'auto');
  ga('send', 'pageview');

</script>

</head>

<body onLoad="<?php echo $view->BODYONLOAD;?>">

		
	
		<div class="fond"></div>
                <?php 
					if (Bdo_Error::notEmpty()) echo $jquery->alert(Bdo_Error::flush());
					if ($view->a_alertPage) echo $jquery->alert($view->a_alertPage);
                                        if ($view->a_infoPage) echo $jquery->info($view->a_infoPage);
						
					?>
					<?php echo $view->BODY;?>



</body>
</html>