<?php
$ficheAlbum = $view->getHelper('ficheAlbum');
$page = $view->getHelper('pagination');
?>
<hr class="expSep"/>
<div class="cadre1">
    <div class="middle_title"><h3>Collection de <?php echo $view->USERNAME; ?></h3></div>
<?php echo $page->menuGuest(encodeUserId($view->IDUSER)); ?>
    <br>
    <h2>Les avis de lecture de <?php echo $view->USERNAME; ?></h2>

    <!-- Column 1 start -->



<?php
if (isset($view->dbs_comment)) {
    //echo ("<table>");

    foreach ($view->dbs_comment->a_dataQuery as $tome) { ?>

        <div class='cadre1'>
        <table>
       <tr><td style='vertical-align:top'>
       <?php echo $ficheAlbum->urlalbum($tome, 'couvBig'); ?>


        </td>

       <td style='vertical-align:top'>

                                    <strong><?php echo $ficheAlbum->urlalbum($tome, 'albTitle'); ?></strong>
                                    <span id='noteTome<?php echo $tome->ID_TOME; ?>'> </span>
                                    <p class="fiche_album">
                                     S&eacute;rie : <?php echo $ficheAlbum->urlSerie($tome); ?> <br>
                                    Publié par <a href='./guest?user=<?php echo $tome->user_id; ?>'><?php echo $tome->username; ?></a> le <?php echo $tome->DTE_POST; ?></p>
                                    <p> <?php echo (stripslashes(nl2br($tome->COMMENT))); ?>
                                </td>
                        </table>
            <script>$('#noteTome<?php echo $tome->ID_TOME; ?>').raty({score: <?php echo $tome->NOTE / 2; ?>, readOnly: true});</script>
                    </div>
 <?php   }
}
?><div align="center">
    <?php
    // pagination

    $a_qstring = $_GET;
    unset($a_qstring["page"]);
    $qstring = http_build_query($a_qstring);
    if ($view->NUM_PAGE > 1)
        echo "<a href='?" . $qstring . "&page=" . ($view->NUM_PAGE - 1) . "'>Précédent &nbsp;</a>";
    if ($view->NUM_PAGE < 20)
        echo "<a href='?" . $qstring . "&page=" . ($view->NUM_PAGE + 1) . "'>&nbsp;Suivant</a>";
    ?>

        <!-- Column 1 end -->
    </div>

</div>