<?php


$ficheAlbum = $view->getHelper('ficheAlbum');
$page = $view->getHelper('pagination');


?>
<hr class="expSep"/>

<div class="middle_title"><h3>Collection de <?php echo $view->USERNAME;?></h3></div>
 <?php echo $page->menuGuest(encodeUserId($view->IDUSER)); ?>
  <br>
<div class="cadre1" style="float:left;">
  
<h2>Carr&eacute; Magique de <?php echo $view->USERNAME;?></h2>

	<table width="300" border="0">

		<tr>

        <?php

        $i = 1;

        foreach ($view->a_carre as $o_tome) {

            if ($i > 3) {

                $i = 1;

                echo '</tr><tr>';

            }

            echo '<td width="100" class="CarreMagique">'.$ficheAlbum->urlAlbum ($o_tome,'couvMedium').'</td>';

            $i ++;

        }

        ?> 

        </tr>

	</table>

</div>



    <div class="cadre1" style="float:left;margin: auto; margin-left:5px ;padding:auto;">

    				<h2>Informations sur la collection de l'utilisateur</h2>

    				<p>

                        Nombre d'albums : <?php echo $view->NBALBUMS;?> dont <?php echo $view->NBINTEGRALES;?> int&eacute;grales.

                        <br />

                        Nombre de coffrets : <?php echo $view->NBCOFFRETS;?>

                        <br />

                        Nombre de s&eacute;ries suivies par cet utilisateur : <?php echo $view->NBSERIES;?>

                        <br />

                        Nombre d'achats pr&eacute;vus par cet utilisateur : <?php echo $view->NBACHATS;?>

                    </p>

    				<p>

    					<font color="#990000"><b>Contributions &agrave; la base de

    							donn&eacute;es</b></font>

    				</p>

    				<p>

                        Propositions de nouveaux albums : <?php echo $view->NBPROPS;?>

                        <br />

                        Propositions de corrections : <?php echo $view->NBCORRECTIONS;?>

                    </p>

    </div>



<hr class="expSep"/>





<div class="cadre1">

	<h2>Derniers achats</h2>

	

    <?php

    foreach ($view->a_lastAchat->a_dataQuery as $o_tome) {

        echo '<div style="float:left; margin:5px">'.$ficheAlbum->urlAlbum ($o_tome,'couvMedium').'</div>';

    }

    ?> 



<hr class="expSep"/>

</div>

