<div class="cadre1">
<form name="addrole" method="POST" action="">
<input type="hidden" name="formAction" value="addRole">
Rôle : <input type="text" name="NOM_ACL_ROLE" value="">
<input type="submit" name="submitaddrole" value="Ajouter un rôles">
</form>
</div>
<?php


if (0 < count($acl->getAllIdRoleByCreationOrder()))
{
	echo '
	<table border="0" cellspacing="1" cellpadding="2">
	<tr>
	<td class="oftAclRoleTitle">'.LANG_LEGACY.'</td>';

	foreach ($acl->getAllIdRoleByCreationOrder() as $idrole) {
		$role = $acl->getRole($idrole);
		if ($idrole !== 'all'){

			$title = LANG_MODIFIER . ' ' .htmlentities($role,ENT_QUOTES,'UTF-8');

				$onClick = "window.location.href='".BDO_URL."acl?ID_ACL_ROLE=".$idrole."'";



			echo '<td class="oftAclRole" onClick="'.$onClick.'" title="'.$title.'">'.htmlentities($role,ENT_QUOTES,'UTF-8').'</td>';

		}
	}
	echo '</tr>';

	$i=0;
	foreach ($acl->getAllIdRoleByCreationOrder() as $idrole) {
		$role = $acl->getRole($idrole);
		if ($idrole !== 'all'){
			if (++$i != 1) echo '<tr>';

			$title = LANG_MODIFIER . ' ' .htmlentities($role,ENT_QUOTES,'UTF-8');

				$onClick = "window.location.href='".BDO_URL."acl?ID_ACL_ROLE=".$idrole."'";


			echo '<td class="oftAclRole" onClick="'.$onClick.'" title="'.$title.'">'
			.htmlentities($role,ENT_QUOTES,'UTF-8').'</td>';

			foreach ($acl->getAllIdRoleByCreationOrder() as $idroleparent) {
				$parent = $acl->getRole($idroleparent);
				if ($idroleparent !== 'all'){
					if ($parent){
						if ($acl->isParent($idrole, $idroleparent))
						{
							$class = 'oftAclLegacyDirect';
							$classOut = 'oftAclLegacyDirectON';
							$formName='changeLegacyForm'.++$i;
							$val = '<b><-</b>';
							$onClick = 'document.'.$formName.'.submit()';
							$title = '[' . $parent.'] '. LANG_ACL_LEGACY_OFF.' ['.$role.']';
						}
						else if (in_array($idrole,$acl->getLegacy($idroleparent)))
						{
							$class = 'oftAclLegacyIndirect';
							$classOut = 'oftAclLegacyDirect';
							$formName='changeLegacyForm'.++$i;
							$val = '<b><-</b>';
							$onClick = 'document.'.$formName.'.submit()';
							$title = '[' . $parent.'] '. LANG_ACL_LEGACY_OFF.' ['.$role.']';
						}
						else if ($idrole == $idroleparent)
						{
							$class = 'oftAclRoleTitle';
							$classOut = 'oftAclRoleTitle';
							$formName='';
							$val = '&nbsp;';
							$onClick = '';
							$title = '';
						}
						else if (in_array($idroleparent,$acl->getLegacy($idrole)))
						{
							$class = 'oftAclLegacyImpossible';
							$classOut = 'oftAclLegacyImpossible';
							$formName='';
							$val = '&nbsp;';
							$onClick = '';
							$title = LANG_IMPOSSIBLE;
						}
						else
						{
							$class = 'oftAclLegacyPossible';
							$classOut = 'oftAclLegacyDirect';
							$formName='changeLegacyForm'.++$i;
							$val = '<b>&nbsp;</b>';
							$onClick = 'document.'.$formName.'.submit()';
							$title = '[' . $parent.'] '. LANG_ACL_LEGACY_NO_OFF.' ['.$role.']';
						}

						if (!empty($formName))
						{
							echo '
				<form name="'.$formName.'" method="POST" action="">
				<input type="hidden" name="formAction" value="changeLegacy">
				<input type="hidden" name="ID_ACL_ROLE" value="'.$idrole.'">
				<input type="hidden" name="ID_ACL_ROLE_PARENT" value="'.$idroleparent.'">
				</form>
				';
						}
						echo '<td class="'.$class.'" onClick="'.$onClick.'" title="'.$title.'" width="15"
						onmouseover="this.className=\''.$classOut.'\'"
	  		onmouseout="this.className=\''.$class.'\'">'.$val.'</td>';
					}
				}
			}




		if (User::minAccesslevel(0))
		{
			$onClick = ' style="cursor:hand" onClick="if (confirm(\''.LANG_SUPPCONFIRM.'\')) {document.delrole_'.$idrole.'.submit()}"';
			echo '<td '.$onClick.' valign=top>

				<form name="delrole_'.$idrole.'" method="POST">
<input type="hidden" name="formAction" value="deleteRole">
<input type="hidden" name="ID_ACL_ROLE" value="'.$idrole.'">
</form>


				<img src="'.BDO_URL_IMAGE.'site/b_effacer.gif" border=0 title="'.LANG_SUPP.'"></td>';
		}



			echo '</tr>';
		}
	}
	echo '
	</table>';

        if (!is_null($ID_ACL_ROLE)){
	?>
	<div class="cadre1">
	<form name="updateRole" method="POST" action="">
	<input type="hidden" name="formAction" value="updateRole">
		<input type="hidden" name="ID_ACL_ROLE" value="<?php  echo $ID_ACL_ROLE;?>">
		Rôle : <input type="text" name="NOM_ACL_ROLE" value="<?php  echo $acl->getRole($ID_ACL_ROLE);?>">
	<input type="submit" name="submitupdateRole" value="Modifier">
	</form>
	</div>
<?php }?>
	<u><?php echo LANG_LEGEND;?> :</u>
	<table border="0" cellspacing="1" cellpadding="2">
	<tr><td valign=top><i><?php echo LANG_LEGACY;?></i><br />
		<table>
			<tr><td class="oftAclLegacyDirect" title="change" >X</td><td><?php echo LANG_DIRECT;?></td></tr>
			<tr><td class="oftAclLegacyIndirect">X</td><td><?php echo LANG_INDIRECT;?></td></tr>
			<tr><td class="oftAclLegacyPossible" title="change legacy" >&nbsp;</td><td><?php echo LANG_POSSIBLE;?></td></tr>
			<tr><td class="oftAclLegacyImpossible">&nbsp;</td><td><?php echo LANG_IMPOSSIBLE;?></td></tr>
		</table>
	</td>
	</tr>
	</table>
	<?php
}
