<?php  


//if (0 < count($acl->getAllIdRoleByCreationOrder()))
if (0 < count($acl->getAllAclRole()))
{
	echo '
	<table border=0 cellspacing=1 cellpadding=2>
	        	<tr>
	<td colspan=2>&nbsp;</td>
	<td class="oftAclRoleTitle" colspan='.(count($acl->getAllIdRoleByCreationOrder())).'>'.LANG_ACL_ROLE.'</td>
	        </tr>
	<tr>
	<td colspan=2>&nbsp;</td>
	';
//	foreach ($acl->getAllIdRoleByCreationOrder() as $idrole) {
	foreach ($acl->getAllAclRole() as $idrole=>$role) {
	   // $role = $acl->getRole($idrole);
		$roleValHtml = $role;

		if ($idrole!=='all')
		{
			$title = LANG_MODIFIER . ' '.htmlentities($role,ENT_QUOTES,'UTF-8');
			$onClick = "window.location.href='".BDO_URL."acl?ID_ACL_ROLE=".$idrole."'";		}
		else {
			$title='';
			$onClick='';
		}
		//echo '<td class="oftAclRole" onClick="'.$onClick.'" title="'.$title.'">'.htmlentities($roleValHtml,ENT_QUOTES,'UTF-8').'</td>';

		echo '<td rowspan=2 class="oftAclRole" onClick="'.$onClick.'" title="'.$title.'">'.$role.'</td>';

	}
	echo '</tr>';
	echo '
	<tr>
	<td class="oftAclResourceTitle">'.LANG_ACL_RESOURCE.'</td>
	<td class="oftAclPrivilegeTitle">'.LANG_ACL_RESOURCE_PRIVILEGE.'</td>
	</tr>';

	$k = 0;
	foreach ($acl->getAllResource() as $idres=>$resource) {
		if (count($acl->getAllPrivilegeForResource($idres)) > 0)
		{
			echo '<tr>';

		if ($idres==='all')
						{
				$class = "oftAclResourceAll";
				$onClick = '';
				$title = '';
			}
			else
			{
				$class = "oftAclResource";
				$title = LANG_VOIR . ' '.htmlentities($resource,ENT_QUOTES,'UTF-8');
				$onClick = "window.location.href='".BDO_URL."acl?ID_ACL_RESOURCE=".$idres."'";
			}

			echo '<td class="'.$class.'" onClick='.$onClick.' title="'.$title.'" rowspan='.count($acl->getAllPrivilegeForResource($idres)).'>'
			.$resource.'</td>';

			$j = 0;
			foreach ($acl->getAllPrivilegeForResource($idres) as $idpriv=>$privilege) {

				$privilegeValHtml = (is_null($privilege))?LANG_ALL:$privilege;
				if (++$j != 1) echo '<tr>';
				if ($idpriv==='all')
				{
					$privilege = '';
					$class = "oftAclPrivilegeAll";
					$onClick = '';
					$title = '';
				}
				else
				{
					$class = "oftAclPrivilege";
					$title = LANG_MODIFIER . ' '.htmlentities($resource.'.'.$privilege,ENT_QUOTES,'UTF-8');
				$onClick = "window.location.href='".BDO_URL."acl?ID_ACL_RESOURCE=".$idres."&ID_ACL_RESOURCE_PRIVILEGE=".$idpriv."'";
				}
				echo '<td class="'.$class.'" OnClick='.$onClick.' title="'.$title.'" valign=top>'
				.$privilegeValHtml.'</td>';

//				foreach ($acl->getAllIdRoleByCreationOrder() as $idrole) {
					foreach ($acl->getAllAclRole() as $idrole=>$role) {
					    // $role = $acl->getRole($idrole);
					$roleValHtml = ($idrole==='all') ? LANG_ALL : $role ;


					$k++;
					$formName='changePrivilegeForm'.$k;
					$onClick = 'document.'.$formName.'.submit()';

					if ($acl->isAllowedById($idrole, $idres, $idpriv))
					{
						$title = htmlentities(LANG_ALLOW .' : '.$roleValHtml.' - '.$resource.' - '.$privilegeValHtml, ENT_QUOTES,'UTF-8');
						$val = 'A';
						if ($acl->isDefinedPrivilege($idrole, $idres, $idpriv))
						{
							$class = 'oftAclAccessAllow';
							$classOut = 'oftAclAccessDeny';
						}
						else
						{
							$class = 'oftAclAccessAllowLegacy';
							$classOut = 'oftAclAccessDeny';
						}
					}
					else
					{
						$title = htmlentities(LANG_DENY .' : '.$roleValHtml.' - '.$resource.' - '.$privilegeValHtml, ENT_QUOTES,'UTF-8');
						$val = 'D';
						if ($acl->isDefinedPrivilege($idrole, $idres, $idpriv))
						{
							$class = 'oftAclAccessDeny';
							$classOut = 'oftAclAccessAllow';
						}
						else
						{
							if ($acl->isLegacyPrivilege($idrole, $idres, $idpriv)
							or $acl->isLegacyPrivilege($idrole, 'all', $idpriv)
							or $acl->isLegacyPrivilege($idrole, $idres, 'all')
							or $acl->isLegacyPrivilege($idrole, 'all', 'all')
							
							or ($acl->isDefinedPrivilege($idrole, 'all', $idpriv))
							or ($acl->isDefinedPrivilege('all', 'all', $idpriv))
							or ($acl->isDefinedPrivilege($idrole, $idres, 'all'))
							or ($acl->isDefinedPrivilege($idrole, 'all', 'all'))
							or ($acl->isDefinedPrivilege('all', $idres, 'all'))
							)
							{
								$class = 'oftAclAccessDenyLegacy';
								$classOut = 'oftAclAccessAllow';
							}
							else
							{
								$class = 'oftAclAccess';
								$classOut = 'oftAclAccessAllow';							}
						}
					}
					echo '<td class="'.$class.'" onClick="'.$onClick.'" title="'.$title.'"  
						onmouseover="this.className=\''.$classOut.'\'" 
	  		onmouseout="this.className=\''.$class.'\'">'.$val;
					echo '
				<form name="'.$formName.'" method="POST" action="">
				<input type="hidden" name="formAction" value="changePrivilege">
				<input type="hidden" name="ID_ACL_ROLE" value="'.$idrole.'">
				<input type="hidden" name="ID_ACL_RESOURCE" value="'.$idres.'">
				<input type="hidden" name="ID_ACL_RESOURCE_PRIVILEGE" value="'.$idpriv.'">
				</form>';

					echo '
			</td>';

				}
				echo '</tr>';

			}
		}
	}
	echo '</table>';

?>
<u><?php echo LANG_LEGEND;?> :</u>
<table border="0" cellspacing="1" cellpadding="2">
<tr>
<td valign=top><i><?php echo LANG_ACCES;?></i><br />
<div style="float:left">
	<table>
		<tr><td class="oftAclAccessAllow" title="<?php echo LANG_ALLOW;?>" >A</td><td><?php echo LANG_ALLOW;?></td></tr>
		<tr><td class="oftAclAccessAllowLegacy" title="<?php echo LANG_ALLOW;?>" >A</td><td><?php echo LANG_ALLOW;?> (<?php echo LANG_LEGACY;?>)</td></tr>
	</table>
</div>
<div style="float:left">
	<table>
		<tr><td class="oftAclAccessDeny" title="<?php echo LANG_DENY;?>" >D</td><td><?php echo LANG_DENY;?></td></tr>
		<tr><td class="oftAclAccessDenyLegacy" title="<?php echo LANG_DENY;?>" >D</td><td><?php echo LANG_DENY;?> (<?php echo LANG_LEGACY;?>)</td></tr>
	</table>
</div>
<div style="float:left">
	<table>
		<tr><td class="oftAclAccess" title="<?php echo LANG_DENY;?>" >D</td><td><?php echo LANG_UNDEFINED;?> (<?php echo LANG_DENY;?>)</td></tr>
	</table>
</div>
</td></tr>
</table>
<?php	
}

