<?php  

if (0 < count($acl->getAllIdRoleByCreationOrder()))
{
	$a_resource = $acl->getAllResource();
	$resourceValHtml = $a_resource[$ID_ACL_RESOURCE];
	echo '
	<table border="0" cellspacing="1" cellpadding="2">
	<tr>
	<td class="oftAclResourceTitle">'.$resourceValHtml.'</td>
	<td colspan='.(count($acl->getAllIdRoleByCreationOrder())).' class="oftAclRoleTitle">'.LANG_ACL_ROLE.'</td>
	</tr>
	';

	echo '
	<tr>
	<td class="oftAclPrivilegeTitle">'.LANG_ACL_RESOURCE_PRIVILEGE.'</td>
	';
	foreach ($acl->getAllIdRoleByCreationOrder() as $idrole) {
	    $role = $acl->getRole($idrole);

		if ($idrole!=='all')
		{
			$title = LANG_MODIFIER . ' '.htmlentities($role,ENT_QUOTES,'UTF-8');
			$onClick = "window.location.href='".BDO_URL."acl?ID_ACL_ROLE=".$idrole."'";		}
		else {
			$title='';
			$onClick='';
		}
		//echo '<td class="oftAclRole" onClick="'.$onClick.'" title="'.$title.'">'.htmlentities($roleValHtml,ENT_QUOTES,'UTF-8').'</td>';

		echo '<td class="oftAclRole" onClick="'.$onClick.'" title="'.$title.'">'.$role.'</td>';


	}
	echo '</tr>';

	if (count($acl->getAllPrivilegeForResource($ID_ACL_RESOURCE)) > 0)
	{
		echo '<tr>';


		$j = 0;
		foreach ($acl->getAllPrivilegeForResource($ID_ACL_RESOURCE) as $idpriv=>$privilege) {

			$privilegeValHtml = (is_null($privilege))?LANG_ALL:$privilege;
			if (++$j != 1) echo '<tr>';
				if ($idpriv==='all')
						{
				$privilege = '';
				$class = "oftAclPrivilegeAll";
				$onClick = '';
				$title = '';
			}
			else
			{
				$class = "oftAclPrivilege";

					$title = LANG_MODIFIER . ' '.htmlentities($resourceValHtml.'.'.$privilege,ENT_QUOTES,'UTF-8');
				$onClick = "window.location.href='".BDO_URL."acl?ID_ACL_RESOURCE=".$ID_ACL_RESOURCE."&ID_ACL_RESOURCE_PRIVILEGE=".$idpriv."'";
							}
			echo '<td class="'.$class.'" OnClick='.$onClick.' title="'.$title.'" valign=top>'
			.$privilegeValHtml.'</td>';

			foreach ($acl->getAllIdRoleByCreationOrder() as $idrole) {
				$role = $acl->getRole($idrole);


				$k++;
				$formName='changePrivilegeForm'.$k;
				$onClick = 'document.'.$formName.'.submit()';

				if ($acl->isAllowedById($idrole, $ID_ACL_RESOURCE, $idpriv))
				{
					$title = htmlentities(LANG_ALLOW .' : '.(('all' === $idrole) ? LANG_ALL : $role).' - '.$resourceValHtml.' - '.$privilegeValHtml, ENT_QUOTES,'UTF-8');
					$val = 'A';
					if ($acl->isDefinedPrivilege($idrole, $ID_ACL_RESOURCE, $idpriv))
					{
						$class = 'oftAclAccessAllow';
					}
					else
					{
						$class = 'oftAclAccessAllowLegacy';
					}
				}
				else
				{
					$title = htmlentities(LANG_DENY .' : '.(('all' === $idrole) ? LANG_ALL : $role).' - '.$resourceValHtml.' - '.$privilegeValHtml, ENT_QUOTES,'UTF-8');
					$val = 'D';
					if ($acl->isDefinedPrivilege($idrole, $ID_ACL_RESOURCE, $idpriv))
					{
						$class = 'oftAclAccessDeny';
					}
					else
					{
							if ($acl->isLegacyPrivilege($idrole, $ID_ACL_RESOURCE, $idpriv)
							or $acl->isLegacyPrivilege($idrole, 'all', $idpriv)
							or $acl->isLegacyPrivilege($idrole, $ID_ACL_RESOURCE, 'all')
							or $acl->isLegacyPrivilege($idrole, 'all', 'all')
							
							or ($acl->isDefinedPrivilege($idrole, 'all', $idpriv))
							or ($acl->isDefinedPrivilege('all', 'all', $idpriv))
							or ($acl->isDefinedPrivilege($idrole, $ID_ACL_RESOURCE, 'all'))
							or ($acl->isDefinedPrivilege($idrole, 'all', 'all'))
							or ($acl->isDefinedPrivilege('all', $ID_ACL_RESOURCE, 'all'))
							)						
						{
							$class = 'oftAclAccessDenyLegacy';
						}
						else
						{
							$class = 'oftAclAccess';
						}
					}
				}
				echo '<td class="'.$class.'" onClick="'.$onClick.'" title="'.$title.'"  
						onmouseover="this.className=\'oftAclAccessON\'" 
	  		onmouseout="this.className=\''.$class.'\'">'.$val;
				echo '
				<form name="'.$formName.'" method="POST" action="">
				<input type="hidden" name="formAction" value="changePrivilege">
				<input type="hidden" name="ID_ACL_ROLE" value="'.$idrole.'">
				<input type="hidden" name="ID_ACL_RESOURCE" value="'.$ID_ACL_RESOURCE.'">
				<input type="hidden" name="ID_ACL_RESOURCE_PRIVILEGE" value="'.$idpriv.'">
				</form>';

				echo '</td>';
			}
			if (('all' !== $idpriv) and User::minAccesslevel(0))
			{
				$onClick = ' style="cursor:pointer" onClick="if (confirm(\''.LANG_SUPPCONFIRM.'\')) {document.delprivilege_'.$idpriv.'.submit()}"';
				echo '<td '.$onClick.' valign=top>
				
				<form name="delprivilege_'.$idpriv.'" method="POST">
<input type="hidden" name="formAction" value="delResourcePrivilege">
<input type="hidden" name="ID_ACL_RESOURCE" value="'.$ID_ACL_RESOURCE.'">
<input type="hidden" name="ID_ACL_RESOURCE_PRIVILEGE" value="'.$idpriv.'">
</form>				
<img src="'.BDO_URL_IMAGE.'site/b_effacer.gif" border=0 title="'.LANG_SUPP. ' '.htmlentities($privilege,ENT_QUOTES,'UTF-8').'"></td>';
			}

			echo '</tr>';

		}

	}
	echo '
</table>';
	
}