ALTER TABLE `bd_edition`
  ADD COLUMN `FLAG_EAN_ISBN_IDENTIQUE` tinyint(1) UNSIGNED DEFAULT NULL
  AFTER `FLAG_DTE_PARUTION`;

ALTER TABLE `users_alb_prop`
  ADD COLUMN `FLAG_EAN_ISBN_IDENTIQUE` tinyint(1) UNSIGNED DEFAULT NULL
  AFTER `ISBN`;
