ALTER TABLE `bd_auteur`
  ADD COLUMN `FLG_SCULPT` char(1) COLLATE utf8_unicode_ci DEFAULT NULL AFTER `FLG_COLOR`,
  ADD COLUMN `FLG_DESIGN` char(1) COLLATE utf8_unicode_ci DEFAULT NULL AFTER `FLG_SCULPT`,
  ADD COLUMN `FLG_PEINT` char(1) COLLATE utf8_unicode_ci DEFAULT NULL AFTER `FLG_DESIGN`;
