-- MVP Para-BD - MySQL 5.7 / utf8_unicode_ci
-- Sauvegarder la base avant application. Les liens vers les tables historiques
-- MyISAM sont volontairement validés par l'application et non par des FK.

ALTER TABLE `users` ADD COLUMN `CREATED_AT` DATETIME NULL AFTER `LAST_UPDATE`;

UPDATE `users` u
LEFT JOIN (
    SELECT user_id, MIN(activity_at) AS first_activity
    FROM (
        SELECT user_id, MIN(date_ajout) AS activity_at FROM users_album WHERE date_ajout > '1000-01-01 00:00:00' GROUP BY user_id
        UNION ALL
        SELECT user_id, MIN(PROP_DTE) AS activity_at FROM users_alb_prop WHERE PROP_DTE > '1000-01-01 00:00:00' GROUP BY user_id
        UNION ALL
        SELECT user_id, MIN(DTE_POST) AS activity_at FROM users_comment WHERE DTE_POST > '1000-01-01 00:00:00' GROUP BY user_id
    ) activity
    WHERE activity_at IS NOT NULL AND activity_at > '1000-01-01 00:00:00'
    GROUP BY user_id
) firsts ON firsts.user_id = u.user_id
SET u.CREATED_AT = COALESCE(firsts.first_activity, NOW());

ALTER TABLE `users`
    MODIFY COLUMN `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE `parabd_type` (
    `ID_TYPE` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR(40) NOT NULL,
    `LABEL` VARCHAR(100) NOT NULL,
    `PARENT_ID` SMALLINT UNSIGNED NULL,
    `IS_REQUIRED_SUBTYPE` TINYINT(1) NOT NULL DEFAULT 0,
    `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
    `SORT_ORDER` SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (`ID_TYPE`),
    UNIQUE KEY `uq_parabd_type_code` (`CODE`),
    KEY `idx_parabd_type_parent` (`PARENT_ID`),
    CONSTRAINT `fk_parabd_type_parent` FOREIGN KEY (`PARENT_ID`) REFERENCES `parabd_type` (`ID_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `parabd_type` (`ID_TYPE`, `CODE`, `LABEL`, `PARENT_ID`, `IS_REQUIRED_SUBTYPE`, `SORT_ORDER`) VALUES
    (1, 'STATUETTE', 'Statuette', NULL, 0, 10),
    (2, 'PRINT', 'Image imprimée', NULL, 1, 20),
    (3, 'EXLIBRIS', 'Ex-libris', 2, 0, 10),
    (4, 'TIRE_A_PART', 'Tiré à part', 2, 0, 20),
    (5, 'IMPRESSION', 'Impression', 2, 0, 30),
    (6, 'FIGURINE', 'Figurine', 1, 0, 10),
    (7, 'BUSTE', 'Buste', 1, 0, 20),
    (8, 'DIORAMA', 'Diorama', 1, 0, 30),
    (9, 'ARTICULEE', 'Figurine articulée', 1, 0, 40),
    (10, 'OTHER', 'Autre', 1, 0, 50);

CREATE TABLE `parabd_item` (
    `ID_ITEM` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `TYPE_ID` SMALLINT UNSIGNED NOT NULL,
    `SUBTYPE_ID` SMALLINT UNSIGNED NULL,
    `TITLE` VARCHAR(255) NOT NULL,
    `TITLE_NORMALIZED` VARCHAR(255) NOT NULL,
    `DESCRIPTION` TEXT NULL,
    `MATERIAL` VARCHAR(255) NULL,
    `COLOR` VARCHAR(120) NULL,
    `WIDTH_MM` DECIMAL(10,2) NULL,
    `HEIGHT_MM` DECIMAL(10,2) NULL,
    `DEPTH_MM` DECIMAL(10,2) NULL,
    `WEIGHT_G` DECIMAL(10,2) NULL,
    `SCALE` VARCHAR(40) NULL,
    `RELEASE_DATE` DATE NULL,
    `DATE_PRECISION` ENUM('DAY','MONTH','YEAR','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    `PRINT_RUN` INT UNSIGNED NULL,
    `IS_NUMBERED` TINYINT(1) NULL,
    `IS_SIGNED` TINYINT(1) NULL,
    `HAS_CERTIFICATE` TINYINT(1) NULL,
    `IS_LIMITED` TINYINT(1) NULL,
    `MANUFACTURER` VARCHAR(180) NULL,
    `MANUFACTURER_NORMALIZED` VARCHAR(180) NOT NULL DEFAULT '',
    `PUBLISHER` VARCHAR(180) NULL,
    `LICENSE_NAME` VARCHAR(180) NULL,
    `RANGE_NAME` VARCHAR(180) NULL,
    `UNIVERSE_NAME` VARCHAR(180) NULL,
    `IS_EXPLICIT` TINYINT(1) NOT NULL DEFAULT 0,
    `STATUS` ENUM('ACTIVE','HIDDEN','MERGED') NOT NULL DEFAULT 'ACTIVE',
    `MERGED_INTO_ID` INT UNSIGNED NULL,
    `REVISION_NO` INT UNSIGNED NOT NULL DEFAULT 1,
    `CREATED_BY` MEDIUMINT UNSIGNED NULL,
    `UPDATED_BY` MEDIUMINT UNSIGNED NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_ITEM`),
    KEY `idx_parabd_item_search` (`STATUS`, `TYPE_ID`, `TITLE_NORMALIZED`(190)),
    KEY `idx_parabd_item_manufacturer` (`MANUFACTURER_NORMALIZED`),
    KEY `idx_parabd_item_merged` (`MERGED_INTO_ID`),
    CONSTRAINT `fk_parabd_item_type` FOREIGN KEY (`TYPE_ID`) REFERENCES `parabd_type` (`ID_TYPE`),
    CONSTRAINT `fk_parabd_item_subtype` FOREIGN KEY (`SUBTYPE_ID`) REFERENCES `parabd_type` (`ID_TYPE`),
    CONSTRAINT `fk_parabd_item_merged` FOREIGN KEY (`MERGED_INTO_ID`) REFERENCES `parabd_item` (`ID_ITEM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `parabd_identifier` (
    `ID_IDENTIFIER` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INT UNSIGNED NOT NULL,
    `SCHEME` ENUM('EAN13','UPCA','ISBN10','ISBN13','MANUFACTURER_REF','PUBLISHER_REF','EXTERNAL_DB') NOT NULL,
    `ISSUER` VARCHAR(120) NULL,
    `ISSUER_NORMALIZED` VARCHAR(120) NOT NULL DEFAULT '',
    `VALUE` VARCHAR(120) NOT NULL,
    `VALUE_NORMALIZED` VARCHAR(120) NOT NULL,
    `CREATED_BY` MEDIUMINT UNSIGNED NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_IDENTIFIER`),
    UNIQUE KEY `uq_parabd_identifier` (`SCHEME`, `ISSUER_NORMALIZED`, `VALUE_NORMALIZED`),
    KEY `idx_parabd_identifier_item` (`ITEM_ID`),
    CONSTRAINT `fk_parabd_identifier_item` FOREIGN KEY (`ITEM_ID`) REFERENCES `parabd_item` (`ID_ITEM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `parabd_item_author` (
    `ITEM_ID` INT UNSIGNED NOT NULL,
    `AUTHOR_ID` MEDIUMINT UNSIGNED NOT NULL,
    `ROLE` VARCHAR(40) NOT NULL DEFAULT 'ARTIST',
    `CREATED_BY` MEDIUMINT UNSIGNED NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ITEM_ID`, `AUTHOR_ID`, `ROLE`),
    KEY `idx_parabd_author` (`AUTHOR_ID`),
    CONSTRAINT `fk_parabd_item_author_item` FOREIGN KEY (`ITEM_ID`) REFERENCES `parabd_item` (`ID_ITEM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `parabd_item_series` (
    `ITEM_ID` INT UNSIGNED NOT NULL,
    `SERIES_ID` MEDIUMINT UNSIGNED NOT NULL,
    `RELATION_TYPE` VARCHAR(40) NOT NULL DEFAULT 'RELATED',
    `CREATED_BY` MEDIUMINT UNSIGNED NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ITEM_ID`, `SERIES_ID`, `RELATION_TYPE`),
    KEY `idx_parabd_series` (`SERIES_ID`),
    CONSTRAINT `fk_parabd_item_series_item` FOREIGN KEY (`ITEM_ID`) REFERENCES `parabd_item` (`ID_ITEM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `parabd_item_tome` (
    `ITEM_ID` INT UNSIGNED NOT NULL,
    `TOME_ID` MEDIUMINT UNSIGNED NOT NULL,
    `RELATION_TYPE` VARCHAR(40) NOT NULL DEFAULT 'RELATED',
    `PAGE_NO` SMALLINT UNSIGNED NULL,
    `PANEL_NO` SMALLINT UNSIGNED NULL,
    `CREATED_BY` MEDIUMINT UNSIGNED NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ITEM_ID`, `TOME_ID`, `RELATION_TYPE`),
    KEY `idx_parabd_tome` (`TOME_ID`),
    CONSTRAINT `fk_parabd_item_tome_item` FOREIGN KEY (`ITEM_ID`) REFERENCES `parabd_item` (`ID_ITEM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `parabd_media` (
    `ID_MEDIA` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INT UNSIGNED NOT NULL,
    `MEDIA_TYPE` ENUM('PRIMARY','GALLERY','CERTIFICATE','BOX','DETAIL') NOT NULL DEFAULT 'GALLERY',
    `FILE_PATH` VARCHAR(255) NOT NULL,
    `MIME_TYPE` VARCHAR(50) NOT NULL,
    `WIDTH_PX` SMALLINT UNSIGNED NOT NULL,
    `HEIGHT_PX` SMALLINT UNSIGNED NOT NULL,
    `IS_PRIMARY` TINYINT(1) NOT NULL DEFAULT 0,
    `IS_HIDDEN` TINYINT(1) NOT NULL DEFAULT 0,
    `SORT_ORDER` SMALLINT NOT NULL DEFAULT 0,
    `CREATED_BY` MEDIUMINT UNSIGNED NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_MEDIA`),
    KEY `idx_parabd_media_item` (`ITEM_ID`, `IS_HIDDEN`, `SORT_ORDER`),
    CONSTRAINT `fk_parabd_media_item` FOREIGN KEY (`ITEM_ID`) REFERENCES `parabd_item` (`ID_ITEM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `parabd_source` (
    `ID_SOURCE` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INT UNSIGNED NOT NULL,
    `SOURCE_TYPE` ENUM('URL','BOOK','CATALOG','OTHER') NOT NULL DEFAULT 'URL',
    `URL` VARCHAR(1000) NULL,
    `LABEL` VARCHAR(255) NULL,
    `NOTES` TEXT NULL,
    `CREATED_BY` MEDIUMINT UNSIGNED NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_SOURCE`),
    KEY `idx_parabd_source_item` (`ITEM_ID`),
    CONSTRAINT `fk_parabd_source_item` FOREIGN KEY (`ITEM_ID`) REFERENCES `parabd_item` (`ID_ITEM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `users_parabd` (
    `ID_COPY` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `USER_ID` MEDIUMINT UNSIGNED NOT NULL,
    `ITEM_ID` INT UNSIGNED NOT NULL,
    `STATE` ENUM('OWNED','WISHLIST') NOT NULL DEFAULT 'OWNED',
    `QUANTITY` SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    `COPY_NUMBER` VARCHAR(80) NULL,
    `CONDITION_CODE` ENUM('UNKNOWN','MINT','NEAR_MINT','VERY_GOOD','GOOD','FAIR','POOR') NOT NULL DEFAULT 'UNKNOWN',
    `COPY_IS_SIGNED` TINYINT(1) NULL,
    `COPY_IS_DEDICATED` TINYINT(1) NULL,
    `HAS_BOX` TINYINT(1) NULL,
    `HAS_CERTIFICATE` TINYINT(1) NULL,
    `IS_GIFT` TINYINT(1) NOT NULL DEFAULT 0,
    `PURCHASE_DATE` DATE NULL,
    `PRICE` DECIMAL(12,2) NULL,
    `CURRENCY` CHAR(3) NULL,
    `IS_PRICE_PUBLIC` TINYINT(1) NOT NULL DEFAULT 0,
    `SELLER` VARCHAR(255) NULL,
    `ESTIMATED_VALUE` DECIMAL(12,2) NULL,
    `PERSONAL_NOTES` TEXT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_COPY`),
    KEY `idx_users_parabd_user` (`USER_ID`, `STATE`),
    KEY `idx_users_parabd_item` (`ITEM_ID`),
    CONSTRAINT `fk_users_parabd_item` FOREIGN KEY (`ITEM_ID`) REFERENCES `parabd_item` (`ID_ITEM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `parabd_revision` (
    `ID_REVISION` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ITEM_ID` INT UNSIGNED NOT NULL,
    `AUTHOR_ID` MEDIUMINT UNSIGNED NULL,
    `BASE_REVISION_NO` INT UNSIGNED NOT NULL,
    `PATCH_BEFORE` MEDIUMTEXT NULL,
    `PATCH_AFTER` MEDIUMTEXT NOT NULL,
    `CHANGE_KIND` ENUM('CREATE','UPDATE','DELETE_LINK','TYPE_CHANGE','MERGE','MODERATION') NOT NULL DEFAULT 'UPDATE',
    `STATUS` ENUM('APPLIED','PENDING','CONFLICT','ACCEPTED','REJECTED') NOT NULL DEFAULT 'PENDING',
    `APPLIED_AT` DATETIME NULL,
    `VALIDATED_BY` MEDIUMINT UNSIGNED NULL,
    `VALIDATED_AT` DATETIME NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_REVISION`),
    KEY `idx_parabd_revision_queue` (`STATUS`, `CREATED_AT`),
    KEY `idx_parabd_revision_item` (`ITEM_ID`),
    KEY `idx_parabd_revision_author` (`AUTHOR_ID`, `STATUS`),
    CONSTRAINT `fk_parabd_revision_item` FOREIGN KEY (`ITEM_ID`) REFERENCES `parabd_item` (`ID_ITEM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `parabd_revision_vote` (
    `REVISION_ID` BIGINT UNSIGNED NOT NULL,
    `USER_ID` MEDIUMINT UNSIGNED NOT NULL,
    `VOTE` ENUM('CONFIRM','CONTEST') NOT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`REVISION_ID`, `USER_ID`),
    KEY `idx_parabd_revision_vote_user` (`USER_ID`),
    CONSTRAINT `fk_parabd_vote_revision` FOREIGN KEY (`REVISION_ID`) REFERENCES `parabd_revision` (`ID_REVISION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `parabd_duplicate` (
    `ID_DUPLICATE` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ITEM_ID_LOW` INT UNSIGNED NOT NULL,
    `ITEM_ID_HIGH` INT UNSIGNED NOT NULL,
    `LEVEL` ENUM('CERTAIN','STRONG','POSSIBLE') NOT NULL,
    `SCORE` DECIMAL(5,2) NOT NULL,
    `REASONS` TEXT NOT NULL,
    `STATUS` ENUM('OPEN','IGNORED','MERGED','COLLISION') NOT NULL DEFAULT 'OPEN',
    `RESOLVED_BY` MEDIUMINT UNSIGNED NULL,
    `RESOLVED_AT` DATETIME NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_DUPLICATE`),
    UNIQUE KEY `uq_parabd_duplicate_pair` (`ITEM_ID_LOW`, `ITEM_ID_HIGH`),
    KEY `idx_parabd_duplicate_queue` (`STATUS`, `LEVEL`, `SCORE`),
    CONSTRAINT `fk_parabd_duplicate_low` FOREIGN KEY (`ITEM_ID_LOW`) REFERENCES `parabd_item` (`ID_ITEM`),
    CONSTRAINT `fk_parabd_duplicate_high` FOREIGN KEY (`ITEM_ID_HIGH`) REFERENCES `parabd_item` (`ID_ITEM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `parabd_report` (
    `ID_REPORT` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `REPORTER_ID` MEDIUMINT UNSIGNED NOT NULL,
    `TARGET_TYPE` ENUM('ITEM','MEDIA','REVISION') NOT NULL,
    `TARGET_ID` BIGINT UNSIGNED NOT NULL,
    `REASON` VARCHAR(80) NOT NULL,
    `DETAILS` TEXT NULL,
    `STATUS` ENUM('OPEN','RESOLVED','DISMISSED') NOT NULL DEFAULT 'OPEN',
    `RESOLVED_BY` MEDIUMINT UNSIGNED NULL,
    `RESOLVED_AT` DATETIME NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_REPORT`),
    KEY `idx_parabd_report_queue` (`STATUS`, `CREATED_AT`),
    KEY `idx_parabd_report_user` (`REPORTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `parabd_user_profile` (
    `USER_ID` MEDIUMINT UNSIGNED NOT NULL,
    `CHARTER_VERSION` VARCHAR(20) NULL,
    `CHARTER_ACCEPTED_AT` DATETIME NULL,
    `TRUST_OVERRIDE` ENUM('NONE','GRANT','REVOKE') NOT NULL DEFAULT 'NONE',
    `TRUST_OVERRIDE_BY` MEDIUMINT UNSIGNED NULL,
    `TRUST_OVERRIDE_AT` DATETIME NULL,
    `CREATIONS_WINDOW_AT` DATETIME NULL,
    `CREATIONS_IN_WINDOW` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `UPLOADS_WINDOW_AT` DATETIME NULL,
    `UPLOADS_IN_WINDOW` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
