<?php
    
    $page = $view->getHelper('pagination');
    ?>
<SCRIPT LANGUAGE="JavaScript"><!--

function newWindow(myCategory,myText,myForm,myElement,isMandatory,myEditeur) {
	if ((isMandatory == true) && (myText.length < 3)) {
		alert('Veuillez saisir au moins 3 caractères');
	}
	else {
		if (myCategory == "collection") {
			if (myEditeur == '') {
				alert("Veuillez saisir l'éditeur en premier");
			}
			else {
			mywindow=open("pickup?cat=" + myCategory + "&text=" + myText + "&ReturnDoc=" + myForm + "&ReturnElement=" + myElement + "&IdEditeur=" + myEditeur,'myname','scrollbars=yes,resizable=yes,width=350,height=270');
			}
		}
		else {
			mywindow=open('pickup?cat=' + myCategory + "&text=" + myText + "&ReturnDoc=" + myForm + "&ReturnElement=" + myElement,'myname','scrollbars=yes,resizable=yes,width=350,height=270');
		}
	}
}

//--></SCRIPT>
<div align="center" class="cadre1" width="100%">
    <h1>Validation d'une correction</h1>
    <form action="<?php echo $view->URLACTION;?>" method="post" enctype="multipart/form-data" name="myform" target="_self" id="myform">
	<table width="100%" border="0">
		<tr>
			<td>
				<table width="100%" border="1" cellpadding="5" bordercolor="#333333" bgcolor="#FFFFCC">
			    	<tr bordercolor="#FFFFCC"> 
			        	<td width="38" class="label">Titre</td>
			            <td width="34">
							<div align="left"> 
								<input name="txtPropId" type="hidden" id="txtPropId" value="<?php echo $view->PROPID;?>" />
							</div>
						</td>
			            <td width="300">
							<input name="txtTitre" type="text" id="txtTitre2" value="<?php echo $view->TITRE;?>" size="40" class="<?php echo $view->CLTITRE;?>" />
						</td>
			            <td width="70"><!--DWLayoutEmptyCell-->&nbsp;</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td><!--DWLayoutEmptyCell-->&nbsp;</td>
			            <td><!--DWLayoutEmptyCell-->&nbsp;</td>
			            <td class="original"><?php echo $view->ORITITRE;?></td>
			            <td><!--DWLayoutEmptyCell-->&nbsp;</td>
			        </tr>
					<tr bordercolor="#FFFFCC"> 
			            <td class="label">Tome</td>
			            <td> </td>
			            <td>
							<div align="left"> 
								<input name="txtNumTome" type="text" id="txtNumTome2" value="<?php echo $view->TOME;?>" size="2" class="<?php echo $view->CLTOME;?>" />
				            </div>
						</td>
			            <td></td>
					</tr>
					<tr bordercolor="#FFFFCC"> 
						<td class="label">&nbsp;</td>
						<td></td>
						<td class="original"><?php echo $view->ORITOME;?></td>
						<td>&nbsp;</td>
					</tr>
					<tr bordercolor="#FFFFCC"> 
						<td colspan="4" class="label">
							<table width="100%" border="0">
				                <tr> 
					                <td width="25%">&nbsp;</td>
					                <td width="25%" align="center" class="entete">Int&eacute;grale<?php echo $view->NEW_FLG_INT;?></td>
					                <td width="25%" align="center" class="entete">Type<?php echo $view->NEW_FLG_TYPE;?></td>
					                <td width="25%">&nbsp;</td>
				                </tr>
				                <tr> 
					                <td>&nbsp;</td>
						            <td class="data" align="center">
										<input type="checkbox" name="chkIntegrale" value="checkbox" <?php echo $view->ISINT;?> />
									</td>
					                <td class="data" align="center">
										<select name="lstType" size="1">
											<?php echo $view->OPTTYPE;?>
					                    </select>
									</td>
					                <td>&nbsp;</td>
				             	</tr>
							</table>
						</td>
					</tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td colspan="4" class="label">
							Histoire
							<br />
							<br />
							<textarea name="txtHistoire" cols="50" rows="8" id="textarea" class="<?php echo $view->CLHISTOIRE;?>"><?php echo $view->HISTOIRE;?></textarea> 
				            <br />
						</td>
					</tr>
			        <tr bordercolor="#FFFFCC">
			            <td colspan="4" class="original"><?php echo $view->ORIHISTOIRE;?></td>
			        </tr>
				</table>
				<br /> 
		        <table width="100%" border="1" cellpadding="5" bordercolor="#333333" bgcolor="#FFFFCC">
			        <tr bordercolor="#FFFFCC"> 
			            <td class="label">Serie</td>
			            <td>
							<div align="left"> 
				                <input name="txtSerieId" type="text" id="txtSerieId2" value="<?php echo $view->IDSERIE;?>" size="5" class="<?php echo $view->CLIDSERIE;?>" />
				            </div>
						</td>
			            <td><input name="txtSerie" type="text" id="txtSerie3" value="<?php echo $view->SERIE;?>" size="37" class="<?php echo $view->CLSERIE;?>" /> <?php echo $view->LIENEDITNEWSERIE;?></td>
			            <td> 
							<img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('serie',document.myform.txtSerie.value,'myform','txtSerie',true)" alt="Loupe" />
						</td>
					</tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td><!--DWLayoutEmptyCell-->&nbsp;</td>
			            <td><!--DWLayoutEmptyCell-->&nbsp;</td>
			            <td class="original"><?php echo $view->ORISERIE;?></td>
			            <td><!--DWLayoutEmptyCell-->&nbsp;</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td width="10%" class="label">Genre</td>
			            <td width="8%">
							<div align="center"> 
				                <input name="txtGenreId" id="txtGenreId" type="text" value="<?php echo $view->IDGENRE;?>" size="3" class="<?php echo $view->CLIDGENRE;?>" />
				            </div>
						</td>
			            <td width="66%">
							<input name="txtGenre" id="txtGenre" type="text" value="<?php echo $view->GENRE;?>" size="30"class="<?php echo $view->CLGENRE;?>" />
						</td>
			            <td width="16%">
							<img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('genre',document.myform.txtGenre.value,'myform','txtGenre',false)" alt="Loupe" />
						</td>
					</tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td>&nbsp;</td>
			            <td>&nbsp;</td>
			            <td class="original"><?php echo $view->ORIGENRE;?></td>
			            <td>&nbsp;</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td class="label">Status</td>
			            <td>
							<div align="center"> </div>
						</td>
			            <td>
							<select name="lstStatus" size="1" >
								<?php echo $view->OPTSTATUS;?>
				            </select>
				            <?php echo $view->NEW_FLG_FINI;?>
						</td>
			            <td>&nbsp; </td>
					</tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td>&nbsp;</td>
			            <td>&nbsp;</td>
			            <td class="original"><?php echo $view->ORISERIEFINI;?></td>
			            <td>&nbsp;</td>
			        </tr>
		        </table>
		        <br /> 
		        <table width="100%" border="1" cellpadding="5" bordercolor="#666666" bgcolor="#FFFFCC">
			        <tr bordercolor="#FFFFCC"> 
			            <td width="18%" class="label">Scenariste</td>
			            <td width="10%">
							<input name="txtScenarId" id="txtScenarId" type="text" value="<?php echo $view->IDSCEN;?>" size="4" class="<?php echo $view->CLIDSCEN;?>" />
						</td>
			            <td width="59%">
							<input name="txtScenar" id="txtScenar"  type="text" value="<?php echo $view->SCENARISTE;?>" size="33"class="<?php echo $view->CLSCENARISTE;?>" />
						</td>
			            <td width="13%">
							<img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('auteur',document.myform.txtScenar.value,'myform','txtScenar',true)" alt="Loupe" />
						</td>
					</tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td>&nbsp;</td>
			            <td>&nbsp;</td>
			            <td class="original"><?php echo $view->ORISCENARISTE;?></td>
			            <td>&nbsp;</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td class="label">Scenariste #2</td>
			            <td>
							<input name="txtScenarAltId" id="txtScenarAltId" type="text" value="<?php echo $view->IDSCENALT;?>" size="4" class="<?php echo $view->CLIDSCENALT;?>" />
						</td>
			            <td>
							<input name="txtScenarAlt" id="txtScenarAlt" type="text" value="<?php echo $view->SCENARISTEALT;?>" size="33"class="<?php echo $view->CLSCENARISTEALT;?>" />
						</td>
			            <td>
							<img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('auteur',document.myform.txtScenarAlt.value,'myform','txtScenarAlt',true)" alt="Loupe" />
						</td>
					</tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td>&nbsp;</td>
			            <td>&nbsp;</td>
			            <td class="original"><?php echo $view->ORISCENARISTEALT;?></td>
			            <td>&nbsp;</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td class="label">Dessinateur</td>
			            <td>
							<input name="txtDessiId" id="txtDessiId" type="text" value="<?php echo $view->IDDESS;?>" size="4" class="<?php echo $view->CLIDDESS;?>" />
						</td>
			            <td>
							<input name="txtDessi" id="txtDessi" type="text" value="<?php echo $view->DESSINATEUR;?>" size="33" class="<?php echo $view->CLDESSINATEUR;?>" />
						</td>
			            <td>
							<img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('auteur',document.myform.txtDessi.value,'myform','txtDessi',true)" alt="Loupe" />
						</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td>&nbsp;</td>
			            <td>&nbsp;</td>
			            <td class="original"><?php echo $view->ORIDESSINATEUR;?></td>
			            <td>&nbsp;</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td class="label">Dessinateur #2</td>
			            <td>
							<input name="txtDessiAltId" id="txtDessiAltId"  type="text" value="<?php echo $view->IDDESSALT;?>" size="4" class="<?php echo $view->CLIDDESSALT;?>" />
						</td>
			            <td>
							<input name="txtDessiAlt" id="txtDessiAlt" type="text" value="<?php echo $view->DESSINATEURALT;?>" size="33" class="<?php echo $view->CLDESSINATEURALT;?>" />
						</td>
			            <td>
							<img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('auteur',document.myform.txtDessiAlt.value,'myform','txtDessiAlt',true)" alt="Loupe" />
						</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td>&nbsp;</td>
			            <td>&nbsp;</td>
			            <td class="original"><?php echo $view->ORIDESSINATEURALT;?></td>
			            <td>&nbsp;</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td class="label">Coloriste</td>
			            <td>
							<input name="txtColorId" id="txtColorId" type="text" value="<?php echo $view->IDCOLOR;?>" size="4" class="<?php echo $view->CLIDCOLOR;?>" />
						</td>
			            <td>
							<input name="txtColor"  id="txtColor" type="text" value="<?php echo $view->COLORISTE;?>" size="33" class="<?php echo $view->CLCOLORISTE;?>" />
						</td>
			            <td>
							<img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('auteur',document.myform.txtColor.value,'myform','txtColor',true)" alt="Loupe" />
						</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td>&nbsp;</td>
			            <td>&nbsp;</td>
			            <td class="original"><?php echo $view->ORICOLORISTE;?></td>
			            <td>&nbsp;</td>
			        </tr>
				</table>
		        <p> 
			        <div align="center"> 
				        <p></p>
				        <input type="submit" name="Submit" value="<?php echo $view->ACTIONNAME;?>" />
				        <br />
			        </div>
			</td>
		    <td valign="top">
				<table width="100%" border="1" cellpadding="5" bordercolor="#333333" bgcolor="#FFFFCC">
					<tr bordercolor="#FFFFCC"> 
						<td class="label">
							<?php echo $view->USEROWN;?>
							<br />
				            <?php echo $view->USERHASEDITION;?>
							<br />
				            <input name="txtDefEdition" type="hidden" id="txtDefEdition" value="<?php echo $view->DEFEDITIONID;?>" />
				            <?php echo $view->MODIFONDEFAULT;?>
						</td>
					</tr>
				</table>
				<br />
		        <table width="100%" border="1" cellpadding="5" bordercolor="#666666" bgcolor="#FFFFCC">
			        <tr bordercolor="#FFFFCC"> 
			            <td width="21%" class="label">Editeur</td>
			            <td width="9%">
							<input name="txtEditeurId"  id="txtEditeurId" type="text" value="<?php echo $view->IDEDIT;?>" size="3" class="<?php echo $view->CLIDEDIT;?>" />
						</td>
			            <td width="58%">
							<input name="txtEditeur" id="txtEditeur" type="text" value="<?php echo $view->EDITEUR;?>" size="33"class="<?php echo $view->CLEDITEUR;?>" />
						</td>
			            <td width="12%">
							<img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('editeur',document.myform.txtEditeur.value,'myform','txtEditeur',true)" alt="Loupe" />
						</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td>&nbsp;</td>
			            <td>&nbsp;</td>
			            <td class="original"><?php echo $view->ORIEDITEUR;?></td>
			            <td>&nbsp;</td>
					</tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td class="label">Collection</td>
			            <td> 
							<input name="txtCollecId" id="txtCollecId" type="text" value="<?php echo $view->IDCOLLEC;?>" size="3" class="<?php echo $view->CLIDCOLLEC;?>" />
						</td>
			            <td>
							<input name="txtCollec" id="txtCollec" type="text" value="<?php echo $view->COLLECTION;?>" size="33" class="<?php echo $view->CLCOLLECTION;?>" />
						</td>
					    <td>
							<img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('collection',document.myform.txtCollec.value,'myform','txtCollec',false,document.myform.txtEditeurId.value)" alt="Loupe" />
						</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td>&nbsp;</td>
			            <td>&nbsp;</td>
			            <td class="original"><?php echo $view->ORICOLLECTION;?></td>
			            <td>&nbsp;</td>
			        </tr>	
					<tr bordercolor="#FFFFCC"> 
			            <td colspan="4" class="label">
							<table width="100%" border="0">
				                <tr> 
				                	<td align="center"><a href="<?php echo $view->URLEAN;?>" title="Teste le code EAN sur BDNet" target="_blank">EAN</a> : 
				                	<input name="txtEAN" type="text" value="<?php echo $view->EAN;?>" size="14" class="<?php echo $view->CLEAN;?>" /><?php echo $view->ISEAN;?></td>
				                	<td align="center"><a href="<?php echo $view->URLISBN;?>" title="Teste le code ISBN sur Amazon" target="_blank">ISBN</a> : 
				                    <input name="txtISBN" type="text" value="<?php echo $view->ISBN;?>" size="10" class="<?php echo $view->CLISBN;?>" /><?php echo $view->ISISBN;?></td>
				                </tr>
						<tr>
                                                    <td class="original" align="center"><?php echo $view->ORIEAN;?></td>
                                                    <td class="original" align="center"><?php echo $view->ORIISBN;?></td>
                                                </tr>
			            	</table>
						</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td class="label">Date de parution</td>
			            <td>&nbsp; </td>
			            <td>
							<input name="txtDateParution" type="text" id="txtDateParution" value="<?php echo $view->DTPAR;?>" size="15" class="<?php echo $view->CLDTPAR;?>" />
						</td>
			            <td>&nbsp;</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td class="label">&nbsp;</td>
			            <td>&nbsp;</td>
			            <td class="original"><?php echo $view->ORIDTPAR;?></td>
			            <td>&nbsp;</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td colspan="4" class="label">
							Ignorer les modifications relatives &agrave; l'&eacute;dition 
				            <input type="checkbox" name="chkModifEdition" value="checked" />
						</td>
			        </tr>
				</table>
				<br />
				<table width="100%" border="1" cellpadding="5" bordercolor="#666666" bgcolor="#FFFFCC">
			        <tr> 
			            <td width="50%" align="center" bordercolor="#FFFFCC" bgcolor="#FFFFCC">
							<img src="<?php echo $view->URLIMAGE;?>" width="180" border="0" align="absmiddle" alt="Couverture" />
							<br />
							<?php echo $view->DIMIMAGE;?>
						</td>
			            <td width="50%" align="center" bordercolor="#FFFFCC" bgcolor="#FFFFCC" class="original">
							<img src="<?php echo $view->URLORIIMAGE;?>" width="180" border="0" align="absmiddle" alt="Couverture originale" />
							<br />
							<?php echo $view->ORIDIMIMAGE;?>
						</td>
			        </tr>
			        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
			            <td colspan="2" class="label">
							Ignorer le changement de couverture (les dimensions de l'image de gauche n'apparaissent pas si l'utilisateur ne propose pas de nouvelle couverture)
							<input type="checkbox" name="chkDelete" value="checked" />
				        </td>
	        		</tr>
	        		<tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
			            <td class="label">Redimensionner la couverture</td>
			            <td><input type="checkbox" name="chkResize" value="checked"></td>
		            </tr>
				</table>
				<br />
				<table width="100%" border="1" cellpadding="5" bordercolor="#333333" bgcolor="#FFFFCC">
					<tr bordercolor="#FFFFCC"> 
						<td class="label">Commentaire de l'utilisateur :</td>
					</tr>
					<tr bordercolor="#FFFFCC"> 
						<td class="label"><?php echo $view->USERCOMMENT;?></td>
					</tr>
				</table>
				<br />
				<table width="100%" border="1" bordercolor="#333333" bgcolor="#FFFFCC">
					<tr bordercolor="#FFFFCC">
						<td>
							<p class="texte">
								Contact
								<br />
					            <a href="mailto:<?php echo $view->ADRESSEMAIL;?>?subject=<?php echo $view->MAILSUBJECT;?>" style="font-weight: bold;">
									Envoyer un email à <?php echo $view->MEMBRE;?>
								</a>
								(<?php echo $view->ADRESSEMAIL;?>)
							</p>
						</td>
					</tr>
				</table>
				<br /> 
		        <table width="100%" border="1" cellpadding="5" bordercolor="#333333" bgcolor="#FFFFCC">
			        <tr bordercolor="#FFFFCC"> 
			            <td width="18%" class="label">
							En rouge <div align="center"> </div>
						</td>
			            <td width="82%" class="texte">
							Incoh&eacute;rence entre l'ID et la valeur saisie
						</td>
			        </tr>
			        <tr bordercolor="#FFFFCC"> 
			            <td class="label">En orange</td>
			            <td class="texte">Champ modifi&eacute; par l'utilisateur</td>
			        </tr>
			        <tr bordercolor="#FFFFCC">
			            <td class="label">En gris</td>
			            <td class="texte">Information actuellement dans la base</td>
			        </tr>
				</table>
			</td>
		</tr>
	</table>
</form>
<table width="635">
    <tr align="center">
    	<td width="100">
    		<?php echo $view->BOUTONPRECEDENT;?>
    	</td>
    	<td width="435">
   			&nbsp;
		</td>
		<td width="100">
    		<?php echo $view->BOUTONSUIVANT;?>
    	</td>
	</tr>
	<tr align="center">
		<td width="100">
    		&nbsp;
    	</td>
    	<td width="435">
   			<form action="<?php echo $view->URLDELETE;?>" method="post">
                            <input type="hidden" name="ID" id="ID" value="<?php echo $view->PROPID; ?>">
                            <input type="submit" value="Supprimer">
			</form>
		</td>
		<td width="100">
    		&nbsp;
    	</td>
	</tr>
</table>
</div>
<script src="<?php echo BDO_URL;?>script/genautocomplete.js" type="text/javascript"></script>
<script>
    /*
     * On remplit les champs de saisie par l'autocompletion
     * 
     */
    
    addAutocomplete("txtSerie3","txtSerieId2","txtSerieId2","<?php echo BDO_URL; ?>getjson?data=Serie");
    addAutocomplete("txtGenre","txtGenreId","txtGenreId","<?php echo BDO_URL; ?>getjson?data=Genre");
    addAutocomplete("txtScenar","txtScenarId","txtScenarId","<?php echo BDO_URL; ?>getjson?data=Auteur");
    addAutocomplete("txtScenarAlt","txtScenarAltId","txtScenarAltId","<?php echo BDO_URL; ?>getjson?data=Auteur");
    addAutocomplete("txtDessiAlt","txtDessiAltId","txtDessiAltId","<?php echo BDO_URL; ?>getjson?data=Auteur");
    addAutocomplete("txtDessi","txtDessiId","txtDessiId","<?php echo BDO_URL; ?>getjson?data=Auteur");
    
     addAutocomplete("txtColor","txtColorId","txtColorId","<?php echo BDO_URL; ?>getjson?data=Auteur");
     addAutocomplete("txtColorAlt","txtColorAltId","txtColorAltId","<?php echo BDO_URL; ?>getjson?data=Auteur");
     addAutocomplete("txtEditeur","txtEditeurId","txtEditeurId","<?php echo BDO_URL; ?>getjson?data=Editeur");
     
     addAutocomplete("txtExistingTome","txtExistingTomeId","txtExistingTomeId","<?php echo BDO_URL; ?>getjson?data=Album");
     
     addAutocomplete("txtFutAlb","txtFutAlbId","txtFutAlbId","<?php echo BDO_URL; ?>getjson?data=Album");
     changeEditeur();
    function changeEditeur() {
        addAutocomplete("txtCollec","spCollec","txtCollecId","<?php echo BDO_URL; ?>getjson?data=Collection&id_editeur="+$("#txtEditeurId").val());
    
        //addSelectOption("txtCollec","<?php echo BDO_URL; ?>getjson?data=Collection&id_editeur="+$("#txtEditeurId").val(),<?php echo $view->IDCOLLEC;?>);
    
    }
</script>