<script src="<?php echo BDO_URL;?>jquery/jquery.mask.min" type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>script/genautocomplete.js" type="text/javascript"></script>
<form action="<?php echo $view->URLACTION;?>" method="post" enctype="multipart/form-data" name="myform" target="_self" id="myform">
    <input name="txtFlgDef" type="hidden" value="<?php echo $view->FLGDEF;?>" />
    <input name="txtEditionId" type="hidden" value="<?php echo $view->IDEDITION;?>" />
    <table class="fond_admin">
        <tr>
            <td valign="top" width="60%">
                <table class="tableaux_admin">
                    <!--DWLayoutTable-->
                    <tr bordercolor="#FFFFCC">
                        <td width="10%" class="label">
                            <div align="center">
                                Album
                            </div>
                        </td>
                        <td width="10%">
                            <div align="left">
                                <input name="txtTomeId" type="text" id="txtTomeId" value="<?php echo $view->IDTOME;?>" size="5" class="champ_form_desactive" />
                            </div>
                        </td>
                        <td colspan="2" width="80%">
                            <input name="txtTome" type="text" id="txtTome" value="<?php echo $view->TITRE;?>" class="champ_form_desactive" style="width: 100%;" />
                        </td>
                    </tr>
                </table>

                <div class="submit">
                    <input type="submit" name="Submit" value="<?php echo $view->ACTIONNAME;?>" />
                </div>
                            <table class="tableaux_admin">
    <tr>
        <td width="16%" class="label"><div align="center">Editeur</div></td>
        <td width="12%"><input name="txtEditeurId" id="txtEditeurId" type="text" value="<?php echo $view->IDEDIT;?>" size="5" /></td>
        <td width="58%"><input name="txtEditeur" id="txtEditeur" type="text" value="<?php echo $view->EDITEUR;?>" size="30" onchange="changeEditeur();"/></td>
        <td width="14%">
            <a href="<?php echo $view->URLEDITEDIT;?>" class="fancybox fancybox.iframe {width:600,height:300}"><img src="<?php echo BDO_URL_IMAGE;?>edit.gif" width="18" height="13" border="0" /></a>

        </td>
    </tr>
    <tr>
        <td class="label"><div align="center">Collection</div></td>
        <td><input name="txtCollecId" id="txtCollecId" type="text" value="<?php echo $view->IDCOLLEC;?>" size="5" /></td>
        <td><input name="txtCollec" id="txtCollec" type="text" value="<?php echo $view->COLLECTION;?>" size="30" /></td>
        <td>
            <a href="<?php echo $view->URLEDITCOLL;?>" class="fancybox fancybox.iframe {width:600,height:300}"><img src="<?php echo BDO_URL_IMAGE;?>edit.gif" width="18" height="13" border="0" /></a>

        </td>
    </tr>
    <tr>
        <td colspan="4" class="label">
            <table class="tableaux_admin_sans-bord">
                <tr>
                    <td align="center">
                        ISBN-13 (EAN) :
                        <input name="txtEAN" type="text" value="<?php echo $view->EAN;?>" size="14" />
                    </td>
                    <td align="center">
                        ISBN-10 :
                        <input name="txtISBN" type="text" value="<?php echo $view->ISBN;?>" size="10" />
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="4" class="label">
            <table class="tableaux_admin_sans-bord">
                <tr>
                    <td width="22%" align="center" title="si 0000-00-00 apparaît, cela signifie que le membre a mal saisi la date">
                        Date Parution
                        <div class="petite_police" style="margin-bottom: 10px;">(aaaa-mm-jj)</div>
                        <input name="txtDateParution" type="text" id="txtDateParution" value="<?php echo $view->DTPAR;?>" size="10" class="<?php echo $view->PARUTION_0;?>" />
                        <br />
                        <label for="FLAG_DTE_PARUTION">Introuvable <input name="FLAG_DTE_PARUTION" type="checkbox" id="FLAG_DTE_PARUTION" value="1" <?php echo $view->CHKFLAG_DTE_PARUTION;?> /></label>
                    </td>
                    <td width="1%" align="center"></td>
                    <td width="8%" align="center">
                        <div>Tirage de t&ecirc;te</div>
                        <input type="checkbox" name="chkTT" value="checkbox" <?php echo $view->ISTT;?> />
                    </td>
                    <td width="1%" align="center"></td>
                    <td width="68%" align="center">
                        Description de l'édition<br />
                        <textarea name="txtComment" class="textarea_description_edition"><?php echo $view->COMMENT;?></textarea>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
            </td>

            <!-- colonne de droite -->
            <td valign="top" width="40%">
                <table class="tableaux_admin">
    <tr>
        <td align="center">
            <img src="<?php echo $view->URLIMAGE;?>" width="180" border="0" align="absmiddle" />
            <br />
            <?php echo $view->DIMIMAGE;?>
        </td>
    </tr>
    <tr>
        <td class="label">
            Redimensionner la couverture :
            <input type="checkbox" name="chkResize" value="checked" />
        </td>
    </tr>
    <tr>
        <td class="label">
            Envoyer depuis un fichier local :
            <br /><input name="txtFileLoc" type="file" id="txtFileLoc" style="width: 100%;" />
        </td>
    </tr>
    <tr>
        <td class="label">
            Envoyer depuis une URL :
            <br /><input name="txtFileURL" type="text" id="txtFileURL" style="width: 100%;" />
        </td>
    </tr>
</table>

            </td>
        </tr>
    </table>
        <table class="cadre_texte-admin">
                    <tr>
                        <td>
                            <p class="b">Statistiques</p>
                            <p><?php echo $view->NBUSERS;?> utilisateur(s) ont cette edition dans leur collection <?php echo $view->VIEWUSEREDITION;?></p>
                            <p class="b">Menu Express</p>
                            <p>
                                <?php echo $view->ACTIONAUTORIZE;?> <?php echo $view->CONTACTUSER;?>
                                <ul>
                                    <a href="<?php echo $view->URLFUSIONEDITION;?>"><li>Fusionner cette édition</li></a>
                                    <a href="<?php echo $view->URLDELETE;?>"><li>Supprimer cette edition</li></a>
                                    <a href="#" onclick="javascript:window.open('addauteur','myauteur','scrollbars=no,resizable=yes,width=400,height=150');return(false)"></a>
                                </ul>
                            </p>
                        </td>
                    </tr>
                </table>
</form>
<script>
    /*
     * On remplit les champs de saisie par l'autocompletion
     *
     */


     addAutocomplete("txtEditeur","txtEditeurId","txtEditeurId","<?php echo BDO_URL; ?>getjson?data=Editeur");

     changeEditeur();
    function changeEditeur() {
        //addSelectOption("txtCollec","<?php echo BDO_URL; ?>getjson?data=Collection&id_editeur="+$("#txtEditeurId").val(),<?php echo $view->IDCOLLEC + 0;?>);
    addAutocomplete("txtCollec","spCollec","txtCollecId","<?php echo BDO_URL; ?>getjson?data=Collection&id_editeur="+$("#txtEditeurId").val());
    }
    $(document).ready(function(){
  $('#txtDateParution').mask('0000-00-00', {placeholder: "0000-00-00"});
});
</script>