<SCRIPT type="text/javascript"><!--
function valider(){
    // si la valeur du champ Série est non vide
    if((document.forms['input_form'].elements['txtSerie'].value != "") && (document.forms['input_form'].elements['txtGenreId'].value != "")) {
        // les données sont ok, on peut envoyer le formulaire    
        return true;
    }else {
        // sinon on affiche un message
        alert("Saisissez les champs requis");
        // et on indique de ne pas envoyer le formulaire
        return false;
    } 
}
//--></SCRIPT>
<script src="<?php echo BDO_URL; ?>jquery/jQuery-TE_v.1.4.0/jquery-te-1.4.0.min.js" type="text/javascript"></script>
<script src="<?php echo BDO_URL;?>script/genautocomplete.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="<?php echo BDO_URL;?>jquery/jQuery-TE_v.1.4.0/jquery-te-1.4.0.css" />
<form action="<?php echo $view->URLACTION; ?>" method="post" name="input_form" onSubmit="return valider();">
    <table class="tableaux_admin">
                    <tr class="petite_police" align="center"> 
                        <td>&nbsp;</td>
                        <td>#id-BDo</td>
                        <td>titre</td>
                        <td>&nbsp;</td>
                        <td>ser</td>
                    </tr>
                    <tr align="center"> 
                        <td width="13%" height="27">Série</td>
                        <td width="9%"><input name="txtSerieId" type="text" value="<?php echo $view->IDSERIE; ?>" size="3" class="<?php echo $view->CHAMPFORMSTYLE_NEWFSERIE; ?>" /></td>
                        <td width="60%"><input name="txtSerie" type="text" value="<?php echo $view->SERIE; ?>" style="width: 100%" class="<?php echo $view->CHAMPFORMSTYLE_NEWFSERIE; ?>" /></td>
                        <td width="12%">
                            <a href="<?php echo $view->URLEDITSERIE; ?>"><img src="<?php echo BDO_URL_IMAGE; ?>edit.gif" width="18" height="13" border="0" /></a> 
                            <img src="<?php echo BDO_URL_IMAGE; ?>site/loupe.gif" width="24" height="14" onClick="newWindow('serie',document.myform.txtSerie.value,'myform','txtSerie',true)" />
                        </td>
                        <td width="9%"><input name="txtTri" type="text" id="txtTri" value="<?php echo $view->TRI; ?>" size="1" maxlength="3" class="<?php echo $view->CHAMPFORMSTYLE; ?>" /></td>
                    </tr>
                    <tr> 
                        <td height="28" align="center">Genre</td>
                        <td align="center">
                            <input name="txtGenreId" type="text" id="txtGenreId" value="<?php echo $view->IDGENRE; ?>" size="1" class="<?php echo $view->CHAMPFORMSTYLE; ?>" />
                        </td>
                        <td colspan="3">
                            <input name="txtGenre" type="text" id="txtGenre" value="<?php echo $view->GENRE; ?>" size="35" class="<?php echo $view->CHAMPFORMSTYLE; ?>" />
                            <a href="<?php echo $view->URLEDITGENRE; ?>"><img src="<?php echo BDO_URL_IMAGE; ?>edit.gif" width="18" height="13" border="0" /></a> 
                            
                        </td>
                    </tr>
                    <tr> 
                        <td align="center">Statut</td>
                        <td colspan="4"><select name="chkFini" size="1" class="<?php echo $view->CHAMPFORMSTYLE; ?>"><?php echo $view->OPTSTATUS; ?></select></td>
                    </tr>
                    <tr> 
                        <td align="center">Nb final</td>
                        <td colspan="4"><input name="txtNbTome" type="text" id="txtNbTome" value="<?php echo $view->NBTOME; ?>" size="2" class="<?php echo $view->CHAMPFORMSTYLE; ?>" style="text-align: center;" /> tomes</td>
                    </tr>
                    <tr> 
                        <td>Intro Série</td>
                        <td colspan="4"><textarea name="txtSerieHist" id="txtSerieHist" class="<?php echo $view->CHAMPFORMSTYLE; ?>champ_commentaire"><?php echo nl2br($view->HISTOIRE_SERIE); ?></textarea></td>
                    </tr>
                </table>
    <div class="submit"> 
                    <input type="submit" name="Submit" value="<?php echo $view->ACTIONNAME; ?>" />
                </div>
 <div class="b">Menu Express</div>
                <p>
                <ul>
                     <p>
                    <?php echo $view->WARNING_NOTE; ?>
                    <a href="<?php echo $view->URLDELETE; ?>">Supprimer cette s&eacute;rie</a><br />
                    Fusionner cette s&eacute;rie
                </p>
                    <a href="<?php echo $view->URLMASSDETAIL; ?>"><li>Affichage rapide des albums</li></a>
                    <a href="<?php echo $view->URLMASSUPDATE; ?>"><li>Mise à jour multiples</li></a>
                    <a href="<?php echo $view->URLMASSRENAME; ?>"><li>Renommer les albums de la série</li></a>
                    <a href="<?php echo $view->URLMASSCOUV; ?>"><li>Controler les couvertures de cette série</li></a>
                </ul>
                </p>
    
                <div class="b"><?php echo $view->NBALBUMS; ?> albums dans la s&eacute;rie :</div>
                <!-- BEGIN AlbBlock -->
                <?php if (issetNotEmpty($view->dbs_tome)) { 
                    foreach ($view->dbs_tome->a_dataQuery as $tome) { ?> 
                <a href="editalbum?alb_id=<?php echo $tome->ID_TOME; ?>" target="_blank"><?php echo $tome->TITRE_TOME; ?></a> - &nbsp;
                <?php }} ?>
                <!-- END AlbBlock -->
                <p><div class="b"><a href="<?php echo $view->URLAJOUTALB; ?>" target="_parent">Ajouter un album dans la série</a></div></p>
          
               
                <p>
                    <?php echo $view->NBAUTEURS; ?> auteurs ont travaill&eacute; sur la s&eacute;rie : 
                    <br />
                    <!-- BEGIN AutBlock -->
                    <?php if (issetNotEmpty($view->dbs_auteur)) { foreach ($view->dbs_auteur as $auteur) { ?>
                    <a href="editauteur?auteur_id=<?php echo $auteur->ID_AUTEUR; ?>"><?php echo $auteur->PSEUDO; ?></a> - 
                    <?php }} ?>
                    <!-- END AutBlock -->
                </p>
                <p>&nbsp;</p>
            
</form>

<script>
    /*
     * On remplit les champs de saisie par l'autocompletion
     * 
     */
    
   
  addAutocomplete("txtGenre","txtGenreId","txtGenreId","<?php echo BDO_URL; ?>getjson?data=Genre");
</script>
<script>$("#txtSerieHist").jqte(); </script>
