<script src="<?php echo BDO_URL; ?>jquery/jQuery-TE_v.1.4.0/jquery-te-1.4.0.min.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="<?php echo BDO_URL;?>jquery/jQuery-TE_v.1.4.0/jquery-te-1.4.0.css" />
<script type="text/javascript">
function valider(){
  // si la valeur du champ prenom est non vide
  if(document.forms['input_form'].elements['txtPseudoAuteur'].value != "") {
    // les données sont ok, on peut envoyer le formulaire
    return true;
  }
  else {
    // renseigner alors nom et prenom
    if (document.forms['input_form'].elements['txtNomAuteur'].value != "" &&
            document.forms['input_form'].elements['txtPrenomAuteur'].value != "" ) {
            // sinon on affiche un message
            return true;
    }
    else {
        alert("Si l'auteur signe sous un pseudonyme, vous devez le saisir, dans le cas contraire saisissez nom et prénom !");
        // et on indique de ne pas envoyer le formulaire
         return false;
    }
  }
}
</script>

<form action="<?php echo $view->URLACTION;?>" method="post" name="input_form" enctype="multipart/form-data" onSubmit="return valider()">

    <table width="100%" border="1" bgcolor="#FFFFCC">
          <tr bordercolor="#FFFFCC">
            <td width="25%" height="27">Pseudo</td>
            <td colspan="4"><input name="txtIdAuteur" type="hidden" value="<?php echo $view->IDAUTEUR;?>">
              <input name="txtPseudoAuteur" type="text" id="txtPseudoAuteur" value="<?php echo $view->PSEUDO;?>" size="38"></td>
          </tr>
          <tr bordercolor="#FFFFCC">
            <td height="28">Nom - Pr&eacute;nom</td>
            <td colspan="4">
              <input name="txtNomAuteur" type="text" id="txtNomAuteur" value="<?php echo $view->NOM;?>" size="20">
              ,
              <input name="txtPrenomAuteur" type="text" id="txtPrenomAuteur" value="<?php echo $view->PRENOM;?>" size="20"></td>
          </tr>
          <tr>
              <td height="28">
                  Image :
              </td>
              <td colspan="4">
                  <img src="<?php echo BDO_URL_IMAGE."auteur/". $view->IMG_AUT; ?>" class="couvBig" id="imgAut">
                <br /> Envoyer depuis un fichier local :
                <br /><input name="txtFileLoc" type="file" id="txtFileLoc" style="width: 100%;" />
                <br>
                 Envoyer depuis une URL :
            <br /><input name="txtFileURL" type="text" id="txtFileURL" style="width: 100%;" />
              </td>

          </tr>
          <tr bordercolor="#FFFFCC">
            <td height="28">Date Naissance</td>
            <td colspan="4"><input name="txtDateNaiss" type="text" id="txtDateNaiss" value="<?php echo $view->DTNAIS;?>" size="10"></td>
          </tr>
          <tr bordercolor="#FFFFCC">
            <td height="28">Date d&eacute;c&egrave;s</td>
            <td colspan="4"><input name="txtDateDeces" type="text" id="txtDateDeces" value="<?php echo $view->DTDECES;?>" size="10"></td>
          </tr>
          <tr bordercolor="#FFFFCC">
            <td height="28">Nationalite</td>
            <td colspan="4"><input name="txtNation" type="text" id="txtNation" value="<?php echo $view->DTNATION;?>" size="15"></td>
          </tr>
          <tr bordercolor="#FFFFCC">
            <td height="28">&nbsp;</td>
            <td width="12%"> <div align="center">Sc&eacute;nariste</div></td>
            <td width="16%"> <div align="center">Dessinateur</div></td>
            <td width="13%"> <div align="center">Coloriste</div></td>
            <td width="34%">&nbsp;</td>
          </tr>
          <tr bordercolor="#FFFFCC">
            <td height="28">&nbsp;</td>
            <td> <div align="center">
                <input name="chkScen" type="checkbox" id="chkScen" value="checked" <?php echo $view->ISSCENAR;?>>
              </div></td>
            <td> <div align="center">
                <input name="chkDess" type="checkbox" id="chkDess" value="checked" <?php echo $view->ISDESSIN;?>>
              </div></td>
            <td> <div align="center">
                <input name="chkColor" type="checkbox" id="chkColor" value="checked" <?php echo $view->ISCOLOR;?>>
              </div></td>
            <td>&nbsp;</td>
          </tr>
          <tr bordercolor="#FFFFCC">
            <td height="28">Biographie</td>
            <td colspan="4"><textarea name="txtCommentaire" id="txtCommentaire"cols="40" rows="20"><?php echo $view->COMMENT;?></textarea></td>
          </tr>
          <tr bordercolor="#FFFFCC">
            <td colspan="5"> <input type="submit" name="Submit" value="<?php echo $view->ACTIONNAME;?>"></td>
          </tr>
        </table>
   <p><strong>Statistiques</strong></p>
        <p>Cet auteur a travaill&eacute; sur <?php echo $view->NBALBUMS;?> albums.</p>
        <p><strong>Menu Express</strong></p>
        <p><a href="<?php echo $view->URLDELETE;?>">Supprimer cet auteur</a><br>
          <a href="<?php echo $view->URLFUSION;?>" target="_parent">Fusionner cet auteur</a></p>
        <p><strong>Aide</strong></p>
        <p>Le pseudo ne doit &ecirc;tre renseign&eacute; que si l'auteur signe
          sous un pseudonyme. Dans le cas contraire, les champs nom et pr&eacute;nom
          sont obligatoires.</p>



</form>
<script>$("#txtCommentaire").jqte();

function readURL(input) {

    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#imgAut').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$("#txtFileLoc").change(function(){
    readURL(this);
});
$("#txtFileUrl").change(function(){
    $('#imgAut').attr('src',$("#txtFileUrl").val());
});
</script>