<script type="text/javascript">
function newWindow(myCategory,myText,myForm,myElement,isMandatory,myEditeur) {
    if ((isMandatory == true) && (myText.length < 3)) {
        alert('Veuillez saisir au moins 3 caractères');
    }
    else {
        if (myCategory == "collection") {
            if (myEditeur == '') {
                alert("Veuillez saisir l'éditeur en premier");
            }
            else {
            mywindow=open("pickup?cat=" + myCategory + "&text=" + myText + "&ReturnDoc=" + myForm + "&ReturnElement=" + myElement + "&IdEditeur=" + myEditeur,'myname','scrollbars=yes,resizable=yes,width=350,height=270');
            }
        }
        else {
            mywindow=open('pickup?cat=' + myCategory + "&text=" + myText + "&ReturnDoc=" + myForm + "&ReturnElement=" + myElement,'myname','scrollbars=yes,resizable=yes,width=350,height=270');
        }
    }
}

function valider(){
  // si la valeur du champ prenom est non vide
  if((document.forms['input_form'].elements['txtNomColl'].value != "") && (document.forms['input_form'].elements['txtEditeurId'].value != "")) {
    // les données sont ok, on peut envoyer le formulaire
    return true;
  }
  else {
    // sinon on affiche un message
    alert("Saisissez les champs requis");
    // et on indique de ne pas envoyer le formulaire
    return false;
  }
}
</script>
<script src="<?php echo BDO_URL;?>script/genautocomplete.js" type="text/javascript"></script>
<form action="<?php echo $view->URLACTION;?>" method="post" name="input_form" onSubmit="return valider()">
  <table width="100%" border="1">
    <tr>
      <td width="65%" rowspan="2"><table width="100%" border="1" bgcolor="#FFFFCC">
          <tr bordercolor="#FFFFCC">
            <td width="18%" height="27">Nom</td>
            <td width="82%"><input name="txtIdColl" type="hidden" id="txtIdColl" value="<?php echo $view->IDCOLL ?? "";?>">
              <input name="txtNomColl" type="text" id="txtNomColl" value="<?php echo $view->NOM ?? "";?>" size="38"></td>
          </tr>
          <tr bordercolor="#FFFFCC">
            <td height="28">Editeur</td>
            <td> <input name="txtEditeurId" type="text" id="txtEditeurId" value="<?php echo $view->IDEDITEUR ?? "";?>" size="2">
              <input name="txtEditeur" type="text" id="txtEditeur" value="<?php echo $view->EDITEUR ?? "";?>" size="35">
              <a href="<?php echo $view->URLEDITEDIT;?>"><img src="<?php echo BDO_URL_IMAGE;?>edit.gif" width="18" height="13" border="0"></a> <img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('editeur',document.input_form.txtEditeur.value,'input_form','txtEditeur',true)"></td>
          </tr>
          <tr bordercolor="#FFFFCC">
            <td colspan="2"> <input type="submit" name="Submit" value="<?php echo $view->ACTIONNAME;?>"></td>
          </tr>
        </table></td>
    </tr>
    <tr bgcolor="#FFFFCC">
      <td> <p><strong>Statistiques</strong></p>
        <p>Nombres d'albums dans cette collection : <?php echo $view->NBCOLALB;?></p>
        <p><strong>Menu Express</strong></p>
        <p><a href="<?php echo $view->URLDELETE;?>">Supprimer cette collection</a><br>
          Fusionner cette collection</p></td>
    </tr>
  </table>


</form>
<script>
addAutocomplete("txtEditeur","txtEditeurId","txtEditeurId","<?php echo BDO_URL; ?>getjson?data=Editeur");</script>