<script src="<?php echo BDO_URL;?>script/genautocomplete.js" type="text/javascript"></script>
<SCRIPT LANGAUGE="JavaScript"><!--
function newWindow(myCategory,myText,myForm,myElement,isMandatory,myEditeur) {
	if ((isMandatory == true) && (myText.length < 3)) {
		alert('Veuillez saisir au moins 3 caractères');
	}
	else {
		if (myCategory == "collection") {
			if (myEditeur == '') {
				alert("Veuillez saisir l'éditeur en premier");
			}
			else {
			mywindow=open("pickup.php?cat=" + myCategory + "&text=" + myText + "&ReturnDoc=" + myForm + "&ReturnElement=" + myElement + "&IdEditeur=" + myEditeur,'myname','scrollbars=yes,resizable=yes,width=350,height=270');
			}
		}
		else {
			mywindow=open('pickup.php?cat=' + myCategory + "&text=" + myText + "&ReturnDoc=" + myForm + "&ReturnElement=" + myElement,'myname','scrollbars=yes,resizable=yes,width=350,height=270');
		}
	}
}

function refreshpage()
{
if (document.forms['formRefresh'].elements['txtNewTitreId'].value == "")
	{
	alert ("Saisissez un titre");
	return false;
	}else{
	document.forms['formRefresh'].action = "<?php echo $view->REFRESHPAGE;?>"+"&report_id="+document.forms['formRefresh'].elements['txtNewTitreId'].value;
	return true;
	}
}
//--></SCRIPT>
<div class="cadre1">
<table width="100%" border="1" cellpadding="10" cellspacing="10" bordercolor="#333333">
  <tr>
    <td width="66%">
	<form action="" method="post" name="formRefresh" onsubmit="return refreshpage();">
	<table width="100%" border="1" cellpadding="2" cellspacing="0" bordercolor="#333333" bgcolor="#FFFFCC">
        <!--DWLayoutTable-->
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC">
          <td colspan="5" class="label"><strong>Album sur lequel reporter les
            &eacute;ditions existantes </strong></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC">
          <td width="46" class="label"> <div align="center">Titre</div></td>
          <td width="47"> <div align="left">
                <input name="txtNewTitreId" type="text" id="txtNewTitreId" value="<?php echo $view->IDTOME2;?>" size="5">
            </div></td>
          <td width="246"> <input name="txtNewTitre" type="text" id="txtNewTitre" value="<?php echo $view->TITRE2;?>" size="40"></td>
          <td width="60"><img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('album',document.formRefresh.txtNewTitre.value,'formRefresh','txtNewTitre',true)"></td>
          <td width="145"><input type="submit" name="Refresh" value="Rafraichir">
          </tr>
      </table>
</form>
<form action="<?php echo $view->URLACTION;?>" method="post" enctype="multipart/form-data" onsubmit="return confirm('Voulez-vous vraiment continuer ?');" name="myform" target="_self" id="myform">
      <br> <table width="100%" border="1" cellpadding="1" cellspacing="0" bordercolor="#333333" bgcolor="#CCCCCC">
        <!--DWLayoutTable-->
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC">
          <td colspan="5" class="label"><strong>Album sur lequel les &eacute;ditions
            seront report&eacute;es</strong></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC">
          <td width="117" class="label"> <div align="center">Titre :</div></td>
          <td width="17"> <div align="left">
              <input name="txtTome2Id" type="hidden" id="txtTome2Id" value="<?php echo $view->IDTOME2;?>">
            </div></td>
          <td width="268"><?php echo $view->TITRE2;?></td>
          <td width="46">Tome :</td>
          <td width="96"><?php echo $view->TOME2;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC">
          <td valign="top" class="label"><div align="center">Serie :</div></td>
          <td><!--DWLayoutEmptyCell-->&nbsp;</td>
          <td colspan="3"><?php echo $view->SERIE2;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC">
          <td valign="top" class="label"><div align="center">Sc&eacute;nariste(s)
              :</div></td>
          <td><!--DWLayoutEmptyCell-->&nbsp;</td>
          <td colspan="3"><?php echo $view->SCENARISTES2;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC">
          <td valign="top" class="label"><div align="center">Dessinateur(s) :</div></td>
          <td><!--DWLayoutEmptyCell-->&nbsp;</td>
          <td colspan="3"><?php echo $view->DESSINATEURS2;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC">
          <td valign="top" class="label"><div align="center">Coloriste(s) :</div></td>
          <td><!--DWLayoutEmptyCell-->&nbsp;</td>
          <td colspan="3"><?php echo $view->COLORISTES2;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC">
          <td valign="top" class="label"><div align="center">Editeur / Collec
              :</div></td>
          <td><!--DWLayoutEmptyCell-->&nbsp;</td>
          <td colspan="3"><?php echo $view->EDCOLLEC2;?></td>
        </tr>
      </table>
	  <br>

        <table width="100%" border="1" bordercolor="#666666" bgcolor="#CCCCCC">
          <tr>
            <td> <p><strong>Editions existantes:</strong>
                <?php echo $view->NBEDITIONS2;?></p>
              <table width="100%" border="0">
                <tr>
                  <td width="28%" class="entete">Editeur</td>
                  <td width="23%" class="entete">Collection</td>
                  <td width="14%" class="entete">Dte Parution</td>
                  <td width="16%" class="entete">Couverture</td>
                </tr>
                <!-- BEGIN Edition2Block -->
                <?php if (issetNotEmpty($view->dbs_edition2)) {
                    foreach($view->dbs_edition2->a_dataQuery as $edition) {
                        $urlimage = $edition->IMG_COUV ? BDO_URL_COUV.$edition->IMG_COUV : BDO_URL_COUV."default.png" ;
                ?>
                <tr>
                  <td><?php echo $edition->NOM_EDITEUR;?></td>
                  <td><?php echo $edition->NOM_COLLECTION;?></td>
                  <td><?php echo $edition->DTE_PARUTION;?></td>
                  <td align="center"><a href="<?php echo $urlimage;?>" target="_blank"><img src="<?php echo $urlimage;?>" width="50" height="60" border="0" align="absmiddle"></a>
                  </td>
                </tr>
                <?php }} ?>
                <!-- END Edition2Block -->
              </table>
              </td>
          </tr>
        </table>

      <br> <table width="100%" border="1" cellpadding="1" cellspacing="0" bordercolor="#333333" bgcolor="#CCCCCC">
        <!--DWLayoutTable-->
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC">
          <td colspan="5" class="label"><strong>Album &agrave; supprimer</strong></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC">
          <td width="117" class="label"> <div align="center">Titre :</div></td>
          <td width="17"> <div align="left">
              <input name="txtTomeId" type="hidden" id="txtTomeId" value="<?php echo $view->IDTOME;?>">
            </div></td>
          <td width="268"><?php echo $view->TITRE;?></td>
          <td width="46">Tome :</td>
          <td width="96"><?php echo $view->TOME;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC">
          <td valign="top" class="label"> <div align="center">Serie :</div></td>
          <td><!--DWLayoutEmptyCell-->&nbsp;</td>
          <td colspan="3"><?php echo $view->SERIE;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC">
          <td valign="top" class="label"> <div align="center">Sc&eacute;nariste(s)
              :</div></td>
          <td><!--DWLayoutEmptyCell-->&nbsp;</td>
          <td colspan="3"><?php echo $view->SCENARISTES;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC">
          <td valign="top" class="label"> <div align="center">Dessinateur(s) :</div></td>
          <td><!--DWLayoutEmptyCell-->&nbsp;</td>
          <td colspan="3"><?php echo $view->DESSINATEURS;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC">
          <td valign="top" class="label"> <div align="center">Coloriste(s) :</div></td>
          <td><!--DWLayoutEmptyCell-->&nbsp;</td>
          <td colspan="3"><?php echo $view->COLORISTES;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC">
          <td valign="top" class="label"> <div align="center">Editeur / Collec
              :</div></td>
          <td><!--DWLayoutEmptyCell-->&nbsp;</td>
          <td colspan="3"><?php echo $view->EDCOLLEC;?></td>
        </tr>
      </table>
      <br>
        <table width="100%" border="1" bordercolor="#333333" bgcolor="#FFFFCC">
          <tr>
            <td bordercolor="#FFFFCC" class="label"> <p>Différentes éditions existant
                sur l'album &agrave; supprimer : <?php echo $view->NBEDITIONS;?></p>
              <p>
              <table width="100%" border="0">
                <tr>
                  <td width="10%" class="entete">Reporter</td>
                  <td width="28%" class="entete">Editeur</td>
                  <td width="23%" class="entete">Collection</td>
                  <td width="14%" class="entete">Dte Parution</td>
                  <td width="16%" class="entete">Couverture</td>
                </tr>
                <!-- BEGIN EditionBlock -->
                <?php
                foreach($view->dbs_edition->a_dataQuery as $edition) {
                        $urlimage = $edition->IMG_COUV ? BDO_URL_COUV.$edition->IMG_COUV : BDO_URL_COUV."default.png" ;
                ?>
                <tr>
                  <td class="data"><input type="checkbox" name="chkEdition[]" value="<?php echo $edition->ID_EDITION;?>" checked></td>
                  <td><?php echo $edition->NOM_EDITEUR;?></td>
                  <td><?php echo $edition->NOM_COLLECTION;?></td>
                  <td><?php echo $edition->DTE_PARUTION;?></td>
                  <td align="center"><a href="<?php echo $urlimage;?>" target="_blank"><img src="<?php echo $urlimage;?>" width="50" height="60" border="0" align="absmiddle"></a>
                   <input name="txtCouv[<?php echo $edition->ID_EDITION;?>]" type="hidden" value="<?php echo $edition->IMG_COUV;?>"></td>
                </tr>
                <?php } ?>
                <!-- END EditionBlock -->
              </table>
              </p>
              </td>
          </tr>
        </table>
        <p>
        <div align="center"></p>
          <input type="submit" name="Submit" value="<?php echo $view->ACTIONNAME;?>">
          <br>
        </div>
      </form></td></td>
    <td width="287" bordercolor="#333333" bgcolor="#FFFFCC" > <p><strong>Aide</strong></p>
      <p>Les éditions cochées seront reportées sur un album existant : les utilisateurs
        en possession des éditions cochées se retrouveront avec le nouvel album
        et l'ancienne édition. <br>
        <br>
        Les utilisateurs en possession d'une édition non cochée se retrouveront
        avec le nouvel album et avec l'édition par défaut. <br>
        <br>
        Si aucune édition n'est cochée, ce form se comporte comme le form de fusion
        normal. </p>
      <p><strong>Menu Express</strong></p>
      <p><a href="<?php echo $view->URLRETOURFICHE;?>">Retour à la fiche album</a><br>
      </p></td>
  </tr>
</table>
</div>
<script>
    addAutocomplete("txtNewTitre","txtNewTitreId","txtNewTitreId","<?php echo BDO_URL; ?>getjson?data=Album");
 </script>
