
  <script src="<?php echo BDO_URL;?>jquery/datatable/js/jquery.dataTables.min.js" type="text/javascript"></script>
<?php
    $ficheAlbum = $view->getHelper('ficheAlbum');
    $page = $view->getHelper('pagination');


?>
<div align="center" class="cadre1">
   <?php echo $page->menuAdmin(); ?>
    <h1>Tableau de bord de l'administration</h1>

    <div class="cadre1">
        <h3>Propositions en attente </h3>
        <br />
         Il y a actuellement <a href="./adminproposition?type=AJOUT"><b><?php echo $view->NBAJOUT;?> propositions d'album</b></a>, <a href="./adminproposition?type=EDITION"><b><?php echo $view->NBEDITION;?> propositions de nouvelle édition</b></a>
             et <a href="./adminproposition?type=CORRECTION"><b><?php echo $view->NBCORRECTION;?> propositions de correction</b></a>
             en cours de traitement pour l'ensemble de la communauté BDovore.
            <br />
             <br>
    </div>
    <br>

    <div class="cadre1">
        <h3>100 Dernières modifications d'albums / éditions</h3>
        <br />
        <table id="listAlbum">
            <thead>
                <th>Série</th>
                <th>Album</th>
                <th>Date de modification</th>
                <th>Correcteur</th>
            </thead>
            <tbody>
                <?php foreach ($view->dbs_tome->a_dataQuery as $tome) { ?>
                <tr>
                    <td><?php echo $ficheAlbum->urlSerie($tome) ; ?></td>
                    <td><?php echo $ficheAlbum->urlAlbum($tome,$class="albTitle"); ?></td>
                    <td><?php echo $tome->VALID_DTE; ?></td>
                    <td><?php echo $tome->VALIDATOR_USERNAME; ?></td>
                </tr>

                <?php } ?>
            </tbody>
        </table>
    </div>
     <div class="cadre1">
        <h3>Raccourcis : </h3>
        <ul>
            <li>- <a href='http://admin.bdovore.com/pma-3'>PHP My Admin</a></li>
            <li>- <a href='http://mantis.bdovore.com'>BDo'Bug</a></li>

        </ul>
        <p>PHP version : <?php echo PHP_VERSION; ?>
    </div>

</div>
<script>
$(document).ready(function() {
    $('#listAlbum').dataTable({
        "paging":   true,
        "ordering": true,
        "info":     false,
        "searching": false,
        "order": [[ 2, "desc" ]]
    } );
} );

</script>