<script src="<?php echo BDO_URL;?>script/genautocomplete.js" type="text/javascript"></script>
<script type="text/javascript">
function newWindow(myCategory,myText,myForm,myElement,isMandatory,myEditeur) {
	if ((isMandatory == true) && (myText.length < 3)) {
		alert('Veuillez saisir au moins 3 caractères');
	}
	else {
		if (myCategory == "collection") {
			if (myEditeur == '') {
				alert("Veuillez saisir l'éditeur en premier");
			}
			else {
			mywindow=open("pickup?cat=" + myCategory + "&text=" + myText + "&ReturnDoc=" + myForm + "&ReturnElement=" + myElement + "&IdEditeur=" + myEditeur,'myname','scrollbars=yes,resizable=yes,width=350,height=270');
			}
		}
		else {
			mywindow=open('pickup?cat=' + myCategory + "&text=" + myText + "&ReturnDoc=" + myForm + "&ReturnElement=" + myElement,'myname','scrollbars=yes,resizable=yes,width=350,height=270');
		}
	}
}

function valider(){
  // si la valeur du champ prenom est non vide
  if((document.forms['form1'].elements['txtTome1Id'].value != "") && (document.forms['form2'].elements['txtTome2Id'].value != "")) {
    // les données sont ok, on peut envoyer le formulaire    
    return true;
  }
  else {
    // sinon on affiche un message
    alert("Saisissez les champs requis");
    // et on indique de ne pas envoyer le formulaire
    return false;
  }
}

function urlsource(){
	document.forms['form1'].action = "<?php echo $view->URLREFRESH;?>?source_id="+document.forms['form1'].elements['txtTome1Id'].value+"&dest_id=<?php echo $view->DESTID;?>";
    //alert("Saisissez les champs requis");
	return true;
}
 
function urldest(){
	document.forms['form2'].action = "<?php echo $view->URLREFRESH;?>?source_id=<?php echo $view->SOURCEID;?>&dest_id="+document.forms['form2'].elements['txtTome2Id'].value;
    //alert("Saisissez les champs requis");
	return true;
}

</script>
<div class="cadre1">
<table width="100%" border="1">
  <tr> 
    <td colspan="2" align="center"><font color="#FF0000" face="Arial, Helvetica, sans-serif"><strong><?php echo $view->ERRORMESSAGE;?></strong></font></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td width="50%" bordercolor="#CCCCCC" bgcolor="#CCCCCC"> <p><strong>ALBUM 
        A SUPPRIMER</strong></p>
      <form name="form1" method="post" action="" onSubmit="return urlsource()">
        <input name="txtTome1Id" type="text" id="txtTome1Id" value="<?php echo $view->TOMEID1;?>" size="5">
        <input name="txtTome1" type="text" id="txtTome1" value="<?php echo $view->TITRE1;?>" size="40">
        <img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('album',document.form1.txtTome1.value,'form1','txtTome1',true)"><br>
        <input name="Submit1" type="submit" id="Submit1" value="Rafraichir">
      </form></td>
    <td width="50%"> <p><strong>ALBUM A GARDER</strong></p>
      <form name="form2" method="post" action="" onSubmit="return urldest()">
        <input name="txtTome2Id" type="text" id="txtTome2Id" value="<?php echo $view->TOMEID2;?>" size="5">
        <input name="txtTome2" type="text" id="txtTome2" value="<?php echo $view->TITRE2;?>" size="40">
        <img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('album',document.form2.txtTome2.value,'form2','txtTome2',true)"><br>
        <input name="Submit1" type="submit" id="Submit1" value="Rafraichir">
      </form></td>
  </tr>
  <tr> 
    <td valign=top><table width="100%" border="1" cellspacing="0">
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC"> 
          <td width="22%">Serie</td>
          <td width="43%"><?php echo $view->IDSERIE1;?>- <?php echo $view->SERIE1;?></td>
          <td width="35%" rowspan="12" align="center" valign="middle"><img src="<?php echo $view->URLIMAGE1;?>" width="150" height="210"></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC"> 
          <td>Tome</td>
          <td><?php echo $view->TOME1;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC"> 
          <td>Genre</td>
          <td><?php echo $view->IDGENRE1;?> - <?php echo $view->GENRE1;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC"> 
          <td>Scenariste</td>
          <td><?php echo $view->IDSCENAR1;?> - <?php echo $view->SCENAR1;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC"> 
          <td>Scenariste #2</td>
          <td><?php echo $view->IDSCENARALT1;?> - <?php echo $view->SCENARALT1;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC"> 
          <td>Dessinateur</td>
          <td><?php echo $view->IDDESS1;?> - <?php echo $view->DESS1;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC"> 
          <td>Dessinateur #2</td>
          <td><?php echo $view->IDDESSALT1;?> - <?php echo $view->DESSALT1;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC"> 
          <td>Coloriste</td>
          <td><?php echo $view->IDCOLOR1;?> - <?php echo $view->COLOR1;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC"> 
          <td>Coloriste #2</td>
          <td><?php echo $view->IDCOLORALT1;?> - <?php echo $view->COLORALT1;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC"> 
          <td>Editeur</td>
          <td><?php echo $view->IDEDIT1;?> - <?php echo $view->EDIT1;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC"> 
          <td>Collection</td>
          <td><?php echo $view->IDCOLL1;?> - <?php echo $view->COLL1;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC"> 
          <td>Date Parution</td>
          <td><?php echo $view->DTEPAR1;?></td>
        </tr>
        <tr bordercolor="#CCCCCC" bgcolor="#CCCCCC"> 
          <td>Aper&ccedil;u histoire</td>
          <td colspan="2"><?php echo $view->HISTOIRE1;?></td>
        </tr>
      </table></td>
    <td valign=top><table width="100%" border="1" cellspacing="0">
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
          <td width="22%">Serie</td>
          <td width="43%"><?php echo $view->IDSERIE2;?>- <?php echo $view->SERIE2;?></td>
          <td width="35%" rowspan="12" align="center" valign="middle"><img src="<?php echo $view->URLIMAGE2;?>" width="150" height="210"></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
          <td>Tome</td>
          <td><?php echo $view->TOME2;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
          <td>Genre</td>
          <td><?php echo $view->IDGENRE2;?> - <?php echo $view->GENRE2;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
          <td>Scenariste</td>
          <td><?php echo $view->IDSCENAR2;?> - <?php echo $view->SCENAR2;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
          <td>Scenariste #2</td>
          <td><?php echo $view->IDSCENARALT2;?> - <?php echo $view->SCENARALT2;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
          <td>Dessinateur</td>
          <td><?php echo $view->IDDESS2;?> - <?php echo $view->DESS2;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
          <td>Dessinateur #2</td>
          <td><?php echo $view->IDDESSALT2;?> - <?php echo $view->DESSALT2;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
          <td>Coloriste</td>
          <td><?php echo $view->IDCOLOR2;?> - <?php echo $view->COLOR2;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
          <td>Coloriste #2</td>
          <td><?php echo $view->IDCOLORALT2;?> - <?php echo $view->COLORALT2;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
          <td>Editeur</td>
          <td><?php echo $view->IDEDIT2;?> - <?php echo $view->EDIT2;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
          <td>Collection</td>
          <td><?php echo $view->IDCOLL2;?> - <?php echo $view->COLL2;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
          <td>Date Parution</td>
          <td><?php echo $view->DTEPAR2;?></td>
        </tr>
        <tr bordercolor="#FFFFCC" bgcolor="#FFFFCC"> 
          <td>Aper&ccedil;u histoire</td>
          <td colspan="2"><?php echo $view->HISTOIRE2;?></td>
        </tr>
      </table></td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCCC"> <p><strong>Statistiques</strong></p>
      <p><?php echo $view->NBUSERS1;?> utilisateur(s) ont cet album dans leur collection.<br>
        Il existe <?php echo $view->NBCOMMENT1;?> commentaire(s) sur cet album.</p></td>
    <td bordercolor="#FFFFCC" bgcolor="#FFFFCC"> <p><strong>Statistiques</strong></p>
      <p><?php echo $view->NBUSERS2;?> utilisateur(s) ont cet album dans leur collection.<br>
        Il existe <?php echo $view->NBCOMMENT2;?> commentaire(s) sur cet album.</p></td>
  </tr>
  <tr> 
    <td colspan="2" align="center"><p><a href="<?php echo $view->URLECHANGE;?>">Inverser la sélection</a><br>
        <a href="<?php echo $view->URLFUSION;?>" onClick="return valider()">Fusionner les deux albums</a></p></td>
  </tr>
</table>
</div>

<script>
    addAutocomplete("txtTome1","txtTome1Id","txtTome1Id","<?php echo BDO_URL; ?>getjson?data=Album");
    addAutocomplete("txtTome2","txtTome2Id","txtTome2Id","<?php echo BDO_URL; ?>getjson?data=Album");
 </script>