<?php include_once (BDO_DIR . 'inc' . DS . 'function.amazon.inc.php');?>
<script src="<?php echo BDO_URL;?>script/genautocomplete.js" type="text/javascript"></script>
<SCRIPT LANGAUGE="JavaScript"><!--
function newWindow(myCategory,myText,myForm,myElement,isMandatory,myEditeur) {
	if ((isMandatory == true) && (myText.length < 3)) {
		alert('Veuillez saisir au moins 3 caractères');
	}
	else {
		if (myCategory == "collection") {
			if (myEditeur == '') {
				alert("Veuillez saisir l'éditeur en premier");
			}
			else {
			mywindow=open("pickup?cat=" + myCategory + "&text=" + myText + "&ReturnDoc=" + myForm + "&ReturnElement=" + myElement + "&IdEditeur=" + myEditeur,'myname','scrollbars=yes,resizable=yes,width=350,height=270');
			}
		}
		else {
			mywindow=open('pickup?cat=' + myCategory + "&text=" + myText + "&ReturnDoc=" + myForm + "&ReturnElement=" + myElement,'myname','scrollbars=yes,resizable=yes,width=350,height=270');
		}
	}
}

function urlsource(){
	document.forms['form1'].action = "<?php echo $view->URLREFRESH;?>?serie="+document.forms['form1'].elements['txtSerieId'].value;
    //alert("Saisissez les champs requis");
	return true;
}

function Chargement() { 
 for (i = 0; i < document.myform.elements.length; i++) {
   if (document.myform.elements[i].name == "alb_id[]") {
     document.myform.elements[i].checked = true;
   }
 }
}
//--></SCRIPT>
 <p><strong>Menu Express</strong><br>
              <a href="<?php echo $view->URLEDITSERIE;?>">Retour à la fiche série</a><br>
            </p>
         <form name="form1" method="post" action="" onSubmit="return urlsource()">
        <table width="100%" border="1" cellpadding="5" cellspacing="0" bordercolor="#333333" bgcolor="#FFFFCC">
          <tr bordercolor="#FFFFCC"> 
            <td width="10%" class="label"> <div align="center">Serie</div></td>
            <td width="10%"> <div align="left"> 
                <input name="txtSerieId" type="text" id="txtSerieId" value="<?php echo $view->IDSERIE;?>" size="5">
              </div></td>
            <td width="27%"> <input name="txtSerie" type="text" id="txtSerie" value="<?php echo $view->SERIE;?>" size="40"></td>
            <td width="28%"><img src="<?php echo BDO_URL_IMAGE;?>site/loupe.gif" width="24" height="14" onClick="newWindow('serie',document.form1.txtSerie.value,'form1','txtSerie',true)"></td>
            <td width="51"> <input name="Submit1" type="submit" id="Submit1" value="Rafraichir"></td>
          </tr>
        </table>
      </form>
      <br> <form action="<?php echo $view->URLACTION;?>" method="post" enctype="multipart/form-data" name="myform" target="_self" id="myform">
        <table width="100%" border="1" cellpadding="5" cellspacing="0" bordercolor="#333333" bgcolor="#FFFFCC">
         <?php  
         foreach ($view->dbs_tome->a_dataQuery as $tome ) {
             if (is_null($tome->IMG_COUV) | ($tome->IMG_COUV=='')){
				$url_image = BDO_URL_COUV."default.png";
				$dimension="";
				$poids="";
			}else{
				$url_image = BDO_URL_COUV.$tome->IMG_COUV;
				$imageproperties = getimagesize(BDO_DIR_COUV.$tome->IMG_COUV);
				$imagetype = $imageproperties[2];
				$imagelargeur = $imageproperties[0];
				$imagehauteur = $imageproperties[1];
				$dimension = $imagelargeur."x".$imagehauteur;
				$poids = round(filesize(BDO_DIR_COUV.$tome->IMG_COUV)/1024,2);
				$poids .="Ko";
				$imagename = $tome->IMG_COUV;
			}
                        if ( !issetNotEmpty( $tome->ISBN_EDITION) and issetNotEmpty($tome->EAN_EDITION)) {
                            $isbn = EAN_to_ISBN($tome->EAN_EDITION);
                        } else {
                            $isbn = $tome->ISBN_EDITION;
                        }
			// Vérifie l'existence d'une couv chez amazon
			$url_page_amazon = "http://www.amazon.fr/exec/obidos/ASIN/".$isbn;
			$url_img_amazon = get_couv_url($url_page_amazon,$isbn);
			if ($url_img_amazon == "") $url_img_amazon = BDO_URL_COUV."default.png";
         
         ?>
          <tr bordercolor="#999999"> 
            <td colspan="3" align="center"><?php echo $tome->NUM_TOME;?> - <?php echo $tome->TITRE_TOME;?></td>
          </tr>
          <tr bordercolor="#999999"> 
            <td width="43%" align="center"><img src="<?php echo $url_image;?>" width="111"><input type="hidden" name="url_bdo[<?php echo $tome->ID_TOME;?>]" value="<?php echo $imagename;?>"><br>
              <?php echo $dimension;?><br>
              <?php echo $poids;?></td>
            <td width="14%" align="center"><input type="checkbox" name="alb_id[]" value="<?php echo $tome->ID_TOME;?>"> 
              <input name="num_tome[<?php echo $tome->ID_TOME;?>]" type="hidden" value="<?php echo $tome->NUM_TOME;?>"></td>
            <td width="43%" align="center"><p><img src="<?php echo $url_img_amazon;?>" width="111" > 
                <input type="hidden" name="url_amz[<?php echo $tome->ID_TOME;?>]" value="<?php echo $url_img_amazon;?>">
              </p>
              <p><a href="<?php echo $url_page_amazon;?>">Voir sur Amazon</a></p></td>
          </tr>
          <!-- END AlbumsBlock -->
         <?php } ?>
          <tr bordercolor="#FFFFCC"> 
            <td colspan="3" align="center"><a name="ici" href="#ici" onClick="Chargement();">Tout 
              selectionner</a></td>
          </tr>
        </table>
        <br>
        <p> 
        <div align="center"></p> 
          <input type="submit" name="Submit" value="<?php echo $view->ACTIONNAME;?>">
          <br>
        </div>
      </form></td>
    <!-- Debut colonne Gauche-->
   
      </table>
      <script>
    /*
     * On remplit les champs de saisie par l'autocompletion
     * 
     */
    
   
  addAutocomplete("txtSerie","txtSerieId","txtSerieId","<?php echo BDO_URL; ?>getjson?data=Serie");
</script>