<?php

$view->dbSearch->formName = str_replace('_list','',basename(__FILE__,'.phtml')).'Form';
$view->dbSearch->formNameModeSubmit = 'xhr';

echo $view->dbSearch->affNumPage() ;
espace ();

echo "<table align=center cellspacing=2 width=100%>";

echo htmlLineTitleTable2($view->dbSearch);

$l = 0;
foreach ($view->dbSearch->a_dataQuery as $obj)
{
	$colorl = 'cfg'.(($l++) %2);
	$color2 = "cfg2";

	echo '<tr class="'.$colorl.'" onmouseover=\'this.className="'.$color2.'"\' onmouseout=\'this.className="'.$colorl.'"\' style="cursor:hand">';
	foreach ($view->dbSearch->a_langField as $champ)
	{
		$nom_champ = $champ->COLUMN_NAME;
		if (in_array($champ->DATA_TYPE,array('date','datetime','timestamp')))
		{
			$obj->$nom_champ = fr_date($obj->$nom_champ);
		}
		$onClick = "onClick=\"window.location.href='".CFG_URL_ROOT."catalogue/soft?action=soft_consult&ID_SOFT=".$obj->ID_SOFT."'\"";
		echo "<td valign=top ".$onClick.">".NlToBrWordWrap(TransConstante($obj->$nom_champ))."</td>\n";
	}
	echo "</tr>\n";
}
echo "</table>\n";

espace ();

echo $view->dbSearch->affNumPage() ;

espace();

echo "
	<table align=center border=0 cellpadding=0 cellspacing=0 width=100%>
	<tr>
		<td align=center width=100%>".
CadreVide ( "navigation", "100%", 2)
."</td>";
/*
BoutonTd ("button", "creer", LANG_CREER, "showLightbox('iframe','catalogue/soft?action=soft_edit',745,320)", "action_modification");

if (!empty($view->dbSearch->a_dataQuery)) {
	BoutonTd ("button", "exportListe", LANG_EXPORTEXCEL, "Creation_Excel(this.form,'htmlExcel')", "action_navigation");
}
*/
echo "</tr></table>";


