<link href="<?php echo BDO_URL; ?>style/addition.css" rel="stylesheet" type="text/css">
<script>
$(document).ready(function() {
    $(".fancybox2")
    .fancybox({
        type: 'iframe',
        autoSize : false,
        afterClose: function () {
                parent.location.reload(true);
            }
    });
});
</script>
<?php

$ficheAlbum = $view->getHelper('ficheAlbum');
 $page = $view->getHelper('pagination');


?>
<form name="addForm" method="get" action="">
    <div align="center" class="cadre1">
     <?php echo $page->menuCollection(); ?>
                                                    <!-- Column 1 start -->

    <div class="middle_title">
      <h3>L'Addition </h3>
    </div>

     <div class="cadre1">
    <a href="<?php echo BDO_URL;?>Macollection/detailvalorisation" class="fancybox2 fancybox.iframe {width:415,height:500}">Detail
    de la valorisation</a>
    </div>



        <div class="middle_title">
     <h3>Achats depuis le début de votre collection</h3>
        </div>
      <hr class="addSep">
      <div class="addFreeBlock">
        <table class="addTable">
          <tr>
            <td class="addTitle">Annee</td>
            <td class="addTitleMiddle">Qté</td>
            <td class="addTitle">Coût</td>
          </tr>
         <?php if (issetNotEmpty($view->a_depense)) {
             foreach($view->a_depense as $key => $value) { ?>
          <tr>
            <td class="addData"><a href="?<?php echo "annee=".$key."&info=".$view->info."&mois=1";?>"><?php echo ($key == $view->annee) ? "<b>$key</b>" : $key;?></a></td>
            <td class="addData"><?php echo $view->a_nbalbum[$key];?></td>
            <td class="addDataRight"><?php echo number_format($value,2,".",",");?></td>
          </tr>
         <?php }} ?>
        </table>
      </div>



    <!--        <div class="addFreeBlock"> <img src="<?php echo BDO_URL."graphs/rep_cout_annee.php?info=$view->info";?>" class="addImg"> </div>-->
        <div class="addFreeBlock" style="width:602px;height:300px"> <img src="<?php echo BDO_URL."graphs/rep_cout_annee.php?info=$view->info";?>" class="addImg">
        <div align="center">
        Sélectionner l'information à afficher
        <input name="annee" type="hidden" value="<?php echo $view->annee;?>">
          <label><input type="radio" name="info" value="0" <?php echo ($view->info==0) ? 'checked' : '';?> onClick="submit();">Coût</label>
          <label><input type="radio" name="info" value="1" <?php echo ($view->info==1) ? 'checked' : '';?> onClick="submit();">Nombre</label>
        </div></div>

    <hr class="addSep">
     <div class="middle_title">
     <h3>Achats pour l'année <?php echo $view->annee;?></h3>
        </div>

        <div class="addFreeBlock">

          <select name="mois" size="12" onchange="submit();" class="addSelect">
              <option value="1" <?php echo $view->mois == 1 ? "selected=''" : "" ?>>Janvier</option>
              <option value="2" <?php echo $view->mois == 2 ? "selected=''" : "" ?>>Février</option>
              <option value="3" <?php echo $view->mois == 3 ? "selected=''" : "" ?>>Mars</option>
              <option value="4" <?php echo $view->mois == 4 ? "selected=''" : "" ?>>Avril</option>
              <option value="5" <?php echo $view->mois == 5 ? "selected=''" : "" ?>>Mai</option>
              <option value="6" <?php echo $view->mois == 6 ? "selected=''" : "" ?>>Juin</option>
              <option value="7" <?php echo $view->mois == 7 ? "selected=''" : "" ?>>Juillet</option>
              <option value="8" <?php echo $view->mois == 8 ? "selected=''" : "" ?>>Août</option>
              <option value="9" <?php echo $view->mois == 9 ? "selected=''" : "" ?>>Septembre</option>
              <option value="10" <?php echo $view->mois == 10 ? "selected=''" : "" ?>>Octobre</option>
              <option value="11" <?php echo $view->mois == 11 ? "selected=''" : "" ?>>Novembre</option>
              <option value="12" <?php echo $view->mois == 12 ? "selected=''" : "" ?>>Décembre</option>

              </select>

        </div>
            <table class="addTable">
              <tr>
                <td class="addTitle">Serie</td>
                <td class="addTitleMiddle">Titre</td>
                <td class="addTitle">Date</td>
                <td class="addTitle">Coût</td>
                <td width="10">&nbsp;</td>
              </tr>
            <?php
            $i = 0;
            foreach($view->a_album as $album) { ?>
              <tr>
                <td class="addDataSmall"><a href="<?php echo BDO_URL."Seriebd?id_serie=".$album->ID_SERIE;?>" class="addLiens"><?php echo $album->NOM_SERIE;?></a></td>

                <td class="addDataSmall"><?php echo $ficheAlbum->urlalbum($album,$class="albTitle") ; ?></td>
                <td class="addDataSmall"><?php echo date("d/m/Y",strtotime($album->DATE_ACHAT));?></td>
                <td class="addDataSmall"><?php echo number_format($view->prixretenu[$i],2,".",",");?></td>
                <td width="10">&nbsp;</td>
              </tr>
            <?php
            $i++;
            } ?>
              <!-- END MonthBlock -->
            </table>

          <div class="addFreeBlock"> <img src="<?php echo BDO_URL."graphs/rep_cout_mois.php?annee=$view->annee&info=$view->info";?>" class="addImg"> </div>
    <hr class="addSep">
    </div>

</form>




