
        
<?php
    $ficheAlbum = $view->getHelper('ficheAlbum');
    $page = $view->getHelper('pagination');
   
    
?>
<div align="center" class="cadre1">
   <?php echo $page->menuCollection(); ?>
    <h1>Tableau de bord de ma collection</h1>
    
    <div class="cadre1" style="float:left;">

    <h2>Carr&eacute; Magique </h2>

            <table width="300" border="0">

                    <tr>

            <?php

            $i = 1;

            foreach ($view->a_carre as $o_tome) {

                if ($i > 3) {

                    $i = 1;

                    echo '</tr><tr>';

                }

                echo '<td width="100" class="CarreMagique">'.$ficheAlbum->urlAlbum ($o_tome,'couvMedium').'</td>';

                $i ++;

            }

            ?> 

            </tr>

            </table>
    <a href="Paramcarre" class="fancybox fancybox.iframe {width:600,height:400}">Paramètres de mon Carr&eacute; Magique</a>
    
    </div>
    
    <div class="cadre1" style="float:left;margin: auto; margin-left:5px ;padding:auto;max-width:400px;">

    				<h2>Informations sur la collection</h2>

    				<p>

                        Nombre d'albums : <?php echo $view->stat["nbtomes"];?> dont <?php echo $view->stat["nbintegrales"];?> int&eacute;grales.

                        <br />

                        Nombre de coffrets : <?php echo $view->stat["nbcoffrets"];?>

                        <br />

                        Nombre de s&eacute;ries suivies  : <?php echo $view->stat["nbseries"];?>

                        <br />

                        Nombre d'achats pr&eacute;vus : <?php echo $view->stat["nbfuturs_achats"];?>

                    </p>

    				<p>

    					<font color="#990000"><b>Contributions &agrave; la base de

    							donn&eacute;es</b></font>

    				</p>

    				<p>

                        Propositions de nouveaux albums : <?php echo $view->user_prop_alb;?>

                        <br />

                        Propositions de corrections : <?php echo $view->user_prop_corr;?>

                    </p>
                    <h2>Partage de ma collection</h2>
                    <form method="post">
                                <p>Rendre ma collection public : <select name="open_collec">
                                            <option value="Y" <?php if ($view->open_collec == "Y") echo "selected=''"; ?> >Oui</option>
                                            <option value="N" <?php if ($view->open_collec == "N") echo "selected=''"; ?>>Non</option>
                                    </select><input type="submit" value="Ok">
                                    
                                    
                                </p>
                    
                                <p>Adresse public de la collection : <br><a href="<?php echo BDO_URL ?>guest?user=<?php echo encodeUserId($view->user_id);?>"><?php echo BDO_URL; ?>guest?user=<?php echo encodeUserId($view->user_id);?></a>
                                </p>
                    </form>
    </div>

    				

<hr class="expSep"/>





<div class="cadre1">

	<h2>Derniers achats</h2>

	
        <table><tr>
            <?php

            foreach ($view->a_lastAchat->a_dataQuery as $o_tome) {

                echo "<td>".$ficheAlbum->urlAlbum($o_tome,"couvBig", true)."</td>";

            }

            ?> 
        <tr>
        </table>

        <hr class="expSep"/>

</div>
<div class="cadre1">

	<h2>Derniers ajouts dans mes futurs achats</h2>

	
        <table><tr>
            <?php

            foreach ($view->a_lastFuturAchat->a_dataQuery as $o_tome) {

                echo "<td>".$ficheAlbum->urlAlbum($o_tome,"couvBig", true)."</td>";

            }

            ?> 
        <tr>
        </table>

        <hr class="expSep"/>

</div>

<div class="cadre1">

	<h2>Statitiques de la collection</h2>
        <img src="<?php echo BDO_URL; ?>graphs/rep_genres.php" >
        <br>
        <img src="<?php echo BDO_URL; ?>graphs/rep_editeurs.php" >
        <br>
        <img src="<?php echo BDO_URL; ?>graphs/rep_auteurs.php" >
        
     
</div>
