
<?php if ( $_SERVER["CONTENT_TYPE"] == "application/json" ) { 
    echo $view->json;
} else { ?>
<script>
$(document).ready(function() {
    $(".fancybox2")
    .fancybox({
        type: 'iframe',
        autoSize : false,
        afterClose: function () {
                parent.location.reload(true);
            }
    });
});
</script>

<?php
    $ficheAlbum = $view->getHelper('ficheAlbum');
    $page = $view->getHelper('pagination');


?>
<div align="center" class="cadre1">
   <?php echo $page->menuCollection(); ?>
    <h1>Tableau de bord de ma collection</h1>

    <div class="cadre1" style="float:left;">

    <h2>Carr&eacute; Magique </h2>

            <table id="carre_magique">

                    <tr>

            <?php

            $i = 1;

            foreach ($view->a_carre as $o_tome) {

                if ($i > 3) {

                    $i = 1;

                    echo '</tr><tr>';

                }

                echo '<td width="100" class="CarreMagique">'.$ficheAlbum->urlAlbum ($o_tome,'couvMedium').'</td>';

                $i ++;

            }

            ?>

            </tr>

            </table>
    <a href="Paramcarre" class="fancybox2 fancybox.iframe {width:600,height:400}">Paramètres de mon Carr&eacute; Magique</a>

    </div>

    <div class="cadre1" style="float:left;margin: auto; margin-left:5px ;padding:auto;max-width:400px;">

                    <h2>Informations sur la collection</h2>

                    <p>

                        Nombre d'albums : <?php echo $view->stat["nbeditions"];?> dont <?php echo $view->stat["nbintegrales"];?> int&eacute;grales.

                        <br />

                        Nombre de coffrets : <?php echo $view->stat["nbcoffrets"];?>

                        <br />

                        Nombre de s&eacute;ries suivies  : <?php echo $view->stat["nbseries"];?>

                        <br />

                        Nombre d'achats pr&eacute;vus : <?php echo $view->stat["nbfuturs_achats"];?>

                    </p>

                    <p>

                        <font color="#990000"><b>Contributions &agrave; la base de

                                donn&eacute;es</b></font>

                    </p>

                    <p>

                        Propositions de nouveaux albums : <?php echo $view->user_prop_alb;?>

                        <br />

                        Propositions de corrections : <?php echo $view->user_prop_corr;?>

                    </p>
                    <h2>Partage de ma collection</h2>
                    <form method="post">
                                <p>Rendre ma collection publique : <select name="open_collec">
                                            <option value="Y" <?php if ($view->open_collec == "Y") echo "selected=''"; ?> >Oui</option>
                                            <option value="N" <?php if ($view->open_collec == "N") echo "selected=''"; ?>>Non</option>
                                    </select><input type="submit" value="Ok">


                                </p>

                                <p>Adresse publique de la collection : <br><a href="<?php echo BDO_URL ?>guest?user=<?php echo encodeUserId($view->user_id);?>"><?php echo BDO_URL; ?>guest?user=<?php echo encodeUserId($view->user_id);?></a>
                                </p>
                    </form>
                    <h2>Export/Import</h2>
                    <a href="<?php echo BDO_URL;?>export" class="fancybox fancybox.iframe {width:600,height:600}">Exporter ma collection</a><br>
                    <a href="<?php echo BDO_URL;?>import" class="fancybox fancybox.iframe {width:600,height:600}">Importer un fichier</a>
    </div>



<hr class="expSep"/>





<div class="cadre1">

    <h2>Derniers achats</h2>

    <div class="scrollauto">
        <table><tr>
            <?php

            foreach ($view->a_lastAchat->a_dataQuery as $o_tome) {
                // on affiche pas le sponsor sur la collection de l'utilisateur
                echo "<td>".$ficheAlbum->urlAlbum($o_tome,"couvBig", true, $sponsor=false)."</td>";

            }

            ?>
        <tr>
        </table>
        </div>
        <hr class="expSep"/>

</div>
<div class="cadre1">

    <h2>Derniers ajouts dans mes futurs achats</h2>

    <div class="scrollauto">
        <table><tr>
            <?php

            foreach ($view->a_lastFuturAchat->a_dataQuery as $o_tome) {
// on affiche pas le sponsor sur la collection de l'utilisateur
                echo "<td>".$ficheAlbum->urlAlbum($o_tome,"couvBig", true, false)."</td>";

            }

            ?>
        <tr>
        </table>
        </div>
        <hr class="expSep"/>

</div>

<?php } ?>
