<script src="<?php echo BDO_URL;?>jquery/jquery.cookie.js" type="text/javascript"></script>
<script language ='javascript'>
    var uri = "./mesauteurs?";
    q = param();
    for (k in q) {
        if (k.substring(0, 4) != "sort" && k.substring(0, 5) != "order") {
          uri += k + "=" + encodeURIComponent(q[k][0]) + "&";
        }
    }

    $(document).ready(function() {
        $("#length").on('change', function (e) {
             $("#f_collection").submit();
        });
        $('.numbersOnly').keyup(function () {
            this.value = this.value.replace(/[^0-9\.]/g,'');
        });
        $("a#inline").fancybox({
          'autoDimensions': false,
               'minHeight': 320,
               'maxWidth' : 500,
        });

        $("#bsave").button("disable");
        $.datepicker.setDefaults( $.datepicker.regional[ "fr" ] );

        $(function() {
            $( "[name='date_achat']" ).datepicker({dateFormat: "dd/mm/yy"});
        });
    });
</script>


<?php
  $ficheAuteur = $view->getHelper('ficheAuteur');
  $page = $view->getHelper('pagination');
?>
<div align="center" class="cadre1">
  <?php echo $page->menuCollection(); ?>

  <div class="middle_title"><h3 >Mes Auteurs</h3></div>

  <b> <?php echo $view->nbr; ?> auteurs dans la collection. </b>

  <br>
  <input type="hidden" name="page" id="page" value="<?php echo $view->page; ?>" />
  <br>
  <div class="dataTables_wrapper">
      <form id="f_collection" method="GET" action="" >
        <div id="filtre">
          <fieldset id="typeAlbum" class="newButton">
            <legend>Albums</legend>
              <input type="checkbox" name="origin[]" id="checkB" value="BD" onChange='$("#f_collection").submit();' <?php if (in_array("BD",$view->origin)) echo "checked" ?>>
              <label for="checkB">BD</label>
              <input type="checkbox" name="origin[]" id="checkM" value="Mangas" onChange='$("#f_collection").submit();' <?php if (in_array("Mangas",$view->origin)) echo "checked" ?>>
              <label for="checkM">Mangas</label>
              <input type="checkbox" name="origin[]" id="checkC" value="Comics" onChange='$("#f_collection").submit();' <?php if (in_array("Comics",$view->origin)) echo "checked" ?>>
              <label for="checkC">Comics</label>
          </fieldset>
          <fieldset id="typeTravail" class="newButton">
            <legend>Auteurs</legend>
              <input type="checkbox" name="travail[]" id="checkS" value="Scénariste" onChange='$("#f_collection").submit();' <?php if (in_array("Scénariste",$view->travail)) echo "checked" ?>>
              <label for="checkS"><span title="Scénariste" class="fas fa-file-signature"></span></label>
              <input type="checkbox" name="travail[]" id="checkD" value="Dessinateur" onChange='$("#f_collection").submit();' <?php if (in_array("Dessinateur",$view->travail)) echo "checked" ?>>
              <label for="checkD"><span title="Dessinateur" class="fas fa-pencil-alt"></span></label>
              <input type="checkbox" name="travail[]" id="checkO" value="Coloriste" onChange='$("#f_collection").submit();' <?php if (in_array("Coloriste",$view->travail)) echo "checked" ?>>
              <label for="checkO"><span title="Coloriste" class="fas fa-palette"></span></label>
          </fieldset>
        </div><br>
        <div id="data_length" class="dataTables_length">
          Voir :
            <label>
              <select class="" id="length" name="length">
                <option value="12" <?php if ($view->length == 12) { echo "selected"; } ?> >  10</option>
                <option value="24" <?php if ($view->length == 24) { echo "selected"; } ?>>  20</option>
                <option value="48" <?php if ($view->length == 48 ) { echo "selected"; } ?>>  50</option>
                <option value="96" <?php if ($view->length == 96) { echo "selected"; } ?>> 100</option>
              </select>
              éléments
            </label>
        </div>

        <div id="filter" class="dataTables_filter">
          <label>
            Rechercher:
              <input class="" type="search" placeholder="" id="l_search" name="l_search" value="<?php echo $view->searchvalue; ?>" />
          </label>
        </div>
      </form>
  </div>
  <hr>
  <div class="cadre1">
    <table class="list_album">  <!-- Pas de raison, pour le moment, d'utiliser un autre style que pour les albums. -->
     
        <?php
         
          $tr = true;
          $tr = 1;

          foreach ($view->dbs_auteur as $auteur) {
             if ($tr == 1) echo "<tr>";
        ?>
            <td class="mw50">
              <?php 
                echo $ficheAuteur->big($auteur); 
              ?>
            
            </td>
        <?php
            $tr++;
            if ($tr > 3) {
              echo "</tr>";
              $tr = 1;
            }
          }
            if ($tr !== 1) echo "</tr>";
        ?>
      
    </table>
  </div>
  
  <div align="center">
    <?php
      $nbpage = ceil($view->nbr / $view->length);
      $uri = "";
      $a_uri = explode("?", $_SERVER['REQUEST_URI']);
      $a_uri = explode("&", $a_uri [1]);
      foreach ($a_uri as $key => $value) {
          if (substr($a_uri[$key], 0, 4) <> "page" and $a_uri[$key] <> "") {
              $uri .= "&" . $a_uri[$key];
          }
      }
      $url = BDO_URL . "macollection/mesauteurs?" . $uri . "&";

      echo $page->paginate($url, "page=", $nbpage, $view->page);
    ?>
  </div>
</div>
