<?php
foreach(range('A','Z') as $i) {

    ?>

<sitemap>
    <loc><?php echo BDO_URL; ?>liste_auteur_bd/sitemap?lettre=<?php echo $i; ?></loc>
    <lastmod><?php echo substr(date("Y-m-d"),0,8)."01";?></lastmod>
</sitemap>
<sitemap>
    <loc><?php echo BDO_URL; ?>liste_serie_bd/sitemap?lettre=<?php echo $i; ?></loc>
    <lastmod><?php echo substr(date("Y-m-d"),0,8)."01";?></lastmod>
</sitemap>
<?php } ?>
<sitemap>
    <loc><?php echo BDO_URL; ?>sitemapbase.xml</loc>
    <lastmod>2019-03-16</lastmod>
</sitemap>